### ISSUE TITLE
[FR] FR-24 The preview box feature displays the query configuration in real time

### ISSUE THREAD

**Issue by zyxfei** [deepflowio/deepflow#1760]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Plugin

### What you expected to happen

# The preview box feature displays the query configuration in real time

### How to reproduce

# The preview box feature will only work properly if the query is correct
1. When create a deepflow panel，if you configured a wrong query , sql preview box will not display
2. When modify a deepflow panel，if you configured a wrong query , sql preview  box  will not change

![image](https://user-images.githubusercontent.com/14983449/207014603-297c029c-c2c7-4d30-b2e0-f87c3e6f4736.png)

### DeepFlow version

```
Name: deepflow-server community edition
Branch: v6.1.7
CommitID: ec882eea9310bd13495e086694a42f5caa04d7bd
RevCount: 7195
Compiler: go version go1.18.8 linux/amd64
CompileTime: 2022-11-29 02:48:14
```
```
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
7195-ec882eea9310bd13495e086694a42f5caa04d7bd
Name: deepflow-agent community edition
Branch: v6.1.7
CommitId: ec882eea9310bd13495e086694a42f5caa04d7bd
RevCount: 7195
Compiler: rustc 1.65.0 (897e37553 2022-11-02)
CompileTime: 2022-11-29 02:48:30
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
feature merged.
