### ISSUE TITLE
[FR] FR-014: trace data export to OpenTelemetry Collector 

### ISSUE THREAD

**Issue by zhangfane** [deepflowio/deepflow#2304]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The OpenTelemetry protocol has become the observable standard and is supported by many vendors.
deepflow trace support for exporting to otel collector will help deepflow to integrate with other observable platforms.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
Field mapping document:  https://deepflow.yunshan.net/docs/zh/server-integration/export/opentelemetry-collector/

**Comment by chenmudu** [comment]
@lzf575 Any discussion can take place here. Including other people.

**Comment by chenmudu** [comment]
There are still some things that need to be done, let us continue to wait.

**Comment by tomatopunk** [comment]
Hello @chenmudu 

> There are still some things that need to be done, let us continue to wait.

Hello @chenmudu and team, 
I am writing to request recent information regarding this project. 
I noticed that the work stoped in 2023. Is there any unfinished work, and is anyone continuing this project? Is there anything pending?

by the way, I am currently working with Deepflow `agent module`. It appears to only have the `ingester`, but it is not functioning correctly as there is no supporting code. 

Regarding the trace export to the OTLP collector, are there any updates, will this work be continued?
