### ISSUE TITLE
[FR] FR-019: Advice on Security

### ISSUE THREAD

**Issue by tyroarchitect** [deepflowio/deepflow#2335]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowys/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

安全相关建议

### Use case

mysql和redis相关的执行语句都是明文，有安全风险，是否可以优化？2企业版支持传输数据加密，开源版是否能提供支持，否则有安全问题无法上生产环境使用，谢谢！

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowys/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
We will support masking of application protocol sensitive data in v6.3: #2516 

There is currently no plan to support encrypted transmission in the community edition. If you transmit data on the public network, it is recommended to use a gateway to implement encryption.
