### ISSUE TITLE
[FR] FR-024:  Support to tag `os.app` for children processes

### ISSUE THREAD

**Issue by eddietanshuo** [deepflowio/deepflow#2456]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Some projects use multi-processes to handle I/O. For example, a nginx master process forks workers to establish connection with upstreams.

However, the deepflow agent only tags to the flow of sockets which are created by master process. We need an availability to tag not only the flow created by master process but also created by children processes those have the same ppid with master process.

## suggestion
We could add regex rules to match processes and allow or disallow agents to tag children processes.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
The process will automatically inherit the tag of the parent process.
