### ISSUE TITLE
[FR] FR-26: Support masking application-flow's query detail for mysql & redis

### ISSUE THREAD

**Issue by eddietanshuo** [deepflowio/deepflow#2516]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Some sql or redis query could have user sensitive content, e.g. phone number, address, identity. It's illegal to store those info in plaintext. We suggest to mask critical field of query. For example: convert `select * from test_table where name='edward'` into `select * from test_table where name=***`. 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
This feature is already supported in v6.4.

[deepflwo-agent config](https://github.com/deepflowio/deepflow/blob/main/server/controller/model/agent_group_config_example.yaml#L1003)

```yaml
    ## List of L7 protocols that need to be obfuscated
    ## Note: For the sake of data security, the data of the protocol that needs
    ## to be desensitized is configured here and is not processed by default.
    ## Default: obfuscate-enabled-protocols: [], by default, neither sql statements nor redis commands are obfuscated
    ## If you want to obfuscate sql statements and redis commands, you can set it to:
    ## obfuscate-enabled-protocols:
    ## - MySQL
    ## - PostgreSQL
    ## - Redis
    #obfuscate-enabled-protocols: []
```
