### ISSUE TITLE
[BUG] Kernel Not fit

### ISSUE THREAD

**Issue by wgy-ts** [deepflowio/deepflow#2543]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

grafana dashboard [DeepFlow Templates/Distributed Tracing] has no data

### How to reproduce

`helm install deepflow -n deepflow deepflow/deepflow`

### DeepFlow version

`kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v`
2023/03/06 14:06:35 ENV K8S_NODE_NAME_FOR_DEEPFLOW=192-168-199-163; K8S_NODE_IP_FOR_DEEPFLOW=192.168.199.163; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-7cf88959c7-dq8pq; K8S_POD_IP_FOR_DEEPFLOW=10.96.10.51; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: v6.2.2
CommitID: ad5a34f7c813fd9e9321500c14261d06ec2aaf74
RevCount: 7726
Compiler: go version go1.18.10 linux/amd64
CompileTime: 2023-02-09 02:37:12

----------------------------------------------------------------------------
`kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v`
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
7726-ad5a34f7c813fd9e9321500c14261d06ec2aaf74
Name: deepflow-agent community edition
Branch: v6.2.2
CommitId: ad5a34f7c813fd9e9321500c14261d06ec2aaf74
RevCount: 7726
Compiler: rustc 1.65.0 (897e37553 2022-11-02)
CompileTime: 2023-02-09 02:37:54

### DeepFlow agent list

`deepflow-ctl agent list`
NAME               TYPE       CTRL_IP          CTRL_MAC           STATE    GROUP   EXCEPTIONS
192-168-199-161-V1 K8S_VM     192.168.199.161  fa:36:ae:74:0a:00  NORMAL   default
192-168-199-163-V2 K8S_VM     192.168.199.163  fa:3e:46:f2:52:00  NORMAL   default
192-168-199-162-V3 K8S_VM     192.168.199.162  fa:3f:9b:93:f8:00  NORMAL   default

### Kubernetes CNI

`kubectl get nodes -o wide`
NAME              STATUS   ROLES                  AGE    VERSION   INTERNAL-IP       EXTERNAL-IP   OS-IMAGE                  KERNEL-VERSION                    CONTAINER-RUNTIME
192-168-199-161   Ready    control-plane,master   244d   v1.21.5   192.168.199.161   <none>        Oracle Linux Server 7.9   5.4.17-2102.201.3.el7uek.x86_64   docker://20.10.8
192-168-199-162   Ready    worker                 118d   v1.21.5   192.168.199.162   <none>        Oracle Linux Server 7.9   5.4.17-2102.201.3.el7uek.x86_64   docker://20.10.8
192-168-199-163   Ready    <none>                 37d    v1.21.5   192.168.199.163   <none>        Oracle Linux Server 7.9   5.4.17-2102.201.3.el7uek.x86_64   docker://20.10.8

--------------------------------------------------------------------------------------------------------------------
kubectl -n kube-system get pods -l k8s-app=calico-node -o custom-columns=NAME:.metadata.name,IMG:.spec.containers[].image
NAME                IMG
calico-node-64pps   docker.io/calico/node:v3.23.2
calico-node-s95p5   docker.io/calico/node:v3.23.2
calico-node-xngfv   docker.io/calico/node:v3.23.2

### Operation-System/Kernel version

`awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`
"Oracle Linux Server 7.9"

`uname -r`
5.4.17-2102.201.3.el7uek.x86_64

### Anything else

this problem occur every time

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
@wgy-ts 

Post the agent error log.
```
    error!(
                        "The tracer_start() error. Kernel offset adapt failed. \
                            Provide the operating system name and the \
                            'kernel-devel' package for developers to adapt."
                    );
```

**Comment by dundun9** [comment]
`bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h`

And this output

**Comment by dundun9** [comment]
Try it with the latest kernel version
