### ISSUE TITLE
[BUG]  problem with timezones on the dashboards

### ISSUE THREAD

**Issue by dirtyren** [deepflowio/deepflow#2848]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

All deploys are running on my local timezone,  all were installed via helm with the GMT-3 timezone. I've checked all pods and all show GMT-3 timezone running date on the shell.
![Grafana_dash](https://user-images.githubusercontent.com/1627055/230775423-cb8c9c9c-1adc-45da-9199-3616de6689c7.png)

You can see here, that the summary count is on the right date and time, but the flowlog is in the future, in the Shanghai timezone.
What I dont get is why this is happening since the data comes from the same table, no? Tks a l

### How to reproduce

   Install deepflow on a different timezone than the default one.

### DeepFlow version

`➜  utils git:(main) ✗ kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
2023/04/09 10:28:48 ENV K8S_NODE_NAME_FOR_DEEPFLOW=gke-c-hj29c-default-2-a282ba21-ec6x; K8S_NODE_IP_FOR_DEEPFLOW=10.93.149.41; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-7447fbc84d-cdgg6; K8S_POD_IP_FOR_DEEPFLOW=100.96.25.155; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: v6.2.5
CommitID: fa3c5eac7feddc24e66e49c43e8a0a6aa0f3d5b7
RevCount: 7968
Compiler: go version go1.18.10 linux/amd64
CompileTime: 2023-03-22 02:05:51`

`➜  utils git:(main) ✗ kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
8020-f068cbf48cbea36ebe58199afa17b786dc4d8aaf
Name: deepflow-agent community edition
Branch: offsets-map
CommitId: f068cbf48cbea36ebe58199afa17b786dc4d8aaf
RevCount: 8020
Compiler: rustc 1.68.0 (2c8cc3432 2023-03-06)
CompileTime: 2023-03-29 08:29:03
➜  utils git:(main) ✗`

### Anything else

   A noticed that the DataTime and DataTime64 tables fields on the Clickhouse database are all on the Shanghai timezone. I wonder if this could not be the underlying problem.
   One other question I had is why instead of Datetime fields deepflow could not use timestamp.

   Tks

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by casmssm** [comment]
I have this problem too

**Comment by lzf575** [comment]
now in server.yaml  your can config time-zone:
![image](https://user-images.githubusercontent.com/44988793/231369436-eceb1c8a-720a-48e7-be43-1ae5c01aa517.png)
as, 
```
  ingester:
    ckdb:
      external: false
      host: deepflow-clickhouse
      port: 9000
      endpoint-tcp-port-name: tcp-port
      time-zone: Asia/Shanghai
```
