### ISSUE TITLE
[BUG] ck default ttl unit  may have wrong comment in the code.

### ISSUE THREAD

**Issue by eddietanshuo** [deepflowio/deepflow#2859]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

I see the default flow log ttl is 72 hour (3 days)
https://github.com/deepflowio/deepflow/blob/7540a6127a74a5150ed24129782a9c356b58a640/server/ingester/flow_log/config/config.go#L36

However according to the ck client, the ttl unit is day:
https://github.com/deepflowio/deepflow/blob/1b4e347ddc41da3d8647ea070cd30ffb8869ba3f/server/libs/ckdb/table.go#L56

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lzf575** [comment]
ok, have set the comment to hour
