### ISSUE TITLE
[eBPF] ebpf module seem to load uncorrectly on 4.19.90-23.8.v2101.ky10.aarch64

### ISSUE THREAD

**Issue by jimszhang2023** [deepflowio/deepflow#2893]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

I launched the agent via --standalone mode on Kylin10 Linux that be run in a ARMv8 Arch Server。
The following warnning  from the log of agent ,  the ebpf module seem to work uncorrectly.

bpf: Failed to load program: Invalid argument
back-edge from insn 1007 to 990

2023-04-14 09:53:55 [eBPF] WARNING: func load_obj__progs() [user/load.c:410] bcc_prog_load() failed. name: bpf_func_sys_exit_write, errno: 22
2023-04-14 09:53:55 [eBPF] WARNING: func ebpf_obj_load() [user/load.c:715] eBPF load programs failed. (errno 22)
Free ebpf object.
2023-04-14 09:53:55 [eBPF] WARNING: func tracer_bpf_load() [user/tracer.c:231] bpf load "socket-trace-bpf-linux-kylin" failed, error:Invalid argument (22).

### How to reproduce

./deepflow-agent -f /opt/deepflow/agent/config/deepflow-agent.yaml --standalone

### DeepFlow agent list

Name: deepflow-agent community edition
Branch: dev
CommitId: 0e07a30a5f00e6a668084e4decc9af9ad4f0ae9f
RevCount: 8283
Compiler: rustc 1.68.2 (9eb3afe9e 2023-03-27)
CompileTime: 2023-04-14 09:46:30

### Kubernetes CNI

none

### Operation-System/Kernel version

Kylin Linux Advanced Server V10 (Tercel)
4.19.90-23.8.v2101.ky10.aarch64

### Anything else

The Issue occur everytime when we launch the agent

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jimszhang2023** [comment]
We did the same test on kylin v10 X86 server, ebpf seems to be loaded correctly. I don't know the difference and impact of the ARM64 and X86 hardware architectures on the agent.

**Comment by dundun9** [comment]
![image](https://user-images.githubusercontent.com/50027289/232405341-54b612ca-8fba-4af3-85d8-2a16a290a590.png)

https://deepflow.io/docs/zh/install/overview/

The kernel version of the arm64 architecture is more demanding

**Comment by jimszhang2023** [comment]
Thank you very much for your feedback, kylin os (for aarch64\loongarch64) has a very high market coverage in the field of domestic os, and the system currently does not support higher kernel versions. This problem should be a long-term problem for almost all domestic Linux operating systems. So can the deepflow community consider turning this issue into a PR?

**Comment by jimszhang2023** [comment]
The kernel of the kylin v10 system is 4.19. The feature list officially given by this version can support ebpf. 
I can use a third-party tool of ebpf for verification, such as ecapture or other third-party tools recognized by public. 
If it is not satisfied indeed， we can ask the kylin manufacturer to repair it. 
In addition, judging from the recent deepflow flow code, it is true that some special parameters may be required to adapt the kylin system. In the recent #2314 issue submission, it can be seen that there will be some special offset settings  to fix the issue, 
 when dealing with socket data instructure, but this is only useful for the x86 architecture.
I don't quite understand why this offset is specially set for kylin, which should require a certain amount of professional knowledge to understand. But it seems that kylin does have certain particularities in this regard that need to be adapted.

**Comment by dundun9** [comment]
The kernel version of the arm architecture is more demanding, so you can provide a `kernel-devel` package to see

**Comment by jimszhang2023** [comment]
wget https://update.cs2c.com.cn/NS/V10/V10SP1.1/os/adv/lic/base/aarch64/Packages/kernel-devel-4.19.90-23.8.v2101.ky10.aarch64.rpm

**Comment by dundun9** [comment]
Get. Could you please add my wechat under README?

**Comment by jimszhang2023** [comment]
Done@dundun9

**Comment by dundun9** [comment]
The arm64 architecture requires a 5.8+ kernel
