### ISSUE TITLE
[FR] FR-32: Make deepflow agent support for host with Suse os linux kernel 3 or update the agent deploy documents for different os host.

### ISSUE THREAD

**Issue by Wooo8712** [deepflowio/deepflow#2918]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

start failed as following info:
more /var/log/deepflow-agent/deepflow-agent.log

> [2023-04-14 17:34:31.105656 +08:00] WARN [src/trident.rs:421] initialize cgroup controller failed, CpuControllerSetFailed("maybe cgroup is not installed"), agent restart...

OS: Suse11 sp3/Suse11 sp4
kernel: 3.0.101

### Use case

we try to install the rpm of cgroup:
suse11sp3: 

> rpm -ivh libcgroup1-0.37.1-5.16.1

suse11sp4: 

> rpm -ivh libcgroup1-0.41.rc1-2.34

then start cgconfig service:

> service cgconfig start

but agent still starts failed with the same error.

next, we add some configurations and restart the service:

> mount {
>         cpu = /mnt/cgroups/cpu;
>         cpuacct = /mnt/cgroups/cpuacct;
>         memory = /mnt/cgroups/memory;
> }
> 

agent starts successfully.

we start the agent with the above temporary measures, but we don't know what negative impact it will produce.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
When there are no cgroups in the system, we will only periodically check the CPU and memory usage without forcing deepflow-agent to restart.

@TomatoMr will fix this issue

**Comment by TomatoMr** [comment]
https://github.com/deepflowio/deepflow/pull/3327

**Comment by sharang** [comment]
done.

https://github.com/deepflowio/deepflow/pull/3371
