### ISSUE TITLE
[BUG] Code Error

### ISSUE THREAD

**Issue by shaohuading** [deepflowio/deepflow#2921]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

document location: https://github.com/deepflowio/deepflow/blob/main/server/ingester/flow_log/exporter/otlp.go
Should line 120 set the ParentSpanID?
![image](https://user-images.githubusercontent.com/88264066/232818574-58e59ddb-0d54-47dd-abe4-19d2d4cd31ce.png)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lzf575** [comment]
It's a bug, OTLP is still under development and will be fixed soon。
https://deepflow.io/docs/zh/server-integration/export/opentelemetry-collector/

**Comment by sharang** [comment]
fixed
