### ISSUE TITLE
[FR] FR-34: Sync only tagged processes to reduce db overhead

### ISSUE THREAD

**Issue by eddietanshuo** [deepflowio/deepflow#2975]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have to many records in the table gproccess. 
In order to reduce the overhead of metadata, we need only report the processes with os_app_tag which are deployed by our deployment agent. 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
PR merged
