### ISSUE TITLE
[BUG] Data rate metric differs in map and table list

### ISSUE THREAD

**Issue by dirtyren** [deepflowio/deepflow#3162]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

  I expected that the map woud show the same data rate as on the table, map show 18MBytes/s and the table 18MBits/s and the correct if 18Mbps.

### How to reproduce

Just open the Network - K8S Pod Map dashboard

### DeepFlow version

Name: deepflow-server community edition
Branch: v6.2.6.4
CommitID: e17ff03821574c4f8b9c89285bb537b4af0149fd
RevCount: 8241
Compiler: go version go1.18.10 linux/amd64
CompileTime: 2023-05-11 03:28:03

Name: deepflow-agent community edition
Branch: v6.2.6.4
CommitId: e17ff03821574c4f8b9c89285bb537b4af0149fd
RevCount: 8241
Compiler: rustc 1.69.0 (84c898d65 2023-04-16)
CompileTime: 2023-05-11 03:28:40

### DeepFlow agent list

NAME                                                   TYPE       CTRL_IP          CTRL_MAC           STATE    GROUP   EXCEPTIONS
gke-0-6e44a666-lcvd-V1  K8S_VM     10.95.141.206    42:01:0a:5f:8d:ce  NORMAL   default
gke-6e44a666-fmn8-V8  K8S_VM     10.95.141.176    42:01:0a:5f:8d:b0  NORMAL   default
gke-b478b69e-jsh8-V11 K8S_VM     10.95.141.163    42:01:0a:5f:8d:a3  NORMAL   default
gke-b478b69e-wwdl-V9  K8S_VM     10.95.141.171    42:01:0a:5f:8d:ab  NORMAL   default
gke-6e44a666-1dhn-V5  K8S_VM     10.95.141.160    42:01:0a:5f:8d:a0  NORMAL   default
gke-1e57bfdd-z7eh-V2  K8S_VM     10.95.141.154    42:01:0a:5f:8d:9a  NORMAL   default
gke-1e57bfdd-4oai-V10 K8S_VM     10.95.141.150    42:01:0a:5f:8d:96  NORMAL   default
gke-b478b69e-vwmh-V4  K8S_VM     10.95.141.147    42:01:0a:5f:8d:93  NORMAL   default
gke-b478b69e-7svr-V3  K8S_VM     10.95.141.204    42:01:0a:5f:8d:cc  NORMAL   default
gke-6e44a666-wadg-V7  K8S_VM     10.95.141.155    42:01:0a:5f:8d:9b  NORMAL   default
gke-1e57bfdd-41t9-V6  K8S_VM     10.95.141.149    42:01:0a:5f:8d:95  NORMAL   default

### Kubernetes CNI

Calico

### Operation-System/Kernel version

"Container-Optimized OS from Google"
5.10.162+

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dirtyren** [comment]
![image](https://github.com/deepflowio/deepflow/assets/1627055/a330a935-4566-48c8-b969-ba842a802a48)

![image](https://github.com/deepflowio/deepflow/assets/1627055/ae20889e-b937-4a35-8526-33b1c31d1031)

**Comment by dundun9** [comment]
@twou12031 Look at this

**Comment by twou12031** [comment]
@dirtyren THX for report.
Will fix it as quickly as possible.

**Comment by dundun9** [comment]
https://github.com/deepflowio/deepflow-dashboards/pull/123

**Comment by twou12031** [comment]
Hi,
This bug has been fixed, please use the 6.3.1 version we just released.

#### Why the bug happens:
In the DeepFlow datasource, users can use `Math(*)` sub-functions on metrics.
This function affects the units of the metrics, also does `Math(/)`.
In the Table panel, user can use `Overrides` panel options to override the filed.
In the DeepFlow Topo panel, there is no place to override the units.

#### Our fix:
In the DeepFlow Topo panel, we have added the `Metrics Units` option in the panel options, which allows users to override the units of the metrics.
And we have fixed incorrect units display in dashboards using this feature.

Thanks a lot for your report.
