### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by yilingyi** [deepflowio/deepflow#3216]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Helm Chart

### What you expected to happen

# helm install deepflow -n deepflow deepflow/deepflow --create-namespace >   -f values-custom.yaml

Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[0].securityContext): unknown field "seccompProfile" in io.k8s.api.core.v1.SecurityContext

### DeepFlow version

6.2.6.5

### Kubernetes CNI

kubesphere 3.1

### Operation-System/Kernel version

"CentOS Linux 7 (Core)"
3.10.0-1160.45.1.el7.x86_64

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
How many helm chart versions? Try using the latest helm chart?

**Comment by yilingyi** [comment]
> How many helm chart versions? Try using the latest helm chart?

helm version is v3.11.2

**Comment by dundun9** [comment]
View chart version: 
`helm search repo deepflow`

**Comment by yilingyi** [comment]
> View chart version: `helm search repo deepflow`
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION                                       
deepflow/deepflow      	6.2.606      	6.2.6      	An automated observability platform for cloud-n...
deepflow/deepflow-agent	6.2.606      	6.2.6      	An automated observability platform for cloud-n...

**Comment by dundun9** [comment]
```yaml
  containerSecurityContext: {}
```

Write a values-custom file and try to add this section

**Comment by yilingyi** [comment]
> ```yaml
> containerSecurityContext: {}
> ```
I tried, but it still doesn't work
![image](https://github.com/deepflowio/deepflow/assets/36027338/97127c98-413e-4969-8bbe-d23c63ce2f96)

**Comment by dundun9** [comment]
```
grafana:
  containerSecurityContext: []
```
