### ISSUE TITLE
[BUG] Manual ingested hosts and chosts will not show names on dashboards, just IPs

### ISSUE THREAD

**Issue by dirtyren** [deepflowio/deepflow#3240]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

I`ve  manually ingested two subnets and added 1 host and one chost, deepflow will only show the IP addresses instead of the host names.

### How to reproduce

Just ingested the subnets and IPs.

### DeepFlow agent list

v6.2.6.5

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dirtyren** [comment]
![deepflow](https://github.com/deepflowio/deepflow/assets/1627055/a5158f96-de83-4cf9-8989-5a97b35fb489)

**Comment by dundun9** [comment]
@SongZhen0704 See if this should be shown as a vm.

**Comment by SongZhen0704** [comment]
Hi, dirtyren,
Do you have specific IPs associated with hosts or VMs?

@dirtyren

**Comment by SongZhen0704** [comment]
@dirtyren 

Hi，you can upgrade to v6.4 and check if exist the same issue
