### ISSUE TITLE
[BUG] Grafana alerts are not working on deepflow datasource

### ISSUE THREAD

**Issue by dirtyren** [deepflowio/deepflow#3241]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Plugin

### What you expected to happen

I am trying to set up some alert on Grafana based on the deepflow datasource but Grafana will show a error.

![deepflow2](https://github.com/deepflowio/deepflow/assets/1627055/2d361b90-7321-45d8-b210-c6d37a1dff73)

### How to reproduce

Just try to set up a alert on Grafana dashboard

### DeepFlow version

v6.2.6.5

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
@twou12031  Take a look here.

**Comment by twou12031** [comment]
Sorry, missed this one before.
We need multiple members working together to fix it.
If there is progress, will add comment.

**Comment by twou12031** [comment]
Hi,
After our troubleshooting, we found the cause of the bug.

First of all, variables can be used in the dashboards of grafana, but not in the alert of grafana.
Then, when creating an alert based on a panel in dashboards that uses a variable, after the jump, the saved query condition contains the variable.
This is causing the bug, the query is not working properly.

It will take a lot of time to support the above usage scenarios.
If there is progress, will add comment.

Our current recommendation is to manually create grafana alerts on the alert page.

**Comment by dirtyren** [comment]
Tks fo getting back on this issue.

**Comment by dirtyren** [comment]
My workaround that was to use the deepflow promql interface. For the alerts I needed, it worked fine.
