### ISSUE TITLE
[BUG] Part of the request indicator data of grafana Application-k8s-ingress panel is incorrect

### ISSUE THREAD

**Issue by wenhuwang** [deepflowio/deepflow#3321]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

I was use the ab tools to request  sample-gin.demo.*.com  50 times, and then i saw the number of sample-gin.demo.*.* doman_name requests and the number of / path requests on the Application-k8s-ingress panel, and the data i saw were all 150 times.

The client request command is shown below:
```
$ ab -c 1 -n 50 http://sample-gin.demo.*.com/
```

Grafana panel is shown below:
<img width="1498" alt="image" src="https://github.com/deepflowio/deepflow/assets/16423072/912be226-775c-4580-9673-f9820e4abbf7">

### DeepFlow version

```bash
$ kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
Name: deepflow-server community edition
Branch: v6.2
CommitID: e77a530824268c647f09860778b81d68fa3c79b9
RevCount: 8293
Compiler: go version go1.18.10 linux/amd64
CompileTime: 2023-06-06 02:43:06
$ kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Name: deepflow-agent community edition
Branch: v6.2.6.5
CommitId: 3d888cab7e15db5d4f5a51eacf7703acc60ff7a9
RevCount: 8265
Compiler: rustc 1.69.0 (84c898d65 2023-04-16)
CompileTime: 2023-05-18 01:56:26
```
grafana image version:
```
registry.cn-beijing.aliyuncs.com/deepflow-ce/grafana:9.5.2
```

### Kubernetes CNI

calico

### Operation-System/Kernel version

```bash
$ k get node -owide
NAME          STATUS   ROLES    AGE   VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME
10.1.6.37   Ready    master   13d   v1.22.14   10.1.6.37   <none>        CentOS Linux 7 (Core)   5.4.243-1.el7.elrepo.x86_64   containerd://1.5.8
10.1.6.38   Ready    master   13d   v1.22.14   10.1.6.38   <none>        CentOS Linux 7 (Core)   5.4.243-1.el7.elrepo.x86_64   containerd://1.5.8
10.1.6.39   Ready    node     13d   v1.22.14   10.1.6.39   <none>        CentOS Linux 7 (Core)   5.4.243-1.el7.elrepo.x86_64   containerd://1.5.8
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
https://github.com/deepflowio/deepflow-dashboards/pull/122

**Comment by dundun9** [comment]
I have added a tap_side condition to the dashboard, so that there will be no duplicate data if you select one of the indicators of the collection location such as the client network card/process and the server network card/process
