### ISSUE TITLE
[BUG]  Distributed tracing template of grafana issues

### ISSUE THREAD

**Issue by wenhuwang** [deepflowio/deepflow#3333]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

1、Request List panel of distributed-tracing-cloud template  data links configurations error, as show below.
<img width="1501" alt="image" src="https://github.com/deepflowio/deepflow/assets/16423072/d9a6154a-d25e-49ab-a02a-09d05a2242bc">

2、Click once on request List panel of distributed-tracing template data, the data of the distributed tracing panel will jump twice.

### DeepFlow version

```
$ kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
Name: deepflow-server community edition
Branch: v6.2
CommitID: e77a530824268c647f09860778b81d68fa3c79b9
RevCount: 8293
Compiler: go version go1.18.10 linux/amd64
CompileTime: 2023-06-06 02:43:06
$ kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Name: deepflow-agent community edition
Branch: v6.2.6.5
CommitId: 3d888cab7e15db5d4f5a51eacf7703acc60ff7a9
RevCount: 8265
Compiler: rustc 1.69.0 (84c898d65 2023-04-16)
CompileTime: 2023-05-18 01:56:26
```
grafana image version:
```
registry.cn-beijing.aliyuncs.com/deepflow-ce/grafana:9.5.2
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
fix by: https://github.com/deepflowio/deepflow-dashboards/pull/126
