### ISSUE TITLE
[FR] FR-37: Need the support for openkruise crds

### ISSUE THREAD

**Issue by lockerroom** [deepflowio/deepflow#3368]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Cannot get namespace from kruise pod's metadata.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
```
2023-06-14 11:15:07.725 [INFO][0m [cloud.kubernetes_gather] pod.go:107 pod group (xxxx) type (CloneSet) not support
2023-06-14 11:15:07.725 [INFO][0m [cloud.kubernetes_gather] pod.go:107 pod group (xxxxx) type (CloneSet) not support
2023-06-14 11:15:07.725 [INFO][0m [cloud.kubernetes_gather] pod.go:107 pod group (xxxxx) type (TaskRun) not support
2023-06-14 11:15:07.725 [INFO][0m [cloud.kubernetes_gather] pod.go:107 pod group (xxxxxxx) type (CloneSet) not support
```

**Comment by sharang** [comment]
about cloneset:
- https://thenewstack.io/introducing-cloneset-production-grade-kubernetes-deployment-crd/
- https://openkruise.io/zh/docs/
- https://jimmysong.io/kubernetes-handbook/practice/openkruise.html

**Comment by lockerroom** [comment]
There is something new, we also have pod managed by OpenKruise Advanced StatefulSet, the kind field value of these pods' ownerReference is StatefulSet, which is contained in podTypesMap, as below code
`func (k *KubernetesGather) getPods() (pods []model.Pod, nodes []model.PodNode, err error) {
	log.Debug("get pods starting")
	podTypesMap := map[string]bool{
		"DaemonSet":             false,
		"Deployment":            false,
		"InPlaceSet":            false,
		"ReplicaSet":            false,
		"StatefulSet":           false,
		"ReplicationController": false,
		"CloneSet":              false,
	}
`

As usual, these pods's namespace should be collect, but now their pod_ns_id_0 and pod_ns_id_1 are all 0, not point to their real namespace. 

Something more, we used Calico's IP retention technology, I am not sure if this is related.

**Comment by askyrie** [comment]
https://github.com/deepflowio/deepflow/pull/3598
