### ISSUE TITLE
[BUG] Manually compile agent, zilb not found

### ISSUE THREAD

**Issue by dierbei** [deepflowio/deepflow#3378]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

success download zlib-1.2.12.tar.gz 

### How to reproduce

Please use command：wget https://zlib.net/zlib-1.2.12.tar.gz

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
https://github.com/deepflowio/deepflow/pull/3383
