### ISSUE TITLE
[BUG]  https://deepflow.io/docs/zh/install/single-k8s/  官方文档上缺少deepflow-ctl的使用方法。希望能补上

### ISSUE THREAD

**Issue by wuzongling** [deepflowio/deepflow#3398]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

CLI

### What you expected to happen

[BUG]  https://deepflow.io/docs/zh/install/single-k8s/  官方文档上缺少deepflow-ctl的使用方法。希望能补上

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
agent 操作：
https://deepflow.io/docs/zh/best-practice/agent-advanced-config/

server 操作：
https://deepflow.io/docs/zh/best-practice/server-advanced-config/

agent_group_config 参考：
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml

server.yaml 参考：
https://github.com/deepflowio/deepflow/blob/main/server/server.yaml
