### ISSUE TITLE
[BUG] seems like that analyzer_ip does not support domain name

### ISSUE THREAD

**Issue by rosenlo** [deepflowio/deepflow#3399]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

Perform DNS when analyzer_ip is configured as domain name

### How to reproduce

I found an associated [PR](https://github.com/deepflowio/deepflow/pull/2063/files) in issues.

but seem to have encountered some problems; when I configure analyzer_ip as the domain name in custom_agent_group_config.yaml, I get the following error:

![Xnip2023-06-19_20-37-11](https://github.com/deepflowio/deepflow/assets/18186886/a504af6f-f6a4-4e5d-962f-dcadd6fce935)

### DeepFlow version

kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v:

```
Name: deepflow-server community edition
Branch: master
CommitID: fac7d6c9be2cd70b5f357a5e865e01887acc1b39
RevCount: 8412
Compiler: go version go1.18.3 linux/amd64
CompileTime: 2023-06-19 10:00:59
```

kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v:

```
Name: deepflow-agent community edition
Branch: master
CommitId: 0d2afa85640cee43c5c1e88e8bc061c8faad083b
RevCount: 8219
Compiler: rustc 1.69.0 (84c898d65 2023-04-16)
CompileTime: 2023-05-05 04:59:06
```

### DeepFlow agent list

deepflow-ctl agent list:

```
68       ip-192-168-100-123.ap-northeast-1.compute.internal-V95   K8S_VM     192.168.100.123    0e:c6:4e:b5:87:6b  NORMAL    ANALYZER_SOCKET_ERROR
```

### Kubernetes CNI

aws-vpc-cni

### Operation-System/Kernel version

awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release:

```
"Ubuntu 22.04.2 LTS"
```

uname -r:

```
5.4.209-116.363.amzn2.x86_64
```

### Anything else

I configured controller-ips as domain name in deepflow-agent.yaml and it works, but analyzer fails with following error: 

```
[2023-06-19 21:02:22.044939 +08:00] ERROR [src/sender/uniform_sender.rs:395] stats sender tcp connection to 0.0.0.0:30033 failed
```

So I tried to configure analyzer_ip as domain name in custom_agent_group_config.yaml controlled by ```deepflow-ctl```

Please let me know if need any more information, thanks!

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
https://github.com/deepflowio/deepflow/pull/3415

FIXED
