### ISSUE TITLE
[BUG] Simplify switching between Agent-groups

### ISSUE THREAD

**Issue by hanshilei** [deepflowio/deepflow#3402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

希望修改完agent 配置文件的agent-group ID后能直接加入新的group，不需要手动delete

### How to reproduce

现在修改agent-group需要执行 deepflow-ctl agent delete agent 删掉并重新注册agent后才能加入新的group

### DeepFlow version

deepflow-agent:v6.2.6.5

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by roryye** [comment]
`deepflow-ctl agent update-example > update.yaml`
run `deepflow-ctl agent list` to get agent name
run `deepflow-ctl agent-group list` to get agent_group_id
run `deepflow-ctl agent update -f update.yaml` to update agent group id
