### ISSUE TITLE
[BUG] workflow: agent unit test

### ISSUE THREAD

**Issue by dierbei** [deepflowio/deepflow#3426]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

I try to use the command，I want to run the unit tests：
`# docker run --cpus 8 -m 8G --privileged --rm -it -v $(pwd):/deepflow -v ~/.cargo:/usr/local/cargo hub.deepflow.yunshan.net/public/rust-build  bash -c "source /opt/rh/devtoolset-8/enable && cd /deepflow/agent && cargo test check_sql_parse"`

 but I get the error：

![image](https://github.com/deepflowio/deepflow/assets/52097565/f3fd94be-75cb-4710-b160-ce0f829b5e82)
![image](https://github.com/deepflowio/deepflow/assets/52097565/cb1c9e10-1725-4d29-a77c-9ebc12b89a11)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rvql** [comment]
Looks like a compilation error to me. Please help checking the rust-build image @dundun9 .

**Comment by dierbei** [comment]
I finally wanted to try using the command：`cargo test <func-name>`，want to test the uint test function I just finished.

This image executes the `cargo build `command successfully.

**Comment by dundun9** [comment]
Try using 1.20 for tag to compile the image
`hub.deepflow.yunshan.net/public/rust-build:1.20`

**Comment by dierbei** [comment]
> Try using 1.20 for tag to compile the image `hub.deepflow.yunshan.net/public/rust-build:1.20`

Thanks for your suggestion, but I still get the same error：

![image](https://github.com/deepflowio/deepflow/assets/52097565/add1f057-05e7-4d2c-879d-3959b4186e69)

Below is the command I executed：

`docker run --cpus 8 -m 8G --privileged --rm -it -v $(pwd):/deepflow -v ~/.cargo:/usr/local/cargo hub.deepflow.yunshan.net/public/rust-build:1.20  bash -c "source /opt/rh/devtoolset-8/enable && cd /deepflow/agent && cargo test check_sql_parse"`

**Comment by dundun9** [comment]
You might want to try not executing `source /opt/rh/devtoolset-8/enable`

**Comment by dierbei** [comment]
> source /opt/rh/devtoolset-8/enable

I still got some bugs, but it's better than last time：
![image](https://github.com/deepflowio/deepflow/assets/52097565/6ac08b35-918c-49d0-8884-e61a44fe9403)
![image](https://github.com/deepflowio/deepflow/assets/52097565/e3502e18-73a2-478f-8f1c-9fcea608fcb7)

The last prompt was as follows:

![image](https://github.com/deepflowio/deepflow/assets/52097565/089b3b1c-ab27-40fc-a3a8-8fe29489d604)

**Comment by dundun9** [comment]
@rvql Can you take a look? With the same operation, the compilation is fine, but there is a problem here

**Comment by yinjiping** [comment]
retry:

docker pull hub.deepflow.yunshan.net/public/rust-build:1.21
```
sudo docker run --rm  -it  --net=host --privileged --workdir /work  -v $(pwd):/work hub.deepflow.yunshan.net/public/rust-build:1.21 bash
 source /opt/rh/devtoolset-8/enable && cp docker/rust-proxy-config /usr/local/cargo/config && RUSTFLAGS="-D warnings -C force-frame-pointers=yes" cargo build --release && \
    cargo build --release --bin deepflow-agent-ctl
```

**Comment by yinjiping** [comment]
> @dierbei try:
> 
> docker pull hub.deepflow.yunshan.net/public/rust-build:1.21
> 
> ```
> cd /deepflow
> sudo docker run --rm  -it  --net=host --privileged --workdir /work  -v $(pwd):/work hub.deepflow.yunshan.net/public/rust-build:1.21 bash
>  source /opt/rh/devtoolset-11/enable && cd agent &&  cargo test check_sql_parse
> ```

The method did not solve the issue, and the problem you described still persists. We will resolve it as soon as possible.

**Comment by dierbei** [comment]
@yinjiping Thank you for your reply, looking forward to your good news.

**Comment by yinjiping** [comment]
> @yinjiping Thank you for your reply, looking forward to your good news.
@dierbei 
The reason for the duplicate definition of interfaces was due to the usage of both libbcc.a and libbcc_bpf.a. While compilation with cargo build was successful, the error occurred during cargo test as shown before. I have resolved this issue. Here are the steps I took:

- Updated the code with the latest changes from the main branch.
- Utilized the most recent compilation image.

```
cd deepflow/
git fetch --all && git reset --hard origin/main && git pull origin main
/usr/bin/git submodule sync --recursive
/usr/bin/git -c protocol.version=2 submodule update --init --force --recursive
docker pull hub.deepflow.yunshan.net/public/rust-build:latest
sudo docker run --rm  -it  --net=host --privileged --workdir /work  -v $(pwd):/work hub.deepflow.yunshan.net/public/rust-build:latest bash
source /opt/rh/devtoolset-11/enable && cd agent &&  cargo test check_sql_parse
```

Final results display:
```
   Compiling kube v0.74.0 (https://github.com/deepflowio/kube?tag=0.74.2#c423734b)
    Finished test [unoptimized + debuginfo] target(s) in 14m 34s
     Running unittests src/lib.rs (target/debug/deps/deepflow_agent-113851a8a6d05c01)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 167 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/deepflow_agent-e1037ef302857478)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/bin/deepflow-agent-ctl.rs (target/debug/deps/deepflow_agent_ctl-7ce0fdb79036e431)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

**Comment by dierbei** [comment]
After testing, the problem has been solved. Thanks for the help.
@rvql 
@yinjiping 
@dundun9

**Comment by yinjiping** [comment]
The issue has been solved.
