### ISSUE TITLE
deepflow-agent-xxxx  Init:CrashLoopBackOff 

### ISSUE THREAD

**Issue by yk133** [deepflowio/deepflow#3498]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

NAMESPACE              NAME                                         READY   STATUS                  RESTARTS        AGE
deepflow               deepflow-agent-5nxxl                         0/1     Init:CrashLoopBackOff   5 (2m34s ago)   11m
deepflow               deepflow-app-789bff46cf-dbb9w                1/1     Running                 0               11m
deepflow               deepflow-clickhouse-0                        1/1     Running                 0               11m
deepflow               deepflow-grafana-77678b59b9-j2dtd            1/1     Running                 0               11m
deepflow               deepflow-mysql-5c884bcb89-2f8th              1/1     Running                 0               11m
deepflow               deepflow-server-8654966b75-62g7r             1/1     Running                 2 (5m39s ago)   11m

Why deepflow-agent not running？

### DeepFlow version

2023/06/30 17:34:52 ENV K8S_NODE_NAME_FOR_DEEPFLOW=minikube; K8S_NODE_IP_FOR_DEEPFLOW=192.168.49.2; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-8654966b75-62g7r; K8S_POD_IP_FOR_DEEPFLOW=172.17.0.3; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: v6.2.6.5
CommitID: 3d888cab7e15db5d4f5a51eacf7703acc60ff7a9
RevCount: 8265
Compiler: go version go1.18.10 linux/amd64
CompileTime: 2023-05-18 01:55:36

### DeepFlow agent list

none

### Operation-System/Kernel version

5.15

### Anything else

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
Try adding the following to the values-custom.yaml file and update it, providing a log to find out why the init container failed
```
  sysctlInitContainer:
    enabled: false
```

**Comment by dundun9** [comment]
或者使用最新的helm chart再更新一下也可以
