### ISSUE TITLE
[FR] FR-kernel-support: 5.10.0-106.18.0.68.oe2209.x86_64

### ISSUE THREAD

**Issue by innlym** [deepflowio/deepflow#3542]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

make -C /lib/modules/5.10.0-106.18.0.68.oe2209.x86_64/build M=/tmp/show-kernel-struct-offset modules
make[1]: Entering directory '/usr/src/kernels/5.10.0-106.18.0.68.oe2209.x86_64'
  CC [M]  /tmp/show-kernel-struct-offset/skso.o
  MODPOST /tmp/show-kernel-struct-offset/Module.symvers
  CC [M]  /tmp/show-kernel-struct-offset/skso.mod.o
  LD [M]  /tmp/show-kernel-struct-offset/skso.ko
make[1]: Leaving directory '/usr/src/kernels/5.10.0-106.18.0.68.oe2209.x86_64'
objdump -d skso.ko

skso.ko:     file format elf64-x86-64

Disassembly of section .text:

0000000000000000 <STRUCT_TCP_SOCK_COPIED_SEQ_OFFSET>:
   0:	e8 00 00 00 00       	call   5 <STRUCT_TCP_SOCK_COPIED_SEQ_OFFSET+0x5>
   5:	b8 54 06 00 00       	mov    $0x654,%eax
   a:	c3                   	ret    
   b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000010 <STRUCT_TCP_SOCK_WRITE_SEQ_OFFSET>:
  10:	e8 00 00 00 00       	call   15 <STRUCT_TCP_SOCK_WRITE_SEQ_OFFSET+0x5>
  15:	b8 d4 07 00 00       	mov    $0x7d4,%eax
  1a:	c3                   	ret    
  1b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000020 <STRUCT_TASK_FILES_OFFSET>:
  20:	e8 00 00 00 00       	call   25 <STRUCT_TASK_FILES_OFFSET+0x5>
  25:	b8 60 0c 00 00       	mov    $0xc60,%eax
  2a:	c3                   	ret    
  2b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000030 <STRUCT_SOCK_FLAGS_OFFSET>:
  30:	e8 00 00 00 00       	call   35 <STRUCT_SOCK_FLAGS_OFFSET+0x5>
  35:	b8 38 02 00 00       	mov    $0x238,%eax
  3a:	c3                   	ret    
  3b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000040 <STRUCT_FILES_PRIVATE_DATA_OFFSET>:
  40:	e8 00 00 00 00       	call   45 <STRUCT_FILES_PRIVATE_DATA_OFFSET+0x5>
  45:	b8 c8 00 00 00       	mov    $0xc8,%eax
  4a:	c3                   	ret    
  4b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000050 <STRUCT_TASK_TLS_OFFSET>:
  50:	e8 00 00 00 00       	call   55 <STRUCT_TASK_TLS_OFFSET+0x5>
  55:	b8 a8 15 00 00       	mov    $0x15a8,%eax
  5a:	c3                   	ret    
  5b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000060 <init_module>:
  60:	e8 00 00 00 00       	call   65 <init_module+0x5>
  65:	31 c0                	xor    %eax,%eax
  67:	c3                   	ret    
  68:	0f 1f 84 00 00 00 00 	nopl   0x0(%rax,%rax,1)
  6f:	00 

0000000000000070 <cleanup_module>:
  70:	e8 00 00 00 00       	call   75 <cleanup_module+0x5>
  75:	c3                   	ret

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nrjatyunshan** [comment]
@innlym Try to change the tag of the agent to `3542-fr-fr-kernel-support-5100-10618068oe2209x86_64`

**Comment by innlym** [comment]
> @innlym Try to change the tag of the agent to `3542-fr-fr-kernel-support-5100-10618068oe2209x86_64`

It worked, thanks !

**Comment by nrjatyunshan** [comment]
@innlym Automatically close the issue after merging into the main thread
