### ISSUE TITLE
[BUG] deepflow 数据集成至 otel 没有把火焰图所有数据吐出来

### ISSUE THREAD

**Issue by callmediaomao** [deepflowio/deepflow#3550]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

通过消费kafka的消息来和火焰图的_id进行比较，发现有kafka中有_id缺失。然后在deepflow-server上打印了所有的_id日志以及exporter.go->grpcExport()中的DropCounter没有发现丢弃消息。
![image](https://github.com/deepflowio/deepflow/assets/63587783/5dba1472-4fcb-46be-aeb0-c8f636c3baab)
![企业微信截图_1688827368267](https://github.com/deepflowio/deepflow/assets/63587783/1ebf97d3-105e-49d4-9de7-3c9b6bab4f9c)

### DeepFlow version

server版本：v6.3.2
根据五天前的源码打包编译

### Operation-System/Kernel version

centos 7

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lzf575** [comment]
@callmediaomao  看看grafana-server->ingester监控数据图中是否有drop的数据?
![image](https://github.com/deepflowio/deepflow/assets/44988793/15bd9c94-3949-4a4c-9950-a2d3794eec2e)

也可以加大queue-count数量，增大处理能力。https://github.com/deepflowio/deepflow/blob/main/server/server.yaml#L520

**Comment by callmediaomao** [comment]
![image](https://github.com/deepflowio/deepflow/assets/63587783/b1ea66b6-16c2-4b88-810f-77007e3ee4e0)
加大了queueCount和queue ，Drop的数量好像越来越多了。。

**Comment by lzf575** [comment]
@callmediaomao  看下该图左边图中这个queue的in/out数量, 如果in 比较多的话，还是需要加大queueCount, 但最多只支持16。 也排查下接收端会不会接收阻塞，而导致发送丢包。

**Comment by callmediaomao** [comment]
@lzf575 
1. 我加大了queueCount至16，queuesize至6000000，然后我的k8s节点疯狂挂😂，但是发现还是out的数量还是比较少，相对于in来说
2. 调整了replicas数量为3，趋势图发现没有展示所有副本的exporter in/out   以及 exporter的drop数量，只展示了两个副本。设置queueCount为6，queueSize为4000000，多副本情况下还是会丢失数据，out还是比in小很多，基本上in是20多k，out只有2k左右
![93dff2f3805c7a5e7203209f5218c92](https://github.com/deepflowio/deepflow/assets/63587783/2270b62f-9775-4165-b8c9-d46fab915636)

**Comment by lzf575** [comment]
@callmediaomao  queuesize 一般不用修改，目前队列发送阻塞，会占满queue size，导致占用内存。你确认下接收端的处理能力是否有问题，接收端如果慢的话，发送就会阻塞丢包。一般性能不至于收到20k，只发出2k。 后续会增加调试手段，看看空发送的性能，以确认是接收问题，还是发送问题。

**Comment by callmediaomao** [comment]
@lzf575 接收端的otel-gent的配置如下：
1. configMap配置
![image](https://github.com/deepflowio/deepflow/assets/63587783/3fcf89f6-f8cb-4b24-82e9-5eee6288a0e6)
2. ds 配置
![image](https://github.com/deepflowio/deepflow/assets/63587783/51ee5af6-7cd4-4487-b978-bd839c9a17ca)
还会出现dropData数据
还有一个问题，deepflow发送给otel-col最大一条消息是多大的

**Comment by lzf575** [comment]
@callmediaomao  还会drop么，drop有多大， 如果还有多余的cpu, 内存， 继续配置增大。 最大的消息，也不可能超过10k，一般在1k左右。

**Comment by lzf575** [comment]
@callmediaomao 主要是 ptraceotlp.Export 发送性能差导致，后续会聚合发送，单核可以发送20k/s. 
 https://github.com/deepflowio/deepflow/pull/3721

**Comment by callmediaomao** [comment]
> 单

👌想问下大概什么时候上这个版本。现在我用6个副本跑server，但是grafana只会显示两个副本，想问下这个是抽样展示趋势图还是是个bug。
![image](https://github.com/deepflowio/deepflow/assets/63587783/1c5e6844-da97-4441-a25e-e8dd46b4fbf9)
![image](https://github.com/deepflowio/deepflow/assets/63587783/aa02e549-ee53-43f0-8077-fd96ce1216d7)

**Comment by lzf575** [comment]
已经合入，用latest即可。 grafana的显示缺失，主要是折线图太多，默认只显示100行，需要设置下slimit值，
![image](https://github.com/deepflowio/deepflow/assets/44988793/b3b645ef-bca6-49f4-8862-d476d56d99cb)

**Comment by lzf575** [comment]
目前已修改为默认按 32条 batch发送，正常不会丢包，https://github.com/deepflowio/deepflow/blob/main/server/server.yaml#L557
