### ISSUE TITLE
[BUG] bcc/linux/bpf.h not found

### ISSUE THREAD

**Issue by YanjiangChen** [deepflowio/deepflow#3558]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

cargo build, not found bcc/linux/bpf.h

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by YanjiangChen** [comment]
when agent cargo build, happen error: bcc/linux/bpf.h not found

**Comment by yinjiping** [comment]
Please use the image we provide to solve the compilation problem. You can install the following steps to solve the problem:
```
cd deepflow/
git fetch --all && git reset --hard origin/main && git pull origin main
/usr/bin/git submodule sync --recursive
/usr/bin/git -c protocol.version=2 submodule update --init --force --recursive
docker pull hub.deepflow.yunshan.net/public/rust-build:latest
sudo docker run --rm  -it  --net=host --privileged --workdir /work  -v $(pwd):/work hub.deepflow.yunshan.net/public/rust-build:latest bash
source /opt/rh/devtoolset-8/enable && cd agent  &&  RUSTFLAGS="-C force-frame-pointers=yes" cargo build --release
```
