### ISSUE TITLE
[BUG] pod deepflow-server-XXX CrashLoopBackOff

### ISSUE THREAD

**Issue by sxqiu123** [deepflowio/deepflow#3584]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

**### Expected Behavior**
pod deepflow-server-598fb4cdf8-qmhnr  in running status.

**### Actual Behavior:**
pod deepflow-server-598fb4cdf8-qmhnr CrashLoopBackOff

[root@master ~]# kubectl get pods -A
NAMESPACE              NAME                                             READY   STATUS                             RESTARTS        AGE
deepflow               deepflow-agent-gqzmc                        1/1     Running                             0                      15h
deepflow               deepflow-app-846c6645cb-gfgg8        1/1     Running                             0                      15h
deepflow               deepflow-clickhouse-0                          1/1     Running                             0                      15h
deepflow               deepflow-grafana-764cfb5bc6-9hjnf    1/1     Running                             2 (15h ago)      15h
deepflow               deepflow-mysql-7db57b44f4-4fz47     1/1     Running                             0                       15h
deepflow               deepflow-server-598fb4cdf8-qmhnr     0/1     CrashLoopBackOff            6 (5m2s ago)   12m

### How to reproduce

helm repo add deepflow https://deepflowio.github.io/deepflow
helm repo update deepflow
helm install deepflow -n deepflow deepflow/deepflow --create-namespace --set global.allInOneLocalStorage=/opt/deepflow/data 

### DeepFlow version

**### The result is go to error.**
container not found ("deepflow-server")

[root@master ~]# kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
error: unable to upgrade connection: container not found ("deepflow-server")
[root@master ~]# kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
8265-3d888cab7e15db5d4f5a51eacf7703acc60ff7a9
Name: deepflow-agent community edition
Branch: v6.2.6.5
CommitId: 3d888cab7e15db5d4f5a51eacf7703acc60ff7a9
RevCount: 8265
Compiler: rustc 1.69.0 (84c898d65 2023-04-16)
CompileTime: 2023-05-18 01:56:26
[root@master ~]# 

### DeepFlow agent list

**The result of "deepflow-ctl agent list" is go to error.**
connection refused

[root@master ~]# deepflow-ctl agent list
curl (http://10.88.40.149:30417/v1/vtaps/) failed, (Get "http://10.88.40.149:30417/v1/vtaps/": dial tcp 10.88.40.149:30417: connect: connection refused)

### Kubernetes CNI

calico

### Operation-System/Kernel version

[root@master ~]# awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"CentOS Linux 7 (Core)"
[root@master ~]# uname -r
3.10.0-1160.el7.x86_64

### **the version of deepflow**
[root@master ~]# helm search repo deepflow
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION                                       
deepflow/deepflow      	6.2.606      	6.2.6      	An automated observability platform for cloud-n...
deepflow/deepflow-agent	6.2.606      	6.2.6      	An automated observability platform for cloud-n...

### **pods "deepflow-mysql-7db57b44f4-4fz47" error logs**

[root@master ~]# kubectl logs deepflow-mysql-7db57b44f4-4fz47 -n deepflow
Defaulted container "mysql" out of: mysql, hostpath-chown (init)
2023-07-13 01:09:28+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.31-1.el8 started.
2023-07-13 01:09:28+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
2023-07-13 01:09:28+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.31-1.el8 started.
2023-07-12T17:09:29.023383Z 0 [Warning] [MY-011068] [Server] The syntax 'slave_skip_errors' is deprecated and will be removed in a future release. Please use replica_skip_errors instead.
2023-07-12T17:09:29.025094Z 0 [Warning] [MY-010918] [Server] 'default_authentication_plugin' is deprecated and will be removed in a future release. Please use authentication_policy instead.
2023-07-12T17:09:29.025134Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.31) starting as process 1
2023-07-12T17:09:29.035433Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
2023-07-12T17:09:30.291788Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
2023-07-12T17:09:31.003028Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
2023-07-12T17:09:31.003110Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
2023-07-12T17:09:31.161769Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
2023-07-12T17:09:31.161889Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.31'  socket: '/var/lib/mysql/mysql.sock'  port: 30130  MySQL Community Server - GPL.
2023-07-12T17:10:10.201372Z 11 [Warning] [MY-010055] [Server] IP address '10.244.219.94' could not be resolved: Name or service not known
2023-07-12T17:10:23.315007Z 22 [Warning] [MY-010055] [Server] IP address '10.244.219.98' could not be resolved: Name or service not known
2023-07-13T08:04:29.550395Z 8524 [Warning] [MY-010055] [Server] IP address '10.244.219.101' could not be resolved: Name or service not known

### **pods "deepflow-server-598fb4cdf8-qmhnr" error logs**
[root@master ~]# kubectl logs deepflow-server-598fb4cdf8-qmhnr  -n deepflow
2023/07/13 16:16:13 ENV K8S_NODE_NAME_FOR_DEEPFLOW=master; K8S_NODE_IP_FOR_DEEPFLOW=10.88.40.149; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-598fb4cdf8-qmhnr; K8S_POD_IP_FOR_DEEPFLOW=10.244.219.101; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
2023-07-13 16:16:13.089 [INFO] [deepflow-server] main.go:120 deepflow-server config: {LogFile:/var/log/deepflow/server.log LogLevel:info ContinuousProfile:{Enabled:false ServerAddress:http://deepflow-agent/api/v1/profile ProfileTypes:[cpu inuse_objects alloc_objects inuse_space alloc_space] MutexRate:5 BlockRate:5 LogEnabled:true}}
2023-07-13 16:16:13.090 [INFO] [kubernetes] watcher.gen.go:1004 Endpoints watcher starting
2023-07-13 16:16:13.091 [INFO] [querier] querier.go:47 ==================== Launching DeepFlow-Server-Querier ====================
2023-07-13 16:16:13.091 [INFO] [querier] querier.go:48 querier config:
log-file: /var/log/querier.log
log-level: info
listen-port: 20416
clickhouse:
  user-name: default
  user-password: ""
  host: deepflow-clickhouse
  port: 9000
  timeout: 60
  connect-timeout: 2
  max-connection: 20
profile:
  log-file: /var/log/profile.log
  log-level: info
  listen-port: 20419
  flame_query_limit: 1000000
  querier:
    host: 127.0.0.1
    port: 20416
deepflow-app:
  host: deepflow-app
  port: "20418"
prometheus:
  qps-limit: 100
  series-limit: 100
  auto-tagging-prefix: df_
  request-query-with-debug: false
language: en
otel-endpoint: http://10.88.40.149:38086/api/v1/otel/trace
limit: "10000"
time-fill-limit: 20
2023-07-13 16:16:13.091 [INFO] [controller] controller.go:72 ==================== Launching DeepFlow-Server-Controller ====================
2023-07-13 16:16:13.091 [INFO] [controller] controller.go:73 controller config:
log-file: /var/log/controller.log
log-level: info
listen-port: 20417
listen-node-port: 30417
master-controller-name: ""
grpc-max-message-length: 104857600
grpc-port: "20035"
ingester-port: "20033"
grpc-node-port: "30035"
kubeconfig: ""
election-name: deepflow-server
reporting-disabled: false
billing-method: license
pod-cluster-internal-ip-to-ingester: 0
df-web-service:
  enabled: false
  host: df-web
  port: 20106
  timeout: 30
mysql:
  database: deepflow
  host: deepflow-mysql
  port: 30130
  user-name: root
  user-password: deepflow
  timeout: 30
  drop-database-enabled: false
  auto_increment_increment: 1
redis:
  resource_api_database: 1
  resource_api_expire_interval: 3600
  dimension_resource_database: 2
  host: []
  port: 6379
  password: deepflow
  timeout: 30
  enabled: false
  cluster_enabled: false
clickhouse:
  database: flow_tag
  host: deepflow-clickhouse
  port: 9000
  user-name: default
  user-password: ""
  timeout: 30
roze:
  port: 20106
  timeout: 60
spec:
  vtap_group_max: 1000
  vtap_max_per_group: 10000
  az_max_per_server: 10
  data_source_max: 15
  data_source_retention_time_max: 24000
monitor:
  health_check_interval: 60
  health_check_port: 30417
  health_check_handle_channel_len: 1000
  license_check_interval: 60
  vtap_check_interval: 60
  exception_time_frame: 3600
  auto_rebalance_vtap: true
  rebalance_check_interval: 300
  vtap_auto_delete_interval: 3600
  warrant:
    warrant: warrant
    port: 20413
    timeout: 30
manager:
  cloud_config_check_interval: 60
  task:
    resource_recorder_interval: 60
    cloud:
      cloud_gather_interval: 30
      kubernetes_gather_interval: 30
      aliyun_region_name: cn-beijing
      aws_region_name: cn-north-1
      genesis_default_vpc: default_vpc
      hostname_to_ip_file: /etc/hostname_to_ip.csv
      dns_enable: false
      http_timeout: 30
      debug_enabled: false
    recorder:
      cache_refresh_interval: 60
      deleted_resource_clean_interval: 24
      deleted_resource_retention_time: 168
      resource_max_id_0: 64000
      resource_max_id_1: 499999
genesis:
  aging_time: 86400
  vinterface_aging_time: 300
  host_ips: []
  local_ip_ranges: []
  exclude_ip_ranges: []
  queue_length: 60
  data_persistence_interval: 60
  multi_ns_mode: false
  single_vpc_mode: false
  ignore_nic_regex: ^(kube-ipvs)
statsd:
  enabled: true
  host: 127.0.0.1
  port: 20033
trisolaris:
  listen-port: "20014"
  loglevel: info
  tsdb-ip: ""
  chrony:
    host: ntp.aliyun.com
    port: 123
    timeout: 1
  self-update-url: grpc
  remote-api-timeout: 30
  trident-type-for-unkonw-vtap: 3
  platform-vips: []
  node-type: master
  region-domain-prefix: ""
  clear-kubernetes-time: 600
  nodeip: ""
  vtapcache-refresh-interval: 300
  metadata-refresh-interval: 60
  node-refresh-interval: 60
  gpid-refresh-interval: 9
  vtap-auto-register: true
  default-tap-mode: 0
  billingmethod: license
  grpcport: 20035
  ingesterport: 20033
  podclusterinternaliptoingester: 0
  grpcmaxmessagelength: 104857600
tagrecorder:
  timeout: 60
  mysql_batch_size: 1000
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

I0713 16:16:13.092383       1 leaderelection.go:248] attempting to acquire leader lease deepflow/deepflow-server...
[GIN-debug] GET    /v1/health/               --> github.com/deepflowio/deepflow/server/controller/http/router.HealthRouter.func1 (3 handlers)
2023-07-13 16:16:13.091 [INFO] [election] election.go:161 election id is master/10.88.40.149/deepflow-server-598fb4cdf8-qmhnr/10.244.219.101
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
2023-07-13 16:16:13.091 [WARN] [grpc] grpc_session.go:96 Sync from server 127.0.0.1 failed, reason: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:20035: connect: connection refused"
[GIN-debug] Listening and serving HTTP on :20417
2023-07-13 16:16:13.092 [INFO] [config] grpc_server_instrance.go:83 New ServerInstranceInfo ips:[127.0.0.1] port:20035 rpcMaxMsgSize:41943040
2023-07-13 16:16:13.092 [WARN] [config] config.go:248 get clickhouse endpoints(deepflow-clickhouse) failed, err: can't find my clickhouse endpoint now, pleate wait later...
2023-07-13 16:16:13.092 [WARN] [config] grpc_server_instrance.go:78 No reachable server
2023-07-13 16:16:13.100 [INFO] [kubernetes] watcher.gen.go:1024 Endpoints watcher started
2023-07-13 16:16:13.108 [INFO] [querier] querier.go:63 init opentelemetry: otel-endpoint(http://10.88.40.149:38086/api/v1/otel/trace)
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:	export GIN_MODE=release
 - using code:	gin.SetMode(gin.ReleaseMode)

[GIN-debug] POST   /v1/query/                --> github.com/deepflowio/deepflow/server/querier/router.executeQuery.func1 (6 handlers)
[GIN-debug] POST   /api/v1/prom/read         --> github.com/deepflowio/deepflow/server/querier/router.promReader.func1 (6 handlers)
[GIN-debug] GET    /prom/api/v1/query        --> github.com/deepflowio/deepflow/server/querier/router.promQuery.func1 (6 handlers)
[GIN-debug] GET    /prom/api/v1/query_range  --> github.com/deepflowio/deepflow/server/querier/router.promQueryRange.func1 (6 handlers)
[GIN-debug] POST   /prom/api/v1/query        --> github.com/deepflowio/deepflow/server/querier/router.promQuery.func1 (6 handlers)
[GIN-debug] POST   /prom/api/v1/query_range  --> github.com/deepflowio/deepflow/server/querier/router.promQueryRange.func1 (6 handlers)
[GIN-debug] GET    /prom/api/v1/label/:labelName/values --> github.com/deepflowio/deepflow/server/querier/router.promTagValuesReader.func1 (6 handlers)
[GIN-debug] GET    /prom/api/v1/series       --> github.com/deepflowio/deepflow/server/querier/router.promSeriesReader.func1 (6 handlers)
[GIN-debug] POST   /prom/api/v1/series       --> github.com/deepflowio/deepflow/server/querier/router.promSeriesReader.func1 (6 handlers)
[GIN-debug] GET    /api/traces/:traceId      --> github.com/deepflowio/deepflow/server/querier/router.tempoTraceReader.func1 (6 handlers)
[GIN-debug] GET    /api/echo                 --> github.com/deepflowio/deepflow/server/querier/router.QueryRouter.func1 (6 handlers)
[GIN-debug] GET    /api/search/tags          --> github.com/deepflowio/deepflow/server/querier/router.tempoTagsReader.func1 (6 handlers)
[GIN-debug] GET    /api/search/tag/:tagName/values --> github.com/deepflowio/deepflow/server/querier/router.tempoTagValuesReader.func1 (6 handlers)
[GIN-debug] GET    /api/search               --> github.com/deepflowio/deepflow/server/querier/router.tempoSearchReader.func1 (6 handlers)
[GIN-debug] POST   /v1/profile/ProfileTracing --> github.com/deepflowio/deepflow/server/querier/profile/router.profileTracing.func1 (6 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :20416
I0713 16:16:13.114974       1 leaderelection.go:258] successfully acquired lease deepflow/deepflow-server
2023-07-13 16:16:13.115 [INFO] [election] election.go:204 master/10.88.40.149/deepflow-server-598fb4cdf8-qmhnr/10.244.219.101 is the leader
2023-07-13 16:16:18.093 [INFO] [router.health] health.go:55 stage: Election init, time cost: 5.001202601s
2023-07-13 16:16:18.097 [INFO] [election] election.go:147 check leader finish, leader is master/10.88.40.149/deepflow-server-598fb4cdf8-qmhnr/10.244.219.101
2023-07-13 16:16:18.105 [INFO] [db.migrator.mysql] migrator.go:82 upgrade if db version is not the latest
2023-07-13 16:16:18.106 [INFO] [db.migrator.mysql] migrator.go:89 current db version: , expected db version: 6.2.1.38
2023-07-13 16:16:18.106 [ERRO] [db.migrator.mysql] migrator.go:94 current db version is null, need manual handling
2023-07-13 16:16:18.106 [ERRO] [controller] master.go:67 migrate mysql failed

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
Generally, mysql initialization fails due to poor disk performance or deepflow database table initialization fails. Try to log in mysql with root:deepflow to see if it can log in successfully. And add the following fields in the values - the custom files, update deepflow - server, if not successful landing, the empty mysql data directory/opt/deepflow/data/deepflow - mysql, Then add the following field to values-custom and update 

> it.
一般是因为磁盘性能较差导致mysql初始化失败或者deepflow的数据库表初始化失败，使用 `root:deepflow` 尝试登陆 MySQL，看看是否能登陆成功，如果能登陆成功，则drop掉deepflow database，并在values-custom文件中添加如下字段，更新deepflow-server，如果不能成功登陆，则清空mysql数据目录 /opt/deepflow/data/deepflow-mysql，然后在values-custom中添加如下字段，并更新

```yaml
mysql:
  livenessProbe:
    failureThreshold: 20
  readinessProbe
    failureThreshold: 20

server:
  livenessProbe:
    failureThreshold: 20
  readinessProbe
    failureThreshold: 20
```

**Comment by sxqiu123** [comment]
Can you tell me the path of the the values - the custom files?I can't find it.

**Comment by sxqiu123** [comment]
pod deepflow-server-598fb4cdf8-qmhnr in running status. but pod deepflow-grafana-764cfb5bc6-g8ksn goes to CrashLoopBackOff.
**### The log of deepflow-grafana-764cfb5bc6-g8ksn as follw:**
[root@master network-scripts]# kubectl logs deepflow-grafana-764cfb5bc6-g8ksn -n deepflow
logger=settings t=2023-07-13T22:56:27.97595358+08:00 level=info msg="Starting Grafana" version=9.5.2 commit=cfcea75916 branch=HEAD compiled=2023-05-04T17:56:30+08:00
logger=settings t=2023-07-13T22:56:27.976324451+08:00 level=warn msg="\"sentry\" frontend logging provider is deprecated and will be removed in the next major version. Use \"grafana\" provider instead."
logger=settings t=2023-07-13T22:56:27.976359215+08:00 level=info msg="Config loaded from" file=/usr/share/grafana/conf/defaults.ini
logger=settings t=2023-07-13T22:56:27.976368955+08:00 level=info msg="Config loaded from" file=/etc/grafana/grafana.ini
logger=settings t=2023-07-13T22:56:27.976376553+08:00 level=info msg="Config overridden from command line" arg="default.paths.data=/var/lib/grafana/"
logger=settings t=2023-07-13T22:56:27.976383969+08:00 level=info msg="Config overridden from command line" arg="default.paths.logs=/var/log/grafana"
logger=settings t=2023-07-13T22:56:27.976391606+08:00 level=info msg="Config overridden from command line" arg="default.paths.plugins=/var/lib/grafana/plugins"
logger=settings t=2023-07-13T22:56:27.976399275+08:00 level=info msg="Config overridden from command line" arg="default.paths.provisioning=/etc/grafana/provisioning"
logger=settings t=2023-07-13T22:56:27.976406419+08:00 level=info msg="Config overridden from command line" arg="default.log.mode=console"
logger=settings t=2023-07-13T22:56:27.976413854+08:00 level=info msg="Config overridden from Environment variable" var="GF_PATHS_DATA=/var/lib/grafana/"
logger=settings t=2023-07-13T22:56:27.976420745+08:00 level=info msg="Config overridden from Environment variable" var="GF_PATHS_LOGS=/var/log/grafana"
logger=settings t=2023-07-13T22:56:27.976427609+08:00 level=info msg="Config overridden from Environment variable" var="GF_PATHS_PLUGINS=/var/lib/grafana/plugins"
logger=settings t=2023-07-13T22:56:27.976434486+08:00 level=info msg="Config overridden from Environment variable" var="GF_PATHS_PROVISIONING=/etc/grafana/provisioning"
logger=settings t=2023-07-13T22:56:27.976441691+08:00 level=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_USER=admin"
logger=settings t=2023-07-13T22:56:27.976456697+08:00 level=info msg="Config overridden from Environment variable" var="GF_SECURITY_ADMIN_PASSWORD=*********"
logger=settings t=2023-07-13T22:56:27.976463785+08:00 level=info msg=Target target=[all]
logger=settings t=2023-07-13T22:56:27.976483527+08:00 level=info msg="Path Home" path=/usr/share/grafana
logger=settings t=2023-07-13T22:56:27.9764919+08:00 level=info msg="Path Data" path=/var/lib/grafana/
logger=settings t=2023-07-13T22:56:27.976498508+08:00 level=info msg="Path Logs" path=/var/log/grafana
logger=settings t=2023-07-13T22:56:27.976505276+08:00 level=info msg="Path Plugins" path=/var/lib/grafana/plugins
logger=settings t=2023-07-13T22:56:27.976519699+08:00 level=info msg="Path Provisioning" path=/etc/grafana/provisioning
logger=settings t=2023-07-13T22:56:27.976526142+08:00 level=info msg="App mode production"
logger=sqlstore t=2023-07-13T22:56:27.976833126+08:00 level=info msg="Connecting to DB" dbtype=mysql
logger=migrator t=2023-07-13T22:57:07.997415897+08:00 level=error msg="alert migration failure: could not get migration log" error="failed to check table existence: dial tcp: lookup deepflow-mysql on 10.0.0.10:53: read udp 10.244.219.75:35053->10.0.0.10:53: i/o timeout"

**Comment by dundun9** [comment]
看起来是无法解析 deepflow-mysq，检查下coredns 和容器网络是否有问题，比如 跨节点能发ping 通pod ip

**Comment by sxqiu123** [comment]
为什么服务器接入deepflow-agent后，在grafana页面的DeepFlow_Server没有显示数据，都是提示no data

[root@master deepflow]# systemctl status deepflow-agent
● deepflow-agent.service
   Loaded: loaded (/usr/lib/systemd/system/deepflow-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2023-07-13 12:10:22 EDT; 9min ago
 Main PID: 31869 (deepflow-agent)
    Tasks: 30
   Memory: 10.9M
   CGroup: /system.slice/deepflow-agent.service
           └─31869 /usr/sbin/deepflow-agent

Jul 13 12:10:22 master systemd[1]: Started deepflow-agent.service.
[root@master deepflow]# kubectl get pods -A
NAMESPACE              NAME                                         READY   STATUS    RESTARTS      AGE
deepflow               deepflow-agent-k4dmt                         1/1     Running   0             17m
deepflow               deepflow-app-846c6645cb-qt8x8                1/1     Running   0             17m
deepflow               deepflow-clickhouse-0                        1/1     Running   0             17m
deepflow               deepflow-grafana-764cfb5bc6-j87mk            1/1     Running   2 (16m ago)   17m
deepflow               deepflow-mysql-6fd78f7f8b-5mszw              1/1     Running   0             17m
deepflow               deepflow-server-659fd75dc-l2tcj              1/1     Running   2 (16m ago)   17m
kube-system            calico-kube-controllers-79568db7f8-84rbk     1/1     Running   0             19m
kube-system            calico-node-44sxp                            1/1     Running   0             19m
kube-system            coredns-567c556887-9dd4b                     1/1     Running   0             24m
kube-system            coredns-567c556887-w5j7p                     1/1     Running   0             24m
kube-system            etcd-master                                  1/1     Running   0             24m
kube-system            kube-apiserver-master                        1/1     Running   0             24m
kube-system            kube-controller-manager-master               1/1     Running   0             24m
kube-system            kube-proxy-jsfl5                             1/1     Running   0             24m
kube-system            kube-scheduler-master                        1/1     Running   0             24m
kubernetes-dashboard   dashboard-metrics-scraper-6d9cd57f74-j9825   1/1     Running   0             22m
kubernetes-dashboard   kubernetes-dashboard-6788559d58-2qbx4        1/1     Running   0             22m

**Comment by sxqiu123** [comment]
谢谢，coredns的问题解决了。grafana也有数据，但是我看到deepflow-clickhouse-0日志有报错和grafana数据查询语句报错，能帮我看下是什么问题吗？

### **grafana数据查询语句报错：**
Error: tag tag.host 未在deepflow_agent_ebpf_collector, deepflow_system中找到

### **deepflow-clickhouse-0日志报错：**
2023.07.14 17:08:14.126486 [ 383 ] {9c72d210-c008-47a9-9f52-a8c42bfacec5} <Error> TCPHandler: Code: 62. DB::Exception: Syntax error: failed at position 2 ('FROM'): FROM deepflow_system.`deepflow_agent_tcp_packet_sender` PREWHERE `time` >= 1689298033 AND `time` <= 1689301633 LIMIT 100. Expected one of: Query, Query with output, EXPLAIN, SELECT query, possibly with UNION, list of union elements, SELECT query, subquery, possibly with UNION, SELECT subquery, SELECT query, WITH, SELECT, SHOW CREATE QUOTA query, SHOW CREATE, SHOW [TEMPORARY] TABLES|DATABASES|CLUSTERS|CLUSTER 'name' [[NOT] [I]LIKE 'str'] [LIMIT expr], SHOW, EXISTS or SHOW CREATE query, EXISTS, DESCRIBE CACHE query, DESCRIBE, DESC, DESCRIBE query, SHOW PROCESSLIST query, SHOW PROCESSLIST, CREATE TABLE or ATTACH TABLE query, CREATE, ATTACH, REPLACE, CREATE DATABASE query, CREATE VIEW query, CREATE DICTIONARY, CREATE LIVE VIEW query, CREATE WINDOW VIEW query, ALTER query, ALTER TABLE, ALTER LIVE VIEW, ALTER DATABASE, RENAME query, RENAME TABLE, EXCHANGE TABLES, RENAME DICTIONARY, EXCHANGE DICTIONARIES, RENAME DATABASE, DROP query, DROP, DETACH, TRUNCATE, CHECK TABLE, KILL QUERY query, KILL, OPTIMIZE query, OPTIMIZE TABLE, WATCH query, WATCH, SHOW ACCESS query, SHOW ACCESS, ShowAccessEntitiesQuery, SHOW GRANTS query, SHOW GRANTS, SHOW PRIVILEGES query, SHOW PRIVILEGES, INSERT query, INSERT INTO, USE query, USE, SET ROLE or SET DEFAULT ROLE query, SET ROLE DEFAULT, SET ROLE, SET DEFAULT ROLE, SET query, SET, SYSTEM query, SYSTEM, CREATE USER or ALTER USER query, ALTER USER, CREATE USER, CREATE ROLE or ALTER ROLE query, ALTER ROLE, CREATE ROLE, CREATE QUOTA or ALTER QUOTA query, ALTER QUOTA, CREATE QUOTA, CREATE ROW POLICY or ALTER ROW POLICY query, ALTER POLICY, ALTER ROW POLICY, CREATE POLICY, CREATE ROW POLICY, CREATE SETTINGS PROFILE or ALTER SETTINGS PROFILE query, ALTER SETTINGS PROFILE, ALTER PROFILE, CREATE SETTINGS PROFILE, CREATE PROFILE, CREATE FUNCTION query, DROP FUNCTION query, CREATE INDEX query, DROP INDEX query, DROP access entity query, GRANT or REVOKE query, REVOKE, GRANT, EXTERNAL DDL query, EXTERNAL DDL FROM, TCL query, BEGIN TRANSACTION, COMMIT, ROLLBACK, SET TRANSACTION SNAPSHOT, Delete query, DELETE, BACKUP or RESTORE query, BACKUP, RESTORE. (SYNTAX_ERROR), Stack trace (when copying this message, always include the lines below):

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa3ec73a in /usr/bin/clickhouse
1. DB::parseQueryAndMovePosition(DB::IParser&, char const*&, char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, unsigned long, unsigned long) @ 0x1626b55f in /usr/bin/clickhouse
2. ? @ 0x1511427f in /usr/bin/clickhouse
3. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x15113e77 in /usr/bin/clickhouse
4. DB::TCPHandler::runImpl() @ 0x15c0b88c in /usr/bin/clickhouse
5. DB::TCPHandler::run() @ 0x15c1fe99 in /usr/bin/clickhouse
6. Poco::Net::TCPServerConnection::start() @ 0x1898af73 in /usr/bin/clickhouse
7. Poco::Net::TCPServerDispatcher::run() @ 0x1898c2cd in /usr/bin/clickhouse
8. Poco::PooledThread::run() @ 0x18b4ea29 in /usr/bin/clickhouse
9. Poco::ThreadImpl::runnableEntry(void*) @ 0x18b4c2e2 in /usr/bin/clickhouse
10. ? @ 0x7f2ffa638609 in ?
11. clone @ 0x7f2ffa55d133 in ?

**Comment by dundun9** [comment]
看下grafana报错吧

**Comment by sxqiu123** [comment]
已经采集agent一个星期了，还是没看到数据
