### ISSUE TITLE
[BUG] server compile error：Conn has no field or method PrepareReuseBatch

### ISSUE THREAD

**Issue by chluknight** [deepflowio/deepflow#3597]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

[root@localhost server]# CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make -e BINARY_SUFFIX=.amd64
go build -mod vendor -gcflags "-l -l" -ldflags "-X main.Branch=v6.2.6.5 -X main.RevCount=8265 -X main.Revision=3d888cab7e15db5d4f5a51eacf7703acc60ff7a9 -X main.CommitDate=2023-05-18 -X 'main.goVersion=go version go1.18.10 linux/amd64' -X 'main.CompileTime=2023-07-13 14:12:00'" -o bin/deepflow-server.amd64 cmd/server/main.go
# github.com/deepflowio/deepflow/server/ingester/pkg/ckwriter
ingester/pkg/ckwriter/ckwriter.go:347:19: ck.PrepareReuseBatch undefined (type "github.com/ClickHouse/clickhouse-go/v2/lib/driver".Conn has no field or method PrepareReuseBatch)
make: *** [Makefile:88：server] 错误 2

When I try to compile the v6.2.6.5 version of deepflow-server, the above error is reported.

I found several causes of this problem：
1. /deepflow/server/ingester/pkg/ckwriter/ckwriter.go used  the PrepareReuseBatch method of github.com/ClickHouse/clickhouse-go/v2/lib/driver/driver.go
2. go.mod requires github.com/ClickHouse/clickhouse-go/v2 v2.1.0 .   but,This version of github.com/ClickHouse/clickhouse-go/v2/lib/driver/driver.go  does not contain the PrepareReuseBatch method.  
3. And I tried to find out if other versions contain this PrepareReuseBatch method, but I couldn't find it.
4. deepflow-server v6.2.4 has not this PrepareReuseBatch method.
So maybe a custom method that hasn't been published online yet，I used a temporary solution：
/deepflow/server/ingester/pkg/ckwriter/ckwriter.go 注释掉以下内容：
        //else {
        //      batch, err = ck.PrepareReuseBatch(context.Background(), w.prepare, batch)
        //      if err != nil {
        //              return err
        //      }
        //      w.batchs[batchID] = batch
        //}
And now it works ：
[root@localhost server]# CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make -e BINARY_SUFFIX=.amd64
go build -mod vendor -gcflags "-l -l" -ldflags "-X main.Branch=v6.2.6.5 -X main.RevCount=8265 -X main.Revision=3d888cab7e15db5d4f5a51eacf7703acc60ff7a9 -X main.CommitDate=2023-05-18 -X 'main.goVersion=go version go1.18.10 linux/amd64' -X 'main.CompileTime=2023-07-14 11:33:19'" -o bin/deepflow-server.amd64 cmd/server/main.go
[root@localhost server]# cd bin
[root@localhost bin]# ls
deepflow-server.amd64

### DeepFlow version

[root@localhost server]# git branch  --show-current
v6.2.6.5

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lzf575** [comment]
需要使用Makefile编译，这个是clickhouse-go中没有的，要打上patch才能编译通过。
![image](https://github.com/deepflowio/deepflow/assets/44988793/499b703b-7027-4b77-8510-3ea3128d0887)

**Comment by taloric** [comment]
@chluknight plz check this out: https://github.com/deepflowio/deepflow/issues/3597#issuecomment-1635608056

**Comment by chluknight** [comment]
make clean
make vendor
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make server -e BINARY_SUFFIX=.amd64
three steps!  thanks!
