### ISSUE TITLE
[BUG] agent access 0.0.0.0:30033 error and mysql db deepflow.host_device no data

### ISSUE THREAD

**Issue by chengzhenge** [deepflowio/deepflow#3601]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

<html>
<body>

[2023-07-14 17:34:45.821866 +08:00] ERROR [src/sender/uniform_sender.rs:395] stats sender tcp connection to 0.0.0.0:30033 failed
--
Fri, Jul 14 2023 5:34:49 pm | [2023-07-14 17:34:49.917840 +08:00] ERROR [src/sender/uniform_sender.rs:395] 1-proc-event-to-sender sender tcp connection to 0.0.0.0:30033 failed

</body>
</html>

### How to reproduce

deploy first by helm，deepflow-6.2.606

### DeepFlow version

deepflow-6.2.606

### DeepFlow agent list

curl (http://192.168.5.207:30417/v1/vtaps/) failed, (Get "http://192.168.5.207:30417/v1/vtaps/": dial tcp 192.168.5.207:30417: connect: connection refused)

这个是我helm的机器，为何会访问这台机器的30417呢？这个机器不属于k8s集群

### Kubernetes CNI

阿里云terway-eniip

### Operation-System/Kernel version

[root@w013 ~]# awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"Alibaba Cloud Linux 3 (Soaring Falcon)"
[root@w013 ~]# uname -r
5.10.134-13.al8.x86_64

### Anything else

server error：
<html>
<body>

2023-07-14 17:27:03.861 [ERRO] [cloud.kubernetes_gather] pod_service.go:112 service labels initialization simplejson error: (EOF)
--
Fri, Jul 14 2023 5:27:03 pm | 2023-07-14 17:27:03.861 [INFO] [cloud] kubernetes_gather_task.go:109 kubernetes gather (k8s-d-rryPHO2btt) assemble data complete
Fri, Jul 14 2023 5:27:07 pm | 2023-07-14 17:27:07.637 [GIN] 192.168.102.132 GET /v1/health/ 200 41.02µs
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.314 [WARN] [trisolaris/synchronize] vtap.go:270 vtap (ctrl_ip: 192.168.5.176, ctrl_mac: 00:16:3e:09:9e:eb, host_ips: [192.168.5.176 172.17.0.1 172.16.34.204 172.16.103.179 172.16.232.69 172.16.200.2 47.110.70.6 172.16.152.136 172.16.42.227 172.16.149.226 172.16.5.128 172.16.29.225 172.16.46.225 172.16.20.144 172.16.27.160 172.16.238.169 172.16.48.91 172.16.231.25 172.16.248.131 172.16.120.242 172.16.181.49 172.16.188.58 172.16.229.53 172.16.50.101 172.16.126.33 172.16.243.238 172.16.47.129 172.16.173.78 172.16.167.196 172.16.231.139 172.16.47.85 172.16.201.54 172.16.71.229 172.16.21.1 172.16.172.43 172.16.202.55 172.16.154.244 172.16.69.253 172.16.198.5 172.16.78.116 172.16.0.10 172.16.98.39 172.16.20.197 172.16.79.14 172.16.143.63 172.16.5.0 172.16.208.213 172.16.84.126 172.16.60.38 172.16.174.16 172.16.242.201 172.16.165.131 172.16.17.122 172.16.201.235 172.16.94.250 172.16.236.8 172.16.39.89 172.16.27.45 172.16.36.212 172.16.63.26 172.16.145.141 172.16.246.222 172.16.220.81 172.16.129.199 172.16.85.255 172.16.5.63 172.16.147.54 172.16.156.225 172.16.143.218 172.16.0.1 172.16.141.10 172.16.235.237 172.16.113.36 172.16.120.37 172.16.16.184 172.16.102.158 172.16.138.29 172.16.31.179 172.16.106.122 172.16.136.236 172.16.89.116 172.16.27.41 172.16.82.153 172.16.35.185 172.16.215.83 172.16.106.127 172.16.75.78 172.16.20.45 172.16.136.202 172.16.20.127 172.16.118.99 172.16.83.65 172.16.231.34 172.16.223.29 172.16.76.137 172.16.179.61 172.16.175.0 172.16.247.119 172.16.211.135 172.16.104.176 172.16.134.91 172.16.136.35 172.16.138.236 172.16.58.179 172.16.226.10 172.16.157.129 172.16.46.66 172.16.91.67 172.16.224.210 172.16.81.168 192.168.5.176 fc00::10ca:1], kubernetes_cluster_id: d-rryPHO2btt, kubernetes_force_watch: false, group_id: ) not found in cache. NAME:deepflow-agent-ce REVISION:v6.2.6.5 8265-3d888cab7e15db5d4f5a51eacf7703acc60ff7a9 BOOT_TIME:1689322329
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.314 [INFO] [trisolaris/synchronize] vtap.go:526 open cluster(d-rryPHO2btt) kubernetes_api_enabled VTap(ctrl_ip: 192.168.5.176, ctrl_mac: 00:16:3e:09:9e:eb, kubernetes_force_watch: false)
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.314 [INFO] [trisolaris/vtap] vtap.go:1115 start vtap register
Fri, Jul 14 2023 5:27:09 pm |  
Fri, Jul 14 2023 5:27:09 pm | 2023/07/14 17:27:09 /home/runnerx/actions-runner/_work/deepflow/deepflow/server/controller/trisolaris/dbmgr/dbmgr.go:256 record not found
Fri, Jul 14 2023 5:27:09 pm | [0.505ms] [rows:0] SELECT * FROM `vtap` WHERE `ctrl_ip` = '192.168.5.176' AND `ctrl_mac` = '00:16:3e:09:9e:eb' ORDER BY `vtap`.`id` LIMIT 1
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.315 [INFO] [trisolaris/vtap] vtap_discovery.go:693 register vtap: {tapMode:0 vTapGroupID: defaultVTapGroup:1bfd3e61-221e-11ee-b2f4-00163e0ee42f vTapAutoRegister:true VTapLKData:{ctrlIP:192.168.5.176 ctrlMac:00:16:3e:09:9e:eb hostIPs:[192.168.5.176 172.17.0.1 172.16.34.204 172.16.103.179 172.16.232.69 172.16.200.2 47.110.70.6 172.16.152.136 172.16.42.227 172.16.149.226 172.16.5.128 172.16.29.225 172.16.46.225 172.16.20.144 172.16.27.160 172.16.238.169 172.16.48.91 172.16.231.25 172.16.248.131 172.16.120.242 172.16.181.49 172.16.188.58 172.16.229.53 172.16.50.101 172.16.126.33 172.16.243.238 172.16.47.129 172.16.173.78 172.16.167.196 172.16.231.139 172.16.47.85 172.16.201.54 172.16.71.229 172.16.21.1 172.16.172.43 172.16.202.55 172.16.154.244 172.16.69.253 172.16.198.5 172.16.78.116 172.16.0.10 172.16.98.39 172.16.20.197 172.16.79.14 172.16.143.63 172.16.5.0 172.16.208.213 172.16.84.126 172.16.60.38 172.16.174.16 172.16.242.201 172.16.165.131 172.16.17.122 172.16.201.235 172.16.94.250 172.16.236.8 172.16.39.89 172.16.27.45 172.16.36.212 172.16.63.26 172.16.145.141 172.16.246.222 172.16.220.81 172.16.129.199 172.16.85.255 172.16.5.63 172.16.147.54 172.16.156.225 172.16.143.218 172.16.0.1 172.16.141.10 172.16.235.237 172.16.113.36 172.16.120.37 172.16.16.184 172.16.102.158 172.16.138.29 172.16.31.179 172.16.106.122 172.16.136.236 172.16.89.116 172.16.27.41 172.16.82.153 172.16.35.185 172.16.215.83 172.16.106.127 172.16.75.78 172.16.20.45 172.16.136.202 172.16.20.127 172.16.118.99 172.16.83.65 172.16.231.34 172.16.223.29 172.16.76.137 172.16.179.61 172.16.175.0 172.16.247.119 172.16.211.135 172.16.104.176 172.16.134.91 172.16.136.35 172.16.138.236 172.16.58.179 172.16.226.10 172.16.157.129 172.16.46.66 172.16.91.67 172.16.224.210 172.16.81.168 192.168.5.176 fc00::10ca:1 192.168.5.176] host:wz-simulator region:ffffffff-ffff-ffff-ffff-ffffffffffff}}
Fri, Jul 14 2023 5:27:09 pm |  
Fri, Jul 14 2023 5:27:09 pm | 2023/07/14 17:27:09 /home/runnerx/actions-runner/_work/deepflow/deepflow/server/controller/trisolaris/dbmgr/dbmgr.go:83 record not found
Fri, Jul 14 2023 5:27:09 pm | [0.614ms] [rows:0] SELECT * FROM `host_device` WHERE `ip` IN ('192.168.5.176','172.17.0.1','172.16.34.204','172.16.103.179','172.16.232.69','172.16.200.2','47.110.70.6','172.16.152.136','172.16.42.227','172.16.149.226','172.16.5.128','172.16.29.225','172.16.46.225','172.16.20.144','172.16.27.160','172.16.238.169','172.16.48.91','172.16.231.25','172.16.248.131','172.16.120.242','172.16.181.49','172.16.188.58','172.16.229.53','172.16.50.101','172.16.126.33','172.16.243.238','172.16.47.129','172.16.173.78','172.16.167.196','172.16.231.139','172.16.47.85','172.16.201.54','172.16.71.229','172.16.21.1','172.16.172.43','172.16.202.55','172.16.154.244','172.16.69.253','172.16.198.5','172.16.78.116','172.16.0.10','172.16.98.39','172.16.20.197','172.16.79.14','172.16.143.63','172.16.5.0','172.16.208.213','172.16.84.126','172.16.60.38','172.16.174.16','172.16.242.201','172.16.165.131','172.16.17.122','172.16.201.235','172.16.94.250','172.16.236.8','172.16.39.89','172.16.27.45','172.16.36.212','172.16.63.26','172.16.145.141','172.16.246.222','172.16.220.81','172.16.129.199','172.16.85.255','172.16.5.63','172.16.147.54','172.16.156.225','172.16.143.218','172.16.0.1','172.16.141.10','172.16.235.237','172.16.113.36','172.16.120.37','172.16.16.184','172.16.102.158','172.16.138.29','172.16.31.179','172.16.106.122','172.16.136.236','172.16.89.116','172.16.27.41','172.16.82.153','172.16.35.185','172.16.215.83','172.16.106.127','172.16.75.78','172.16.20.45','172.16.136.202','172.16.20.127','172.16.118.99','172.16.83.65','172.16.231.34','172.16.223.29','172.16.76.137','172.16.179.61','172.16.175.0','172.16.247.119','172.16.211.135','172.16.104.176','172.16.134.91','172.16.136.35','172.16.138.236','172.16.58.179','172.16.226.10','172.16.157.129','172.16.46.66','172.16.91.67','172.16.224.210','172.16.81.168','192.168.5.176','fc00::10ca:1','192.168.5.176') AND `host_device`.`deleted_at` IS NULL ORDER BY `host_device`.`id` LIMIT 1
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.316 [ERRO] [trisolaris/vtap] vtap_discovery.go:187 failed to register agent(192.168.5.176-00:16:3e:09:9e:eb) by querying DB table host_device(ip in ([192.168.5.176 172.17.0.1 172.16.34.204 172.16.103.179 172.16.232.69 172.16.200.2 47.110.70.6 172.16.152.136 172.16.42.227 172.16.149.226 172.16.5.128 172.16.29.225 172.16.46.225 172.16.20.144 172.16.27.160 172.16.238.169 172.16.48.91 172.16.231.25 172.16.248.131 172.16.120.242 172.16.181.49 172.16.188.58 172.16.229.53 172.16.50.101 172.16.126.33 172.16.243.238 172.16.47.129 172.16.173.78 172.16.167.196 172.16.231.139 172.16.47.85 172.16.201.54 172.16.71.229 172.16.21.1 172.16.172.43 172.16.202.55 172.16.154.244 172.16.69.253 172.16.198.5 172.16.78.116 172.16.0.10 172.16.98.39 172.16.20.197 172.16.79.14 172.16.143.63 172.16.5.0 172.16.208.213 172.16.84.126 172.16.60.38 172.16.174.16 172.16.242.201 172.16.165.131 172.16.17.122 172.16.201.235 172.16.94.250 172.16.236.8 172.16.39.89 172.16.27.45 172.16.36.212 172.16.63.26 172.16.145.141 172.16.246.222 172.16.220.81 172.16.129.199 172.16.85.255 172.16.5.63 172.16.147.54 172.16.156.225 172.16.143.218 172.16.0.1 172.16.141.10 172.16.235.237 172.16.113.36 172.16.120.37 172.16.16.184 172.16.102.158 172.16.138.29 172.16.31.179 172.16.106.122 172.16.136.236 172.16.89.116 172.16.27.41 172.16.82.153 172.16.35.185 172.16.215.83 172.16.106.127 172.16.75.78 172.16.20.45 172.16.136.202 172.16.20.127 172.16.118.99 172.16.83.65 172.16.231.34 172.16.223.29 172.16.76.137 172.16.179.61 172.16.175.0 172.16.247.119 172.16.211.135 172.16.104.176 172.16.134.91 172.16.136.35 172.16.138.236 172.16.58.179 172.16.226.10 172.16.157.129 172.16.46.66 172.16.91.67 172.16.224.210 172.16.81.168 192.168.5.176 fc00::10ca:1 192.168.5.176])) without finding data, err: record not found
Fri, Jul 14 2023 5:27:09 pm |  
Fri, Jul 14 2023 5:27:09 pm | 2023/07/14 17:27:09 /home/runnerx/actions-runner/_work/deepflow/deepflow/server/controller/trisolaris/dbmgr/dbmgr.go:160 record not found
Fri, Jul 14 2023 5:27:09 pm | [0.503ms] [rows:0] SELECT * FROM `host_device` WHERE `name` = 'wz-simulator' AND `host_device`.`deleted_at` IS NULL ORDER BY `host_device`.`id` LIMIT 1
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.317 [ERRO] [trisolaris/vtap] vtap_discovery.go:191 failed to register agent(192.168.5.176-00:16:3e:09:9e:eb) by querying DB table host_device(name in (wz-simulator)) without finding data, err: record not found
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.318 [ERRO] [trisolaris/vtap] vtap_discovery.go:262 failed to register agent(192.168.5.176-00:16:3e:09:9e:eb) by querying DB table pod_node(ip in ([192.168.5.176 172.17.0.1 172.16.34.204 172.16.103.179 172.16.232.69 172.16.200.2 47.110.70.6 172.16.152.136 172.16.42.227 172.16.149.226 172.16.5.128 172.16.29.225 172.16.46.225 172.16.20.144 172.16.27.160 172.16.238.169 172.16.48.91 172.16.231.25 172.16.248.131 172.16.120.242 172.16.181.49 172.16.188.58 172.16.229.53 172.16.50.101 172.16.126.33 172.16.243.238 172.16.47.129 172.16.173.78 172.16.167.196 172.16.231.139 172.16.47.85 172.16.201.54 172.16.71.229 172.16.21.1 172.16.172.43 172.16.202.55 172.16.154.244 172.16.69.253 172.16.198.5 172.16.78.116 172.16.0.10 172.16.98.39 172.16.20.197 172.16.79.14 172.16.143.63 172.16.5.0 172.16.208.213 172.16.84.126 172.16.60.38 172.16.174.16 172.16.242.201 172.16.165.131 172.16.17.122 172.16.201.235 172.16.94.250 172.16.236.8 172.16.39.89 172.16.27.45 172.16.36.212 172.16.63.26 172.16.145.141 172.16.246.222 172.16.220.81 172.16.129.199 172.16.85.255 172.16.5.63 172.16.147.54 172.16.156.225 172.16.143.218 172.16.0.1 172.16.141.10 172.16.235.237 172.16.113.36 172.16.120.37 172.16.16.184 172.16.102.158 172.16.138.29 172.16.31.179 172.16.106.122 172.16.136.236 172.16.89.116 172.16.27.41 172.16.82.153 172.16.35.185 172.16.215.83 172.16.106.127 172.16.75.78 172.16.20.45 172.16.136.202 172.16.20.127 172.16.118.99 172.16.83.65 172.16.231.34 172.16.223.29 172.16.76.137 172.16.179.61 172.16.175.0 172.16.247.119 172.16.211.135 172.16.104.176 172.16.134.91 172.16.136.35 172.16.138.236 172.16.58.179 172.16.226.10 172.16.157.129 172.16.46.66 172.16.91.67 172.16.224.210 172.16.81.168 192.168.5.176 fc00::10ca:1 192.168.5.176]) or name in (wz-simulator)) without finding data
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.319 [ERRO] [trisolaris/vtap] vtap_discovery.go:389 failed to register agent(192.168.5.176-00:16:3e:09:9e:eb) by querying DB table vinterface_ip(ip in ([192.168.5.176 172.17.0.1 172.16.34.204 172.16.103.179 172.16.232.69 172.16.200.2 47.110.70.6 172.16.152.136 172.16.42.227 172.16.149.226 172.16.5.128 172.16.29.225 172.16.46.225 172.16.20.144 172.16.27.160 172.16.238.169 172.16.48.91 172.16.231.25 172.16.248.131 172.16.120.242 172.16.181.49 172.16.188.58 172.16.229.53 172.16.50.101 172.16.126.33 172.16.243.238 172.16.47.129 172.16.173.78 172.16.167.196 172.16.231.139 172.16.47.85 172.16.201.54 172.16.71.229 172.16.21.1 172.16.172.43 172.16.202.55 172.16.154.244 172.16.69.253 172.16.198.5 172.16.78.116 172.16.0.10 172.16.98.39 172.16.20.197 172.16.79.14 172.16.143.63 172.16.5.0 172.16.208.213 172.16.84.126 172.16.60.38 172.16.174.16 172.16.242.201 172.16.165.131 172.16.17.122 172.16.201.235 172.16.94.250 172.16.236.8 172.16.39.89 172.16.27.45 172.16.36.212 172.16.63.26 172.16.145.141 172.16.246.222 172.16.220.81 172.16.129.199 172.16.85.255 172.16.5.63 172.16.147.54 172.16.156.225 172.16.143.218 172.16.0.1 172.16.141.10 172.16.235.237 172.16.113.36 172.16.120.37 172.16.16.184 172.16.102.158 172.16.138.29 172.16.31.179 172.16.106.122 172.16.136.236 172.16.89.116 172.16.27.41 172.16.82.153 172.16.35.185 172.16.215.83 172.16.106.127 172.16.75.78 172.16.20.45 172.16.136.202 172.16.20.127 172.16.118.99 172.16.83.65 172.16.231.34 172.16.223.29 172.16.76.137 172.16.179.61 172.16.175.0 172.16.247.119 172.16.211.135 172.16.104.176 172.16.134.91 172.16.136.35 172.16.138.236 172.16.58.179 172.16.226.10 172.16.157.129 172.16.46.66 172.16.91.67 172.16.224.210 172.16.81.168 192.168.5.176 fc00::10ca:1 192.168.5.176])) without finding data
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.319 [ERRO] [trisolaris/vtap] vtap_discovery.go:407 failed to register agent(192.168.5.176-00:16:3e:09:9e:eb) by querying DB table ip_resource(ip in ([192.168.5.176 172.17.0.1 172.16.34.204 172.16.103.179 172.16.232.69 172.16.200.2 47.110.70.6 172.16.152.136 172.16.42.227 172.16.149.226 172.16.5.128 172.16.29.225 172.16.46.225 172.16.20.144 172.16.27.160 172.16.238.169 172.16.48.91 172.16.231.25 172.16.248.131 172.16.120.242 172.16.181.49 172.16.188.58 172.16.229.53 172.16.50.101 172.16.126.33 172.16.243.238 172.16.47.129 172.16.173.78 172.16.167.196 172.16.231.139 172.16.47.85 172.16.201.54 172.16.71.229 172.16.21.1 172.16.172.43 172.16.202.55 172.16.154.244 172.16.69.253 172.16.198.5 172.16.78.116 172.16.0.10 172.16.98.39 172.16.20.197 172.16.79.14 172.16.143.63 172.16.5.0 172.16.208.213 172.16.84.126 172.16.60.38 172.16.174.16 172.16.242.201 172.16.165.131 172.16.17.122 172.16.201.235 172.16.94.250 172.16.236.8 172.16.39.89 172.16.27.45 172.16.36.212 172.16.63.26 172.16.145.141 172.16.246.222 172.16.220.81 172.16.129.199 172.16.85.255 172.16.5.63 172.16.147.54 172.16.156.225 172.16.143.218 172.16.0.1 172.16.141.10 172.16.235.237 172.16.113.36 172.16.120.37 172.16.16.184 172.16.102.158 172.16.138.29 172.16.31.179 172.16.106.122 172.16.136.236 172.16.89.116 172.16.27.41 172.16.82.153 172.16.35.185 172.16.215.83 172.16.106.127 172.16.75.78 172.16.20.45 172.16.136.202 172.16.20.127 172.16.118.99 172.16.83.65 172.16.231.34 172.16.223.29 172.16.76.137 172.16.179.61 172.16.175.0 172.16.247.119 172.16.211.135 172.16.104.176 172.16.134.91 172.16.136.35 172.16.138.236 172.16.58.179 172.16.226.10 172.16.157.129 172.16.46.66 172.16.91.67 172.16.224.210 172.16.81.168 192.168.5.176 fc00::10ca:1 192.168.5.176])) without finding data
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.319 [INFO] [trisolaris/vtap] vtap.go:1122 end vtap register
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.515 [INFO] [genesis] grpc_server.go:118 genesis sync received message with vtap_id 0 from 192.168.5.176
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.516 [INFO] [genesis] grpc_server.go:118 genesis sync received message with vtap_id 0 from 192.168.5.176
Fri, Jul 14 2023 5:27:09 pm | 2023-07-14 17:27:09.516 [INFO] [genesis] grpc_server.go:154 genesis sync received version 0 -> 1689322332 from ip 192.168.5.176 vtap_id 0
Fri, Jul 14 2023 5:27:11 pm | 2023-07-14 17:27:11.342 [INFO] [trisolaris/synchronize] ntp.go:37 request ntp proxcy from ip: 192.168.5.176
Fri, Jul 14 2023 5:27:12 pm | 2023-07-14 17:27:12.784 [INFO] [trisolaris/vtap] process_info.go:1066 start generate gpid data from timed
Fri, Jul 14 2023 5:27:12 pm | 2023-07-14 17:27:12.786 [INFO] [trisolaris/vtap] process_info.go:1068 end generate gpid data from timed
Fri, Jul 14 2023 5:27:16 pm | 2023-07-14 17:27:16.571 [WARN] [genesis] grpc_server.go:198 kubernetes api sync received message with vtap_id 0 from 192.168.5.176
Fri, Jul 14 2023 5:27:16 pm | 2023-07-14 17:27:16.571 [INFO] [genesis] grpc_server.go:257 kubernetes api sync received version 1689322405 from ip 192.168.5.176 no vtap_id
Fri, Jul 14 2023 5:27:17 pm | 2023-07-14 17:27:17.638 [GIN] 192.168.102.132 GET /v1/health/ 200 42.598µs
Fri, Jul 14 2023 5:27:17 pm | 2023-07-14 17:27:17.638 [GIN] 192.168.102.132 GET /v1/health/ 200 30.163µs
Fri, Jul 14 2023 5:27:21 pm | 2023-07-14 17:27:21.785 [INFO] [trisolaris/vtap] process_info.go:1066 start generate gpid data from timed
Fri, Jul 14 2023 5:27:21 pm | 2023-07-14 17:27:21.786 [INFO] [trisolaris/vtap] process_info.go:1068 end generate gpid data from timed
Fri, Jul 14 2023 5:27:27 pm | 2023-07-14 17:27:27.637 [GIN] 192.168.102.132 GET /v1/health/ 200 32.178µs
Fri, Jul 14 2023 5:27:30 pm | 2023-07-14 17:27:30.784 [INFO] [trisolaris/vtap] process_info.go:1066 start generate gpid data from timed
Fri, Jul 14 2023 5:27:30 pm | 2023-07-14 17:27:30.786 [INFO] [trisolaris/vtap] process_info.go:1068 end generate gpid data from timed
Fri, Jul 14 2023 5:27:33 pm | 2023-07-14 17:27:33.804 [INFO] [cloud] kubernetes_gather_task.go:97 kubernetes gather (k8s-d-rryPHO2btt) assemble data starting
Fri, Jul 14 2023 5:27:33 pm | 2023-07-14 17:27:33.838 [ERRO] [cloud.kubernetes_gather] pod_service.go:112 service labels initialization simplejson error: (EOF)
Fri, Jul 14 2023 5:27:33 pm | 2023-07-14 17:27:33.838 [INFO] [cloud] kubernetes_gather_task.go:109 kubernetes gather (k8s-d-rryPHO2btt) assemble data complete
Fri, Jul 14 2023 5:27:37 pm | 2023-07-14 17:27:37.638 [GIN] 192.168.102.132 GET /v1/health/ 200 48.615µs
Fri, Jul 14 2023 5:27:37 pm | 2023-07-14 17:27:37.638 [GIN] 192.168.102.132 GET /v1/health/ 200 30.871µs
Fri, Jul 14 2023 5:27:39 pm | 2023-07-14 17:27:39.784 [INFO] [trisolaris/vtap] process_info.go:1066 start generate gpid data from timed
Fri, Jul 14 2023 5:27:39 pm | 2023-07-14 17:27:39.786 [INFO] [trisolaris/vtap] process_info.go:1068 end generate gpid data from timed
Fri, Jul 14 2023 5:27:45 pm | 2023-07-14 17:27:45.808 [WARN] [trisolaris/synchronize] vtap.go:270 vtap (ctrl_ip: 192.168.102.117, ctrl_mac: 00:16:3e:0f:8d:b8, host_ips: [192.168.102.117 172.16.47.85 172.16.0.10 172.16.172.43 172.16.113.36 172.16.60.38 172.16.120.242 172.16.138.29 172.16.141.10 172.16.78.116 172.16.223.29 172.16.143.63 172.16.27.45 172.16.34.204 172.16.232.69 172.16.71.229 172.16.29.225 47.110.70.6 172.16.143.218 172.16.50.101 172.16.136.202 172.16.188.58 172.16.36.212 172.16.156.225 172.16.120.37 172.16.235.237 172.16.20.45 172.16.83.65 172.16.47.129 172.16.200.2 172.16.31.179 172.16.231.34 172.16.5.0 172.16.75.78 172.16.76.137 172.16.154.244 172.16.84.126 172.16.229.53 172.16.145.141 172.16.215.83 172.16.39.89 172.16.102.158 172.16.136.236 172.16.174.16 172.16.149.226 172.16.21.1 172.16.82.153 172.16.231.25 172.16.236.8 172.16.173.78 172.16.69.253 172.16.165.131 172.16.27.160 172.16.63.26 172.16.20.144 172.16.106.127 172.16.152.136 172.16.94.250 172.16.167.196 172.16.246.222 172.16.231.139 172.16.17.122 172.16.118.99 172.16.220.81 172.16.20.197 172.16.181.49 172.16.208.213 172.16.129.199 172.16.35.185 172.16.238.169 172.16.201.235 172.16.198.5 172.16.16.184 172.16.98.39 172.16.106.122 172.16.126.33 172.16.103.179 172.16.242.201 172.16.5.63 172.16.5.128 172.16.46.225 172.16.248.131 172.16.147.54 172.16.27.41 172.16.79.14 172.16.0.1 172.16.89.116 172.16.243.238 172.16.20.127 172.16.85.255 172.16.42.227 172.16.202.55 172.16.201.54 172.16.48.91 172.16.179.61 172.16.175.0 172.16.247.119 172.16.211.135 172.16.104.176 172.16.134.91 172.16.136.35 172.16.138.236 172.16.58.179 172.16.224.210 172.16.46.66 172.16.91.67 172.16.157.129 172.16.226.10 172.16.81.168 192.168.102.117 192.168.102.117 fc00::10ca:1], kubernetes_cluster_id: d-rryPHO2btt, kubernetes_force_watch: false, group_id: ) not found in cache. NAME:deepflow-agent-ce REVISION:v6.2.6.5 8265-3d888cab7e15db5d4f5a51eacf7703acc60ff7a9 BOOT_TIME:1689322365
Fri, Jul 14 2023 5:27:45 pm | 2023-07-14 17:27:45.808 [INFO] [trisolaris/vtap] vtap.go:1115 start vtap register
Fri, Jul 14 2023 5:27:45 pm |  
Fri, Jul 14 2023 5:27:45 pm | 2023/07/14 17:27:45 /home/runnerx/actions-runner/_work/deepflow/deepflow/server/controller/trisolaris/dbmgr/dbmgr.go:256 record not found
Fri, Jul 14 2023 5:27:45 pm | [0.519ms] [rows:0] SELECT * FROM `vtap` WHERE `ctrl_ip` = '192.168.102.117' AND `ctrl_mac` = '00:16:3e:0f:8d:b8' ORDER BY `vtap`.`id` LIMIT 1
Fri, Jul 14 2023 5:27:45 pm | 2023-07-14 17:27:45.810 [INFO] [trisolaris/vtap] vtap_discovery.go:693 register vtap: {tapMode:0 vTapGroupID: defaultVTapGroup:1bfd3e61-221e-11ee-b2f4-00163e0ee42f vTapAutoRegister:true VTapLKData:{ctrlIP:192.168.102.117 ctrlMac:00:16:3e:0f:8d:b8 hostIPs:[192.168.102.117 172.16.47.85 172.16.0.10 172.16.172.43 172.16.113.36 172.16.60.38 172.16.120.242 172.16.138.29 172.16.141.10 172.16.78.116 172.16.223.29 172.16.143.63 172.16.27.45 172.16.34.204 172.16.232.69 172.16.71.229 172.16.29.225 47.110.70.6 172.16.143.218 172.16.50.101 172.16.136.202 172.16.188.58 172.16.36.212 172.16.156.225 172.16.120.37 172.16.235.237 172.16.20.45 172.16.83.65 172.16.47.129 172.16.200.2 172.16.31.179 172.16.231.34 172.16.5.0 172.16.75.78 172.16.76.137 172.16.154.244 172.16.84.126 172.16.229.53 172.16.145.141 172.16.215.83 172.16.39.89 172.16.102.158 172.16.136.236 172.16.174.16 172.16.149.226 172.16.21.1 172.16.82.153 172.16.231.25 172.16.236.8 172.16.173.78 172.16.69.253 172.16.165.131 172.16.27.160 172.16.63.26 172.16.20.144 172.16.106.127 172.16.152.136 172.16.94.250 172.16.167.196 172.16.246.222 172.16.231.139 172.16.17.122 172.16.118.99 172.16.220.81 172.16.20.197 172.16.181.49 172.16.208.213 172.16.129.199 172.16.35.185 172.16.238.169 172.16.201.235 172.16.198.5 172.16.16.184 172.16.98.39 172.16.106.122 172.16.126.33 172.16.103.179 172.16.242.201 172.16.5.63 172.16.5.128 172.16.46.225 172.16.248.131 172.16.147.54 172.16.27.41 172.16.79.14 172.16.0.1 172.16.89.116 172.16.243.238 172.16.20.127 172.16.85.255 172.16.42.227 172.16.202.55 172.16.201.54 172.16.48.91 172.16.179.61 172.16.175.0 172.16.247.119 172.16.211.135 172.16.104.176 172.16.134.91 172.16.136.35 172.16.138.236 172.16.58.179 172.16.224.210 172.16.46.66 172.16.91.67 172.16.157.129 172.16.226.10 172.16.81.168 192.168.102.117 192.168.102.117 fc00::10ca:1 192.168.102.117] host:test-wz-012 region:ffffffff-ffff-ffff-ffff-ffffffffffff}}
Fri, Jul 14 2023 5:27:45 pm |  
Fri, Jul 14 2023 5:27:45 pm | 2023/07/14 17:27:45 /home/runnerx/actions-runner/_work/deepflow/deepflow/server/controller/trisolaris/dbmgr/dbmgr.go:83 record not found

</body>
</html>

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
deepflow-ctl 连接server的默认ip和端口是本机ip的30417端口，在node节点上默认会打开30417端口，如果在node节点上执行命令，默认不需要指定server的ip和端口

**Comment by dundun9** [comment]
看日志，应该等一会就好了

**Comment by chengzhenge** [comment]
现在还没有好，报错内容和之前一样，一直这样 空的；
# deepflow-ctl agent list
ID       NAME TYPE       CTRL_IP          CTRL_MAC           STATE    GROUP EXCEPTIONS

> 看日志，应该等一会就好了

**Comment by chengzhenge** [comment]
现在也还是一样的报错
