### ISSUE TITLE
[BUG] Prometheus remote writer endpoint stopped working after update to 6.3.x

### ISSUE THREAD

**Issue by dirtyren** [deepflowio/deepflow#3615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

After updating to 6.3.x, I am running 6.3.3, the prometheus remote writer endpoint stopped working,

### How to reproduce

Just upgrade to 6,3,x,

### DeepFlow version

```bash 
2023/07/17 11:05:24 ENV K8S_NODE_NAME_FOR_DEEPFLOW=gke-c-hj29c-default-2-c87e3ca7-hpuv; K8S_NODE_IP_FOR_DEEPFLOW=10.93.149.18; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-6888df5579-cdpmn; K8S_POD_IP_FOR_DEEPFLOW=100.96.25.92; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: v6.3.3
CommitID: 0170e213d9f7a941b6a89f168672363f6cca9692
RevCount: 8512
Compiler: go version go1.20.6 linux/amd64
CompileTime: 2023-07-14 07:36:01

kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
8512-0170e213d9f7a941b6a89f168672363f6cca9692
Name: deepflow-agent community edition
Branch: v6.3.3
CommitId: 0170e213d9f7a941b6a89f168672363f6cca9692
RevCount: 8512
Compiler: rustc 1.70.0 (90c541806 2023-05-31)
CompileTime: 2023-07-14 07:36:33
a

```

### DeepFlow agent list

```bash
root@swiss-army-knife-6dc455b4b4-827zv:~# deepflow-ctl --ip deepflow-server.deepflow.svc.cluster.local --api-port 20417 agent list
NAME                                    TYPE       CTRL_IP          CTRL_MAC           STATE    GROUP   EXCEPTIONS
gke-c-hj29c-default-2-a282ba21-lw7y-V40 K8S_VM     10.93.149.56     42:01:0a:5d:95:38  NORMAL   default
gke-c-hj29c-default-2-c87e3ca7-hpuv-V42 K8S_VM     10.93.149.18     42:01:0a:5d:95:12  NORMAL   default
gke-c-hj29c-default-2-c87e3ca7-bmax-V43 K8S_VM     10.93.149.55     42:01:0a:5d:95:37  NORMAL   default
gke-c-hj29c-default-2-bd82f8be-5in7-V44 K8S_VM     10.93.149.20     42:01:0a:5d:95:14  NORMAL   default
r
````

### Operation-System/Kernel version

```bash
"Container-Optimized OS from Google"
5.10.162+
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dirtyren** [comment]
```bahs
deepflow-ctl agent-group-config list -o yaml

vtap_group_id: g-b15b2f08ef
tap_interface_regex: ^(tap.*|gke.*|cali.*|veth.*|eth.*|en[ospx].*|lxc.*|lo|[0-9a-f]+_h)$
external_agent_http_proxy_enabled: 1
external_agent_http_proxy_port: 38086

```

**Comment by dirtyren** [comment]
Just to add anther information. The Otel collector endpoint is working and receiving tracings. The prometheus endpoint seems to be there, because it answers 200 to the prometheus trying to remote write on deeepflow, but nothing is stored on the ext_metrics database on Clickhouse.
I also did not find any error message on the deepflow-agent pods or on the deepflow server.
Let me know if you need anything else.

**Comment by dundun9** [comment]
We've made a few changes to this feature and will update the documentation today. You can also start by adding the following configuration in agent-group-config with the ip and port of prometheus-server

`prometheus_http_api_address: http://192.168.67.180:80`

**Comment by dundun9** [comment]
Noteby default, we consider an agent to work on only one cluster and only access remote-write data from prometheus-server for that cluster

**Comment by dundun9** [comment]
> Hey @dundun9 , I tried the the above config and it did not work. Anything I am missing? Tks a lot.

It needs to be configured via agent-group-config,`deepflow-ctl agent-group-config list -o yaml` to see if it is configured

**Comment by dirtyren** [comment]
I did set up this away. Cheking the deepflow-agent logs it show de options is configured. Unfortunately, no remote writer data from pormetheus is being ingested.
`
} to PlatformConfig {
    sync_interval: 60s,
    kubernetes_cluster_id: "d-dr8m4s8MZP",
    prometheus_http_api_address: "http://10.93.140.3:80",
    libvirt_xml_path: "/etc/libvirt/qemu/",
    kubernetes_poller_type: Adaptive,
    vtap_id: 33,
    enabled: false,
    ingress_flavour: Kubernetes,
    trident_type: TtVmPod,
    epc_id: 1,
    kubernetes_api_enabled: false,
    kubernetes_api_list_limit: 1000,
    kubernetes_api_list_interval: 600s,
`

**Comment by taloric** [comment]
@dirtyren hello, maybe you need to try this out:
- use [this](https://gist.github.com/taloric/f7006bb1b9c1ee5dd86a706e490b97af) as a dashboard to view status of `prometheus target` we captured in deepflow databases. If you see nothing, plz let us know.
- the most important info in this dashboard would be `Targets Count` and `Metrics Count` in `Mysql info` and `Metrics to Target Label` and `Metrics to App Label` in `Clickhouse Info`. Plz show us if you don't mind.

Thanks for the feedback!

**Comment by dundun9** [comment]
Try using the latest helm chart and just fixed a configuration error
`https://github.com/deepflowio/deepflow-charts/commit/8f3f24a635e6e49b9112534307f25717d94bd767`

**Comment by dundun9** [comment]
> Try using the latest helm chart and just fixed a configuration error [deepflowio/deepflow-charts@8f3f24a](https://github.com/deepflowio/deepflow-charts/commit/8f3f24a635e6e49b9112534307f25717d94bd767)

And update deepflow-server to latest

**Comment by dirtyren** [comment]
Hey @dundun9 , I just updated the chart and de configmap for clickhouse and deploy the dashboard you sent. What`s happening is that some metrics are getting ingested info deepflow while other are not, all coming from the same prometheus.
   I don`t really know why this is happening and what I could to to help debug that, please let me know.
   Another question, about how this new feature is working:
- The agent will fetch all the /target on the prometheus endpoint suplied
- The prometheus remote writer feature should be set to effectively send the metrics to deepflow prometheus remote writer endpoint 

   Is this correct? Tks a lot.

**Comment by taloric** [comment]
@dirtyren tks for the feedback.
> * The agent will fetch all the /target on the prometheus endpoint suplied

that's true, but not fully describe what's happening: as we know, prometheu will inject some `labels` through its configuration when scrape or receive metrics, that's so called `target label`, the `deepflow agent` will try to get all active target and their target labels .

> * The prometheus remote writer feature should be set to effectively send the metrics to deepflow prometheus remote writer endpoint

I'm not sure what's the meaning of `effectively`, all we need to do is config `remote_write`  with deepflow remote writer endpoint is fine.

besides, 
> some metrics are getting ingested info deepflow while other are not

I'm also not sure what's happening, can you show us some examples? like: 
- query some series in prometheus server (web), but get nothing with deepflow prometheus datasource, the metric is: `xxxx` from `xxxxExporter`.
- remember the dashboard I show you last time? you can find out in the dashboard about `how to get a metric` in deepflow storage, also, if you don't mind, you can try give us some dashboard query result with THE specific `metric name`.

again, thanks for the feedback, hope it helps

**Comment by dirtyren** [comment]
> 

Tks @taloric for getting back to me on that.
Just onde question before I set up the remote writer test again, the metric changes name when it is ingested into deepflow? If this is the case, this could be the reason.

   The test I did was to send all data com opencost.io on our K8S Cluster to victoria metricas and deepflow, the dashboard using the victoria metrics datasource was working 100% and the same dashborad using de deepflow prometheus datasource was not, just a few metrics were working.

   []s.

**Comment by taloric** [comment]
@dirtyren 
It won't change any metric name when it ingested into deepflow. But maybe I can tell what's happening.. you can check if all `target urls` are config completely under deepflow agent configuration yaml. All targets that write any series into deepflow should be found in `target urls`. To make sure this is working , you can try to find out if there are logs in deepflow server which says something like `target missing`.

**Comment by dundun9** [comment]
Sorry, try to update helm chart again

**Comment by dundun9** [comment]
![image](https://github.com/deepflowio/deepflow/assets/50027289/40464661-1a6f-4863-a93a-709e57c33e1f)
`kubectl get cm -n deepflow deepflow-clickhouse-config -o yaml| grep allow_experimental_live_view`
Update the helm chart again and check to see if clickhouse includes this configuration

**Comment by dirtyren** [comment]
> ![image](https://user-images.githubusercontent.com/50027289/255562551-40464661-1a6f-4863-a93a-709e57c33e1f.png) `kubectl get cm -n deepflow deepflow-clickhouse-config -o yaml| grep allow_experimental_live_view` Update the helm chart again and check to see if clickhouse includes this configuration

#  kubectl get cm -n deepflow deepflow-clickhouse-config -o yaml| grep allow_experimental_live_view
# <allow_experimental_live_view>1</allow_experimental_live_view>

The configation is there. I will check the targets, trey to find which metrics are not there.

**Comment by dirtyren** [comment]
So, let me show the target I am testes

**This is the opencost target as seen on the dashboard you sent me**

![image](https://github.com/deepflowio/deepflow/assets/1627055/ec0cee59-cb20-4e6d-875a-4eefd457a934)


**This is teh Kubecost dashboards from the deepflow prometheus datasource**
![image](https://github.com/deepflowio/deepflow/assets/1627055/407b97d2-f396-4093-bdac-946219ec4203)


This is how the dashboard should look like. This is the victoria metricas datasource
![image](https://github.com/deepflowio/deepflow/assets/1627055/9ca70e1c-d178-4237-9fad-4a70a438318c)

I have this error on the deepflow-server logs

`
2023-07-24 10:51:47.091 [ERRO] [prometheus.synchronizer] synchronizer.go:381 label value id not found, values: [storageNode vmcluster-victoria-metrics-cluster-vmstorage-0.vmcluster-victoria-metrics-cluster-vmstorage.victoria-metrics.svc.cluster.local:8400,vmcluster-victoria-metrics-cluster-vmstorage-1.vmcluster-victoria-metrics-cluster-vmstorage.victoria-metrics.svc.cluster.local:8400 vmcluster-victoria-metrics-cluster-vmstorage-0.vmcluster-victoria-metrics-cluster-vmstorage.victoria-metrics.svc.cluster.local:8401,vmcluster-victoria-metrics-cluster-vmstorage-1.vmcluster-victoria-metrics-cluster-vmstorage.victoria-metrics.svc.cluster.local:8401]
`

I dont have any missing metrics on the logs.

Please, let me know if I can send you any other debug logs.
By the way, I am running Deepflow 6.3.3.

[]s.

**Comment by dirtyren** [comment]
Just to add one metric name, this metric is on victoria metrics and it is not on deepflow. The same prometheus writes to victoria metrics and deepflow, so this metric should be present on both.

node_total_hourly_cost
![image](https://github.com/deepflowio/deepflow/assets/1627055/c85cc1bc-9975-4b3f-ac8b-c7f6e7150221)

![image](https://github.com/deepflowio/deepflow/assets/1627055/a048a7a9-34dc-4abe-bbcc-a6b9b70410b5)


a a example of a metrica that exists on both
pv_hourly_cost
![image](https://github.com/deepflowio/deepflow/assets/1627055/b3a1dee0-1764-4f5c-8ea4-828adb50d9f9)

![image](https://github.com/deepflowio/deepflow/assets/1627055/4ccb1026-c1a0-4279-8f35-f979285d7e82)

I hope this can help.

**Comment by taloric** [comment]
@dirtyren tks, got it.
can you found a target like `instance=gke-c-hj29c-xxx`  and `job=opencost` in the dashboard? Currently, when a series being ingested to deepflow, we need to verify if the series comes from the `targets` we captured. But you just show me the `instance=100.xxx` target . So I wondering if there are errors in target capturing.

**Comment by dirtyren** [comment]
> node_total_hourly_cost

Is that what you needed? Tks.

victoria metrics datasource
![image](https://github.com/deepflowio/deepflow/assets/1627055/05b8e5df-b852-4282-bba7-24a33f6176cd)



deepflow datasource
![image](https://github.com/deepflowio/deepflow/assets/1627055/0d9abbcb-06b1-4bd6-80fb-5de7293b4549)

**Comment by taloric** [comment]
no, I mean something like this: 
![image](https://user-images.githubusercontent.com/1627055/255608888-ec0cee59-cb20-4e6d-875a-4eefd457a934.png)

my expectation: should show a target like this but `instance` like `gke-c-xxx`

**Comment by dirtyren** [comment]
> no, I mean something like this: ![image](https://user-images.githubusercontent.com/1627055/255608888-ec0cee59-cb20-4e6d-875a-4eefd457a934.png)
> 
> my expectation: should show a target like this but `instance` like `gke-c-xxx`

So, this metric has de instance like GKE and job opencost and it is not getting ingested by deepflow

node_total_hourly_cost{instance="gke-c-hj29c-default-2-bd82f8be-5in7",job="opencost"}
![image](https://github.com/deepflowio/deepflow/assets/1627055/47201a5c-ce37-451b-9b54-c5c83624b029)

**Comment by taloric** [comment]
> So, this metric has de instance like GKE and job opencost and it is not getting ingested by deepflow
> 
> node_total_hourly_cost{instance="gke-c-hj29c-default-2-bd82f8be-5in7",job="opencost"} ![image](https://user-images.githubusercontent.com/1627055/256926303-47201a5c-ce37-451b-9b54-c5c83624b029.png)

yes, that's what we're tryin to figure out... all target (identified by `instance` and `job`) should be found in the target list. If is not, maybe we can try to find out why:
1. do you have multiple prometheus servers ?
2. are there some other mechanisms in `opencost` , which will overwrite `instance` tags, that causes we can't get `gke-xx` instance through `/api/v1/targets` ?

**Comment by dirtyren** [comment]
> > So, this metric has de instance like GKE and job opencost and it is not getting ingested by deepflow
> > node_total_hourly_cost{instance="gke-c-hj29c-default-2-bd82f8be-5in7",job="opencost"} ![image](https://user-images.githubusercontent.com/1627055/256926303-47201a5c-ce37-451b-9b54-c5c83624b029.png)
> 
> yes, that's what we're tryin to figure out... all target (identified by `instance` and `job`) should be found in the target list. If is not, maybe we can try to find out why:
> 
> 1. do you have multiple prometheus servers ?
    
    We have a lot o prometheus running, but for all this issue, just one is beeing tested, just one it set up to remote writer on deepflow.
 
> 2. are there some other mechanisms in `opencost` , which will overwrite `instance` tags, that causes we can't get `gke-xx` instance through `/api/v1/targets` ?


 This is how vmagent is setup to scrape the opencost metrics. On the Targets list the instance is the internal POD IP where opencost is running. But the metrics it returns are from the GKE nodes instances, gke-xyz. Is this maybe the problema here?

![image](https://github.com/deepflowio/deepflow/assets/1627055/75025f46-d51e-4428-b12e-9c1a6f8d4748)

The opencost endpoint http://100.126.1.150:9003/metrics has the metrics that prometheus effectively scrapes. I am not seeing how you are connecting metrics from the targets with the remote writer. Deepflow agent you scrape http://100.126.1.150:9003/metrics?

   Tks.

**Comment by taloric** [comment]
> This is how vmagent is setup to scrape the opencost metrics. On the Targets list the instance is the internal POD IP where opencost is running. But the metrics it returns are from the GKE nodes instances, gke-xyz. Is this maybe the problema here?

yes, that's the problem. tks! 

>I am not seeing how you are connecting metrics from the targets with the remote writer. Deepflow agent you scrape http://100.126.1.150:9003/metrics?

no, DeepFlow agent won't scrape any targets, but it will identify `series` with specific `targets` to enhance our performace during remote-writing and quering.

anyway, we all see what's happening and how this issue influence metric query, I think we should take a further research with this issue and fix it, tks!

**Comment by taloric** [comment]
@dirtyren hello, if you don't mind, could you find `honor_labels` config in your own scrape configs? 
maybe something like this:
```yaml
- job_name: opencost
  honor_labels: true
...
```

we want to know what's the value of `honor_labels` in your own config under `opencost` job, tks ~

**Comment by dirtyren** [comment]
> 

It is set.
`
    - job_name: opencost
      honor_labels: true
      scrape_interval: 1m
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      dns_sd_configs:
      - names:
        - opencost.opencost.svc.cluster.local
        type: 'A'
        port: 9003
`

**Comment by taloric** [comment]
@dirtyren tks a lot

**Comment by taloric** [comment]
@dirtyren hello, we recently updated this issue in the latest 6.3 version, you can update `deepflow-server` images to `v6.3` tag for the latest version, then you can retry this with such configurations:
```yaml
prometheus_http_api_addresses:
- http://host1:port1
- http://host2:port2
```

then use `deepflow-ctl agent-group-config update -f xxxxx.yaml` to update this.
plz feel free to reach us if there're any issue with this, thanks~

**Comment by dirtyren** [comment]
Ok, tks a lot.
