### ISSUE TITLE
Application Request Log 面板 PostgreSQL协议 Response Status 为 “Server Error”，请求内容为空。

### ISSUE THREAD

**Issue by smart-aiops** [deepflowio/deepflow#3634]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

**Application Request Log 面板 PostgreSQL协议 Response Status 为 “Server Error”，请求内容为空。**

![image](https://github.com/deepflowio/deepflow/assets/851243/19dd6b71-60a2-46c6-bec8-1c703a29b5eb)

![image](https://github.com/deepflowio/deepflow/assets/851243/ba3d8920-1682-4317-b917-e33a17e435d7)

### DeepFlow version

**kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v**
![image](https://github.com/deepflowio/deepflow/assets/851243/6839b99c-9fed-4c29-bc1e-f05b4f6fface)

**kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v**
![image](https://github.com/deepflowio/deepflow/assets/851243/027b2993-5f19-4452-bf52-703068909ba3)

### DeepFlow agent list

**deepflow-ctl agent list**
![image](https://github.com/deepflowio/deepflow/assets/851243/c89c7782-def1-4104-9194-3232d27de835)

### Kubernetes CNI

**k8s版本**
v1.16.10
![image](https://github.com/deepflowio/deepflow/assets/851243/b651f85c-ba6c-4db4-a7c2-dfa773151fb3)

**calico版本**
v3.13.4
![image](https://github.com/deepflowio/deepflow/assets/851243/caba8c96-2883-42ad-b1bd-bf78ed2ec2e3)

### Operation-System/Kernel version

![image](https://github.com/deepflowio/deepflow/assets/851243/69f60e7a-fe92-4683-9a41-cee9d6e4f279)

### Anything else

抓包：
客户端pod

[client_cap.zip](https://github.com/deepflowio/deepflow/files/12091769/client_cap.zip)

服务端pod
[sever_cap.zip](https://github.com/deepflowio/deepflow/files/12091771/sever_cap.zip)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by cooper190113** [comment]
**kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v**

![image](https://github.com/deepflowio/deepflow/assets/851243/f25eb0e7-506b-4b00-8063-f9afa03ed6b4)

**Comment by 1473371932** [comment]
你好，可尝试更新到最新的 LTS 版本 v6.6，在这几个版本中，我们对协议解析做了很多优化（注：大版本更新时需要清理旧数据后重新部署）

新版本中，PostgreSQL协议不在[默认](https://www.deepflow.io/docs/zh/features/l7-protocols/overview/)的解析中，需要通过 [deepflow-ctl](https://www.deepflow.io/docs/zh/best-practice/agent-advanced-config/) 在 [agent-group-config](https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L1090) 添加此协议的解析
