### ISSUE TITLE
[BUG] prometheus query error

### ISSUE THREAD

**Issue by liexe** [deepflowio/deepflow#3635]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

   使用promql语句 node_cpu_seconds_total{mode="idle"}调用deepflow-server prometheus 查询接口出现如下异常：
```
  [31m2023-07-19 14:18:19.701 [ERRO][0m [clickhouse.client] client.go:121 query clickhouse Error: code: 42, message: Function tuple requires at least one argument.: While processing tuple(): While processing (metric_id = 184) AND ((time >= 1689743595) AND (time <= 1689747495)) AND (app_label_value_id_1 IN tuple()), sql: WITH toUnixTimestamp(time) AS `timestamp` SELECT `timestamp`, value, toJSONString(mapUpdate(map('mode',dictGet(flow_tag.app_label_map, 'label_value', (184, 54, app_label_value_id_1)),'cpu',dictGet(flow_tag.app_label_map, 'label_value', (184, 61, app_label_value_id_2))),CAST((splitByString(', ', dictGet(flow_tag.prometheus_target_label_layout_map, 'target_label_names', target_id)), splitByString(', ', dictGet(flow_tag.prometheus_target_label_layout_map, 'target_label_values', target_id))), 'Map(String, String)'))) AS `tag` FROM prometheus.`samples` PREWHERE (metric_id=184) AND (`time` >= 1689743595 AND `time` <= 1689747495) AND app_label_value_id_1 IN () ORDER BY `timestamp` desc LIMIT 10000, query_uuid: 0487a6f9-ff91-458c-b2d0-35e77b43fd95
```
    debug发现是由于app_label_live_view没有相应label value的数据造成的。

   查看代码发现deepflow server为了优化prometheus查询效率，引入了clickhouse live view， 但是 flow_tag.app_label_live_view 这个live view的数据从创建之后就一直没有刷新， 这时flow_tag.app_label_map 已经有1000多行数据，但是flow_tag.app_label_live_view才400多行，手动执行ALTER LIVE VIEW flow_tag.app_label_live_view REFRESH 刷新依然无效，导致通过某些未同步的label进行查询失败。

### How to reproduce

在确认live view 已经完成创建之后，一段时间之后live view与tag 表的数据出现不同步，使用新的lable value进行查询出现异常

### DeepFlow version

6.3.3

### Operation-System/Kernel version

ubuntu 22.04 
Kernel version: 5.15.0-69

### Anything else

clickhouse: v23.2.1

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
Try using the latest helm chart and just fixed a configuration error
`https://github.com/deepflowio/deepflow-charts/commit/8f3f24a635e6e49b9112534307f25717d94bd767`

**Comment by liexe** [comment]
更新了代码再次验证，ALTER LIVE VIEW flow_tag.xxx REFRESH语句确实执行了，也没有异常，但是从结果来看LIVE VIEW表的数据依然未刷新
<img width="949" alt="image" src="https://github.com/deepflowio/deepflow/assets/25686197/e7471eb6-99b2-4579-9974-4e48cbf19cb4">
<img width="756" alt="image" src="https://github.com/deepflowio/deepflow/assets/25686197/ddaf5fa1-10c6-405c-804e-2460501b172e">
<img width="833" alt="image" src="https://github.com/deepflowio/deepflow/assets/25686197/72e92311-5743-408d-9dc6-ff2df1d31aed">

   修改LIVE VIEW 新建语句 添加 WITH PERIODIC REFRESH 10 之后，数据能够自动刷新了，然后把这个值改大到6000，观察代码执行ALTER LIVE VIEW flow_tag.xxx REFRESH 的效果，结果LIVE VIEW表数据未刷新，是否可以说明ALTER LIVE VIEW flow_tag.xxx REFRESH这个强制刷新操作是完全无效的？如果去掉代码强制刷新，改为clickhouse自动刷新的方式是否可行呢？

**Comment by xiaochaoren1** [comment]
请用最新的main版本，我们做的是触发式刷新view，数据发生变化时，会刷新view；创建view的语句也会定时检查，如果被修改了，也会再自动改回去；相关代码文件为：https://github.com/deepflowio/deepflow/blob/main/server/controller/tagrecorder/dictionary.go

**Comment by liexe** [comment]
@xiaochaoren1 大佬你好，我现在使用是最新的main代码，触发式刷新这种设计思路我认为没有问题，很合理，现在的主要问题是ALTER LIVE VIEW flow_tag.xxx REFRESH这个刷新操作据我观察没有效果，执行刷新之后LIVE VIEW依然没有同步，不知道是否是我使用的clickhouse版本(v23.2.1)存在问题 ？

**Comment by xiaochaoren1** [comment]
> 

我们的版本是v22.8.6，之前没注意这里，我再测试下ALTER LIVE VIEW flow_tag.xxx REFRESH 这个是否真的生效

**Comment by xiaochaoren1** [comment]
![image](https://github.com/deepflowio/deepflow/assets/42240939/9df80e52-07b5-41ee-b32e-95d361e200fe)
经过更新字段的值进行测试，v22.8.6版本，ALTER LIVE VIEW flow_tag.xxx REFRESH确实生效了

**Comment by liexe** [comment]
@xiaochaoren1 谢谢大佬，我降级到 V22.8.6.71 版本之后再次验证，确实可以了：

<img width="775" alt="image" src="https://github.com/deepflowio/deepflow/assets/25686197/f287a5e0-e480-4401-8b3c-8f794f09141c">

这个issue可以关闭了，

不过我还是没有搞明白为什么v23.2.1为什么就是不行，升级到最新版本也是一样的，这是没有降版本前的结果
<img width="892" alt="image" src="https://github.com/deepflowio/deepflow/assets/25686197/8a7cdc0a-368a-4134-ad10-7e8e12808ba6">

**Comment by dundun9** [comment]
Sorry, try to update helm chart again

**Comment by dundun9** [comment]
![image](https://github.com/deepflowio/deepflow/assets/50027289/40464661-1a6f-4863-a93a-709e57c33e1f)
`kubectl get cm -n deepflow deepflow-clickhouse-config -o yaml| grep allow_experimental_live_view`
Update the helm chart again and check to see if clickhouse includes this configuration

**Comment by liexe** [comment]
The problem has already been solved
