### ISSUE TITLE
[BUG] K8S Node NIC 被识别为Other NIC

### ISSUE THREAD

**Issue by monokoo** [deepflowio/deepflow#3668]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

被识别Other NIC的网卡实际属于K8S集群宿主机的网卡

### How to reproduce

![image](https://github.com/deepflowio/deepflow/assets/14267095/1c191ef1-2500-4f67-84df-2ced53ba5706)

![image](https://github.com/deepflowio/deepflow/assets/14267095/1a8c2de3-fe42-43f3-961a-f02e2329419c)

### DeepFlow version

![image](https://github.com/deepflowio/deepflow/assets/14267095/2082591b-aa4e-4fa3-928b-d74834873870)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yuanchaoa** [comment]
@monokoo  可以发一下应用日志对应的流日志信息么，可以通过flow_id查询，主要内容为mac ip l2_end_0/1 l3_end_0/1

**Comment by 1473371932** [comment]
你好，你们 k8s 集群使用的网络插件是什么？

可以尝试更新到最新的 LTS 版本 v6.6，我们对网卡识别做了些优化，可更新后再次查看识别效果
