### ISSUE TITLE
[FR] FR-41:   lack of mac os version deepflow-ctl 

### ISSUE THREAD

**Issue by zjj1002** [deepflowio/deepflow#3710]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Currently, deepflow official documentation lacks download location of macOS arch  deepflow-ctl. 
I would like to use the deepflow-ctl on my macbook ,but got the error code "zsh: exec format error: ./deepflow-ctl "

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
https://github.com/deepflowio/deepflow/pull/4009
