### ISSUE TITLE
[FR] Destination IP instead of 0.0.0.0 on L7 flows

### ISSUE THREAD

**Issue by dirtyren** [deepflowio/deepflow#3764]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

  I've noticed that deepflow will show destination 0.0.0.0 for L7 flows taht the agent does not see, but the destination IPs will be set correctly on l4 flows.
  I'd like to understand why the destination IP can not also be set for L7 Flows as it would make analyzing the flows easier when there are UDP and TCP sessions being made to outside de K8S cluster. A  example is connections from a POD to a Pub/Sub or any other endpoint outside de cluster.
   Tks a lot

### Use case

Every endpoint outside my own K8S cluster.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
Do you have a screenshot?

**Comment by dirtyren** [comment]
I have another example, 4 pods that connect to Pub/Sub on GCP. The Pub/Sub show as a 0.0.0.0. I think, it should show the IP and maybe, if possible, the IP can be resolved, show the hostname.
 Tks.

![image](https://github.com/deepflowio/deepflow/assets/1627055/ca31c9e0-39f8-41f7-a7d1-129417061956)

**Comment by dundun9** [comment]
https://deepflow.io/docs/zh/auto-tagging/additional-resource/

l7_request_log should be the target IP, flow_metrics used by topo, which is not the target IP, you can refer to this document, enter a subnet, so that you can split the IP from 0.0.0.0

**Comment by dirtyren** [comment]
Tks @dundun9 , I know the additional resource docs. The idea was that instead of listing  0.0.0.0, why not just show de destination IP for the connection?
 Tks.

**Comment by dundun9** [comment]
In order to reduce the amount of data, for the aggregated data of the topology, the storage cost will increase and the display effect will become worse.

**Comment by dirtyren** [comment]
Tks @dundun9 , I get that.
