### ISSUE TITLE
[BUG] agent接入两周后，在grafana看不到agent信息

### ISSUE THREAD

**Issue by sxqiu123** [deepflowio/deepflow#3776]
### Search before asking

- [x] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

可以在agent上采集到传统服务器指标

### How to reproduce

（1）安装agent
curl -O https://deepflow-ce.oss-cn-beijing.aliyuncs.com/rpm/agent/stable/linux/$(arch | sed 's|x86_64|amd64|' | sed 's|aarch64|arm64|')/deepflow-agent-rpm.zip
yum install unzip
unzip deepflow-agent-rpm.zip
yum -y localinstall x86_64/deepflow-agent-1.0*.rpm

（2）修改 deepflow-agent 的配置文件 /etc/deepflow-agent.yaml：
controller-ips:
  - 10.88.40.149  # FIXME: K8s Node IPs
vtap-group-id-request: "g-NlgYytGhnM"  # FIXME: agent-group ID
controller-port: 30476

（3）启动 deepflow-agent ：
systemctl enable deepflow-agent
systemctl restart deepflow-agent

### DeepFlow version

[root@master ~]# kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
8265-3d888cab7e15db5d4f5a51eacf7703acc60ff7a9
Name: deepflow-agent community edition
Branch: v6.2.6.5
CommitId: 3d888cab7e15db5d4f5a51eacf7703acc60ff7a9
RevCount: 8265
Compiler: rustc 1.69.0 (84c898d65 2023-04-16)
CompileTime: 2023-05-18 01:56:26
[root@master ~]# 

### DeepFlow agent list

[root@master ~]# deepflow-ctl agent list
ID       NAME      TYPE       CTRL_IP          CTRL_MAC           STATE    GROUP   EXCEPTIONS
1        master-V1 K8S_VM     10.88.40.149     00:0a:f7:43:4c:40  NORMAL   default 

#这里没有显示接入的agent机器

### Kubernetes CNI

calico

### Operation-System/Kernel version

[root@master ~]# awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"CentOS Linux 7 (Core)"
[root@master ~]# uname -r
3.10.0-1160.el7.x86_64

### the version of deepflow

[root@master ~]# helm search repo deepflow
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION                                       
deepflow/deepflow      	6.2.606      	6.2.6      	An automated observability platform for cloud-n...
deepflow/deepflow-agent	6.2.606      	6.2.6      	An automated observability platform for cloud-n...

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sxqiu123** [comment]
agent状态如下：：
[gciroot@yw-skywalking-1 gciadm]# systemctl status deepflow-agent
● deepflow-agent.service
   Loaded: loaded (/usr/lib/systemd/system/deepflow-agent.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2023-08-03 15:11:17 CST; 29min ago
 Main PID: 3013933 (deepflow-agent)
    Tasks: 30 (limit: 100771)
   Memory: 2.6M
   CGroup: /system.slice/deepflow-agent.service
           └─3013933 /usr/sbin/deepflow-agent

8月 03 15:11:17 yw-skywalking-1 systemd[1]: Stopped deepflow-agent.service.
8月 03 15:11:17 yw-skywalking-1 systemd[1]: Started deepflow-agent.service.



agent日志如下：
Aug  3 13:20:13 yw-skywalking-1 systemd[1]: Starting system activity accounting tool...
Aug  3 13:20:13 yw-skywalking-1 systemd[1]: sysstat-collect.service: Succeeded.
Aug  3 13:20:13 yw-skywalking-1 systemd[1]: Started system activity accounting tool.
Aug  3 13:30:13 yw-skywalking-1 systemd[1]: Starting system activity accounting tool...
Aug  3 13:30:13 yw-skywalking-1 systemd[1]: sysstat-collect.service: Succeeded.
Aug  3 13:30:13 yw-skywalking-1 systemd[1]: Started system activity accounting tool.
Aug  3 13:40:13 yw-skywalking-1 systemd[1]: Starting system activity accounting tool...
Aug  3 13:40:13 yw-skywalking-1 systemd[1]: sysstat-collect.service: Succeeded.
Aug  3 13:40:13 yw-skywalking-1 systemd[1]: Started system activity accounting tool.
Aug  3 13:50:00 yw-skywalking-1 systemd[1]: Starting system activity accounting tool...
Aug  3 13:50:00 yw-skywalking-1 systemd[1]: sysstat-collect.service: Succeeded.
Aug  3 13:50:00 yw-skywalking-1 systemd[1]: Started system activity accounting tool.
Aug  3 14:00:13 yw-skywalking-1 systemd[1]: Starting system activity accounting tool...
Aug  3 14:00:13 yw-skywalking-1 systemd[1]: sysstat-collect.service: Succeeded.
Aug  3 14:00:13 yw-skywalking-1 systemd[1]: Started system activity accounting tool.
Aug  3 14:10:13 yw-skywalking-1 systemd[1]: Starting system activity accounting tool...
Aug  3 14:10:13 yw-skywalking-1 systemd[1]: sysstat-collect.service: Succeeded.
Aug  3 14:10:13 yw-skywalking-1 systemd[1]: Started system activity accounting tool.
Aug  3 14:10:56 yw-skywalking-1 systemd[1]: deepflow-agent.service: Main process exited, code=exited, status=3/NOTIMPLEMENTED
Aug  3 14:10:56 yw-skywalking-1 systemd[1]: deepflow-agent.service: Failed with result 'exit-code'.
Aug  3 14:11:06 yw-skywalking-1 systemd[1]: deepflow-agent.service: Service RestartSec=10s expired, scheduling restart.
Aug  3 14:11:06 yw-skywalking-1 systemd[1]: deepflow-agent.service: Scheduled restart job, restart counter is at 477.
Aug  3 14:11:06 yw-skywalking-1 systemd[1]: Stopped deepflow-agent.service.
Aug  3 14:11:06 yw-skywalking-1 systemd[1]: Started deepflow-agent.service.
Aug  3 14:20:00 yw-skywalking-1 systemd[1]: Starting system activity accounting tool...
Aug  3 14:20:00 yw-skywalking-1 systemd[1]: sysstat-collect.service: Succeeded.
Aug  3 14:20:00 yw-skywalking-1 systemd[1]: Started system activity accounting tool.
Aug  3 14:21:25 yw-skywalking-1 systemd[1]: Starting dnf makecache...
Aug  3 14:21:26 yw-skywalking-1 dnf[3012703]: 元数据缓存近期已刷新。
Aug  3 14:21:26 yw-skywalking-1 systemd[1]: dnf-makecache.service: Succeeded.
Aug  3 14:21:26 yw-skywalking-1 systemd[1]: Started dnf makecache.

**Comment by dundun9** [comment]
Is it convenient to add my wechat at the bottom of the readme? Let's talk on wechat

**Comment by sxqiu123** [comment]
I have sent a friend request on wechat.

**Comment by sxqiu123** [comment]
The friend request has been sent on wechat.

**Comment by z7210073** [comment]
I have the same issue，agent is installed in VM .staus is runing but agent list not found.
how to  fix it?
