### ISSUE TITLE
[BUG] otel exporter queue block.

### ISSUE THREAD

**Issue by callmediaomao** [deepflowio/deepflow#3848]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

在开启otel exporter的时候，是通过grpc一条一条的导出数据到otel recevier的，这过程中产生的grpc调用也被deepflow采集起来并再次发送到otel exporter队列
这样构成了一个死循环，导出的指标数量成比例不停增加，最终导致队列堵塞。。。
<img width="939" alt="c70e0133d6a3181740ccf4f2afe4736" src="https://github.com/deepflowio/deepflow/assets/63587783/262a4c80-9506-4f1d-bf28-10a149bb1847">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lzf575** [comment]
bpf 过滤采集数据:  https://github.com/deepflowio/deepflow/blob/main/server/controller/model/agent_group_config_example.yaml#L93
![image](https://github.com/deepflowio/deepflow/assets/44988793/2957e5a9-ab47-4e56-84b5-5bba55cfa5da)

ebpf 过滤采集数据：https://github.com/deepflowio/deepflow/blob/main/server/controller/model/agent_group_config_example.yaml#L1075
![image](https://github.com/deepflowio/deepflow/assets/44988793/98d6d072-8197-438b-8433-f0cdc92f8701)

**Comment by lzf575** [comment]
或者使用latest 版本，https://github.com/deepflowio/deepflow/blob/main/server/server.yaml#L553  ， 增大 export-batch-count的设置值， 这样grpc的调用会变少很多。

**Comment by callmediaomao** [comment]
好的👌
