### ISSUE TITLE
[BUG]  Distributed Tracing do not have eBPF data span

### ISSUE THREAD

**Issue by fidoooooowang** [deepflowio/deepflow#4112]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

 #3767  not fixed , I replace the deepflow-agent's image to registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflow-agent:4.19.113-300.el7.x86_64 ,still not work 

### How to reproduce

make -C /lib/modules/4.19.113-300.el7.x86_64/build M=/root/wxf/show-kernel-struct-offset modules
make[1]: Entering directory `/usr/src/kernels/4.19.113-300.el7.x86_64'
  CC [M]  /root/wxf/show-kernel-struct-offset/skso.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/wxf/show-kernel-struct-offset/skso.mod.o
  LD [M]  /root/wxf/show-kernel-struct-offset/skso.ko
make[1]: Leaving directory `/usr/src/kernels/4.19.113-300.el7.x86_64'
objdump -d skso.ko

skso.ko:     file format elf64-x86-64

Disassembly of section .text:

0000000000000000 <STRUCT_TCP_SOCK_COPIED_SEQ_OFFSET>:
   0:   e8 00 00 00 00          callq  5 <STRUCT_TCP_SOCK_COPIED_SEQ_OFFSET+0x5>
   5:   b8 3c 05 00 00          mov    $0x53c,%eax
   a:   c3                      retq   
   b:   0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)

0000000000000010 <STRUCT_TCP_SOCK_WRITE_SEQ_OFFSET>:
  10:   e8 00 00 00 00          callq  15 <STRUCT_TCP_SOCK_WRITE_SEQ_OFFSET+0x5>
  15:   b8 ac 06 00 00          mov    $0x6ac,%eax
  1a:   c3                      retq   
  1b:   0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)

0000000000000020 <STRUCT_TASK_FILES_OFFSET>:
  20:   e8 00 00 00 00          callq  25 <STRUCT_TASK_FILES_OFFSET+0x5>
  25:   b8 40 07 00 00          mov    $0x740,%eax
  2a:   c3                      retq   
  2b:   0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)

0000000000000030 <STRUCT_SOCK_FLAGS_OFFSET>:
  30:   e8 00 00 00 00          callq  35 <STRUCT_SOCK_FLAGS_OFFSET+0x5>
  35:   b8 f8 01 00 00          mov    $0x1f8,%eax
  3a:   c3                      retq   
  3b:   0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)

0000000000000040 <STRUCT_FILES_PRIVATE_DATA_OFFSET>:
  40:   e8 00 00 00 00          callq  45 <STRUCT_FILES_PRIVATE_DATA_OFFSET+0x5>
  45:   b8 c8 00 00 00          mov    $0xc8,%eax
  4a:   c3                      retq   
  4b:   0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)

0000000000000050 <STRUCT_TASK_TLS_OFFSET>:
  50:   e8 00 00 00 00          callq  55 <STRUCT_TASK_TLS_OFFSET+0x5>
  55:   b8 e8 1a 00 00          mov    $0x1ae8,%eax
  5a:   c3                      retq   
  5b:   0f 1f 44 00 00          nopl   0x0(%rax,%rax,1)

0000000000000060 <init_module>:
  60:   e8 00 00 00 00          callq  65 <init_module+0x5>
  65:   31 c0                   xor    %eax,%eax
  67:   c3                      retq   
  68:   0f 1f 84 00 00 00 00    nopl   0x0(%rax,%rax,1)
  6f:   00 

0000000000000070 <cleanup_module>:
  70:   e8 00 00 00 00          callq  75 <cleanup_module+0x5>
  75:   f3 c3                   repz retq

### DeepFlow version

server：
Name: deepflow-server community edition
Branch: v6.3.3
CommitID: 0170e213d9f7a941b6a89f168672363f6cca9692
RevCount: 8512
Compiler: go version go1.20.6 linux/amd64
CompileTime: 2023-07-14 07:36:01

agent:
8755-a872deffa047e53291837c507fbf0f30d42f3730
Name: deepflow-agent community edition
Branch: 4.19.113-300.el7.x86_64
CommitId: a872deffa047e53291837c507fbf0f30d42f3730
RevCount: 8755
Compiler: rustc 1.71.0 (8ede3aae2 2023-07-12)
CompileTime: 2023-09-04 07:51:56

### Kubernetes CNI

flannel:v0.15.1

### Operation-System/Kernel version

4.19.113-300.el7.x86_64

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nrjatyunshan** [comment]
https://github.com/deepflowio/deepflow/issues/3767
