### ISSUE TITLE
[BUG] Server exporter config not match document and fail to achieve same flexability after refactor

### ISSUE THREAD

**Issue by jiekun** [deepflowio/deepflow#4157]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

It seems the document is not updated after https://github.com/deepflowio/deepflow/pull/4050: https://github.com/deepflowio/docs/blob/main/docs/zh/07-server-integration/02-export/02-opentelemetry-collector.md

Also, there are some small issues with this refactor:
1. The new config layout removed the ability of exporting to multiple component with same protocol, for example 2 OTLP collector;
2. ExportDatas and ExportDataTypes are now shared by all exporters. How could user exporter different flow_log to other component with the expectation of different data types? For example, in OTLP exporter we want `ebpf-sys-span` only and in Loki exporter we want `cbpf-net-span` + `ebpf-sys-span`.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lzf575** [comment]
- 更新文档完成。 后续若文档更新滞后，也可先参考 https://github.com/deepflowio/deepflow/blob/main/server/server.yaml#L546
- 一般不会同时使用多个exporter，如果过同时使用，一般配置也是相同的。
- 目前没有单独控制的需求，如果确实需要灵活控制，后续可以放开。

**Comment by jiekun** [comment]
> * 更新文档完成。 后续若文档更新滞后，也可先参考 https://github.com/deepflowio/deepflow/blob/main/server/server.yaml#L546
> * 一般不会同时使用多个exporter，如果同时使用，一般配置也是相同的。
> * 目前没有单独控制的需求，如果确实需要灵活控制，后续可以放开。

Why not raise those point of views in the original PR? We could have the config layout discussed and solve it in time.

We are already developing based on the previous config layout. It's quite common sending o11y data to both cloud provider infrastructure and internal platform at the same time, with different config to filter out different types of span.

**Comment by lzf575** [comment]
你提的PR( https://github.com/deepflowio/deepflow/pull/3932 )已经是完整的了，当时是无需再处理的。
后续考虑到exporters一些配置/模块是公共的，可以提取出来，做了些优化，对接口变化实际不大，主要是代码位置调整有些多。目前的扩展还不是最终的，后续还会继续优化，也欢迎直接提pr优化。
目前会根据你的意见将当前的公共配置，由各expoerter自行处理。

**Comment by jiekun** [comment]
So some of the questions have conclusion (and maybe some advices) here.
1.The following (shared) params can be overwritten by exporter internal params. We can add a new struct and put it to both exporter**s** config and exporter config.
```
	ExportDatas                 []string `yaml:"export-datas"`
	ExportDataBits              uint32   // generate from 'ExportDatas'
	ExportDataTypes             []string `yaml:"export-data-types"`
	ExportDataTypeBits          uint32   // generate from 'ExportDataTypes'
	ExportCustomK8sLabelsRegexp string   `yaml:"export-custom-k8s-labels-regexp"`
	ExportOnlyWithTraceID       bool     `yaml:"export-only-with-traceid"`
```
2. For configuring multiple exporters under same type (e.g. otlp exporter) is still not supported. Please consider it and feel free to discuss.

**Comment by lzf575** [comment]
> So some of the questions have conclusion (and maybe some advices) here. 1.The following (shared) params can be overwritten by exporter internal params. We can add a new struct and put it to both exporter**s** config and exporter config.
> 
> ```
> 	ExportDatas                 []string `yaml:"export-datas"`
> 	ExportDataBits              uint32   // generate from 'ExportDatas'
> 	ExportDataTypes             []string `yaml:"export-data-types"`
> 	ExportDataTypeBits          uint32   // generate from 'ExportDataTypes'
> 	ExportCustomK8sLabelsRegexp string   `yaml:"export-custom-k8s-labels-regexp"`
> 	ExportOnlyWithTraceID       bool     `yaml:"export-only-with-traceid"`
> ```
> 
> 2. Configuring multiple exporters under the same type (e.g. otlp exporter) is still not supported. Please consider it and feel free to discuss.

第一点你已经修改了
第二点目前需要定义配置为数组来实现(https://github.com/deepflowio/deepflow/pull/4177)
 如果多个同类型的exporter的配置是一致的，后续需要定义 `addr`为数组，支持同时向多个地址export， 目前每个地址都生成一个exporter，exporter数量多的话，会加剧内存和cpu的消耗。

**Comment by jiekun** [comment]
> 第一点你已经修改了 第二点目前需要定义配置为数组来实现(#4177) 如果多个同类型的exporter的配置是一致的，后续需要定义 `addr`为数组，支持同时向多个地址export， 目前每个地址都生成一个exporter，exporter数量多的话，会加剧内存和cpu的消耗。

I still suggest making them configurable separately, similar to what we had before, or referring to the OpenTelemetry processor approach: [link to OpenTelemetry Tailsampling Processor README ↗](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/README.md).
我仍想建议让他们完全可独立配置，而非在某一类配置中取巧，就像之前的版本，或者 OpenTelemetry Processor 一样。

The key point is that each exporter instance should be able to work independently, without being affected by the configuration of other exporters.
重点是，每个 exporter 实例应该具备独立运行的可能，不受任何其他的 exporter 影响（当然如果有一些类似 universal tag 的问题除外，至少对于 addr、filter 等应该是相互独立的）。

The current approach still doesn't achieve the goal of sending different types of data to different receivers under the same protocol or export type. For example, sending basic trace data to an external platform like Datadog or New Relic, while sending all data to an internal platform.
在 addr 上取巧的做法不能解决给不同同类 receviver 提供不同 trace data 的问题，例如，向 Data Dog / New Relic 发送基础的 Trace 数据，往内部平台发送所有的 Trace 数据。

Also, we must consider the cost of hardware resources. Users need to be aware that running an additional exporter will incur an additional 100% cost. I assume this is easily understandable. However, sharing the same configuration doesn't reduce the cost, while fully separating them can take advantage of various benefits.
当然，我们需要考虑资源成本，用户需要知道每运行一个额外的 exporter 会有翻倍的开销，这应该很容易理解。然而，对 addr 下手的方案对解决这样的问题并没有帮助，甚至因该说每个 exporter 拥有独立配置更易于做到精细控制。

If you consider it necessary, we can also provide something like "multiple exporter under same type, while having multiple addr for each exporter"...so that we can save a lot of time to handle situation like: 10 exporters with 10 addrs, while 5 of them need smaller trace dataset and others need full trace data. (But yes it's over designed.)
如果有需要，也可以两种方式结合，同类exporter可以有多个，各自有不同配置，而同配置的exporter可以发往多个 addr，去解决一些非常极端的问题（当然，这是过度设计，但是上一段所说的不是，因为发往不同 receiver 的根因正是因为他们需要不同数据，否则一套平台就可以完全支撑了。多 addr 的设计没有解决核心的问题，而只是个表面上支持群发的方法，这会导致在需要群发时，需要filter多平台的并集数据）。

**Comment by jiekun** [comment]
I'm reviewing the code changes again. And found that seperate configuration for each exporter it's already supported. Sorry for the misunderstanding.

**Comment by jiekun** [comment]
This is refactored and solved in https://github.com/deepflowio/deepflow/pull/4177 . Docs updated as well. I'm closing the issue now.
