### ISSUE TITLE
是否支持数据最大保留天数？

### ISSUE THREAD

**Issue by noovertime7** [deepflowio/deepflow#4250]
是否支持数据最大保留天数？我在官网没看到相关参数

**Comment by dundun9** [comment]
https://github.com/deepflowio/deepflow/blob/main/server/server.yaml#L372
支持的

配置方法参考下面这个文档

https://deepflow.io/docs/zh/install/advanced-config/server-advanced-config/#%E4%BF%AE%E6%94%B9-server-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6

**Comment by noovertime7** [comment]
好的谢谢
