### ISSUE TITLE
[BUG] OTel输出的数据中parentSpanId与spanId相同

### ISSUE THREAD

**Issue by mcy567** [deepflowio/deepflow#4252]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

parentSpanId与spanId因是父子关系，应该不一样，但是从导出的数据来看，他们都是一样的。如下图所示：

![image](https://github.com/deepflowio/deepflow/assets/22673808/af7e3490-812c-4836-adb8-5e9fb36208f5)

这是一份通过otel-collector导出来的数据(即上图样例文件)：[deepflow.1.txt](https://github.com/deepflowio/deepflow/files/12603348/deepflow.1.txt)

### How to reproduce

1. 安装DeepFlow
参考 https://deepflow.io/docs/zh/install/all-in-one/

2. 配置DeepFlow Server 通过OTLP导出到OTel-Collector
参考 https://github.com/deepflowio/deepflow/issues/4226

3. 配置 OTel-Collector 导出到文件
注：我没有额外添加DeepFlow Agent，导出的数据应该来自k8s中DeepFlow Agent Pod采集的数据。

```yaml
# otel-collector.yaml

extensions:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:55681

processors:
  batch:

exporters:
  file:
  - path: /root/deepflow/otel/deepflow.txt

service:
  telemetry:
    logs:
    metrics:
  extensions: []
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file]
```
执行命令：
```
./otelcol --config otel-collector.yaml
```
得到输出日志。

### DeepFlow version

deepflow-server version:
```
2023/09/14 11:31:33 ENV K8S_NODE_NAME_FOR_DEEPFLOW=rzy4813; K8S_NODE_IP_FOR_DEEPFLOW=172.21.48.13; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-8676fdf457-p6k9s; K8S_POD_IP_FOR_DEEPFLOW=100.68.128.15; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: v6.3.7
CommitID: 7329db5f746f8ecfdcc52645e5cc9d88f02e25f7
RevCount: 8879
Compiler: go version go1.20.7 linux/amd64
CompileTime: 2023-09-01 06:20:52
```

deepflow-agent version:
```
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
8879-7329db5f746f8ecfdcc52645e5cc9d88f02e25f7
Name: deepflow-agent community edition
Branch: v6.3.7
CommitId: 7329db5f746f8ecfdcc52645e5cc9d88f02e25f7
RevCount: 8879
Compiler: rustc 1.71.1 (eb26296b5 2023-08-03)
CompileTime: 2023-09-01 06:21:59
```

### DeepFlow agent list

```
ID       NAME       TYPE       CTRL_IP            CTRL_MAC           STATE    GROUP   EXCEPTIONS
5        rzy4813-V2 K8S_VM     172.21.48.13       52:54:00:2d:94:19  NORMAL   default 
```

### Kubernetes CNI

calico

### Operation-System/Kernel version

操作系统版本："TencentOS Server 3.1 (Final)"
内核版本："5.4.119-19-0009.11"

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by jiekun** [comment]
I faced similar situation before. I would like to confirm: Is there really a parent span of the span you are looking exists?
我之前也遇到过相似的问题，我想先确认一下：这个 span 是否真的有 parent span 存在？

When looking at the trace_id / span_id / parent_span_id，the are identical / share the same starting 8 bytes.
仔细看这些 trace / span / parent span id 的时候，发现他们是相同的，或者共用相同的头8位。

So my initial guess: Parent span does not exist, span id are generated from trace id.
所以我第一个猜想，没有 parent span，所有的 span id 都是从 trace id 生成的。

Follow this clue and check the codes:
顺着线索检查代码是否有类似逻辑：
```go
...
                // Set trace_id for this span. 为 span 填充 trace id
                // If no trace_id (l7.TraceId is empty), generate one from flow log id. 如果原生的 trace id 不存在，改用 flow log 的 id 生成一个
		span.SetTraceID(getTraceID(l7.TraceId, l7.ID()))

		if l7.SignalSource == uint16(datatype.SIGNAL_SOURCE_OTEL) {
                        ...  // not relevant
		} else {
                        // set parent id. If no parent id exist, generate one from flow log id. 如果原生 parent span id 不存在，改用 flow log 的 id 生成一个
			span.SetParentSpanID(getSpanID(l7.SpanId, l7.ID()))
                        // set span id. generate one from flow log id. 用 flow log id 生成一个 span id
			span.SetSpanID(exporter_common.Uint64ToSpanID(l7.ID()))
		}

...

// getSpanID for ref
func getSpanID(spanID string, id uint64) pcommon.SpanID {
	if spanID == "" {
		return exporter_common.Uint64ToSpanID(id)
	}

	if spanId, err := hex.DecodeString(spanID); err == nil {
		id := [8]byte{}  // Here! First 8 byte of id[:] is used to fill as span_id. 没有原生 id 的时候采用截取的方法生成一个
		copy(id[:], spanId)
		return pcommon.SpanID(id)
	}
	return pcommon.NewSpanIDEmpty()
}
```

So when native trace id and span id are not exist, those id are self-generated and all fake. This apply to most **root** span without trace id / parent span id (by my guess).
所以当原生 trace id 和 span id 不存在的时候，这些 id 是自行生成的，是假的。推测这对大多数 root span 都生效。

**Comment by mcy567** [comment]
OK！那我是否可以理解为：
当前版本使用id关联的逻辑还没有实现，临时使用这种方式占位？
还是说他们之间都是同级的，没有父子关系，parentSpanId都应该为空？

**Comment by dundun9** [comment]
> OK！那我是否可以理解为： 当前版本使用id关联的逻辑还没有实现，临时使用这种方式占位？ 还是说他们之间都是同级的，没有父子关系，parentSpanId都应该为空？

目前只有在环境中使用了APM时，deepflow可以从流量中采集到APM的traceid、spanid、parentSpanid时可以正确关联

**Comment by mcy567** [comment]
> > OK！那我是否可以理解为： 当前版本使用id关联的逻辑还没有实现，临时使用这种方式占位？ 还是说他们之间都是同级的，没有父子关系，parentSpanId都应该为空？
> 
> 目前只有在环境中使用了APM时，deepflow可以从流量中采集到APM的traceid、spanid、parentSpanid时可以正确关联

traceid、spanid、parentSpanid 他们之间的关系只能通过APM关联么？DeepFlow未来是否有能力依靠自身将这些请求关联起来？

**Comment by dundun9** [comment]
> > > OK！那我是否可以理解为： 当前版本使用id关联的逻辑还没有实现，临时使用这种方式占位？ 还是说他们之间都是同级的，没有父子关系，parentSpanId都应该为空？
> > 
> > 
> > 目前只有在环境中使用了APM时，deepflow可以从流量中采集到APM的traceid、spanid、parentSpanid时可以正确关联
> 
> traceid、spanid、parentSpanid 他们之间的关系只能通过APM关联么？DeepFlow未来是否有能力依靠自身将这些请求关联起来？

目前就可以关联起来，不过是在查询的时候进行的关联，而不是在写入数据的时候，判断父子关系，打上traceid、spanid

**Comment by mcy567** [comment]
> > > > OK！那我是否可以理解为： 当前版本使用id关联的逻辑还没有实现，临时使用这种方式占位？ 还是说他们之间都是同级的，没有父子关系，parentSpanId都应该为空？
> > > 
> > > 
> > > 目前只有在环境中使用了APM时，deepflow可以从流量中采集到APM的traceid、spanid、parentSpanid时可以正确关联
> > 
> > 
> > traceid、spanid、parentSpanid 他们之间的关系只能通过APM关联么？DeepFlow未来是否有能力依靠自身将这些请求关联起来？
> 
> 目前就可以关联起来，不过是在查询的时候进行的关联，而不是在写入数据的时候，判断父子关系，打上traceid、spanid

请问查询时是根据什么关联的？

**Comment by jiekun** [comment]
> > > > OK！那我是否可以理解为： 当前版本使用id关联的逻辑还没有实现，临时使用这种方式占位？ 还是说他们之间都是同级的，没有父子关系，parentSpanId都应该为空？
> > > 
> > > 
> > > 目前只有在环境中使用了APM时，deepflow可以从流量中采集到APM的traceid、spanid、parentSpanid时可以正确关联
> > 
> > 
> > traceid、spanid、parentSpanid 他们之间的关系只能通过APM关联么？DeepFlow未来是否有能力依靠自身将这些请求关联起来？
> 
> 目前就可以关联起来，不过是在查询的时候进行的关联，而不是在写入数据的时候，判断父子关系，打上traceid、spanid

听起来如果有一个类似“尾部采样”的feature，就可以在导出时把span关系正确绑定好？

详细来说，server 需要承担一定时间的临时数据，例如10秒，在10秒结束后，需要检索当前的数据哪些和哪些时可以形成关联关系的，重新刷新他们的 span id，最后输送给 exporter。

这里可能会有一些额外的挑战，例如同一条链路上的数据如何通过 load balancing 给到同一个 server 处理，需要怎样的标志位等等。这个功能是让 OTLP exporter 有意义的前提，否则仅获取到杂乱独立的 span 没有太大意义。

**Comment by dundun9** [comment]
是的，多server、多agent的情况下不太好处理

**Comment by jiekun** [comment]
> 是的，多server、多agent的情况下不太好处理

所以这个计划怎么样处理比较好呢，我们之前也试过 OTLP exporter，如果数据不串联的话，导出去的数据量极大，也发挥不了什么作用，最终只能作为 metrics 或者 log。

这是个使用 OTLP exporter 的阻塞点，使用 DeepFlow 比较大可能是因为应用服务缺乏埋点，无法提供足够的 trace 信息，而 DeepFlow 采集了这些信息但没办法在输出时关联起来，那其实整个问题还是没能解决 orz 

就是感觉很多工作都在白费心思，例如研究 OTLP exporter 怎么用，为什么 service name 是空的（已解决），到头来数据还是，怎么说呢，如果你有一套zipkin或者jaeger，加上 deepflow 之后没有什么实际的收益，就会很沮丧 = =

**Comment by mcy567** [comment]
> > OK！那我是否可以理解为： 当前版本使用id关联的逻辑还没有实现，临时使用这种方式占位？ 还是说他们之间都是同级的，没有父子关系，parentSpanId都应该为空？
> 
> 目前只有在环境中使用了APM时，deepflow可以从流量中采集到APM的traceid、spanid、parentSpanid时可以正确关联

我参考 [集成 OpenTelemetry 数据](https://deepflow.io/docs/zh/agent-integration/tracing/opentelemetry/)，使用otel-collector采集了带有trace的数据并通过otlphttp协议发送给deepflow-agent，但输出的traceid、spanid、parentSpanid 依旧和之前的一样，还是没有使用otel生成的traceid、spanid、parentSpanid 。以下是一个过程展示：

![image](https://github.com/deepflowio/deepflow/assets/22673808/7de8c7ce-57ce-4d82-8210-bec4eb791361)
注：红色框是我之前提问时采集数据的方式，我得到了一组相同的traceid、spanid、parentSpanid。蓝色框是我按照你给的建议添加了APM数据后的方式，然而我最后得到的数据还是和之前一样，并没有变为APM中的traceid、spanid、parentSpanid。


deepflow-agent 配置文件 /etc/deepflow-agent.yaml

```
root@192.168.42.252:~$cat /etc/deepflow-agent.yaml |grep -v '^#' |grep -v '^$'

controller-ips:
  - 172.21.48.13
external-agent-http-proxy-enabled: 1   # required
external-agent-http-proxy-port: 38086  # optional, default 38086
vtap-group-id-request: "g-f7ate5E7YK"
```

otel-collector 配置文件 otel-collector.yaml
```
...
exporters:
  otlphttp:
    traces_endpoint: "http://192.168.42.252:38086/api/v1/otel/trace"
    compression: none
    retry_on_failure:
      enabled: true
...
service:
  pipelines:
    ...
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
      ...
...
```
如果将 otel-collector.yaml：exporters: [otlphttp] 改为 exporters: [file] ，通过输出的文件，可以看到如下内容：
```json
      "scopeSpans": [
        {
          "scope": {
            "name": "io.opentelemetry.kafka-clients-0.11",
            "version": "1.28.0-alpha"
          },
          "spans": [
            {
              "traceId": "2ac96c4e10a2419930efebb574ec35bc",
              "spanId": "8f194e3a0ba17731",
              "parentSpanId": "b85c26c3fa49df37",
              "name": "_o11y_trace publish",
              "kind": 4,
              "startTimeUnixNano": "1695029534793974710",
              "endTimeUnixNano": "1695029534805561630",
              "attributes": [
                {
                  "key": "messaging.kafka.client_id",
                  "value": {
                    "stringValue": "collector-1"
                  }
                },
                {
                  "key": "thread.id",
                  "value": {
                    "intValue": "59"
                  }
                },
```
通过输出到文件的内容，可以看到输出的内容是包含traceid、spanid、parentSpanid的，那么deepflow-agent拿到了这些数据为什么还是不能正常输出traceid、spanid、parentSpanid呢？还是说我理解错了？

**Comment by jiekun** [comment]
明白你的意思，这里也是可能文档没有交代得足够清晰的地方。

目前，数据进入 DeepFlow agent - DeepFlow server 这条链路，一共有两种方式：
1. 通过 DeepFlow Agent 直接采集网络流量，这类数据会被标记上来自于 `PACKET` 或 `EBPF`（或其他，名字不重要也不需要记住）；
2. 通过 DeepFlow Agent 作为 Receiver，直接接收来自 OTLP 格式的数据，一般由 OTel Agent / Collector 或其他组件直接发送过来，标记为 `OTEL` 类型数据。

> 详细类型（Signal Source）见：https://github.com/deepflowio/deepflow/blob/main/server/libs/datatype/flow.go#L102C4-L102C4

然后我们梳理一下，`PACKET` 和 `EBPF` 对应应用的网络请求，可能：
1. 有插装埋点，因此有携带 Trace 信息；
2. 没有插装埋点，因此没有携带 Trace 信息。

对于 `OTEL` 类型的数据，通常认为是：
  3. 有携带 Trace 信息的。

那这里一共 3 种情况，处理方式分别是：
1. 情况1：依靠 DeepFlow 自身逻辑，查询时进行关联，因此导出数据无（有效）Trace 信息 ；
2. 情况2：本身携带 Trace 信息，因此导出时会携带（有效）Trace 信息；
3. 情况3：本身携带 Trace 信息，但是已经进入过 OTel Collector 了，因此（设计上）认为，再次进入 DeepFlow 只是为了完成某些额外的目标，并不是为了再再再次被导出。因此，这种数据在 OTLP exporter 的处理方式是：**跳过，不导出**。（逻辑见：[otlp_exporter/exporter.go](https://github.com/deepflowio/deepflow/blob/main/server/ingester/flow_log/exporters/otlp_exporter/exporter.go#L121)）

你想验证的可能是情况 2，因此不能用文档的方式“导入”数据，而是需要一些已经插装过 OpenTelemetry 的应用，让他们的请求被 DeepFlow Agent 捕捉到，再尝试导出。

如果你手头上没有合适的应用可实验，可以尝试 OpenTelemetry 的 Demo：https://opentelemetry.io/docs/demo/kubernetes-deployment/

**Comment by mcy567** [comment]
谢答。根据你的描述，貌似我在用情况3的方式去验证情况2。基于这个前提，我还有几点疑惑：

① 我这边的测试环境是java应用，直接在启动的时候使用 -javaagent 的方式做了自动插码，按理来说是符合情况2的条件的，但是我发现deepflow没有捕获到请求中的traceid这些信息，是不是因为这个过程需要ebpf的能力？

> 注：上面的图片我更新了IP地址。192.168.42.252当前是 3.10 的内核。172.21.48.13 是 4.14+的内核。


② 对于情况3，我画了一个图，请问是我理解的这样吗？
![image](https://github.com/deepflowio/deepflow/assets/22673808/4a0a05bf-1a60-4d57-99b4-2a9742718e1d)

**Comment by jiekun** [comment]
> 谢答。根据你的描述，貌似我在用情况3的方式去验证情况2。基于这个前提，我还有几点疑惑：
> 
> ① 我这边的测试环境是java应用，直接在启动的时候使用 -javaagent 的方式做了自动插码，按理来说是符合情况2的条件的，但是我发现deepflow没有捕获到请求中的traceid这些信息，是不是因为这个过程需要ebpf的能力？
> 
> > 注：上面的图片我更新了IP地址。192.168.42.252当前是 3.10 的内核。172.21.48.13 是 4.14+的内核。
> 
> ② 对于情况3，我画了一个图，请问是我理解的这样吗？ ![image](https://user-images.githubusercontent.com/22673808/268820041-4a0a05bf-1a60-4d57-99b4-2a9742718e1d.png)

问题1：这个我不太确认，因为我们现在暂时搁置了 otlp exporter 的使用计划，所以不确定里面是逻辑限制，还是bug，导致缺了 trace_id。对于原本就有插装的数据，我的预期结果（就是我认为数据应该怎样被保存在 DeepFlow 的 Clickhouse）是：
![image](https://github.com/deepflowio/deepflow/assets/30280396/0fbc6d17-85e5-48f9-b4ea-fc77a60951df)

而原本没插装的数据，预期结果是：
![image](https://github.com/deepflowio/deepflow/assets/30280396/c7354d72-fbc3-4733-af9b-b23b11c8d214)

但是整个数据采集的流程非常复杂，不符合预期结果（PS：不符合我的预期不一定就是错的，或许官方预期就是如此的）需要从采集、传输、存储多个地方确认，成本太高，我也没确定过。最好还是有官方的同学能回复。

问题2：流程图跟我对 exporter 整套逻辑的理解是匹配的，是否和官方的一致需要官方的伙伴确认。

**Comment by mcy567** [comment]
刚刚又过滤了一遍采集的数据，在里面找到了少量的不同的 traceid、spanid、parentSpanid  -_-|| ，不过里面还掺杂着大量的相同的 traceid、spanid、parentSpanid，统计了下他们的比例是 1:700。

这里有个疑惑：随机生成id的作用是什么？为什么捕获不到的id不直接置为空？

下面是我截取的部分采集数据：

```
{
  "resourceSpans": [
    {
      "resource": {},
      "scopeSpans": [
        {
          "scope": {},
          "spans": [
            {
              "traceId": "1f9388848b78cd0078b674699673ac89",
              "spanId": "650826d60056674e",
              "parentSpanId": "f36608cfda53e4d4",
              "attributes": [
                {
                  "key": "df.span.native.trace_id",
                  "value": {
                    "stringValue": "1f9388848b78cd0078b674699673ac89"
                  }
                },
                {
                  "key": "df.span.native.span_id",
                  "value": {
                    "stringValue": "f36608cfda53e4d4"
                  }
                },
                {
                  "key": "df.span.type",
                  "value": {
                    "stringValue": "session"
                  }
                }
              ],
              "status": {}
            }
          ]
        }
      ]
    },
    {
      "resource": {},
      "scopeSpans": [
        {
          "scope": {},
          "spans": [
            {
              "traceId": "650826d6005667520000000000000000",
              "spanId": "650826d600566752",
              "parentSpanId": "650826d600566752",
              "kind": 3,
              "attributes": [
                {
                  "key": "df.span.type",
                  "value": {
                    "stringValue": "session"
                  }
                }
              ],
              "status": {}
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by dundun9** [comment]
@lzf575 说明下这里 为何这样设计、具体的逻辑吧

**Comment by jiekun** [comment]
Any updates here?

**Comment by lzf575** [comment]
以上 @jiekun 的分析都是对的。
- 随机id 是唯一标识一条 l7 flow log信息，比如web同时展示了多条l7 flow log,需要看某条的详细信息时，就会用id去过滤。
- 我们能只能采集到部分协议的traceid，spanid， 具体支持哪些协议 @dundun9 看看有没有文档说明。
- ebpf会采集到部分ssl解密后的信息，进程信息等，但是对于traceid ebpf和packet采集到的是一致的。
- 有个开关，是否导出 traceid非空的数据，可以开启下减少无效traceid的导出。https://github.com/deepflowio/deepflow/blob/main/server/server.yaml#L556
