### ISSUE TITLE
[BUG] 采集MySQL的request log出现乱码

### ISSUE THREAD

**Issue by cfp0425** [deepflowio/deepflow#4335]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

v6.3.7版本 grafana Application - Request Log dashboard，采集MySQL的request log出现乱码情况

![img_v2_d020c7db-1069-4831-a4ef-10b3db14771g](https://github.com/deepflowio/deepflow/assets/31235267/5c2d9336-c020-46b3-9173-765abade78b4)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
@cfp0425 贴一下pcap

**Comment by cfp0425** [comment]
deepflow-hfryo1-clickhouse-0.deepflow-hfryo1-clickhouse-headless.deepflow-observable.svc.cluster.local :) SELECT request_resource FROM  `flow_log`.`l7_flow_log` WHERE request_type='COM_STMT_PREPARE' LIMIT 10

SELECT request_resource
FROM flow_log.l7_flow_log
WHERE request_type = 'COM_STMT_PREPARE'
LIMIT 10

Query id: f43d93b5-41ec-4f94-a419-d28eebc184af

┌─request_resource────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ +-V�`�
        0:ڏ�s/�mܴn                                                    │
│ �C?Dp\�y'@S�s8�&�A]���                                                     │
│ ��ħ���+��;��YḖW^                                                     │
│ G�uј
      n"\<3����                                                  │
│ +-V�`�
        0:ڏ�s/�mܴn                                                    │
│ G�uј
      n"\<3����                                                  │
│ SELECT `id`, `uid`, `slug`, `org_id`, `gnet_id`, `version`, `plugin_id`, `created`, `updated`, `updated_by`, `created_by`, `folder_id`, `is_folder`, `has_acl`, `title`, `data` FROM `dashboard` WHERE `uid`=? AND `org_id`=? LIMIT 1                   │
│ SELECT `id`, `user_id`, `auth_token`, `prev_auth_token`, `user_agent`, `client_ip`, `auth_token_seen`, `seen_at`, `rotated_at`, `created_at`, `updated_at`, `revoked_at` FROM `user_auth_token` WHERE ((auth_token = ? OR prev_auth_token = ?)) LIMIT 1 │
│ 7��i� �ʩ�p�[�O��C                                                     │
│ �J�wGˁ�J�`���A
��                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────���───────────────────────────────────┘

10 rows in set. Elapsed: 0.034 sec. Processed 7.67 million rows, 24.77 MB (223.89 million rows/s., 723.51 MB/s.)

**Comment by StLeoX** [comment]
`Data Type` 为 `eBPF` 不出现乱码，为 `Local NIC` 出现乱码.

**Comment by sharang** [comment]
In previous versions, we enhanced SQL parsing by evaluating the first word of the command. However, this enhancement had a bug, which we have recently fixed: https://github.com/deepflowio/deepflow/pull/4893/files

I believe that after this fix, this issue should no longer occur.
