### ISSUE TITLE
[FR] FR-01: 主机同时有IPV6和IPV4时，通过配置项分别控制是否采集IPV6、IPV4的IP等相关信息

### ISSUE THREAD

**Issue by cooper190113** [deepflowio/deepflow#4412]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

**需求实现细节：**
1、主机同时有IPV6和IPV4时，通过配置项控制是否采集IPV6、IPV4信息
2、增加两个配置项，分别控制IPV6和IPV4的配置采集（例如IP等信息）

**需求价值：**
项目安全防护诉求，服务后端只能存储IPV6信息，需要屏蔽掉所有主机的IPV4后端存储。IPV4只用于登录机器。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
@cooper190113 可以试试这个，只采集 ipv6 流量：

https://github.com/deepflowio/deepflow/blob/main/server/controller/model/agent_group_config_example.yaml#L99

**Comment by haozhijie9527** [comment]
> @cooper190113 可以试试这个，只采集 ipv6 流量：
> 
> https://github.com/deepflowio/deepflow/blob/main/server/controller/model/agent_group_config_example.yaml#L99

可以详细说明下具体如何修改配置及如何使用吗？

**Comment by wys-AQ** [comment]
> > @cooper190113 可以试试这个，只采集 ipv6 流量：
> > https://github.com/deepflowio/deepflow/blob/main/server/controller/model/agent_group_config_example.yaml#L99
> 
> 可以详细说明下具体如何修改配置及如何使用吗？

你好，请问您现在了解到如何使用该配置文件了吗？
