### ISSUE TITLE
[BUG] aliyun 4.19内核无法采集eBPF数据

### ISSUE THREAD

**Issue by cyzcyzz** [deepflowio/deepflow#4494]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

make -C /lib/modules/4.19.91-25.6.al7.x86_64/build M=/root/show-kernel-struct-offset-master modules
make[1]: Entering directory `/usr/src/kernels/4.19.91-25.6.al7.x86_64'
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Leaving directory `/usr/src/kernels/4.19.91-25.6.al7.x86_64'
objdump -d skso.ko

skso.ko:     file format elf64-x86-64

Disassembly of section .text:

0000000000000000 <STRUCT_TCP_SOCK_COPIED_SEQ_OFFSET>:
   0:	e8 00 00 00 00       	callq  5 <STRUCT_TCP_SOCK_COPIED_SEQ_OFFSET+0x5>
   5:	b8 dc 05 00 00       	mov    $0x5dc,%eax
   a:	c3                   	retq
   b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000010 <STRUCT_TCP_SOCK_WRITE_SEQ_OFFSET>:
  10:	e8 00 00 00 00       	callq  15 <STRUCT_TCP_SOCK_WRITE_SEQ_OFFSET+0x5>
  15:	b8 4c 07 00 00       	mov    $0x74c,%eax
  1a:	c3                   	retq
  1b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000020 <STRUCT_TASK_FILES_OFFSET>:
  20:	e8 00 00 00 00       	callq  25 <STRUCT_TASK_FILES_OFFSET+0x5>
  25:	b8 b0 0b 00 00       	mov    $0xbb0,%eax
  2a:	c3                   	retq
  2b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000030 <STRUCT_SOCK_FLAGS_OFFSET>:
  30:	e8 00 00 00 00       	callq  35 <STRUCT_SOCK_FLAGS_OFFSET+0x5>
  35:	b8 08 02 00 00       	mov    $0x208,%eax
  3a:	c3                   	retq
  3b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000040 <STRUCT_FILES_PRIVATE_DATA_OFFSET>:
  40:	e8 00 00 00 00       	callq  45 <STRUCT_FILES_PRIVATE_DATA_OFFSET+0x5>
  45:	b8 c8 00 00 00       	mov    $0xc8,%eax
  4a:	c3                   	retq
  4b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000050 <STRUCT_TASK_TLS_OFFSET>:
  50:	e8 00 00 00 00       	callq  55 <STRUCT_TASK_TLS_OFFSET+0x5>
  55:	b8 68 14 00 00       	mov    $0x1468,%eax
  5a:	c3                   	retq
  5b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000060 <init_module>:
  60:	e8 00 00 00 00       	callq  65 <init_module+0x5>
  65:	31 c0                	xor    %eax,%eax
  67:	c3                   	retq
  68:	0f 1f 84 00 00 00 00 	nopl   0x0(%rax,%rax,1)
  6f:	00

0000000000000070 <cleanup_module>:
  70:	e8 00 00 00 00       	callq  75 <cleanup_module+0x5>
  75:	f3 c3                	repz retq

### DeepFlow version

v6.3.6

### Kubernetes CNI

aliyun terway

### Operation-System/Kernel version

4.19.91-25.6.al7.x86_64

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
PR： https://github.com/deepflowio/deepflow/pull/4649
已解决适配问题
