### ISSUE TITLE
[BUG] deepflow-server Database flow_tag doesn't exist and migrate mysql failed

### ISSUE THREAD

**Issue by dirtyren** [deepflowio/deepflow#4498]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

I just did a new install of deepflow 6.4.0 and deepflow-server is not coming up. Already try to delete delete and recreate de pod, same error.
![image](https://github.com/deepflowio/deepflow/assets/1627055/fa09e628-3065-4183-8d17-6c9121cc1153)

The deepflow databases were not created

![image](https://github.com/deepflowio/deepflow/assets/1627055/4f069ad0-ac27-4b4d-bb50-5c958bccf021)

### How to reproduce

Install deepflow 6.4.0

### DeepFlow version

```bash
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
9073-b9a9d1faee54524f60b33a5cb231373b4f8fa8e9
Name: deepflow-agent community edition
Branch: v6.4.0
CommitId: b9a9d1faee54524f60b33a5cb231373b4f8fa8e9
RevCount: 9073
Compiler: rustc 1.73.0 (cc66ad468 2023-10-03)
CompileTime: 2023-10-13 02:36:18
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by dundun9** [comment]
https://github.com/deepflowio/deepflow/issues/544#issuecomment-1207846716

You can refer to this issue, which is generally caused by the performance problem of mysql. You can first enter the database of mysql drop deepflow, and then increase the number of server failureThreshold

**Comment by dirtyren** [comment]
I installed with the setting used on another issue and it installed.
--set server.readinessProbe.failureThreshold=135 --set server.livenessProbe.failureThreshold=135
