### ISSUE TITLE
请问Deepflow Server如何搭建开发环境， server一些功能想打断点分析

### ISSUE THREAD

**Issue by zxcvf** [deepflowio/deepflow#4506]
感谢， 直接在docker中运行会直接卡死，  并且一定要在k8s环境下。 不知道有没有搭建本地环境的说法

**Comment by taloric** [comment]
可以使用 golang 的远程调试，远程调试的目的主机是 pod ，但此方法仍然要求运行在 k8s 中。可参考以下步骤：

1. 使用一个基础镜像，内置安装 golang 环境，并安装 `github.com/go-delve/delve/cmd/dlv@latest` 包。
2. server 代码需要在本地执行过 `CGO_ENABLED=0 make server` 命令，确保所有 go vendor 的依赖已下载到本地目录中。
3. 将 server 代码打包成一个镜像，注意拷贝代码的镜像内目标目录需要与本机代码目录完全一致（目录路径完全一致），并在 k8s 中运行（下称 dev pod），可直接使用 `deepflow-server` 组件运行时的 configmap，只是需要修改镜像为你新打包的 dev 镜像。注意此方法因为会与编译过的 deepflow-server 运行在一个集群内，集群最好至少有两个节点，保证原功能正常运行情况下再运行 dev pod。
拷贝时注意包含以下内容：
```Dockerfile
COPY ./controller/db/mysql/migration/rawsql /etc/mysql
COPY ./controller/cloud/filereader/manual_data_samples.yaml /etc/
COPY ./querier/db_descriptions /etc/db_descriptions/
COPY ./ ${CODE_DIR} #FIXME: 你的代码目录
WORKDIR ${CODE_DIR} #FIXME: 你的代码目录

CMD ["tail", "-f", "/dev/null"] # 这个 pod 不需要运行，使 pod 保持 Running 即可
```
5. 创建一个 k8s service，内容参考 `deepflow-server` 的 svc，但需要增加一个 dev pod 2345 端口的转发
6. 在本地使用 vscode 配置远程调试，k8s exec 进入 dev pod 内 `cmd/server/` 目录并运行 `dlv debug --headless --listen ":2345" --log --api-version 2` 命令，pod 内就绪后直接连接即可调试。
vscode 远程调试可参考配置：
```json
{
            "name": "Connect to server",
            "type": "go",
            "request": "attach",
            "mode": "remote",
            "remotePath": "你的代码目录",
            "port": {k8s service 公开的 nodeport },
            "host": "k8s node ip",
            "apiVersion": 2
}
```

**Comment by zxcvf** [comment]
> 可以使用 golang 的远程调试，远程调试的目的主机是 pod ，但此方法仍然要求运行在 k8s 中。可参考以下步骤：
> 
> 1. 使用一个基础镜像，内置安装 golang 环境，并安装 `github.com/go-delve/delve/cmd/dlv@latest` 包。
> 2. server 代码需要在本地执行过 `CGO_ENABLED=0 make server` 命令，确保所有 go vendor 的依赖已下载到本地目录中。
> 3. 将 server 代码打包成一个镜像，注意拷贝代码的镜像内目标目录需要与本机代码目录完全一致（目录路径完全一致），并在 k8s 中运行（下称 dev pod），可直接使用 `deepflow-server` 组件运行时的 yaml，只是需要修改镜像为你新打包的 dev 镜像。注意此方法因为会与编译过的 deepflow-server 运行在一个集群内，集群最好至少有两个节点，保证原功能正常运行情况下再运行 dev pod。
>    拷贝时注意包含以下内容：
> 
> ```dockerfile
> COPY ./controller/db/mysql/migration/rawsql /etc/mysql
> COPY ./controller/cloud/filereader/manual_data_samples.yaml /etc/
> COPY ./querier/db_descriptions /etc/db_descriptions/
> COPY ./ ${CODE_DIR} #FIXME: 你的代码目录
> WORKDIR ${CODE_DIR} #FIXME: 你的代码目录
> 
> CMD ["tail", "-f", "/dev/null"] # 这个 pod 不需要运行，使 pod 保持 Running 即可
> ```
> 
> 5. 创建一个 k8s service，内容参考 `deepflow-server` 的 svc，但需要增加一个 dev pod 2345 端口的转发
> 6. 在本地使用 vscode 配置远程调试，k8s exec 进入 dev pod 内 `cmd/server/` 目录并运行 `dlv debug --headless --listen ":2345" --log --api-version 2` 命令，pod 内就绪后直接连接即可调试。
>    vscode 远程调试可参考配置：
> 
> ```json
> {
>             "name": "Connect to server",
>             "type": "go",
>             "request": "attach",
>             "mode": "remote",
>             "remotePath": "{你的代码目录}",
>             "port": {k8s service 公开的 nodeport },
>             "host": "{k8s node ip}",
>             "apiVersion": 2
> }
> ```

感谢！ 我之前也是这么尝试的，但是每次启动时机器会卡死可能是机器性能问题 windows-docker-wsl  8c16g固态, 可能是wsl性能羸弱， 正在切换到虚拟机上
