### ISSUE TITLE
[FR] FR-XXX: add partition info for Kafka protocol

### ISSUE THREAD

**Issue by andyidea** [deepflowio/deepflow#4685]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The experience for version of Kafka topic is great, i am really looking forward to the support of the partition part.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
In v6.5, we plan to support retrieving partition ID, group ID, and offset from the wire protocol.

https://github.com/deepflowio/docs/pull/445/files

**Comment by sharang** [comment]
Support for parsing `partition` and `offset` 😄  in the Kafka protocol is already available. https://deepflow.io/docs/zh/features/universal-map/l7-protocols/#kafka
