### ISSUE TITLE
Just a question though. Does deepflow provide observability of memory usage the page level?

### ISSUE THREAD

**Issue by rexxy-sasori** [deepflowio/deepflow#4804]
curious how fine-grained deepflow can be regarding monitoring memory usage at the page level? Assuming the container uses normal containerd runtime

**Comment by dundun9** [comment]
We will have in-memory profiles in the future, but we will need users to do the UI themselves

**Comment by sharang** [comment]
ChatGPT
Yes, Memory Profiling is one of our milestone features. If you have a need for this feature, please feel free to submit a Feature Request Issue. I will close this issue for now.
