### ISSUE TITLE
导入 OpenTelemetry 数据的教程无法复现

### ISSUE THREAD

**Issue by cmZoO** [deepflowio/deepflow#4861]
我参考[All-in-One 快速部署](http://deepflow.yunshan.net/docs/zh/ce-install/all-in-one/#%E7%AE%80%E4%BB%8B)在一台华为云服务器上搭建了单机版的k8s集群并且安装了 All-in-One DeepFlow
后续我参考 [导入OpenTelemetry 数据](http://deepflow.yunshan.net/docs/zh/integration/input/tracing/opentelemetry/)配置 OpenTelemetry、DeepFlow、并使用 Spring Boot Demo 体验
1. OpenTelemetry我是直接通过2.1 安装 otel-agent中的`kubectl apply -n open-telemetry -f https://raw.githubusercontent.com/deepflowio/deepflow-demo/main/open-telemetry/open-telemetry.yaml
`命令安装的open-telemetry，此时otel-agent ConfigMap中的配置与2.2 配置 otel-agent中的一样，所以我没有做修改
2. 配置 DeepFlow时，因为是全新的环境，我先创建了your-agent-group-config.yaml存储所需的三个配置项，其中vtap_group_id已经修改为了我的agent-group-id，再通过deepflow-ctl agent-group-config create -f your-agent-group-config.yaml配置采集器组
3. 使用 Spring Boot Demo 体验时，我直接使用了提供的命令进行部署`kubectl apply -n deepflow-otel-spring-demo -f https://raw.githubusercontent.com/deepflowio/deepflow-demo/main/DeepFlow-Otel-Spring-Demo/deepflow-otel-spring-demo.yaml
`
部署完成后我通过nginx将grafana和deepflow-otel-spring-demo映射到外网来进行访问
在Distributed_Tracing页面中，可以看到OTel、网卡以及eBPF的数据如下图：
<img width="1412" alt="image" src="https://github.com/deepflowio/deepflow/assets/31054389/03ee76ee-caec-410e-934a-3e1494b931a8">
在查看trace的火焰图时
<img width="1109" alt="image" src="https://github.com/deepflowio/deepflow/assets/31054389/75a41730-6843-41b8-9f71-33c9100fff27">
OTel数据的火焰图如上图所示
<img width="1198" alt="image" src="https://github.com/deepflowio/deepflow/assets/31054389/3668af96-a1b5-438c-8d60-42d254e12e07">
其他数据的火焰图如上图所示

deepflow的数据并没有与OTel的数据串联在一起
与导入OpenTelemetry 数据教程中的示例图以及在线开源Demo中的火焰图相差甚远
我按照FAQ中以下步骤进行了检查
<img width="859" alt="image" src="https://github.com/deepflowio/deepflow/assets/31054389/10354928-bbcc-4b8b-9bce-7681067aac5e">
检查结果如下：
请确认应用已经做了 OTel SDK 集成或启动了 OTel Agent：我使用的是你们提供deepflow-otel-spring-demo.yaml，所以应该是已经配置好了
在 Application - K8s Pod Map dashboard 中检查是否存在应用到 otel-agent 到容器节点的流量的结果如下：
<img width="743" alt="image" src="https://github.com/deepflowio/deepflow/assets/31054389/df833b08-29de-43cf-98b0-3963e782625b">
是存在应用到 otel-agent 到容器节点的流量的
在 Application - Request Log dashboard 中确认发出的请求是否存在异常：
<img width="1405" alt="image" src="https://github.com/deepflowio/deepflow/assets/31054389/e481928e-9dfe-485f-84fa-0238cddb2f3b">
有发往otel-agent的数据
确认服务器内核版本符合要求：
<img width="747" alt="image" src="https://github.com/deepflowio/deepflow/assets/31054389/dcdf7796-c7ad-441c-a0f1-bac91d10e742">
检查 deepflow-agent 的所有副本:
<img width="1177" alt="image" src="https://github.com/deepflowio/deepflow/assets/31054389/bfba7868-cbe9-4132-b357-ccb71f43ca9c">
<img width="1191" alt="image" src="https://github.com/deepflowio/deepflow/assets/31054389/a46551c1-d643-488e-a6dd-874f7bee0a32">

**Comment by dundun9** [comment]
agent和server什么版本？

**Comment by cmZoO** [comment]
> agent和server什么版本？

<img width="1382" alt="image" src="https://github.com/deepflowio/deepflow/assets/31054389/748482ca-01dc-42a3-b39f-d1e74cf2b847">

**Comment by dundun9** [comment]
升级到v6.4.3试试

**Comment by dundun9** [comment]
helm repo update
helm upgrade xxxxxx

**Comment by cmZoO** [comment]
谢谢
