### ISSUE TITLE
[FR] FR-XXX: Grafana UI 所有的视图增加Cluster级别的过滤条件

### ISSUE THREAD

**Issue by 1851616111** [deepflowio/deepflow#4887]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

当一个Server管理多个集群的时候，这个Server对应的grafana在管理多集群时部分dashboard缺少cluster的过滤条件

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by liqian1834** [comment]
目前与 K8s 相关的 dashboard 都已经有 cluster 过滤条件的
![image](https://github.com/deepflowio/deepflow/assets/19233457/ceabe2f9-e920-4ed2-a132-69335e09fcda)
