### ISSUE TITLE
[BUG] 6.4.4 版本导致Grafana面板获取cluster变量查询失败

### ISSUE THREAD

**Issue by icylord** [deepflowio/deepflow#4916]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

6.4.4版本导致Grafana面板的变量查询失败，例如：
```
"query": {
          "database": "flow_metrics",
          "sql": "SELECT pod_cluster as `value`, pod_cluster as `display_name` FROM `vtap_flow_port.1m` WHERE  time >= ${__from:date:seconds} AND time <= ${__to:date:seconds} GROUP BY `value` LIMIT 999999999999",
          "useAny": true,
          "useDisabled": false
        },
```
看源码是在这个commit后受影响，https://github.com/deepflowio/deepflow/commit/5be4b08a5aec7cdbfb5bfdab2209064ba5b10f8e#diff-666ae3a77760748621abd96d229f845adb340a405e21fd360dc72c4b84f0a707

该变更会导致查询变量时执行 GetDatasourceInterval 函数，并调用http://localhost:20417/v1/data-sources/?type=，返回500错误失败。
6.4.3版本没这个问题。

### DeepFlow version

6.4.4

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by xiaochaoren1** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.
> 
> ### DeepFlow Component
> Agent
> 
> ### What you expected to happen
> 6.4.4版本导致Grafana面板的变量查询失败，例如：
> 
> ```
> "query": {
>           "database": "flow_metrics",
>           "sql": "SELECT pod_cluster as `value`, pod_cluster as `display_name` FROM `vtap_flow_port.1m` WHERE  time >= ${__from:date:seconds} AND time <= ${__to:date:seconds} GROUP BY `value` LIMIT 999999999999",
>           "useAny": true,
>           "useDisabled": false
>         },
> ```
> 
> 看源码是在这个commit后受影响，[5be4b08#diff-666ae3a77760748621abd96d229f845adb340a405e21fd360dc72c4b84f0a707](https://github.com/deepflowio/deepflow/commit/5be4b08a5aec7cdbfb5bfdab2209064ba5b10f8e#diff-666ae3a77760748621abd96d229f845adb340a405e21fd360dc72c4b84f0a707)
> 
> 该变更会导致查询变量时执行 GetDatasourceInterval 函数，并调用[http://localhost:20417/v1/data-sources/?type=，返回500错误失败。](http://localhost:20417/v1/data-sources/?type=%EF%BC%8C%E8%BF%94%E5%9B%9E500%E9%94%99%E8%AF%AF%E5%A4%B1%E8%B4%A5%E3%80%82) 6.4.3版本没这个问题。
> 
> ### How to reproduce
> _No response_
> 
> ### DeepFlow version
> 6.4.4
> 
> ### DeepFlow agent list
> _No response_
> 
> ### Kubernetes CNI
> _No response_
> 
> ### Operation-System/Kernel version
> _No response_
> 
> ### Anything else
> _No response_
> 
> ### Are you willing to submit a PR?
> * [ ]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

感谢指出问题，对造成的不好体验表示抱歉，正在修复中
