### ISSUE TITLE
[BUG] tcp retrans ratio calculate error

### ISSUE THREAD

**Issue by JimLeeee** [deepflowio/deepflow#4923]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

pcapfile 
[
![robotgw-1](https://github.com/deepflowio/deepflow/assets/46155146/eb8c2d72-d7a7-40d0-84ad-f4ed0987ae28)
](url)

### How to reproduce

 #[
/](url)
grafana shows retrans ratio is high. but pcap file shows not 
![image](https://github.com/deepflowio/deepflow/assets/46155146/753382bc-91d5-461f-909c-6a9b6cdb025b)

### DeepFlow version

6.4.3

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
Thank you for submitting the issue, but I can't see the PCAP image you mentioned. Could you resubmit the image? @JimLeeee

**Comment by JimLeeee** [comment]
after delete pod, it disappeared
