### ISSUE TITLE
[BUG] The deepflow agent ebpf collector needs to adapt to the new kernel

### ISSUE THREAD

**Issue by sangfei** [deepflowio/deepflow#5012]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

[2023-12-08 13:20:43.672725 +08:00] ERROR [src/ebpf_dispatcher/ebpf_dispatcher.rs:609] [eBPF Kernel Adapt] The socket_tracer_start() error. Kernel offset adapt failed. Please ensure that BTF is enabled (kernel bu
ilt with CONFIG_DEBUG_INFO_BTF=y option). If the current kernel version is low (<5.2), upgrading the Linux kernel to 5.2+ (kernel built with CONFIG_DEBUG_INFO_BTF=y option) can solve the problem. If it is not possible to upgrade the kernel, the kernel-de
vel package can be provided for developers to adapt and solve the problem.

### How to reproduce

make -C /lib/modules/4.19.117.business.1-amd64/build M=/root/show-kernel-struct-offset modules
make[1]: Entering directory '/usr/src/linux-headers-4.19.117.business.1-amd64'
  CC [M]  /root/show-kernel-struct-offset/skso.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/show-kernel-struct-offset/skso.mod.o
  LD [M]  /root/show-kernel-struct-offset/skso.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.19.117.business.1-amd64'
objdump -d skso.ko

skso.ko:     file format elf64-x86-64

Disassembly of section .text:

0000000000000000 <STRUCT_TCP_SOCK_COPIED_SEQ_OFFSET>:
   0:	e8 00 00 00 00       	callq  5 <STRUCT_TCP_SOCK_COPIED_SEQ_OFFSET+0x5>
   5:	b8 7c 05 00 00       	mov    $0x57c,%eax
   a:	c3                   	retq
   b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000010 <STRUCT_TCP_SOCK_WRITE_SEQ_OFFSET>:
  10:	e8 00 00 00 00       	callq  15 <STRUCT_TCP_SOCK_WRITE_SEQ_OFFSET+0x5>
  15:	b8 ec 06 00 00       	mov    $0x6ec,%eax
  1a:	c3                   	retq
  1b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000020 <STRUCT_TASK_FILES_OFFSET>:
  20:	e8 00 00 00 00       	callq  25 <STRUCT_TASK_FILES_OFFSET+0x5>
  25:	b8 b8 06 00 00       	mov    $0x6b8,%eax
  2a:	c3                   	retq
  2b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000030 <STRUCT_SOCK_FLAGS_OFFSET>:
  30:	e8 00 00 00 00       	callq  35 <STRUCT_SOCK_FLAGS_OFFSET+0x5>
  35:	b8 f8 01 00 00       	mov    $0x1f8,%eax
  3a:	c3                   	retq
  3b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000040 <STRUCT_FILES_PRIVATE_DATA_OFFSET>:
  40:	e8 00 00 00 00       	callq  45 <STRUCT_FILES_PRIVATE_DATA_OFFSET+0x5>
  45:	b8 c8 00 00 00       	mov    $0xc8,%eax
  4a:	c3                   	retq
  4b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000050 <STRUCT_TASK_TLS_OFFSET>:
  50:	e8 00 00 00 00       	callq  55 <STRUCT_TASK_TLS_OFFSET+0x5>
  55:	b8 a8 0a 00 00       	mov    $0xaa8,%eax
  5a:	c3                   	retq
  5b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000060 <init_module>:
  60:	e8 00 00 00 00       	callq  65 <init_module+0x5>
  65:	31 c0                	xor    %eax,%eax
  67:	c3                   	retq
  68:	0f 1f 84 00 00 00 00 	nopl   0x0(%rax,%rax,1)
  6f:	00

0000000000000070 <cleanup_module>:
  70:	e8 00 00 00 00       	callq  75 <cleanup_module+0x5>
  75:	f3 c3                	repz retq

### DeepFlow version

-003:kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
2023/12/21 19:41:35 ENV K8S_NODE_NAME_FOR_DEEPFLOW=xxxx; K8S_NODE_IP_FOR_DEEPFLOW=xxxx; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-848b8c8758-5cw4h; K8S_POD_IP_FOR_DEEPFLOW=xxxx; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: v6.4.3
CommitID: 8e168feb8335c5938959516ba62b34ea0143c237
RevCount: 9294
Compiler: go version go1.20.11 linux/amd64
CompileTime: 2023-11-24 02:25:13

-003:~# kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
9294-8e168feb8335c5938959516ba62b34ea0143c237
Name: deepflow-agent community edition
Branch: v6.4.3
CommitId: 8e168feb8335c5938959516ba62b34ea0143c237
RevCount: 9294
Compiler: rustc 1.73.0 (cc66ad468 2023-10-03)
CompileTime: 2023-11-24 02:27:06

### Operation-System/Kernel version

"Debian GNU/Linux 9 (stretch)"
4.19.117.business.1-amd64

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
This issue has been fixed in the main and v6.4 branches. Thank you for submitting the issue.
PR: https://github.com/deepflowio/deepflow/pull/5234

**Comment by yinjiping** [comment]
Execute the command 'uname - v' to see the return information
@sangfei

**Comment by sangfei** [comment]
> Execute the command 'uname - v' to see the return information @sangfei

# uname -v
#4.19.117.bsk.business.1 SMP Debian 4.19.117.bsk.business.1 Wed
