### ISSUE TITLE
[FR] FR-XXX: 这些rpc接口的功能是什么

### ISSUE THREAD

**Issue by liangtianlun** [deepflowio/deepflow#5090]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1.rpc Sync (SyncRequest) returns (SyncResponse) {} 这个接口注意到agent会调用多次, 同步什么信息? 主要的功能是什么会做什么事情, 调用这个接口, 会更新哪一些mysql的表?
2.rpc Push (SyncRequest) returns (stream SyncResponse) {} 这个接口的功能是什么, agent在什么时候会触发这个调用, 核心代码在哪处理, event是什么? vTapEvent和tsdbEvent分别做什么事情?
3.server端有什么角色, 数据节点和控制节点的具体功能是什么?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by liangtianlun** [comment]
rpc Plugin (PluginRequest) returns (stream PluginResponse) {}这个接口是干什么的, 是安装server的插件还是agent的? 有哪些插件, 分别什么功能?如果自定义的插件要怎么写?

**Comment by SongZhen0704** [comment]
https://github.com/deepflowio/deepflow/issues/5090

**Comment by liangtianlun** [comment]
可参考PR：https://github.com/deepflowio/deepflow/issues/5090? 并没有你的说明, 查看那个文件?给个具体地址
