### ISSUE TITLE
[BUG] The deepflow agent needs to be adapted to 4.19.90-2107.6.0.0192.8.oe1.bclinux

### ISSUE THREAD

**Issue by tailerong** [deepflowio/deepflow#5127]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

[eBPF Kernel Adapt] The socket_tracer_start() error. Kernel offset adapt failed. Please ensure that BTF is enabled (kernel built with CONFIG_DEBUG_INFO_BTF=y option). If the current kernel version is low (<5.2), upgrading the Linux kernel to 5.2+ (kernel built with CONFIG_DEBUG_INFO_BTF=y option) can solve the problem. If it is not possible to upgrade the kernel, the kernel-devel package can be provided for developers to adapt and solve the problem.

### How to reproduce

[root@host-10 ~/lhq/show-kernel-struct-offset-master]$  make
make -C /lib/modules/4.19.90-2107.6.0.0192.8.oe1.bclinux.x86_64/build M=/root/lhq/show-kernel-struct-offset-master modules
make[1]: Entering directory '/usr/src/kernels/4.19.90-2107.6.0.0192.8.oe1.bclinux.x86_64'
  CC [M]  /root/lhq/show-kernel-struct-offset-master/skso.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /root/lhq/show-kernel-struct-offset-master/skso.mod.o
  LD [M]  /root/lhq/show-kernel-struct-offset-master/skso.ko
make[1]: Leaving directory '/usr/src/kernels/4.19.90-2107.6.0.0192.8.oe1.bclinux.x86_64'
objdump -d skso.ko

skso.ko:     file format elf64-x86-64

Disassembly of section .text:

0000000000000000 <STRUCT_TCP_SOCK_COPIED_SEQ_OFFSET>:
   0:	e8 00 00 00 00       	callq  5 <STRUCT_TCP_SOCK_COPIED_SEQ_OFFSET+0x5>
   5:	b8 54 06 00 00       	mov    $0x654,%eax
   a:	c3                   	retq   
   b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000010 <STRUCT_TCP_SOCK_WRITE_SEQ_OFFSET>:
  10:	e8 00 00 00 00       	callq  15 <STRUCT_TCP_SOCK_WRITE_SEQ_OFFSET+0x5>
  15:	b8 c4 07 00 00       	mov    $0x7c4,%eax
  1a:	c3                   	retq   
  1b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000020 <STRUCT_TASK_FILES_OFFSET>:
  20:	e8 00 00 00 00       	callq  25 <STRUCT_TASK_FILES_OFFSET+0x5>
  25:	b8 08 0b 00 00       	mov    $0xb08,%eax
  2a:	c3                   	retq   
  2b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000030 <STRUCT_SOCK_FLAGS_OFFSET>:
  30:	e8 00 00 00 00       	callq  35 <STRUCT_SOCK_FLAGS_OFFSET+0x5>
  35:	b8 18 02 00 00       	mov    $0x218,%eax
  3a:	c3                   	retq   
  3b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000040 <STRUCT_FILES_PRIVATE_DATA_OFFSET>:
  40:	e8 00 00 00 00       	callq  45 <STRUCT_FILES_PRIVATE_DATA_OFFSET+0x5>
  45:	b8 c8 00 00 00       	mov    $0xc8,%eax
  4a:	c3                   	retq   
  4b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000050 <STRUCT_TASK_TLS_OFFSET>:
  50:	e8 00 00 00 00       	callq  55 <STRUCT_TASK_TLS_OFFSET+0x5>
  55:	b8 68 13 00 00       	mov    $0x1368,%eax
  5a:	c3                   	retq   
  5b:	0f 1f 44 00 00       	nopl   0x0(%rax,%rax,1)

0000000000000060 <init_module>:
  60:	e8 00 00 00 00       	callq  65 <init_module+0x5>
  65:	31 c0                	xor    %eax,%eax
  67:	c3                   	retq   
  68:	0f 1f 84 00 00 00 00 	nopl   0x0(%rax,%rax,1)
  6f:	00 

0000000000000070 <cleanup_module>:
  70:	e8 00 00 00 00       	callq  75 <cleanup_module+0x5>
  75:	f3 c3                	repz retq

### DeepFlow version

v6.3.9

deepflow-agent -v
8953-27f802990d1669d4d48f0028d2fb3d9df01b9dd3
Name: deepflow-agent community edition
Branch: HEAD
CommitId: 27f802990d1669d4d48f0028d2fb3d9df01b9dd3
RevCount: 8953
Compiler: rustc 1.72.0 (5680fa18f 2023-08-23)
CompileTime: 2023-09-20 06:19:05

### Operation-System/Kernel version

4.19.90-2107.6.0.0192.8.oe1.bclinux.x86_64

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
This issue has been fixed in the main and v6.4 branches. Thank you for submitting the issue.
PR: https://github.com/deepflowio/deepflow/pull/5237
