### ISSUE TITLE
[BUG]  agent采集MYSQL日志失败 

### ISSUE THREAD

**Issue by zeusYi** [deepflowio/deepflow#5315]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

想要收集mysql 访问日志 遇到一个问题
我再问一下 我在一台部署有Mysql的服务器上 部署了agent， 通过脚本持续对mysql进行查询，无日志。

测试脚本
```sh
#!/bin/bash
 
i=1
step=1
while (($i<=3))
do
  cmd="select * from testdb.t1"
  echo ${cmd}

  /usr/local/mysql/bin/mysql -h'10.116.104.237' -u'root' -p'xxxx'  -D testdb -s -e "${cmd}"
  i=`expr $i + $step`
done
echo "执行完毕：${i}"
```

![image](https://github.com/deepflowio/deepflow/assets/22519964/eb4fd846-4dc3-4671-ba01-41e637b0638e)

抓包文件
[mysql.pcap.zip](https://github.com/deepflowio/deepflow/files/13973023/mysql.pcap.zip)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by zeusYi** [comment]
MySQL Version: 5.7.30 和 5.7.40 都不行。一开始Agent内核版本 3.10 不行，升级到了6版本也不行。

**Comment by Terrynech** [comment]
请问有后续吗? 我也遇到了同样的问题, 以二进制包的形式部署agent, 采集不到mysql的数据

**Comment by 1473371932** [comment]
你好，通过抓包数据看出，基本都是 mysql greeting，它不会生成调用日志，另一部分看起来是 login 的数据，这部分数据在 v6.4 版本中也不会识别，可以更新至最新的 LTS 版本，v6.6 或者 v6.5 即可解决（注：大版本更新时需请求旧数据后重装）
