### ISSUE TITLE
[BUG] 基于 docker-compose 部署 All-in-One DeepFlow 时提示 镜像 deepflowio-init-grafana-ds-dh:latest not found不存在

### ISSUE THREAD

**Issue by phpiscute** [deepflowio/deepflow#5348]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

不涉及

### How to reproduce

基于 docker-compose 部署 All-in-One DeepFlow 时提示 镜像 deepflowio-init-grafana-ds-dh:latest not found不存在

https://deepflow.io/docs/zh/ce-install/all-in-one/#%E9%83%A8%E7%BD%B2-all-in-one-deepflow-2

```
# docker-compose -f docker-compose.yaml up -d
Pulling deepflow-grafana-init-worksdir (registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana-ds-dh:latest)...
Trying to pull repository registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana-ds-dh ...
Pulling repository registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana-ds-dh
ERROR: Error: image deepflow-ce/deepflowio-init-grafana-ds-dh:latest not found
```

### DeepFlow version

不涉及

### DeepFlow agent list

不涉及

### Kubernetes CNI

不涉及

### Operation-System/Kernel version

不涉及

### Anything else

不涉及

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
![Snipaste_2024-01-23_16-57-13](https://github.com/deepflowio/deepflow/assets/84362246/06096257-23e8-4ba4-848e-dc63e3da30cf)

这个镜像如果不行的话，可以把 "xianggang" 换成 "beijing"

**Comment by dundun9** [comment]
@phpiscute 我们测试发现这个镜像没有问题，你可以试试把 `hongkong` 换成 `beijing`

**Comment by dundun9** [comment]
@phpiscute 如果方便的话，可以加一下这个 Repo Readme最下面的微信二维码，方便沟通

**Comment by phpiscute** [comment]
@1473371932  @dundun9 感谢二位大佬，原来是我的 docker版本有问题，在另外一台服务器上是正常的，重新升级 docker 版本解决了。

deepflow 的社区支持很好。

**Comment by phpiscute** [comment]
我关闭issue 了哈
