### ISSUE TITLE
compile libtrace.a error! -- cargo check fails on main

### ISSUE THREAD

**Issue by vobbilis** [deepflowio/deepflow#5349]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

```
my-machine:~/go/src/github.com/deeepflowio/deepflow/agent/src$ cargo check
   Compiling zstd-safe v5.0.2+zstd.1.5.2
    Checking zstd-sys v2.0.8+zstd.1.5.5
    Checking pnet_transport v0.29.0
    Checking ittapi-sys v0.3.3
    Checking psm v0.1.21
    Checking kube-runtime v0.74.0 (https://github.com/deepflowio/kube?tag=0.74.2#c423734b)
   Compiling deepflow-agent v0.1.0 (/home/my-machine/go/src/github.com/deeepflowio/deepflow/agent)
    Checking dns-lookup v1.0.8
    Checking page_size v0.4.2
    Checking sysinfo v0.26.9
    Checking cloud_platform v0.1.0 (/home/my-machine/go/src/github.com/deeepflowio/deepflow/agent/plugins/cloud_platform)
    Checking ittapi v0.3.3
    Checking pnet v0.29.0
    Checking bytesize v1.2.0
    Checking public v0.1.0 (/home/my-machine/go/src/github.com/deeepflowio/deepflow/agent/crates/public)
    Checking l7 v0.1.0 (/home/my-machine/go/src/github.com/deeepflowio/deepflow/agent/plugins/l7)
    Checking wasmtime-jit v12.0.1
    Checking zstd v0.11.2+zstd.1.5.2
    Checking packet_dedup v0.1.0 (/home/my-machine/go/src/github.com/deeepflowio/deepflow/agent/plugins/packet_dedup)
error: failed to run custom build command for `deepflow-agent v0.1.0 (/home/my-machine/go/src/github.com/deeepflowio/deepflow/agent)`

Caused by:
  process didn't exit successfully: `/home/my-machine/go/src/github.com/deeepflowio/deepflow/agent/target/debug/build/deepflow-agent-9a3e9a46baf0b1e7/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-env=AGENT_NAME=deepflow-agent-ce
  cargo:rustc-env=BRANCH=main

  cargo:rustc-env=COMPILE_TIME=2024-01-21 19:38:49
  cargo:rustc-env=COMMIT_ID=4f925e8f0ea762730918bf10e33d5fe7da9f79a4

  cargo:rustc-env=REV_COUNT=9623

  cargo:rustc-env=RUSTC_VERSION=rustc 1.75.0 (82e1608df 2023-12-21)


  --- stderr
  make[1]: *** No rule to make target 'clean'.  Stop.
  make: *** [Makefile:262: clean] Error 2

  thread 'main' panicked at build.rs:94:9:
  compile libtrace.a error!
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
my-machine::~/go/src/github.com/deeepflowio/deepflow/agent/src$

Linux (uname -a):
```Linux my-machine 6.2.0-1019-gcp #21~22.04.1-Ubuntu SMP Thu Nov 16 18:18:34 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```

Distro (lsb_release -a):
```No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy```
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lialosiu** [comment]
Do u forget `git submodule update --init` for the submodule, like *agent/src/ebpf/libs/jattach*?
just try it.

**Comment by rvql** [comment]
@vobbilis Greetings.
Did you try initializing submodules with `git submoudle update --init`?

**Comment by vobbilis** [comment]
Yes. I did.

**Comment by rvql** [comment]
> Thanks. It helped. But the check still fails now. I have JDK8 installed.
> 
> ```
> user/profile/java/agent.c:36:10: fatal error: jni.h: No such file or directory
>      36 | #include <jni.h>
>         |          ^~~~~~~
>   compilation terminated.
>   make: *** [Makefile:166: df_java_agent_v1.so] Error 1
> 
>   thread 'main' panicked at build.rs:94:9:
>   compile libtrace.a error!
>   stack backtrace:
>      0: rust_begin_unwind
>                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
>      1: core::panicking::panic_fmt
>                at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
>      2: build_script_build::set_build_libtrace
>      3: build_script_build::main
>      4: core::ops::function::FnOnce::call_once
>   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```

Package `openjdk-8-jdk-headless` contains `jni.h`, make sure you have it installed.
If that doesn't work, [building with docker](https://github.com/deepflowio/deepflow/blob/main/agent/build.md#use-docker) is also an option.
If you just want the latest build, check project [packages](https://github.com/orgs/deepflowio/packages?repo_name=deepflow).

**Comment by vobbilis** [comment]
Yes. I switched to docker build and it works. Thanks.

**Comment by rvql** [comment]
> Yes. I switched to docker build and it works. Thanks.

Glad it worked. I'm closing the issue.
