### ISSUE TITLE
[BUG] deepflow-agent 采集传统服务器挂掉

### ISSUE THREAD

**Issue by callmediaomao** [deepflowio/deepflow#5451]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen
日志显示最后一条error的时候直接挂掉

![image](https://github.com/deepflowio/deepflow/assets/63587783/d071ed91-2006-4255-8684-7b7cc27b7ec0)

### DeepFlow version

v6.3.9
![image](https://github.com/deepflowio/deepflow/assets/63587783/e0b24e98-49b7-46d5-bff4-33567fef701f)

### DeepFlow agent list

![image](https://github.com/deepflowio/deepflow/assets/63587783/9eb1d5de-bf9b-4f84-b7cd-270c300553c2)

### Operation-System/Kernel version

![image](https://github.com/deepflowio/deepflow/assets/63587783/5a35c5b3-9787-4cec-be3a-26e8721a9514)

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
您好，对于 ERROR 错误造成程序退出，这个是已知BUG，早已修复，您的6.3.9需要进行更新一下，比如新的镜像`deepflow-agent:v6.3.4336`

另外，6.3版本不支持对3.10的内核支持（内核版本的要求是4.14+），我们已经在6.4版本中进行支持3.10内核（开源版本main, v6.4已经支持，企业版本v6.4会在近期发版支持3.10的内核）
