### ISSUE TITLE
[BUG] Tracing dashboard Flame panel error

### ISSUE THREAD

**Issue by yhcloud123** [deepflowio/deepflow#5559]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

![b9af19c49cb29539c864f19d9d3e6b3](https://github.com/deepflowio/deepflow/assets/110751250/312a57c4-adea-49e0-9ea2-3fbee82d3a9b)
Red exclamation mark appears on the Flame panel, reporting error
![929067a36b77abaaf0967eda51b92a5](https://github.com/deepflowio/deepflow/assets/110751250/c462dd50-a669-4133-bd9a-598b48d94eed)
![21a9c7d48e6acfe92c8ddf2b06c769b](https://github.com/deepflowio/deepflow/assets/110751250/d4122da2-486a-4bd1-afd8-7db383a1500e)

### How to reproduce

Using a deepflow data source
A Grafana deployed using templates within a chart
Connect to an existing Grafana on your own
Except for the difference in yaml (which I tried and should not be related to), the other versions of Grafana are the same, but the only data cannot be generated is the flame. The internal version in the chart has this, while the external version of Grafana does not have this flame

### DeepFlow version

Branch：v6.4

### DeepFlow agent list

normal

### Kubernetes CNI

calico

### Anything else

This issue may occur when using an external database

But the Flame panel version 6.2.6 used before was normal

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yhcloud123** [comment]
In addition to using the original version of DeepFlow, I switched to using the chart version of Grafana and found that the flame was normal. It seems that there is a problem with the Grafana version

Why does this happen

I hope the official website can provide external connections like this, with testing version requirements

**Comment by yhcloud123** [comment]
In addition to using the original version of DeepFlow, I switched to using the chart version of Grafana and found that the flame was normal. It seems that there is a problem with the Grafana version

Why does this happen

I hope the official website can provide external connections like this, with testing version requirements

**Comment by yhcloud123** [comment]
@rvql @sharang Do you have any insights? Is it because version 6.4.9 is not compatible with Grafana 8? It must be 9, but theoretically not. What is the reason？

**Comment by sharang** [comment]
@1473371932 Please help to solve this problem.

**Comment by yhcloud123** [comment]
> @1473371932 Please help to solve this problem.

Found the reason, the external Grafana initc plugin still uses the 6.2 upgrade to resolve the issue
thanks
