### ISSUE TITLE
[BUG] 调用deepflow-app查询接口同样的参数，多次请求返回结果报错

### ISSUE THREAD

**Issue by chrisdamon** [deepflowio/deepflow#5637]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

调用deepflow-app /v1/stats/querier/tracing-completion-by-external-app-spans 接口时，同样的参数多次请求后结果不一样，其中有的请求可以正常返回，个别请求会报错，返回结果： {"OPT_STATUS":"INTERNAL_SERVER_ERROR","DESCRIPTION":"sequence item 0: expected str instance, tuple found"}

### How to reproduce

curl  -XPOST  -d @res.json  http://deepflow-app:20418/v1/stats/querier/tracing-completion-by-external-app-spans

res.json 请求参数内容如下：
{
    "max_iteration": 30,
    "network_delay_us": 3000000,
    "app_spans": [
        {
            "trace_id": "6e0d4e8400d6245cd7d79bd3e93a9331",
            "span_id": "9b4f811a79ae2e23",
            "parent_span_id": "c6de620aad290f5b",
            "span_kind": 3,
            "start_time_us": 1708912800000000,
            "end_time_us": 1708914000000000
        }
    ]
}

多次请求过程如下：
[root@iZbp1cwk6wj01xgalmbmxwZ ~]# date && sh deepflow-res.sh
**Mon Feb 26 18:18:12 CST 2024**
{"OPT_STATUS":"SUCCESS","DESCRIPTION":"","DATA":{"tracing":[{"_ids":["194515355480136"],"related_ids":[],"start_time_us":1708912800000000,"end_time_us":1708914000000000,"duration":1200000000,"tap_side":"c-app","l7_protocol":0,"l7_protocol_str":"","endpoint":"","request_type":"","request_resource":"","response_status":0,"flow_id":"0","request_id":0,"x_request_id_0":"","x_request_id_1":"","trace_id":"6e0d4e8400d6245cd7d79bd3e93a9331","span_id":"9b4f811a79ae2e23","parent_span_id":"c6de620aad290f5b","req_tcp_seq":0,"resp_tcp_seq":0,"syscall_trace_id_request":"0","syscall_trace_id_response":"0","syscall_cap_seq_0":0,"syscall_cap_seq_1":0,"attribute":null,"process_id":null,"vtap_id":0,"app_service":"","app_instance":"","tap_id":0,"tap":"","deepflow_span_id":"9b4f811a79ae2e23","deepflow_parent_span_id":""}]},"TYPE":"tracing-completion-by-external-app-spans"}
[root@iZbp1cwk6wj01xgalmbmxwZ ~]# date && sh deepflow-res.sh
**Mon Feb 26 18:18:17 CST 2024**
{"OPT_STATUS":"SUCCESS","DESCRIPTION":"","DATA":{"tracing":[{"_ids":["229096304877981"],"related_ids":[],"start_time_us":1708912800000000,"end_time_us":1708914000000000,"duration":1200000000,"tap_side":"c-app","l7_protocol":0,"l7_protocol_str":"","endpoint":"","request_type":"","request_resource":"","response_status":0,"flow_id":"0","request_id":0,"x_request_id_0":"","x_request_id_1":"","trace_id":"6e0d4e8400d6245cd7d79bd3e93a9331","span_id":"9b4f811a79ae2e23","parent_span_id":"c6de620aad290f5b","req_tcp_seq":0,"resp_tcp_seq":0,"syscall_trace_id_request":"0","syscall_trace_id_response":"0","syscall_cap_seq_0":0,"syscall_cap_seq_1":0,"attribute":null,"process_id":null,"vtap_id":0,"app_service":"","app_instance":"","tap_id":0,"tap":"","deepflow_span_id":"9b4f811a79ae2e23","deepflow_parent_span_id":""}]},"TYPE":"tracing-completion-by-external-app-spans"}
[root@iZbp1cwk6wj01xgalmbmxwZ ~]# date && sh deepflow-res.sh
**Mon Feb 26 18:18:20 CST 2024**
{"OPT_STATUS":"SUCCESS","DESCRIPTION":"","DATA":{"tracing":[{"_ids":["130641604982580"],"related_ids":[],"start_time_us":1708912800000000,"end_time_us":1708914000000000,"duration":1200000000,"tap_side":"c-app","l7_protocol":0,"l7_protocol_str":"","endpoint":"","request_type":"","request_resource":"","response_status":0,"flow_id":"0","request_id":0,"x_request_id_0":"","x_request_id_1":"","trace_id":"6e0d4e8400d6245cd7d79bd3e93a9331","span_id":"9b4f811a79ae2e23","parent_span_id":"c6de620aad290f5b","req_tcp_seq":0,"resp_tcp_seq":0,"syscall_trace_id_request":"0","syscall_trace_id_response":"0","syscall_cap_seq_0":0,"syscall_cap_seq_1":0,"attribute":null,"process_id":null,"vtap_id":0,"app_service":"","app_instance":"","tap_id":0,"tap":"","deepflow_span_id":"9b4f811a79ae2e23","deepflow_parent_span_id":""}]},"TYPE":"tracing-completion-by-external-app-spans"}
[root@iZbp1cwk6wj01xgalmbmxwZ ~]# date && sh deepflow-res.sh
**Mon Feb 26 18:18:23 CST 2024**
{"OPT_STATUS":"INTERNAL_SERVER_ERROR","DESCRIPTION":"sequence item 0: expected str instance, tuple found"}

### DeepFlow version

deepflow-server: v6.4.9
deepflow-agent: v6.4.9

### Kubernetes CNI

flannel

### Operation-System/Kernel version

"Alibaba Cloud Linux (Aliyun Linux) 2.1903 LTS (Hunting Beagle)"
4.19.91-27.6.al7.x86_64

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
这个问题正在修复中

**Comment by xiaochaoren1** [comment]
可以提供下报错时的日志吗

**Comment by chrisdamon** [comment]
![image](https://github.com/deepflowio/deepflow/assets/45988065/08c85682-4c2a-40b3-8bd8-eae8ed319d04)
这个是当时使用deepflow-app查询时日志报错的截图
