### ISSUE TITLE
[FR] FR-XXX: 提问：如何在deepflow-agent中控制采集的协议或数据，以及如何控制采样频率？

### ISSUE THREAD

**Issue by wys-AQ** [deepflowio/deepflow#5674]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我下载了deepflow的社区版，但是我在https://deepflow.io/docs/zh/best-practice 中的server.yaml和agent.yaml中没找到可以控制采集协议或数据的选项，以及控制采样频率的选项。请问以上功能在社区版中是可以实现的吗？

### Use case

希望能够控制采集协议或数据（比如我不想采集redis的数据），以及控制采样频率（比如1分钟采样一次）

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
你好，指定采集协议：
https://github.com/deepflowio/deepflow/blob/main/server/controller/model/agent_group_config_example.yaml#L944

控制采集数据，可以参考下各表存作用以及如何控制采集数据：
https://deepflow.io/blog/zh/043-how-to-reduce-deepflow-storage-overhead/

不能控制采样率，要么关、要么开、要么采集特定位置、协议的数据，不能按比例采集。
