### ISSUE TITLE
[BUG] Deepflow server多节点时其中一个节点故障/重启恢复后会出现负载不均的情况

### ISSUE THREAD

**Issue by monokoo** [deepflowio/deepflow#5699]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

Deepflow server多节点时其中一个节点故障/重启恢复后 agent应重新负载均衡

### How to reproduce

多节点server环境，重启其中一个server，agent会全部注册到其他存活的server pod；但是故障server节点启动之后agent未重新负载均衡注册导致流量全部集中到其他server上，资源消耗过大进而出现循环重启的恶性情况。server端存在持续消耗内存导致pod OOM的情况

analyzer table表
| id | state | ha\_state | name | description | ip | nat\_ip | agg | cpu\_num | memory\_size | arch | os | kernel\_version | tsdb\_shard\_id | tsdb\_replica\_ip | tsdb\_data\_mount\_path | pcap\_data\_mount\_path | vtap\_max | synced\_at | nat\_ip\_enabled | pod\_ip | pod\_name | ca\_md5 | lcuuid |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 59 | 2 | 1 | cn-hangzhou.10.183.35.79 |  | 10.183.35.79 |  | 1 | 16 | 66161647616 | x86\_64 | alpine 3.15.0 | 4.19.91 | null | null | null |  | 200 | 2024-03-04 18:33:10 | 0 | 10.183.62.96 | deepflow-server-68b4b6878c-smrrs | 960b90e29e4f04af5e9d9608e7a50df6 | 8788cf15-0759-4437-8604-24469e9d3ffa |
| 61 | 2 | 1 | cn-hangzhou.10.183.35.92 |  | 10.183.35.92 |  | 1 | 8 | 66163224576 | x86\_64 | alpine 3.15.0 | 4.19.91 | null | null | null |  | 200 | 2024-03-04 18:33:08 | 0 | 10.183.62.99 | deepflow-server-7b9db96bd9-24tdh | 960b90e29e4f04af5e9d9608e7a50df6 | 957e3ab4-8853-4a30-8b3e-4c9c611a7b4a |
| 62 | 2 | 1 | cn-hangzhou.10.183.35.80 |  | 10.183.35.80 |  | 1 | 16 | 66161651712 | x86\_64 | alpine 3.15.0 | 4.19.91 | null | null | null |  | 200 | 2024-03-04 18:33:29 | 0 | 10.183.62.95 | deepflow-server-697c56d794-6wkdr | 960b90e29e4f04af5e9d9608e7a50df6 | 994e801c-d23e-416d-9c94-01dd8a54619b |

controller table表
| id | state | name | description | ip | nat\_ip | cpu\_num | memory\_size | arch | os | kernel\_version | vtap\_max | synced\_at | nat\_ip\_enabled | node\_type | region\_domain\_prefix | node\_name | pod\_ip | pod\_name | ca\_md5 | lcuuid |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 59 | 2 | cn-hangzhou.10.183.35.79 |  | 10.183.35.79 |  | 16 | 66161647616 | x86\_64 | alpine 3.15.0 | 4.19.91 | 2000 | 2024-02-20 10:49:05 | 0 | 1 |  | cn-hangzhou.10.183.35.79 | 10.183.62.96 | deepflow-server-c769b5ddd-45mkh | 960b90e29e4f04af5e9d9608e7a50df6 | 332e932f-5414-4294-847f-70a27f97b7b8 |
| 61 | 2 | cn-hangzhou.10.183.35.92 |  | 10.183.35.92 |  | 8 | 66163224576 | x86\_64 | alpine 3.15.0 | 4.19.91 | 2000 | 2024-02-28 14:50:34 | 0 | 1 |  | cn-hangzhou.10.183.35.92 | 10.183.62.99 | deepflow-server-c769b5ddd-zh5j5 | 960b90e29e4f04af5e9d9608e7a50df6 | 799d5ddc-8482-4d4e-b5c9-b240ed465a5d |
| 62 | 2 | cn-hangzhou.10.183.35.80 |  | 10.183.35.80 |  | 16 | 66161651712 | x86\_64 | alpine 3.15.0 | 4.19.91 | 2000 | 2024-03-01 13:11:19 | 0 | 1 |  | cn-hangzhou.10.183.35.80 | 10.183.62.95 | deepflow-server-c769b5ddd-d7k9j | 960b90e29e4f04af5e9d9608e7a50df6 | 52d61376-eabd-4bf1-9716-81f4f1a8bdc8 |

![image](https://github.com/deepflowio/deepflow/assets/14267095/a3b8ec97-8a9a-49ec-96a0-eaa393f48452)
![image](https://github.com/deepflowio/deepflow/assets/14267095/02835591-85e2-4431-aead-83f198f47d56)
![image](https://github.com/deepflowio/deepflow/assets/14267095/c7c5e481-6fec-4b18-86f4-f743735698d2)

### DeepFlow version

v6.4最新代码分支编译

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by roryye** [comment]
看下 Server 的 ConfigMap 配置值：algorithm
提供下 Grafana deepflow-server logs，过滤下日志："need rebalance vtap for analyzer"

**Comment by monokoo** [comment]
> algorithm
algorithm 使用的默认 by-ingested-data
![image](https://github.com/deepflowio/deepflow/assets/14267095/9e50b0e0-f186-466e-b7a7-abc7bf033f01)

**Comment by roryye** [comment]
我看 12:58 的日志 10.183.35.92 （早上重启的 server）上分配了采集器，看起来每个数据节点的采集器权重都接近 1，是比较均衡的，现在是恢复了吗
可以看下早上重启时，到其他 server 崩溃区间的 traffic.go 日志截图

**Comment by monokoo** [comment]
> 我看 12:58 的日志 10.183.35.92 （早上重启的 server）上分配了采集器，看起来每个数据节点的采集器权重都接近 1，是比较均衡的，现在是恢复了吗？
> 
> 可以看下早上重启时，到其他 server 崩溃区间的 traffic.go 日志

这个均衡动作看日志很少触发。deepflow-ctl agent rebalance 这个命令也无法手动均衡，执行后server端没动静

**Comment by monokoo** [comment]
> > > 我看 12:58 的日志 10.183.35.92 （早上重启的 server）上分配了采集器，看起来每个数据节点的采集器权重都接近 1，是比较均衡的，现在是恢复了吗？
> > > 可以看下早上重启时，到其他 server 崩溃区间的 traffic.go 日志
> > 
> > 
> > 这个均衡动作看日志很少触发。deepflow-ctl agent rebalance 这个命令也无法手动均衡，执行后server端没动静
> 
> 定时均衡间隔默认是 1h，对应配置：rebalance-interval
> 
> `deepflow-ctl agent rebalance -t analyzer` 命令输出 "no balance required" 说明采集器分配数据节点均衡，不需要执行均衡操作；否则输出均衡前后的操作日志

rebalance.go:147 fail to rebalance analyzer by data(if check: false): <nil> 此处日志不是说均衡失败了吗

**Comment by roryye** [comment]
此处日志有问题，忘记做 err 判断了，欢迎提 PR

上面的日志打印说明已经执行完均衡了

**Comment by monokoo** [comment]
> 此处日志有问题，忘记做 err 判断了，欢迎提 PR
> 
> 上面的日志打印说明已经执行完均衡了，这个时间点之后数据节点流量还是不均衡吗
是有这种情况，如下
![image](https://github.com/deepflowio/deepflow/assets/14267095/99acf963-325e-4738-ac8a-a1e430cc443b)
![image](https://github.com/deepflowio/deepflow/assets/14267095/7957b621-0e8d-4268-8309-4e33b6c204b7)

**Comment by roryye** [comment]
algorithm 配置设置成 by-ingested-data 是按照采集器的流量来分配的，不是按照个数来分配的；按个数分配可配置：by-agent-count

采集器采集流量统计可通过下面查看
<img width="1281" alt="image" src="https://github.com/deepflowio/deepflow/assets/43332712/1c0f09c9-7673-4a2a-8753-2d987fe380ba">

**Comment by monokoo** [comment]
https://github.com/deepflowio/deepflow/issues/5738 这个缺陷修复后，目前负载均衡也运行正常了

**Comment by monokoo** [comment]
@roryye server新增了一个节点，没有正常按照日志显示的预期分配负载
![image](https://github.com/deepflowio/deepflow/assets/14267095/60cbfc8b-5326-4912-9c40-b712d6b540c7)
