### ISSUE TITLE
[BUG] panicked kafka:  byte index 680 is not a char boundary inside

### ISSUE THREAD

**Issue by yhcloud123** [deepflowio/deepflow#5704]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

It seems to be a problem with character boundaries
![69497bf51852be294100ed8948f0a62](https://github.com/deepflowio/deepflow/assets/110751250/9e11ccde-bf73-4483-8f20-09c54addb9d1)

确认一下是否都是一个问题
Please confirm if it is all the same issue
[Agent] Fix panic at kafka sw8  https://github.com/deepflowio/deepflow/commit/01dec84c6de8935282cee63ccc2492fcd1078339

### DeepFlow version

 deepflow-agent v6.4 9683

### Operation-System/Kernel version

All different physical machines will appear

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
@yhcloud123 I think your issue has been fixed in #5690. Could you please confirm it using the latest 6.4 image? @yuanchaoa please also help confirm.

**Comment by sharang** [comment]
comfirmed by @yuanchaoa
