### ISSUE TITLE
在k8s 集群中安装V6.4 版本DeepFlow 无业务命名空间调用链路监控数据 [BUG] 

### ISSUE THREAD

**Issue by yupanlong** [deepflowio/deepflow#5713]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

显示所有k8s命名空间选项和数据

### How to reproduce

![image](https://github.com/deepflowio/deepflow/assets/66449880/58707729-8408-43d3-9ccc-a1d2851c7532)

### DeepFlow version

```2024/03/06 14:35:26 ENV K8S_NODE_NAME_FOR_DEEPFLOW=192.168.0.62; K8S_NODE_IP_FOR_DEEPFLOW=192.168.0.62; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-58b45f555d-8zszf; K8S_POD_IP_FOR_DEEPFLOW=172.16.14.243; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: v6.4
CommitID: c721bbf707fb853d44ee8f15bb24ade10241b9d8
RevCount: 9709
Compiler: go version go1.20.14 linux/amd64
CompileTime: 2024-03-05 09:09:39

Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
9706-fa82985253d91d03b1cdb5617c9c4b7381996b86
Name: deepflow-agent community edition
Branch: v6.4
CommitId: fa82985253d91d03b1cdb5617c9c4b7381996b86
RevCount: 9706
Compiler: rustc 1.75.0 (82e1608df 2023-12-21)
CompileTime: 2024-03-05 08:07:54

```

### DeepFlow agent list

```bash 
ID   NAME               TYPE     CTRL_IP         CTRL_MAC            STATE    GROUP     EXCEPTIONS   REVISION    UPGRADE_REVISION   
1    192.168.0.62-V2    K8S_VM   192.168.0.62    fa:16:3e:46:9e:dc   NORMAL   default                v6.4 9706                      
2    192.168.0.250-V1   K8S_VM   192.168.0.250   fa:16:3e:46:9e:98   NORMAL   default                v6.4 9706  
```

### Operation-System/Kernel version

```
"CentOS Linux 7 (Core)"
3.10.0-1160.66.1.el7.x86_64
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
你好，能否贴一下这两处的截图？
![Snipaste_2024-03-11_14-42-01](https://github.com/deepflowio/deepflow/assets/84362246/716a4d2a-62e0-425a-b7cc-20f9219bdffd)
![Snipaste_2024-03-11_14-42-30](https://github.com/deepflowio/deepflow/assets/84362246/8d8c8450-0bc0-42cb-800e-ea64ffb0265f)

**Comment by 1473371932** [comment]
后续 ns 同步数据还有问题，可以参考此 [issue](https://github.com/deepflowio/deepflow/issues/8539)
