### ISSUE TITLE
clickhouse引擎是否可以替换为Doris之类的引擎呢

### ISSUE THREAD

**Issue by joewee** [deepflowio/deepflow#5715]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

clickhouse引擎是否可以替换为Doris之类的引擎呢

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
目前没有明确的计划，若有需求的话，期待社区的贡献。
