### ISSUE TITLE
[BUG] 函数名未成功翻译,java版本为：“1.8.0_401”

### ISSUE THREAD

**Issue by numachen** [deepflowio/deepflow#5739]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

希望获取解决方案

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
@numachen 
- 注意agent镜像 （确保大于等于 `deepflow-agent:v6.4.4541` 这个版本）
- java 运行添加 XX:+PreserveFramePointer 
- 做一些业务访问，使得业务追踪栈呈现在火焰图上
