### ISSUE TITLE
[BUG] Grafana distributed tracing, no k8s clusters display

### ISSUE THREAD

**Issue by DrAuYueng** [deepflowio/deepflow#5766]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

<img width="1001" alt="image" src="https://github.com/deepflowio/deepflow/assets/1527849/f2db26f5-cf54-407b-a264-7a9be1a30f71">
Grafana distributed tracing, no k8s cluster display.   

Version: v6.4  
It looks like the reason is that the table doesn't exist.
`DB::Exception: Table flow_metrics.`network.1m` does not exist. (UNKNOWN_TABLE)`

### DeepFlow version

Name: deepflow-server community edition
Branch: v6.4
CommitID: ae7405521a46f6e66843e70de89a678c4e8542c8
RevCount: 9700
Compiler: go version go1.20.14 linux/amd64
CompileTime: 2024-03-01 09:44:27

### DeepFlow agent list

<img width="954" alt="image" src="https://github.com/deepflowio/deepflow/assets/1527849/34ec6f53-5893-4768-87f9-c3120b5734a6">

### Kubernetes CNI

`{
  "name": "k8s-pod-network",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "calico",
      "datastore_type": "kubernetes",
      "mtu": 0,
      "nodename_file_optional": false,
      "log_level": "Info",
      "log_file_path": "/var/log/calico/cni/cni.log",
      "ipam": { "type": "calico-ipam", "assign_ipv4" : "true", "assign_ipv6" : "false"},
      "container_settings": {
          "allow_ip_forwarding": false
      },
      "policy": {
          "type": "k8s"
      },
      "kubernetes": {
          "k8s_api_root":"https://10.96.0.1:443",
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type": "bandwidth",
      "capabilities": {"bandwidth": true}
    },
    {"type": "portmap", "snat": true, "capabilities": {"portMappings": true}}
  ]
}`

### Operation-System/Kernel version

Ubuntu 20.04.6 LTS
5.4.0-167-generic

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
Execute ```kubectl describe pods -n deepflow deepflow-grafana-xxx | grep Image:``` Check the image and init image version used by grafana, and check whether the tag of deepflowio-init-grafana-ds-dh is latest. If the deepflow version you are using is v6.4, you need to change the corresponding version to v6.4, because latest is for the latest version.

**Comment by DrAuYueng** [comment]
@1473371932 
I've adjusted the version of deepflowio-init-grafana-ds-dh to v6.4 and it's working fine now. 
Thanks.

**Comment by syzhang42** [comment]
我也遇到了这个问题，但是我将deepflowio-init-grafana-ds-dh调整为了v6.4。
    Image:          registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana:v6.4
    Image ID:       registry.cn-beijing.aliyuncs.com/deepflow-ce/deepflowio-init-grafana@sha256:f5ce063af86db6ca893ca26ab66293410b2de4b1d5bd61bcd0f4e0fd4377be96
    Image:          registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana-ds-dh:v6.4
    Image ID:       registry.cn-beijing.aliyuncs.com/deepflow-ce/deepflowio-init-grafana-ds-dh@sha256:4095cfed29018c27771eb04f1237b3e9f61e045c269ba716041944081927f784
    Image:          registry.cn-beijing.aliyuncs.com/deepflow-ce/grafana:10.4.0
    Image ID:       registry.cn-beijing.aliyuncs.com/deepflow-ce/grafana@sha256:f9811e4e687ffecf1a43adb9b64096c50bc0d7a782f8608530f478b6542de7d5
但是我的grafana界面仍然不能正常显示：
![image](https://github.com/deepflowio/deepflow/assets/155063522/8ad16ef6-65f8-40e5-a9d3-6a77262a66d5)
我查看了sql命令为：
SELECT pod_cluster as `value`, pod_cluster as `display_name` FROM `network.1m`
我检查了我的clickhouse，flow_metrics下并没有network.1m表。
 vtap_acl.1m                  │
│ vtap_acl.1m_local            │
│ vtap_app_edge_port.1m        │
│ vtap_app_edge_port.1m_local  │
│ vtap_app_edge_port.1s        │
│ vtap_app_edge_port.1s_local  │
│ vtap_app_port.1m             │
│ vtap_app_port.1m_local       │
│ vtap_app_port.1s             │
│ vtap_app_port.1s_local       │
│ vtap_flow_edge_port.1m       │
│ vtap_flow_edge_port.1m_local │
│ vtap_flow_edge_port.1s       │
│ vtap_flow_edge_port.1s_local │
│ vtap_flow_port.1m            │
│ vtap_flow_port.1m_local      │
│ vtap_flow_port.1s            │
│ vtap_flow_port.1s_local
我该如何修改让我的grafana正常工作或者该如何定位问题？
