### ISSUE TITLE
[FR] :  Suggest adding a deepflow system dashboard user manual document

### ISSUE THREAD

**Issue by yhcloud123** [deepflowio/deepflow#5771]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Suggest adding a deepflow system dashboard user manual document
Too many indicator icons, unable to understand

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
We are currently writing documentation for the Grafana Dashboard panel, as well as some common deepflow-server / deepflow-agent troubleshooting processes, which will be updated on the official website in succession.

**Comment by yhcloud123** [comment]
> We are currently writing documentation for the Grafana Dashboard panel, as well as some common deepflow-server / deepflow-agent troubleshooting processes, which will be updated on the official website in succession.

You are the best
