### ISSUE TITLE
[BUG] Error: tag auto_service 未在application, flow_metrics中找到

### ISSUE THREAD

**Issue by zzoujinn** [deepflowio/deepflow#5785]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

使用helm部署deepflow，pod running后，grafana数据展示错误
![image](https://github.com/deepflowio/deepflow/assets/28640714/faf4583e-d2c0-48a1-b194-271d37d1f222)

### DeepFlow version

Name: deepflow-server community edition
Branch: v6.3.9
CommitID: 27f802990d1669d4d48f0028d2fb3d9df01b9dd3
RevCount: 8953
Compiler: go version go1.20.8 linux/amd64
CompileTime: 2023-09-18 02:29:20

### DeepFlow agent list

ID   NAME                    TYPE     CTRL_IP        CTRL_MAC            STATE    GROUP     EXCEPTIONS   REVISION      UPGRADE_REVISION
1    2023-k8s-slave-35-V5    K8S_VM   172.16.6.187   52:54:00:23:b1:9d   NORMAL   default                v6.3.9 8953
2    2023-k8s-slave-11-V32   K8S_VM   172.16.6.219   52:54:00:ea:a5:19   NORMAL   default                v6.3.9 8953
3    2023-k8s-slave-12-V15   K8S_VM   172.16.6.220   52:54:00:c6:5a:cb   NORMAL   default                v6.3.9 8953
4    2023-k8s-slave-31-V3    K8S_VM   172.16.6.182   52:54:00:14:dc:b2   NORMAL   default                v6.3.9 8953
5    2023-k8s-slave-6-V39    K8S_VM   172.16.6.207   52:54:00:b9:97:f1   NORMAL   default                v6.3.9 8953
6    2023-k8s-slave-36-V24   K8S_VM   172.16.6.188   52:54:00:4a:54:53   NORMAL   default                v6.3.9 8953
7    2023-k8s-slave-10-V37   K8S_VM   172.16.6.215   52:54:00:99:bf:09   NORMAL   default                v6.3.9 8953
8    2023-k8s-slave-4-V7     K8S_VM   172.16.6.198   52:54:00:8a:76:89   NORMAL   default                v6.3.9 8953
9    2023-k8s-slave-34-V35   K8S_VM   172.16.6.186   52:54:00:d7:15:ee   NORMAL   default                v6.3.9 8953
10   2023-k8s-slave-18-V27   K8S_VM   172.16.6.243   52:54:00:06:8b:ca   NORMAL   default                v6.3.9 8953
11   2023-k8s-slave-33-V8    K8S_VM   172.16.6.185   52:54:00:70:20:5e   NORMAL   default                v6.3.9 8953
12   2023-k8s-slave-17-V38   K8S_VM   172.16.6.242   52:54:00:59:6f:a4   NORMAL   default                v6.3.9 8953
13   2023-k8s-slave-32-V14   K8S_VM   172.16.6.183   52:54:00:5f:a0:b4   NORMAL   default                v6.3.9 8953
14   2023-k8s-slave-5-V19    K8S_VM   172.16.6.204   52:54:00:ab:b9:92   NORMAL   default                v6.3.9 8953
15   2023-k8s-slave-1-V20    K8S_VM   172.16.6.194   52:54:00:ab:e0:64   NORMAL   default                v6.3.9 8953
16   2023-k8s-slave-8-V31    K8S_VM   172.16.6.209   52:54:00:a7:86:ca   NORMAL   default                v6.3.9 8953
17   2023-k8s-slave-15-V28   K8S_VM   172.16.6.232   52:54:00:41:24:48   NORMAL   default                v6.3.9 8953
18   2023-k8s-slave-2-V23    K8S_VM   172.16.6.195   52:54:00:dc:a2:4f   NORMAL   default                v6.3.9 8953
19   2023-k8s-slave-3-V2     K8S_VM   172.16.6.196   52:54:00:f2:9d:e2   NORMAL   default                v6.3.9 8953
20   2023-k8s-slave-14-V6    K8S_VM   172.16.6.230   52:54:00:aa:c0:5c   NORMAL   default                v6.3.9 8953
21   2023-k8s-slave-23-V26   K8S_VM   172.16.6.248   52:54:00:ce:d5:df   NORMAL   default                v6.3.9 8953
22   2023-k8s-slave-26-V33   K8S_VM   172.16.6.175   52:54:00:b0:84:f3   NORMAL   default                v6.3.9 8953
23   2023-k8s-slave-7-V16    K8S_VM   172.16.6.208   52:54:00:83:7a:fb   NORMAL   default                v6.3.9 8953
24   2023-k8s-slave-25-V1    K8S_VM   172.16.6.174   52:54:00:45:99:a8   NORMAL   default                v6.3.9 8953
25   2023-k8s-slave-21-V21   K8S_VM   172.16.6.246   52:54:00:a5:18:a0   NORMAL   default                v6.3.9 8953
26   2023-k8s-slave-22-V22   K8S_VM   172.16.6.247   52:54:00:af:84:18   NORMAL   default                v6.3.9 8953
27   2023-k8s-slave-24-V9    K8S_VM   172.16.6.249   52:54:00:ea:2b:17   NORMAL   default                v6.3.9 8953
28   2023-k8s-slave-27-V13   K8S_VM   172.16.6.176   52:54:00:38:76:af   NORMAL   default                v6.3.9 8953
29   2023-k8s-slave-29-V18   K8S_VM   172.16.6.179   52:54:00:26:bf:8e   NORMAL   default                v6.3.9 8953
30   2023-k8s-slave-30-V30   K8S_VM   172.16.6.181   52:54:00:18:80:17   NORMAL   default                v6.3.9 8953
31   2023-k8s-slave-19-V10   K8S_VM   172.16.6.244   52:54:00:ee:f9:24   NORMAL   default                v6.3.9 8953
32   2023-k8s-slave-28-V4    K8S_VM   172.16.6.178   52:54:00:66:aa:3f   NORMAL   default                v6.3.9 8953
33   2023-k8s-slave-20-V29   K8S_VM   172.16.6.245   52:54:00:9a:02:53   NORMAL   default                v6.3.9 8953
34   2023-k8s-slave-9-V34    K8S_VM   172.16.6.214   52:54:00:56:d7:cf   NORMAL   default                v6.3.9 8953
35   2023-k8s-slave-16-V17   K8S_VM   172.16.6.233   52:54:00:4f:0c:6a   NORMAL   default                v6.3.9 8953

### Kubernetes CNI

flannel

### Operation-System/Kernel version

"Ubuntu 22.04.3 LTS"
5.15.0-88-generic

### Anything else

no

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 0mobb0** [comment]
我也遇到了同样的问题

**Comment by 1473371932** [comment]
> 我也遇到了同样的问题

你好，通过
`kubectl describe pods -n deepflow deepflow-grafana-xxx | grep Image:`
过滤出目前使用的 init 容器镜像，查看对应版本是否和当前 deepflow 使用的 chart 包版本一致，例如当前 DeepFlow 版本为 v6.4 而使用的 init 容器镜像版本为 latest，则需要把 latest 替换为 v6.4

**Comment by 0mobb0** [comment]
> > 我也遇到了同样的问题
> 
> 你好，通过 `kubectl describe pods -n deepflow deepflow-grafana-xxx | grep Image:` 过滤出目前使用的 init 容器镜像，查看对应版本是否和当前 deepflow 使用的 chart 包版本一致，例如当前 DeepFlow 版本为 v6.4 而使用的 init 容器镜像版本为 latest，则需要把 latest 替换为 v6.4

您好，请问是在拉去的chart里面的value.yaml中的
grafana.ini:
    - name: init-grafana-ds-dh
      image: "{{ .Values.global.image.repository }}/deepflowio-init-grafana-ds-dh:6.3.5"
 改吗？
 我修改了并且放到了value-custom.yaml中：
 global:
  allInOneLocalStorage: true
  image:
      repository: registry.cn-beijing.aliyuncs.com/deepflow-ce
grafana:
  image:
    repository: registry.cn-beijing.aliyuncs.com/deepflow-ce/grafana
  grafana.ini:
    paths:
      plugins: /var/lib/grafana/plugins
    analytics:
      check_for_updates: true
    log:
      mode: console
    database:
      type: mysql
      host: "{{ if $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.ip}}{{ else }}{{ $.Release.Name }}-mysql{{end}}:{{ if $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.port}}{{ else }}30130{{end}}"
      name: grafana
      user: "{{ if $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.username}}{{ else }}root{{end}}"
      password: "{{ if $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.password}}{{ else }}{{ .Values.global.password.mysql }}{{end}}"
    plugins:
      allow_loading_unsigned_plugins: deepflow-querier-datasource,deepflow-apptracing-panel,deepflow-topo-panel,deepflowio-tracing-panel,deepflowio-deepflow-datasource,deepflowio-topo-panel

  extraInitContainers:
    - name: init-custom-plugins
      image: "{{ .Values.global.image.repository }}/deepflowio-init-grafana:v6.3.5"
      imagePullPolicy: "{{ tpl .Values.global.image.pullPolicy . }}"
      volumeMounts:
      - name: custom-plugins
        mountPath: /var/lib/grafana/plugins
    - name: init-grafana-ds-dh
      image: "{{ .Values.global.image.repository }}/deepflowio-init-grafana-ds-dh:6.3.5"
      imagePullPolicy: "{{ tpl .Values.global.image.pullPolicy . }}"
      volumeMounts:
      - name: deepflow-dashboards
        mountPath: /tmp/dashboards
      - name: grafana-dashboards-config
        mountPath: /etc/grafana/provisioning/dashboards
      - name: grafana-datasources-config
        mountPath: /etc/grafana/provisioning/datasources
但是我执行helm upgrade deepflow -n deepflow deepflow/deepflow -f values-custom.yaml之后，拉取deepflow-grafana-xxxxx的image一直失败

**Comment by 0mobb0** [comment]
> > 我也遇到了同样的问题
> 
> 你好，通过 `kubectl describe pods -n deepflow deepflow-grafana-xxx | grep Image:` 过滤出目前使用的 init 容器镜像，查看对应版本是否和当前 deepflow 使用的 chart 包版本一致，例如当前 DeepFlow 版本为 v6.4 而使用的 init 容器镜像版本为 latest，则需要把 latest 替换为 v6.4

显示信息如下：
root@k8smaster:/home/mobb# kubectl describe pods -n deepflow deepflow-grafana-5bd9fbc89f-qw6gl | grep Image
    Image:          registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana:v6.3.5
    Image ID:       docker-pullable://registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana@sha256:fddf7a6c6df86c20e42789ca48afcdba40bdfaeb808e96edb93923a2b40f3869
    Image:          registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana-ds-dh:6.3.5
    Image ID:
      Reason:       ImagePullBackOff
    Image:          grafana/grafana:10.1.0
    Image ID:
  Warning  Failed     9m13s (x3 over 11m)   kubelet            Error: ErrImagePull
  Warning  Failed     8m36s (x5 over 11m)   kubelet            Error: ImagePullBackOff

**Comment by 0mobb0** [comment]
> > > 我也遇到了同样的问题
> > 
> > 
> > 你好，通过 `kubectl describe pods -n deepflow deepflow-grafana-xxx | grep Image:` 过滤出目前使用的 init 容器镜像，查看对应版本是否和当前 deepflow 使用的 chart 包版本一致，例如当前 DeepFlow 版本为 v6.4 而使用的 init 容器镜像版本为 latest，则需要把 latest 替换为 v6.4
> 
> 显示信息如下： root@k8smaster:/home/mobb# kubectl describe pods -n deepflow deepflow-grafana-5bd9fbc89f-qw6gl | grep Image Image: registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana:v6.3.5 Image ID: docker-pullable://registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana@sha256:fddf7a6c6df86c20e42789ca48afcdba40bdfaeb808e96edb93923a2b40f3869 Image: registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana-ds-dh:6.3.5 Image ID: Reason: ImagePullBackOff Image: grafana/grafana:10.1.0 Image ID: Warning Failed 9m13s (x3 over 11m) kubelet Error: ErrImagePull Warning Failed 8m36s (x5 over 11m) kubelet Error: ImagePullBackOff



> > > 我也遇到了同样的问题
> > 
> > 
> > 你好，通过 `kubectl describe pods -n deepflow deepflow-grafana-xxx | grep Image:` 过滤出目前使用的 init 容器镜像，查看对应版本是否和当前 deepflow 使用的 chart 包版本一致，例如当前 DeepFlow 版本为 v6.4 而使用的 init 容器镜像版本为 latest，则需要把 latest 替换为 v6.4
> 
> 您好，请问是在拉去的chart里面的value.yaml中的 grafana.ini: - name: init-grafana-ds-dh image: "{{ .Values.global.image.repository }}/deepflowio-init-grafana-ds-dh:6.3.5" 改吗？ 我修改了并且放到了value-custom.yaml中： global: allInOneLocalStorage: true image: repository: registry.cn-beijing.aliyuncs.com/deepflow-ce grafana: image: repository: registry.cn-beijing.aliyuncs.com/deepflow-ce/grafana grafana.ini: paths: plugins: /var/lib/grafana/plugins analytics: check_for_updates: true log: mode: console database: type: mysql host: "{{ if Unable to render expression. $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.ip}}{{ else }}{{ Unable to render expression. $.Release.Name }}-mysql{{end}}:{{ if $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.port}}{{ else }}30130{{end}}" name: grafana user: "{{ if Unable to render expression. $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.username}}{{ else }}root{{end}}" password: "{{ if Unable to render expression. $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.password}}{{ else }}{{ .Values.global.password.mysql }}{{end}}" plugins: allow_loading_unsigned_plugins: deepflow-querier-datasource,deepflow-apptracing-panel,deepflow-topo-panel,deepflowio-tracing-panel,deepflowio-deepflow-datasource,deepflowio-topo-panel
> 
> extraInitContainers: - name: init-custom-plugins image: "{{ .Values.global.image.repository }}/deepflowio-init-grafana:v6.3.5" imagePullPolicy: "{{ tpl .Values.global.image.pullPolicy . }}" volumeMounts: - name: custom-plugins mountPath: /var/lib/grafana/plugins - name: init-grafana-ds-dh image: "{{ .Values.global.image.repository }}/deepflowio-init-grafana-ds-dh:6.3.5" imagePullPolicy: "{{ tpl .Values.global.image.pullPolicy . }}" volumeMounts: - name: deepflow-dashboards mountPath: /tmp/dashboards - name: grafana-dashboards-config mountPath: /etc/grafana/provisioning/dashboards - name: grafana-datasources-config mountPath: /etc/grafana/provisioning/datasources 但是我执行helm upgrade deepflow -n deepflow deepflow/deepflow -f values-custom.yaml之后，拉取deepflow-grafana-xxxxx的image一直失败

是不是我改的地方不对？

**Comment by 1473371932** [comment]
> > > > 我也遇到了同样的问题
> > > 
> > > 
> > > 你好，通过 `kubectl describe pods -n deepflow deepflow-grafana-xxx | grep Image:` 过滤出目前使用的 init 容器镜像，查看对应版本是否和当前 deepflow 使用的 chart 包版本一致，例如当前 DeepFlow 版本为 v6.4 而使用的 init 容器镜像版本为 latest，则需要把 latest 替换为 v6.4
> > 
> > 
> > 显示信息如下： root@k8smaster:/home/mobb# kubectl describe pods -n deepflow deepflow-grafana-5bd9fbc89f-qw6gl | grep Image Image: registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana:v6.3.5 Image ID: docker-pullable://registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana@sha256:fddf7a6c6df86c20e42789ca48afcdba40bdfaeb808e96edb93923a2b40f3869 Image: registry.cn-hongkong.aliyuncs.com/deepflow-ce/deepflowio-init-grafana-ds-dh:6.3.5 Image ID: Reason: ImagePullBackOff Image: grafana/grafana:10.1.0 Image ID: Warning Failed 9m13s (x3 over 11m) kubelet Error: ErrImagePull Warning Failed 8m36s (x5 over 11m) kubelet Error: ImagePullBackOff
> 
> > > > 我也遇到了同样的问题
> > > 
> > > 
> > > 你好，通过 `kubectl describe pods -n deepflow deepflow-grafana-xxx | grep Image:` 过滤出目前使用的 init 容器镜像，查看对应版本是否和当前 deepflow 使用的 chart 包版本一致，例如当前 DeepFlow 版本为 v6.4 而使用的 init 容器镜像版本为 latest，则需要把 latest 替换为 v6.4
> > 
> > 
> > 您好，请问是在拉去的chart里面的value.yaml中的 grafana.ini: - name: init-grafana-ds-dh image: "{{ .Values.global.image.repository }}/deepflowio-init-grafana-ds-dh:6.3.5" 改吗？ 我修改了并且放到了value-custom.yaml中： global: allInOneLocalStorage: true image: repository: registry.cn-beijing.aliyuncs.com/deepflow-ce grafana: image: repository: registry.cn-beijing.aliyuncs.com/deepflow-ce/grafana grafana.ini: paths: plugins: /var/lib/grafana/plugins analytics: check_for_updates: true log: mode: console database: type: mysql host: "{{ if Unable to render expression. Unable to render expression.
> >         
> >         $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.ip}}{{ else }}{{ Unable to render expression. Unable to render expression.
> >         
> >         $.Release.Name }}-mysql{{end}}:{{ if $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.port}}{{ else }}30130{{end}}" name: grafana user: "{{ if Unable to render expression. Unable to render expression.
> >         
> >         $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.username}}{{ else }}root{{end}}" password: "{{ if Unable to render expression. Unable to render expression.
> >         
> >         $.Values.global.externalMySQL.enabled }}{{$.Values.global.externalMySQL.password}}{{ else }}{{ .Values.global.password.mysql }}{{end}}" plugins: allow_loading_unsigned_plugins: deepflow-querier-datasource,deepflow-apptracing-panel,deepflow-topo-panel,deepflowio-tracing-panel,deepflowio-deepflow-datasource,deepflowio-topo-panel
> > extraInitContainers: - name: init-custom-plugins image: "{{ .Values.global.image.repository }}/deepflowio-init-grafana:v6.3.5" imagePullPolicy: "{{ tpl .Values.global.image.pullPolicy . }}" volumeMounts: - name: custom-plugins mountPath: /var/lib/grafana/plugins - name: init-grafana-ds-dh image: "{{ .Values.global.image.repository }}/deepflowio-init-grafana-ds-dh:6.3.5" imagePullPolicy: "{{ tpl .Values.global.image.pullPolicy . }}" volumeMounts: - name: deepflow-dashboards mountPath: /tmp/dashboards - name: grafana-dashboards-config mountPath: /etc/grafana/provisioning/dashboards - name: grafana-datasources-config mountPath: /etc/grafana/provisioning/datasources 但是我执行helm upgrade deepflow -n deepflow deepflow/deepflow -f values-custom.yaml之后，拉取deepflow-grafana-xxxxx的image一直失败
> 
> 是不是我改的地方不对？

你的 tag 版本不对呀，你看其他的 tag，前面都有一个 v，所以应该是 v6.3.5，不过目前 LTS 版本是 v6.4，建议升级到这个版本
