### ISSUE TITLE
[BUG] 监控多个 K8s 集群情况下如何为agent指定agent-group

### ISSUE THREAD

**Issue by wys-AQ** [deepflowio/deepflow#5824]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

在监控多个k8s集群时以
`helm install … -f values-custom.yaml`方式进行agent的部署，
希望能够通过修改values-custom.yaml的方式指定agent-group，但是我现在只有clusterNAME和deepflowK8sClusterID两个配置项生效，vtap-group-id-request不生效
不知道values-custom.yaml中指定agent-group的字段名称是什么

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by wys-AQ** [comment]
> https://deepflow.io/docs/zh/best-practice/agent-advanced-config/
> 
> 参考一下这里

直接修改configmap后，[https://github.com/deepflowio/deepflow/issues/3402](url) 中提到的问题还在吗？需不需要在组内删除agent

**Comment by 1473371932** [comment]
> > https://deepflow.io/docs/zh/best-practice/agent-advanced-config/
> > 参考一下这里
> 
> 直接修改configmap后，[https://github.com/deepflowio/deepflow/issues/3402](url) 中提到的问题还在吗？需不需要在组内删除agent

有两种方式：
1. 例如你发的这个 issue，需要通过 deepflow-ctl 删除 agent 后重新注册
2. 通过`deepflow-ctl agent update-example·`查看示例后使用`deepflow-ctl agent update -f 指定文件`更新即可
