### ISSUE TITLE
[BUG] 部署agent，agent通过nginx连接主集群时候，失败

### ISSUE THREAD

**Issue by yangjie1993** [deepflowio/deepflow#5862]
### Search before asking

- [ ] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

![image](https://github.com/deepflowio/deepflow/assets/18029405/1d6ab4d1-cbd9-4905-83dc-740d08fcf574)
agent 连接server异常

### How to reproduce

通过216.11上的nginx31035，31033代理，216.62上的30035，30033端口（62为server集群）
nginx配置如下
server {

        listen          31035;
        server_name     12.1.216.11;
        #ssl on;
        ### SSL log files ###
        access_log      logs/deepflow-31035-access.log;
        error_log       logs/deepflow-31035-error.log;

        ### SSL cert files ###
        #ssl_certificate      key/server.crt;
        #ssl_certificate_key  key/server.key;
        ### Add SSL specific settings here ###
        keepalive_timeout    60;
        error_page   404 500 502 503 504  /50x.html;

        ###  Limiting Ciphers ########################
        # Uncomment as per your setup
        #ssl_ciphers HIGH:!ADH;
        #ssl_perfer_server_ciphers on;
        #ssl_protocols SSLv3;
        ##############################################
        ### We want full access to SSL via backend ###

        client_max_body_size   60m;
		
        location / {
            proxy_pass  http://12.0.216.62:30035;
            #proxy_set_header  Host  $host;
            #proxy_set_header X-Real-IP $remote_addr;
            #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            #proxy_ssl_ciphers RC4-MD5;
            #proxy_ssl_protocols TLSv1;
        }
}

agent cm 配置如下
![image](https://github.com/deepflowio/deepflow/assets/18029405/04033757-fa2b-42dd-9ac8-3b0cac434b8d)
nginx 报错如下
![image](https://github.com/deepflowio/deepflow/assets/18029405/2977f0a1-2cb8-45c5-83c9-49ad42f31f97)

### DeepFlow version

6.3.9

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
https://www.nginx.com/blog/nginx-1-13-10-grpc/

<img width="686" alt="image" src="https://github.com/deepflowio/deepflow/assets/1598518/2607365f-f3b1-41e3-92fb-b63db3fd4edc">

应该是 nginx 配置不正确。

DeepFlow 控制面使用 gRPC 协议，数据面用的 TCP 协议。

**Comment by yangjie1993** [comment]
> https://www.nginx.com/blog/nginx-1-13-10-grpc/
> 
> <img alt="image" width="686" src="https://private-user-images.githubusercontent.com/1598518/317967081-2607365f-f3b1-41e3-92fb-b63db3fd4edc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTM4MzMsIm5iZiI6MTcxMTY5MzUzMywicGF0aCI6Ii8xNTk4NTE4LzMxNzk2NzA4MS0yNjA3MzY1Zi1mM2IxLTQxZTMtOTJmYi1iNjNkYjNmZDRlZGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjlUMDYyNTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGFjN2EzM2Y3MjgwOGZhZDRjZDc3ODBjZjQ0NDAyZTcwZTIzN2EyYzVhNzIzNDdlNDUzNzVjZGIzZjBjOTg3MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UwZ9ZENO1bBT_EKifsncnAUF2Nof7NrYnNnJ8Z9aNFs">
> 应该是 nginx 配置不正确。
> 
> DeepFlow 控制面使用 gRPC 协议，数据面用的 TCP 协议。

能否方便提供一下另一个端口30033的nginx配置
