### ISSUE TITLE
[BUG] 进程方式部署的Agent的一些指标，例如quadruple-queue-size，没法通过deepflow-ctl进行更新下发

### ISSUE THREAD

**Issue by SeSehaha** [deepflowio/deepflow#5914]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

进程方式部署的Agent的一些指标，例如quadruple-queue-size，没法通过deepflow-ctl  agent-group-config update -f agent-group-config.yaml进行更新后下发，具体agent-group配置如下：
vtap_group_id: g-XRZHv702Ny
max_cpus: 4
max_memory: 4096
platform_enabled: 1
static_config:
    flow-queue-size: 1000000
    quadruple-queue-size: 1000000
    flow-sender-queue-size: 1000000

### DeepFlow version

kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v:
2024/03/27 10:17:20 ENV K8S_NODE_NAME_FOR_DEEPFLOW=minikube; K8S_NODE_IP_FOR_DEEPFLOW=192.168.49.2; K8S_POD_NAME_FOR_DEEPFLOW=deepflow-server-b75f57786-8v5h6; K8S_POD_IP_FOR_DEEPFLOW=10.244.0.24; K8S_NAMESPACE_FOR_DEEPFLOW=deepflow
Name: deepflow-server community edition
Branch: v6.4
CommitID: 4fbba1c9b4df8b8115c798f8ab497d723a1a23e8
RevCount: 9753
Compiler: go version go1.20.14 linux/amd64
CompileTime: 2024-03-26 17:55:05

agent进程方式部署
/usr/sbin/deepflow-agent -v：
9864-61d84ca50ed6826c993a2dacafb51edbb9ac88fe
Name: deepflow-agent community edition
Branch: v6.5.2
CommitId: 61d84ca50ed6826c993a2dacafb51edbb9ac88fe
RevCount: 9864
Compiler: rustc 1.75.0 (82e1608df 2023-12-21)
CompileTime: 2024-03-13 02:40:58

### Operation-System/Kernel version

awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"Alibaba Cloud Linux 3 (Soaring Falcon)"

uname -r
5.10.134-16.1.al8.x86_64

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
注：格式没问题，上面因为没使用代码块，前面的缩进没了，实际格式
![ab643b7c4f91933463a5471f27fe3b8](https://github.com/deepflowio/deepflow/assets/84362246/0e98c00e-6f55-49b4-81aa-0efe637f1d27)
更新后，通过日志并没有过滤到对应参数

**Comment by rvql** [comment]
@SeSehaha @1473371932 我测试没有问题

高级配置的修改会触发采集器重启，可以检索如下日志
```
yaml_config updated, deepflow-agent restart...
```

**Comment by 1473371932** [comment]
> @SeSehaha @1473371932 我测试没有问题
> 
> 高级配置的修改会触发采集器重启，可以检索如下日志
> 
> ```
> yaml_config updated, deepflow-agent restart...
> ```

昨天这个 ISSUE 已解决，忘记关了，static_config: 下对应的三个参数，日志中不输出，是在预期内的，不会影响配置的效果
