### ISSUE TITLE
网卡数据是怎么获取的？

### ISSUE THREAD

**Issue by lobsterHe** [deepflowio/deepflow#5948]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在deepflow-agent的代码中，没看到bpf获取网卡数据的代码。这块逻辑是怎么样的？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
使用 af_packet 接口获取的。在 dispatcher 中可以查看到代码。

agent/src/dispatcher/base_dispatcher.rs

**Comment by RichardoMrMu** [comment]
请问下，dispatcher获取到网卡数据后是如何串联起来的呢？flow_id吗。这部分逻辑是在哪里实现的呢？
