### ISSUE TITLE
[BUG] 基于 docker-compose 部署 All-in-One DeepFlow 时提示 镜像 deepflow-ce/deepflow-app:v6.5.3 不存在

### ISSUE THREAD

**Issue by JellyTony** [deepflowio/deepflow#5949]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

![image](https://github.com/deepflowio/deepflow/assets/106534114/07e0cbcf-113a-4097-a647-910fd9fb9a20)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
当时应该是镜像没有同步上传导致的原因，后续已同步更新对应版本镜像

**Comment by JellyTony** [comment]
ali one 能把 agent  加进去吗
