### ISSUE TITLE
跨节点的链路显示异常

### ISSUE THREAD

**Issue by yunzck8s** [deepflowio/deepflow#5950]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

查看不同节点服务的调用链路和在同一节点的显示一致

### How to reproduce

使用文档中提供的链路deepflow-ebpf-spring-demo，查看不同节点服务的链路

### DeepFlow version

deepflow-server: v6.4
deepflow-agent: v6.4

### Kubernetes CNI

flannel

### Operation-System/Kernel version

"Rocky Linux 9.3 (Blue Onyx)"
5.14.0-362.8.1.el9_3.x86_64

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
能否提供一下对应 Dashboard 的展示效果，以及你预期的效果呢？

**Comment by yunzck8s** [comment]
@1473371932 好的，首先是跨节点异常的链路，
![pic](https://github.com/deepflowio/deepflow/assets/86189975/f197c8e8-adcd-406e-a384-9bfbcbc2f069)

下面是同节点正常的链路
![pic(1)](https://github.com/deepflowio/deepflow/assets/86189975/0cd59f9c-8334-4a9b-9e92-12dc9489cae1)

**Comment by sharang** [comment]
@yunzck8s 你的问题应该是不同节点的时差造成的，确认 NTP 是否已经正确进行了时钟同步。不过同步之后不同节点之间仍然可能会有毫秒级别的时差。

**Comment by sharang** [comment]
从图中来看，跨节点、同节点均展示了正确的数据：
- 跨节点
  - Client NIC（Pod 的网卡）
  - Client Node NIC
  - Server Node NIC
  - Server NIC（Pod 的网卡）
- 同节点
  - Client NIC（Pod 的网卡）
  - Server NIC（Pod 的网卡）
