### ISSUE TITLE
[BUG] 关于click house flow_metrics中表与示例grafana中不符的问题。

### ISSUE THREAD

**Issue by syzhang42** [deepflowio/deepflow#5952]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

我检查了grafana中的查询sql。比如：
![image](https://github.com/deepflowio/deepflow/assets/155063522/45ad21e8-3769-42c6-ad9c-79f9eb2c97c1)
![image](https://github.com/deepflowio/deepflow/assets/155063522/8690cdd9-5693-4129-a34e-c932d4a0ac60)
我查看了clickhouse中flow_metrics中的表，非常疑惑的是只有下面这些表，并没有grafana中查询语句提到那些表：
![image](https://github.com/deepflowio/deepflow/assets/155063522/efac328a-1a39-4e49-9dca-9d91a2be92ef)
是我环境有问题吗?我该如何修复他？

### How to reproduce

使用官方部署单个集群案例。

### DeepFlow version

v6.4.9

### DeepFlow agent list

flannel

### Kubernetes CNI

flannel

### Operation-System/Kernel version

5.15.0-52-generic

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by syzhang42** [comment]
我的 agent list:
ID   NAME            TYPE     CTRL_IP          CTRL_MAC            STATE    GROUP     EXCEPTIONS   REVISION    UPGRADE_REVISION
1    ebpf-node1-V2   K8S_VM   172.31.185.136   fa:16:3e:be:92:16   NORMAL   default                v6.4 9758

2    ebpf-node2-V3   K8S_VM   172.31.186.154   fa:16:3e:41:eb:5b   NORMAL   default                v6.4 9758

**Comment by lzf575** [comment]
v6.5 和main 的 ck中的表名称 和v6.4 中不同了。 你的server使用v6.4版本，而grafana使用了main的，切换grafana为6.4版本的即可。  也可能是开源的grafana打包有问题  @1473371932 确认下

**Comment by 1473371932** [comment]
https://github.com/deepflowio/deepflow/issues/5785

参考一下这个 issue

**Comment by syzhang42** [comment]
我导出了我的grafana配置：
kubectl get pod deepflow-grafana-746798d66-4g8kv -n deepflow -o yaml > deepflow-grafana-pod.yaml
然后修改了版本并apply,得到如下结果：
![image](https://github.com/deepflowio/deepflow/assets/155063522/cfaec11c-9fe3-4332-bd3e-58cf44580fa9)
使用NODE_PORT=$(kubectl get --namespace deepflow -o jsonpath="{.spec.ports[0].nodePort}" services deepflow-grafana)
NODE_IP=$(kubectl get nodes -o jsonpath="{.items[0].status.addresses[0].address}")
echo -e "Grafana URL: http://$NODE_IP:$NODE_PORT  \nGrafana auth: admin:deepflow"命令获得我的grafana地址，
遗憾的是我的grafana依旧是新的表
![image](https://github.com/deepflowio/deepflow/assets/155063522/d95b0b83-fec9-4aa7-a7f7-241694a79829)
是因为grafana没有正常重新加载吗

**Comment by 1473371932** [comment]
![Snipaste_2024-04-01_10-17-58](https://github.com/deepflowio/deepflow/assets/84362246/3357b527-c942-4c03-bacc-0d464d5f6813)
![Snipaste_2024-04-01_10-19-05](https://github.com/deepflowio/deepflow/assets/84362246/524d51ad-a737-42f5-a9c7-b3b9c22591bb)

我建议先把 grafana 重建一下（如果没有进行数据持久化），如果进行了数据持久化，建议先把 dashboard 目录里面的面板都删掉，然后再重建一下
