### ISSUE TITLE
[BUG] agent standalone模式下ebpf采集不生效

### ISSUE THREAD

**Issue by qyzhaoxun** [deepflowio/deepflow#5967]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

standalone模式下agent ebpf采集器也能正常工作，将flow_log写入l7_flow_log

### How to reproduce

在k8s环境下直接部署deepflow-agent daemonset，deepflow-agent容器启动后，在/var/log/deepflow-agent/目录正常生成l4_flow_log和l7_flow_log，不过l7_flow_log signal_source只有Packet，没有ebpf
<img width="1727" alt="image" src="https://github.com/deepflowio/deepflow/assets/6142614/23d5e34d-d299-45ce-ac86-5c86e39f31e8">

部署yaml信息: 
[deepflow-agent.yaml.txt](https://github.com/deepflowio/deepflow/files/14816509/deepflow-agent.yaml.txt)

### DeepFlow version

9935-cfb3560378f755d37bb9b9c1e41305483b0eff4e
Name: deepflow-agent community edition
Branch: v6.5.3
CommitId: cfb3560378f755d37bb9b9c1e41305483b0eff4e
RevCount: 9935
Compiler: rustc 1.75.0 (82e1608df 2023-12-21)
CompileTime: 2024-03-27 02:15:14

### Kubernetes CNI

deepflow-agent是以hostnetwork方式运行在tke集群上

### Operation-System/Kernel version

"Ubuntu 22.04 LTS"
5.15.0-94-generic

### Anything else

# deepflow-agent 日志
[deepflow-agent.log](https://github.com/deepflowio/deepflow/files/14816503/deepflow-agent.log)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lzf575** [comment]
@qyzhaoxun  本地看了下，有ebpf的数据。
![image](https://github.com/deepflowio/deepflow/assets/44988793/d628d259-358d-4175-ab71-de203e1fac2c)
你确认下，ebpf需要 kernel 版本大于 4.14+ 才支持。也看下有没有'ebpf collector init' 日志
![image](https://github.com/deepflowio/deepflow/assets/44988793/4f33098e-0f6b-4aa0-a25b-47ad1087f7e2)

**Comment by sharang** [comment]
@yinjiping 看看 issue 正文中的 deepflow log 文件

**Comment by yinjiping** [comment]
@qyzhaoxun 我看日志没发现什么异常
可执行下面命令，来看看数据统计：
- 进入POD
```
kubectl exec deepflow-agent-sgm5p -n deepflow -it -- bash
```
- 查询统计
```
root@deepflow-agent-sgm5p:/# deepflow-ebpfctl tracer show
Tracer             socket-trace
Bpf buffer         socket-trace-bpf-linux-common
Workers            1
Perf-Pages-Count   128
Events Lost        0
Probes Count       6
State              TRACER_RUNNING
Adapt              1
data_limit_max     1024

-------------------- Queue ---------------------------
worker 0 for queue, de 68 en 68 lost 0 alloc failed 0 burst 7325125 queue size 0 cap 65535

SUM dequeue 68 enqueue 68 lost 0 alloc failed 0 burst count 7325125

-------------------- Protocol ------------------------
- Unknown   (0) 1822436
- HTTP1     (20) 2122072
- HTTP2     (21) 1213292
- Dubbo     (40) 2
- MySQL     (60) 125647271
- PgSQL     (61) 3690
- Redis     (80) 42822
- MongoDB   (81) 1840
- MQTT      (101) 981
- AMQP      (102) 6004204
- DNS       (120) 2503711
- TLS       (121) 422145
```

多次执行上面的命令，如果上面各个协议的数据统计大于0并且多次执行观察是递增的，说明eBPF获取数据正常。

**Comment by qyzhaoxun** [comment]
感谢，这块使用v6.4可以看到ebpf正常工作，并且能将http/dns协议采集到并且成功落盘，但是https和http2协议采集不到，怀疑是不是类似问题

**deepflow-agent配置文件**
<img width="564" alt="image" src="https://github.com/deepflowio/deepflow/assets/6142614/05a37b1c-b9ea-4ec1-a694-8e38245d36c8">
**配置文件下能看到针对kube-proxy-bin确实hook了相关uprobe函数**
<img width="1727" alt="image" src="https://github.com/deepflowio/deepflow/assets/6142614/2314cbd6-10f4-4c4a-848e-5e5abb54d5f8">
**但是l7_flow_log下一直没有看到对应https的日志**
<img width="678" alt="image" src="https://github.com/deepflowio/deepflow/assets/6142614/dbbd80b3-fa8a-4e88-b4ec-58591e7dc03b">
**另外使用deepflow-ebpfctl tracer show没有看到TLS/HTTP2有增加**
<img width="690" alt="image" src="https://github.com/deepflowio/deepflow/assets/6142614/f25d7c89-81ef-49cd-b793-2674f5de12d3">

**Comment by sharang** [comment]
@yuanchaoa 来继续看看，并确认 standalone 和普通模式差异点在哪些环节，确认是否还有其他问题。

**Comment by yinjiping** [comment]
@qyzhaoxun 您好，确认下下面这些类型符号是否存在：
```
go.itab.*net.TCPConn,net.Conn
go.itab.*crypto/tls.Conn,net.Conn
go.itab.*golang.org/x/net/http2/h2c.rwConn,net.Conn
go:itab.*golang.org/x/net/http2/h2c.bufConn,net.Conn
```
eBPF会利用上面这些类型符号地址，进行`conn`的判断来获取必要的数据。

```bash
nm /proc/518263/root/usr/local/bin/kube-proxy-bin | grep "Conn,net.Conn"
```

**Comment by qyzhaoxun** [comment]
<img width="1111" alt="image" src="https://github.com/deepflowio/deepflow/assets/6142614/2bc9498e-a4e2-4e09-9c0e-80e96433095f">

nm: /proc/615963/root/usr/local/bin/kube-proxy-bin: no symbols
这样是表明支持不了吗？

**Comment by yinjiping** [comment]
@qyzhaoxun 是的，没有符号表，就没有办法了这是个前提条件。

**Comment by qyzhaoxun** [comment]
不过上面日志不是显示的INFO Uprobe了一些函数吗？这个是实际上没有uprobe成功啊

**Comment by sharang** [comment]
> 不过上面日志不是显示的INFO Uprobe了一些函数吗？这个是实际上没有uprobe成功啊

这个日志打印的不合理，图中的 nil 实际上是一个失败的行为，我们会改为 Warning 并给出明确的失败说明

![image](https://github.com/deepflowio/deepflow/assets/1598518/528bb860-1e04-4f9f-98d8-6471bbd53ee9)

**Comment by yinjiping** [comment]
> 不过上面日志不是显示的INFO Uprobe了一些函数吗？这个是实际上没有uprobe成功啊

这个是不是有配置配置项`golang-symbol:` ?，它尝试一把解析，但是最终还是没有把`go:itab.*net.TCPConn,net.Conn`解析出来。
