### ISSUE TITLE
网卡数据获取后，是如何串联起来的？

### ISSUE THREAD

**Issue by RichardoMrMu** [deepflowio/deepflow#6038]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在deepflow-agent的代码中，使用 af_packet 接口获取网卡数据。在 dispatcher 中可以查看到代码。
agent/src/dispatcher/base_dispatcher.rs。请问下，获取到的网卡数据，是通过什么来进行串联起来的，这部分逻辑在哪里实现的。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
我们会获取 TCP Header 中的 Seq 字段，使用它来做数据的串联。

**Comment by sharang** [comment]
在 agent/src/ 下搜索 tcp_seq 可以看到相关代码

**Comment by RichardoMrMu** [comment]
@sharang 我在阅读代码的时候，有一些问题，比如从网卡中通过apacket获取的网卡数据包，是http请求拆分后的结果，那是在哪里进行和并，将网卡数据包合并成一个完整的http请求，并从中提起header中的seq字段的呢？
