### ISSUE TITLE
[FR] gRPC collection supports streaming mode

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [deepflowio/deepflow#6042]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

## RPC 调用类型（普及一些概念）

在 gRPC 的**单次服务调用**中，客户端和服务端在 `HTTP/2` 连接中使用 **相同的流 ID（Stream Identifier）** 进行通信，即在两端之间，帧（Frame）所携带的流 ID 相同。

有以下几种调用类型：

* Unary RPC：最简单的 RPC 类型，客户端请求，服务端应答
* Server streaming RPC：服务端返回信息流（多个 `DATA` 帧）以响应客户端请求
* Client streaming RPC：客户端向服务端发送信息流（多个 `DATA` 帧），服务端通常在接收到所有客户端请求后，以一条消息进行响应
* Bidirectional streaming RPC：由客户端发起调用，客户端和服务端可以**按任意顺序读写消息**，在这种模式下，可以是服务端接收到客户端所有消息后再写入消息，或者基于一答一应的模式进行处理。

*参考自：[RPC life cycle](https://grpc.io/docs/what-is-grpc/core-concepts/#rpc-life-cycle)*

在 `Unary RPC` 模式下，`Server` 和 `Client`  遵循 `请求-响应` 的原则进行工作，而在 `Stream` 模式下，**请求和响应并非一一对应**，服务调用以服务端的  `HEADERS(End Stream=1)` 标识结束。

以一个 `Bidirectional streaming RPC`  举例：

* 【1】客户端发起请求：发送一个 `HEADERS` 帧携带所请求服务接口的 `:path`
* 【2】客户端发送请求数据：发送若干携带请求数据  `DATA` 帧，每个帧携带一个独立客户端消息
* 【3】服务端返回响应：发送一个完整的  `HEADERS` 帧（`End Headers=1`）表示连接成功（`:status=200 OK`）但流并未结束（`End Stream=0`），随后发送若干个携带请求响应的  `DATA`  帧，每个帧携带一个独立服务端消息
* 【4】服务端关闭流：发送一个完整的  `HEADER` 帧（`End Headers=1`），标识请求响应成功（`grpc-status=0`）并结束流（ `End Stream=1`）

![image](https://github.com/deepflowio/deepflow/assets/42019787/cfd7f8e8-151b-471d-b3f5-cabb92e508a7)

### Server streaming RPC

调用模型如下，客户端以一条消息请求，服务端发送消息流进行响应

```mermaid
sequenceDiagram
    participant Client as Client
    participant Server as Server
    
    Client->>Server: stream.Send (Request)  | DATA [StreamID=1]
    Server->>Client: stream.Send (Response)  | DATA [StreamID=1]
    Server->>Client: stream.Send (Response)  | DATA [StreamID=1]
    Server->>Client: stream.Send (Response) | DATA [StreamID=1]
```

可以看到耗时统计不准确，以 Server **第一次** 消息响应作为应用调用日志（RequestLog）结束的响应聚合成回话（Session），所以 Tracing 记录的请求耗时只有 500ms，而实际 C/S 进行了 2s 左右的交互

![image](https://github.com/deepflowio/deepflow/assets/42019787/b3c2d513-bec4-402b-8c7c-04d5c3b82da7)

![image](https://github.com/deepflowio/deepflow/assets/42019787/1ee508ce-0a86-4467-b782-cbef23895181)

### Client streaming RPC

调用模型如下，客户端发送消息流，服务端接收全部消息后返回一条消息进行响应

```mermaid
sequenceDiagram
    participant Client as Client
    participant Server as Server
    
    Client->>Server: stream.Send (Request)  | DATA [StreamID=1]
    Client->>Server: stream.Send (Request)  | DATA [StreamID=1]
    Client->>Server: stream.Send (Request)  | DATA [StreamID=1]
    Server->>Client: stream.Send (Response) | DATA [StreamID=1]
```

可以看到：

* 耗时统计准确
* Deepflow 调用链没有展示出消息交互的过程，该场景通过 Otel SDK 记录 span 后是可以精确到「gPRC 消息（Message）」级别的

![image](https://github.com/deepflowio/deepflow/assets/42019787/4e507bc9-55ac-4347-a015-24054b7568d9)

![image](https://github.com/deepflowio/deepflow/assets/42019787/21af3230-4bea-4653-9e34-a64b99f22794)

### Bidirectional streaming RPC

调用模型如下，由客户端开启请求，客户端服务端之间进行多次消息传递

```mermaid
sequenceDiagram
    participant Client as Client
    participant Server as Server
    
    Client->>Server: stream.Send (Request)  | DATA [StreamID=1]
    Client->>Server: stream.Send (Request)  | DATA [StreamID=1]
    Server->>Client: stream.Send (Response)  | DATA [StreamID=1]
    Server->>Client: stream.Send (Response) | DATA [StreamID=1]
    Client->>Server: stream.Send (Request)  | DATA [StreamID=1]
    Server->>Client: stream.Send (Response) | DATA [StreamID=1]
```

同  `Server streaming RPC`，应用调用日志（RequestLog）以第一条 Server 消息响应聚合成会话（Session），实际 5s 的请求在 Tracing 中记录为 500ms

![image](https://github.com/deepflowio/deepflow/assets/42019787/70310d0f-96b3-413d-95f5-97defd7e6f80)

![image](https://github.com/deepflowio/deepflow/assets/42019787/fc72edd8-6b75-46af-881d-6c67bef54129)

### 总结

综上目前 Deepflow 对 gRPC 流的支持有以下问题：

* 应用调用日志（RequestLog）需要严格遵循 `请求-响应` 才能聚合成会话（Session），而在 `Bidirectional streaming RPC` / `Server streaming RPC` 模式下请求响应**并不是一一对应的关系**，所以出现了上图会话聚合过早，请求耗时统计明显小于实际情况的现象
* 展示粒度过大：无法展示消息（gRPC Message）级别的 span，统计的是会话耗时，而这通过 otel SDK + APM 是可以做到的

通过阅读 Agent 对 `HTTP/2` 的解析源码，我们发现问题大概率出在 [flow_generator/protocol_logs/http.rs #L1103](https://github.com/deepflowio/deepflow/blob/3b04281b2855176c3ab4c56779b5c36cb308efcf/agent/src/flow_generator/protocol_logs/http.rs#L1103)，Agent 认为存在  `:status`  头部时 gRPC 即完成响应并打上 `LogMessageType::Response`，但实际携带有 `:status` 的 `HEADERS` 通常会在响应体之前发出，而实际 gRPC 请求的结束要通过 [grpc-status](https://grpc.io/docs/guides/status-codes/) 判断，该处理会导致接收到响应消息后对应用调用日志（RequestLog）过早地聚合成会话（Session），但实际请求并未完成。

如下，在建立流成功后服务端马上返回带有 `:status=200` 的  `HEADERS` 帧，而实际请求是在 `grpc-status=0` 的 `HEADERS` 帧标识结束。

![image](https://github.com/deepflowio/deepflow/assets/42019787/cbd3d90d-7c06-4fb2-bfa4-000fbbf20d39)

当然上面的分析修复只能解决「流耗时」统计的问题，修复后大概率可以看到一个耗时超长的 span，包含服务端和客户端 n 次消息交换，可以继续探讨 gRPC 是否有可能以 `消息（Message）`  级别展示调用链。

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
赞 FR，很详细

**Comment by ZhuoZhuoCrayon** [comment]
[pcap.tgz](https://github.com/deepflowio/deepflow/files/14976376/pcap.tgz)

**Comment by sharang** [comment]
# 目标

将 gRPC DATA Frame 提取为一种特殊的 Request Log，并使得它能在分布式追踪的结果中出现，以及能通过 Wasm Plugin 进行增强解析。

# 改变

对于 gRPC 协议：
- 当`请求` Frame 的类型为 DATA 时，构建一个 `request_type = _DATA、type = SESSION` 的 Request Log
- 当`响应` Frame 的类型为 HEADER 时
  - 当 `status == 200 && 不包含 grpc-status 字段`时，构建一个 `request_type = _HEADER、type = SESSION` 的 Request Log
  - 否则，正常构建 `type=RESPONSE` 的单向 Request Log 并和前面的 `type = REQUEST` 的 Request Log 聚合
- 当`响应` Frame 的类型为 DATA 时，构建一个 `request_type = _DATA、type = SESSION` 的 Request Log

响应的：gRPC 的 `response_code/status` 等字段改为由 [grpc-status](https://grpc.github.io/grpc/core/md_doc_statuscodes.html) 字段确定

# 效果

一个完整的 gRPC Stream 自此会包含如下 Request Log
1. 一个或多个 Request，对应 HEADER Frame 的请求
2. 零个或多个 Requset，对应 DATA Frame 的请求
3. 零个或一个 Response，对应 HEADER Frame、status == 200 且不含 grpc-status 的响应
4. 零个或多个 Response，对应 DATA Frame 的响应
5. 一个 Response，对应 HEADER Frame 的响应，且 status != 200 或含有 grpc-status

在 DeepFlow 页面上，展现的 Request Log 共有：
- 上述「1」和「5」聚合的一条，`type = SESSION，request_type = $HTTP_METHOD，duration = 整个交互过程耗时`
- 上述「2」每个单独成一条，共零条或多条，`type = SESSION（实际上只有 Request），request_type = _DATA，duration = 0`
- 上述「3」每个单独成一条，共零条或一条，`type = SESSION（实际上只有 Response），request_type = _HEADER，duration = 0`
- 上述「4」每个单独成一条，共零条或多条，`type = SESSION（实际上只有 Response），request_type = _DATA，duration = 0`

在分布式追踪火焰图中，能将上面这些 Request Log 都呈现出来。

# 注意

- 上述「2 - 4」均可使用 Wasm Plugin 增强解析，获取 Protobuf 中的内容。
- 上述「2 - 4」不要贡献到 flow_metrics.application/application_map 表的指标中，即不要为聚合指标中的请求数、响应数、时延、超时、异常等做贡献。

**Comment by sharang** [comment]
更多 pcap 样例：https://wiki.wireshark.org/gRPC
