### ISSUE TITLE
[BUG] on data on Grafana dashboard

### ISSUE THREAD

**Issue by waterloo2018** [deepflowio/deepflow#6060]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

On the Grafana dashboard, the  [DeepFlow Templates] don't work, and there is no data shown on the board. 

### How to reproduce

Linux  6.1.19-7.0.0.17.oe2303.aarch64 #1 SMP Tue Mar 28 00:01:56 CST 2023 aarch64 aarch64 aarch64 GNU/Linux

### DeepFlow version

Name: deepflow-server community edition
Branch: v6.4
CommitID: 3c8e0522e002405d80daa6e9a29c0dd0cb902986
RevCount: 9775
Compiler: go version go1.20.14 linux/amd64
CompileTime: 2024-04-09 06:17:21

Name: deepflow-agent community edition
Branch: v6.4
CommitId: 3d95dcc02082634facb0a062c117bbdb269e974e
RevCount: 9770
Compiler: rustc 1.75.0 (82e1608df 2023-12-21)
CompileTime: 2024-04-02 11:28:21

### DeepFlow agent list

Normal

### Kubernetes CNI

kube-ovn

### Operation-System/Kernel version

6.1.19-7.0.0.17.oe2303.aarch64

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
It is recommended that you refer to this ISSUE first：
https://github.com/deepflowio/deepflow/issues/5785

pass
```kubectl description pods -n deepflow deepflow-grafana-xxx | grep image:```
Filter out the currently used init container image and check whether the corresponding version is consistent with the chart package version currently used by deepflow. For example, if the current DeepFlow version is v6.4 and the init container image version used is latest, you need to replace latest with v6.4

**Comment by waterloo2018** [comment]
Thanks, the solution works well.
