### ISSUE TITLE
[FR] Upgrade glibc in the base compilation image for the agent

### ISSUE THREAD

**Issue by Damon07** [deepflowio/deepflow#6064]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我们希望搭建一个deepflow的开发环境，基于vscode dev container，目前deepflow提供的agent基础镜像的glibc的版本较低，无法运行rust-analyzer, 报错如下。 希望官方能够更新agent基础镜像，便于社区开发者构建deepflow的开发环境。
```shell
INFO [4/9/2024, 12:09:21 PM]: /root/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1916-linux-x64/server/rust-analyzer --version: {
  status: 1,
  signal: null,
  output: [
    null,
    '',
    "/root/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1916-linux-x64/server/rust-analyzer: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /root/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1916-linux-x64/server/rust-analyzer)\n" +
      "/root/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1916-linux-x64/server/rust-analyzer: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /root/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1916-linux-x64/server/rust-analyzer)\n" +
      "/root/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1916-linux-x64/server/rust-analyzer: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /root/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1916-linux-x64/server/rust-analyzer)\n" +
      "/root/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1916-linux-x64/server/rust-analyzer: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /root/.vscode-server/extensions/rust-lang.rust-analyzer-0.3.1916-linux-x64/server/rust-analyzer)\n"
  ],
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Nick-0314** [comment]
![image](https://github.com/deepflowio/deepflow/assets/50027289/bbb17d3e-48ee-4bef-8a3f-e23b965ce105)
计划升级 Glibc 到 Ubuntu GLIBC 2.35-0ubuntu3.1)2.35 版本

@Damon07

**Comment by Nick-0314** [comment]
https://github.com/deepflowio/deepflow/pull/6565
https://github.com/deepflowio/deepflow/pull/6566
