### ISSUE TITLE
QA: 关于 agent Dispacher 设计的问题

### ISSUE THREAD

**Issue by dzy176** [deepflowio/deepflow#6118]
在阅读源码过程中，遇到一些困惑，辛苦大佬解答一下我的几个疑问：
#### 1. 关于 Dispatch
```rust
enum DispatcherFlavor {
    Analyzer(AnalyzerModeDispatcher), // Enterprise Edition Feature: analyzer_mode
    Local(LocalModeDispatcher),
    LocalPlus(LocalPlusModeDispatcher),
    Mirror(MirrorModeDispatcher),
}
```

这里的几类 Dispatch 的含义以及使用场景分别是什么，有没有设计 or 说明文档？

#### 2. 关于包合并于解析
之前在一个 issue 中我看到 https://github.com/deepflowio/deepflow/issues/6074 回复：“社区版没有做多个 Packet 的重组，但我们会把「第一个请求包」与「第一个响应包」做配对，在 SessionAggregator 相关的代码中“，我这边有个疑问，因为 deepflow 支持识别 packet 协议后从 header 中提取 trace id 与上层的 apm 分布式链路打通，那么如果只匹配第一个 packet，那么是否会存在有些 header 很长，trace id 被拆分到**第二个 packet**，导致这类情况无法和 apm 分布式链路打通了？或者咱们这类情况有什么特殊处理来解决这个问题吗

**Comment by sharang** [comment]
1. 参考配置和文档：
- https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L142
- https://deepflow.io/docs/zh/best-practice/special-environment-deployment/#macvlan

Analyzer 仅在企业版中支持。LocalPlus 是 Local 模式的增强，支持 dispatcher 使用队列做缓冲：
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L674

2. 是的，会有这种情况。目前社区版的解决方法是增大 agent 配置中的 l7_log_packet_size，在没有做 TCP 分段的情况下尽量多解析  https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L291

企业版我们支持 eBPF 数据的重组，将相邻的包拼接以后做解析。

但是一般 8192 也够用了，一般 eBPF 数据的 Header 部分如果不是超长不会分拆到两次 syscall 中。
