### ISSUE TITLE
能否支持自定义 k8s api server url

### ISSUE THREAD

**Issue by Tian90coder** [deepflowio/deepflow#6119]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

没有找到 k8s api server url 的配置入口，目前看起来是 agent 启动时自动获取的。
![image](https://github.com/deepflowio/deepflow/assets/56345542/69a5a970-1417-490c-a111-acdf377e271c)

但在我们的网络架构中，pod 无法直接访问 https://10.96.0.1 这个 api server 地址
![企业微信截图_1682bf7a-c333-4beb-bbea-02aa3fa5c5e3](https://github.com/deepflowio/deepflow/assets/56345542/3b926cb5-0b46-4e16-88c6-3642cfa887b2)

希望能够提供 api server 的配置入口

### DeepFlow version

v6.5.4

### DeepFlow agent list

暂未注册

### Kubernetes CNI

calico

### Operation-System/Kernel version

Operating System: Ubuntu 22.04.2 LTS
Kernel: Linux 5.15.0-60-generic

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
可以改一下采集器的环境变量:
KUBERNETES_SERVICE_HOST
KUBERNETES_SERVICE_PORT
不过需要注意的是，HOST 不能通过 ip, ip, ip 的形式填写，只能写一个，例如：
KUBERNETES_SERVICE_HOST=10.96.0.1

**Comment by Tian90coder** [comment]
> 可以改一下采集器的环境变量: KUBERNETES_SERVICE_HOST KUBERNETES_SERVICE_PORT 不过需要注意的是，HOST 不能通过 ip, ip, ip 的形式填写，只能写一个，例如： KUBERNETES_SERVICE_HOST=10.96.0.1

请问能否配置协议头为 http，这个是固定的 https 么？

**Comment by Tian90coder** [comment]
> 可以改一下采集器的环境变量: KUBERNETES_SERVICE_HOST KUBERNETES_SERVICE_PORT 不过需要注意的是，HOST 不能通过 ip, ip, ip 的形式填写，只能写一个，例如： KUBERNETES_SERVICE_HOST=10.96.0.1

目前没有找到配置环境变量的入口，我提交了一个 pr 能够支持这个功能。https://github.com/deepflowio/deepflow-charts/pull/31

**Comment by Tian90coder** [comment]
> > 可以改一下采集器的环境变量: KUBERNETES_SERVICE_HOST KUBERNETES_SERVICE_PORT 不过需要注意的是，HOST 不能通过 ip, ip, ip 的形式填写，只能写一个，例如： KUBERNETES_SERVICE_HOST=10.96.0.1
> 
> 目前没有找到配置环境变量的入口，我提交了一个 pr 能够支持这个功能。[deepflowio/deepflow-charts#31](https://github.com/deepflowio/deepflow-charts/pull/31)

发现通过 KUBE_RS_DEBUG_OVERRIDE_URL 环境变量可以修改整个 url：

https://github.com/deepflowio/kube/blob/7320a9e0821ae70c0433dbb9d5b01f323f1e3373/kube-client/src/config/mod.rs#L357
