### ISSUE TITLE
[MySQL Privilege]What should I do if my managed database only has CRUD permissions and cannot CREATE or DROP?

### ISSUE THREAD

**Issue by zcl1115** [deepflowio/deepflow#6123]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

如题描述，我们托管的数据库是由dba维护的，角色权限只能是普通的crud，这样还能对接到deepflow-server吗？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by zcl1115** [comment]
> deepflow-server 启动时需要初始化，在 mysql 中创建一些库表，如果没有对应权限，则无法完成初始化

如果我事先按照init.sql中要求的初始化完成呢，这样是否还可以正常启动

**Comment by 1473371932** [comment]
> > deepflow-server 启动时需要初始化，在 mysql 中创建一些库表，如果没有对应权限，则无法完成初始化
> 
> @1473371932 如果我事先按照init.sql中要求的将表创建完成呢，这样是否还可以正常启动

除了事先初始化，后续 deepflow 仍要向 数据库 写入数据，对库中写入数据的权限也得有
