### ISSUE TITLE
[BUG] tcp连接断开，agent重新连接发送log数据

### ISSUE THREAD

**Issue by callmediaomao** [deepflowio/deepflow#6154]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

agent发送log数据的时候出现问题
![image](https://github.com/deepflowio/deepflow/assets/63587783/341011ef-3206-4cec-beac-3adf16beb03b)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
目前 agent 恢复了么？出现这个日志时候，可以进 agent pod，telnet 对应 server ip + port 看看连接情况

**Comment by callmediaomao** [comment]
> > @1473371932 telnet是可以通的，猜测网络丢包的特殊情况导致该情况发生。一般出现这个，agent下一条日志就会显示连接成功，但是我看代码发现是不是会抛弃掉连接失败的那批buffer数据，不会进行重发。
> 
> 一般来说，非网络断联造成的丢包都是可以通过 agent_group_config 配置来优化的，如果是由于网络断联导致的丢包，确实无法重发，因为 agent 本身并不存储数据

@1473371932 目前只是猜测是网络丢包的问题，想问下哪些配置可以优化该问题，我尝试下能不能解决

**Comment by 1473371932** [comment]
> > > @1473371932 telnet是可以通的，猜测网络丢包的特殊情况导致该情况发生。一般出现这个，agent下一条日志就会显示连接成功，但是我看代码发现是不是会抛弃掉连接失败的那批buffer数据，不会进行重发。
> > 
> > 
> > 一般来说，非网络断联造成的丢包都是可以通过 agent_group_config 配置来优化的，如果是由于网络断联导致的丢包，确实无法重发，因为 agent 本身并不存储数据
> 
> @1473371932 目前只是猜测是网络丢包的问题，想问下哪些配置可以优化该问题，我尝试下能不能解决

丢包问题，可以通过这个 Dashboard：
https://github.com/deepflowio/deepflow-dashboards/blob/main/dashboards/DeepFlow-System/DeepFlow-Alert-Analysis.json
看到具体丢包位置，把时间周期拉长，例如看最近 24 小时，如果面板中有数据，就说明有丢包，把有数据的面板贴一下看看
