### ISSUE TITLE
[FR] Docke Compose部署的deepflow-server疑问

### ISSUE THREAD

**Issue by zcl1115** [deepflowio/deepflow#6156]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

1. 如果我们使用Docke Compose模式部署deepflow-server，我看限制是不允许水平扩展，那就是Docke Compose模式下只能是一个单点的deepflow-server部署吗？
2. 我们是否能够通过一些代码开发去实现Docke Compose模式部署的deepflow-server的水平扩展，想要知道这方面的难点是什么，看看能不能我们自己去实现？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
server 是可以水平扩展的呀，你是在官网哪里看到的对应描述呀？

**Comment by zcl1115** [comment]
@1473371932 https://deepflow.io/docs/zh/ce-install/all-in-one/#%E9%99%90%E5%88%B6  这里的描述，而且我看docker-compose文件里面也有环境变量DEEPFLOW_SERVER_RUNNING_MODE: STANDALONE

**Comment by 1473371932** [comment]
> @1473371932 https://deepflow.io/docs/zh/ce-install/all-in-one/#%E9%99%90%E5%88%B6 这里的描述，而且我看docker-compose文件里面也有环境变量DEEPFLOW_SERVER_RUNNING_MODE: STANDALONE

抱歉，此处是我混淆了：
1、确实不能水平扩容，但一般来说，我们更推荐 deepflow-server 部署到 k8s 中，agent 单独部署在你们的业务环境，然后与 server 对接
2、非常欢迎来我们社区提供代码，对于代码相关的问题，还得需要我们负责 server 的研发同学来解释一下

**Comment by zcl1115** [comment]
@1473371932 嗯嗯，我们主要是想要脱离我们内部的k8s来实现，我这边看看怎么改写一下剔除k8s的LeaderElector的依赖。
然后还想问个问题，对于flow_metrics库里面的application的表，里面有role的字段用于标识客户端还是服务端，那对于application_map这张表呢，是否有个字段用于标识客户端还是服务端呢

**Comment by zcl1115** [comment]
我看有个字段signal_source，这个是用于标识请求发起方的吗，因为我看捕获的数据中，server_port跟signal_source对应的数据一致

**Comment by sharang** [comment]
> @1473371932 嗯嗯，我们主要是想要脱离我们内部的k8s来实现，我这边看看怎么改写一下剔除k8s的LeaderElector的依赖。 然后还想问个问题，对于flow_metrics库里面的application的表，里面有role的字段用于标识客户端还是服务端，那对于application_map这张表呢，是否有个字段用于标识客户端还是服务端呢

application_map 里面的 xx_0 是客户端、xx_1 是服务端

**Comment by zcl1115** [comment]
> > @1473371932 嗯嗯，我们主要是想要脱离我们内部的k8s来实现，我这边看看怎么改写一下剔除k8s的LeaderElector的依赖。 然后还想问个问题，对于flow_metrics库里面的application的表，里面有role的字段用于标识客户端还是服务端，那对于application_map这张表呢，是否有个字段用于标识客户端还是服务端呢
> 
> application_map 里面的 xx_0 是客户端、xx_1 是服务端

嗯嗯，好的呢，多谢
