### ISSUE TITLE
Merge AgentGroupConfig{} and AgentGroupConfigResponse{}

### ISSUE THREAD

**Issue by sharang** [deepflowio/deepflow#6159]
AgentGroupConfig 与 AgentGroupConfigResponse 非常相似

_Originally posted by @sharang in https://github.com/deepflowio/deepflow/pull/6155#discussion_r1570326582_

**Comment by SongZhen0704** [comment]
AgentGroupConfig 与 AgentGroupConfigResponse 的支持的功能不同，不太方便做合并
