### ISSUE TITLE
关于暂存数据上报的问题

### ISSUE THREAD

**Issue by guolifu** [deepflowio/deepflow#6180]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

暂存数据上报，使用sys_enter_getppid来触发，是出于什么考虑的呢？如果其他进程频繁的调用了getppid，那么数据推送也会频繁的触发，是否影响了设计的初衷呢？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
@guolifu 你的理解是正确的，我们需要找一个系统调用（或者其他方式）把驻留在内核的EBPF数据（这些数据没有达到批量传输数量要求而残留在内核中）踢出来，我们发现sys_enter_getppid()这个系统调用，被进程频繁的调用的情况比较少见，所以采用它（这是我们最初的设计考虑），如果您有更好的想法或者遇到了sys_enter_getppid()频繁调用场景可以告知我们。

**Comment by guolifu** [comment]
很高兴得到你的回复！我的设想是，如果在sys_enter_getppid触发时，仅当tgid为deepflow时，才使后续逻辑生效，切实保障程序行为不受到外界过分干扰的情况

**Comment by guolifu** [comment]
> @guolifu 你的理解是正确的，我们需要找一个系统调用（或者其他方式）把驻留在内核的EBPF数据（这些数据没有达到批量传输数量要求而残留在内核中）踢出来，我们发现sys_enter_getppid()这个系统调用，被进程频繁的调用的情况比较少见，所以采用它（这是我们最初的设计考虑）。
> 
> 另外一方面即使遇到频繁触发的情况，对我们程序也不会影响只会把数据更能及时的push给上层，我们也需要这样做，但是如果是太过于频繁可能会会让syscall getppid()占用CPU资源偏高（比如1秒钟几十万的调用）。
> 
> 如果您有更好的想法或者遇到了sys_enter_getppid()频繁调用场景可以告知我们。


很高兴得到你的回复！我的设想是，如果在sys_enter_getppid触发时，仅当tgid为deepflow时，才使后续逻辑生效，切实保障程序行为不受到外界过分干扰的情况

**Comment by yinjiping** [comment]
> > @guolifu 你的理解是正确的，我们需要找一个系统调用（或者其他方式）把驻留在内核的EBPF数据（这些数据没有达到批量传输数量要求而残留在内核中）踢出来，我们发现sys_enter_getppid()这个系统调用，被进程频繁的调用的情况比较少见，所以采用它（这是我们最初的设计考虑）。
> > 另外一方面即使遇到频繁触发的情况，对我们程序也不会影响只会把数据更能及时的push给上层，我们也需要这样做，但是如果是太过于频繁可能会会让syscall getppid()占用CPU资源偏高（比如1秒钟几十万的调用）。
> > 如果您有更好的想法或者遇到了sys_enter_getppid()频繁调用场景可以告知我们。
> 
> 很高兴得到你的回复！我的设想是，如果在sys_enter_getppid触发时，仅当tgid为deepflow时，才使后续逻辑生效，切实保障程序行为不受到外界过分干扰的情况

@guolifu 感谢你提出的建议，你的建议是正确的，我们也有类同的想法，我们会修改这个问题，致谢。
