### ISSUE TITLE
[BUG]  panic when parse redis

### ISSUE THREAD

**Issue by JiezengDev** [deepflowio/deepflow#6211]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

正常解析redis协议

### DeepFlow version

Name: deepflow-agent community edition
Branch: v6.4
CommitId: b3f2758a3ad8a8b06ff221251a3ef1c80abbc6ff
RevCount: 9760
Compiler: rustc 1.75.0 (82e1608df 2023-12-21)
CompileTime: 2024-03-28 03:09:51

Name: deepflow-server community edition
Branch: v6.4
CommitID: 2f352404119929699874cc3fce8d4b180222db09
RevCount: 9755
Compiler: go version go1.20.14 linux/amd64
CompileTime: 2024-03-27 07:31:49

### DeepFlow agent list

ID       NAME              TYPE       CTRL_IP            CTRL_MAC           STATE    GROUP   EXCEPTIONS
1        10.222.67.13-V137 K8S_VM     10.222.67.13       fa:16:3e:72:d7:a1  NORMAL   default

### Operation-System/Kernel version

Huawei Cloud EulerOS 2.0 (x86_64)   
5.10.0-60.18.0.50.r1002_48.hce2.x86_64

### Anything else

<img width="1483" alt="image" src="https://github.com/deepflowio/deepflow/assets/42398428/f125a037-e9a3-4b08-8e3f-c72c354d68bb">

agent-group-config 如下

```yaml
l7_log_packet_size: 4000
l4_log_collect_nps_threshold: 50000
l7_log_collect_nps_threshold: 50000
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
https://github.com/deepflowio/deepflow/actions/runs/8796600045

这个 CI 跑完之后，重新拉一下 v6.4 的镜像就好了
