### ISSUE TITLE
k8s pod 数据大量缺失

### ISSUE THREAD

**Issue by Tian90coder** [deepflowio/deepflow#6216]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

我采用的部署方式为：[监控多个 K8s 集群](https://deepflow.io/docs/zh/ce-install/multi-k8s/#%E7%AE%80%E4%BB%8B)
deepflow-server 部署在一个单独的集群 k8s-d-8rjLErclHW，业务集群为：vdian_k8s_daily
![截屏2024-04-23 17 05 01](https://github.com/deepflowio/deepflow/assets/56345542/1d5c1969-d71d-49fc-8bda-c80651232446)

目前在两个 node 上面安装了 deepflow-agent，但是缺失了大量的业务应用 pod：
两个 node 上面 default namespace 下面 共有 71 个 pod
![截屏2024-04-23 17 01 30](https://github.com/deepflowio/deepflow/assets/56345542/c20f6c80-8816-48c0-ad8b-4aacd9454141)

业务集群 vdian_k8s_daily 的 default namespace 的 id 为 14：
![image](https://github.com/deepflowio/deepflow/assets/56345542/b8676fe8-1cbb-4158-afb7-c06ae6aab69c)

但是 pod 数据大量缺失，db 中仅有 5 条数据：
![image](https://github.com/deepflowio/deepflow/assets/56345542/1ea8f6c3-b2e3-4e07-aa67-5ef3f976a7e3)

![image](https://github.com/deepflowio/deepflow/assets/56345542/86356f46-4118-4aff-b57a-b50693566649)

![image](https://github.com/deepflowio/deepflow/assets/56345542/6610553b-f36a-4a86-b9b6-95dfb202f438)

另外 L7 Flow log 等数据均正常，仅涉及 k8s pod 的看板展示缺少 namespace 和 pod，这导致我无法关联应用和 ip 数据。

agent-group-conifg：
~~~yaml
vtap_group_id: g-U8T0fwnc3A
tap_interface_regex: bond0
tap_mode: 1
~~~

node ifconfig：
~~~shell
@$ifconfig
bond0: flags=5187<UP,BROADCAST,RUNNING,MASTER,MULTICAST>  mtu 1500
        ether 3e:19:f5:71:3d:47  txqueuelen 1000  (Ethernet)
        RX packets 148949153332  bytes 32740799483455 (32.7 TB)
        RX errors 0  dropped 72071  overruns 0  frame 0
        TX packets 145347686484  bytes 123958595746638 (123.9 TB)
        TX errors 0  dropped 2 overruns 0  carrier 0  collisions 0

docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:17:c4:ed:18  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        ether 3e:19:f5:71:3d:47  txqueuelen 1000  (Ethernet)
        RX packets 74397403565  bytes 16367871953347 (16.3 TB)
        RX errors 0  dropped 38980  overruns 0  frame 0
        TX packets 74209120137  bytes 62465884112281 (62.4 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 16

eth1: flags=6211<UP,BROADCAST,RUNNING,SLAVE,MULTICAST>  mtu 1500
        ether 3e:19:f5:71:3d:47  txqueuelen 1000  (Ethernet)
        RX packets 74551749767  bytes 16372927530108 (16.3 TB)
        RX errors 0  dropped 33087  overruns 0  frame 0
        TX packets 71138566347  bytes 61492711634357 (61.4 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 17

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 25425905161  bytes 5707634321044 (5.7 TB)
        RX errors 0  dropped 9  overruns 0  frame 0
        TX packets 25425905161  bytes 5707634321044 (5.7 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

mac0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.xx.xx.xxx  netmask 255.255.240.0  broadcast 0.0.0.0
        ether 4a:46:cd:a3:74:36  txqueuelen 1000  (Ethernet)
        RX packets 119635588924  bytes 19328161987382 (19.3 TB)
        RX errors 6605  dropped 13210  overruns 0  frame 0
        TX packets 83455362326  bytes 114666266670628 (114.6 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
~~~

其余的相关监控看板：
![image](https://github.com/deepflowio/deepflow/assets/56345542/1aa93eee-a95b-4ce1-99b2-4b88b9f124b7)
![image](https://github.com/deepflowio/deepflow/assets/56345542/7998b8f7-b548-4e36-8156-c201d4afcfbb)

### DeepFlow version

v6.5.4

### DeepFlow agent list

![截屏2024-04-23 16 53 53](https://github.com/deepflowio/deepflow/assets/56345542/d87767c6-1d5b-4c3a-a963-9d93b9d21c84)

### Kubernetes CNI

macvlan

### Operation-System/Kernel version

Operating System: Ubuntu 22.04.2 LTS
Kernel: Linux 5.15.0-60-generic

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
可以先把丢包问题解决后，再次查看其他面板：

1. ```Ingester Recviver Invalid```：server 收到 agent 上报的无效数据，过滤 server 日志，查找关键字```TCP client```可以获取无效数据发送者的 IP 地址，若是 agent 发送，则确认 agent 和 server 版本是否一致，若非 agent 发送，则需禁止该 IP 地址发送数据到数据节点的监听端口（默认：30033）
2. ```Clickhouse Write Failed```：数据写入丢包，查看 server 写入的 clickhouse 运行状态是否正常，检查是否还有足够的磁盘空间，若都无问题，server 日志中过滤```write block failed```查看具体写入失败原因
3. ```Ingester Queue Overwritten```：队列丢包，去```DeepFlow System/DeepFlow Server - Ingester```这个 Dashboard 的```Queue(+pending/-drop)```这个面板，查看具体 -drop 的队列再做判断
4. ```Dispatcher Kernel-Drops```：采集流量突发或处理性能不足导致 agent 丢包，可通过打开[bpf缓冲块](https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L593)并调整[缓冲块大小](https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L600)解决此问题

**Comment by Tian90coder** [comment]
1. `Ingester Recviver Invalid`：已确认所有 ip 均为 deepflow-server 自身，且无`30033`端口对应日志，应该和 agent 无关，目前`deepflow-ctl agent list `获取到的 agent 版本均无问题。
2. `Clickhouse Write Failed`：已确认当时的时间点，ck 集群有重启操作，重启后不再报错。
3. `Ingester Queue Overwritten`：
![image](https://github.com/deepflowio/deepflow/assets/56345542/f7001aa0-1772-47ed-a483-2146953d6722)
4. `Dispatcher Kernel-Drops`：已通过 `values.yaml` 修改
~~~yaml
deepflowAgentConfig:
  deepflow-agent.yaml:
    afpacket-blocks-enabled: true
    afpacket-blocks: 1024
~~~
 
@1473371932

**Comment by 1473371932** [comment]
> 1. `Ingester Recviver Invalid`：已确认所有 ip 均为 deepflow-server 自身，且无`30033`端口对应日志，应该和 agent 无关，目前`deepflow-ctl agent list `获取到的 agent 版本均无问题。
> 2. `Clickhouse Write Failed`：已确认当时的时间点，ck 集群有重启操作，重启后不再报错。
> 3. `Ingester Queue Overwritten`：
>    ![image](https://private-user-images.githubusercontent.com/56345542/324813081-f7001aa0-1772-47ed-a483-2146953d6722.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzMxNTMsIm5iZiI6MTcxMzg3Mjg1MywicGF0aCI6Ii81NjM0NTU0Mi8zMjQ4MTMwODEtZjcwMDFhYTAtMTc3Mi00N2VkLWE0ODMtMjE0Njk1M2Q2NzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExNDczM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODlkNzUyOTE2MTY2MmFmMzZiMzEwMWQ2MTNmNmU4NzY5ZWExYjkwMzU4MGQ4Y2RlMjZhOWQyZjk0NWY1YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uIZPgrH97RDj7HRdSaW_GJZFO8LUXtq2LtZY7TJXCy8)
> 4. `Dispatcher Kernel-Drops`：已通过 `values.yaml` 修改
> 
> ```yaml
> deepflowAgentConfig:
>   deepflow-agent.yaml: |
>     controller-ips:
>       - 10.xx.xx.1
>       - 10.xx.xx.2
>     vtap-group-id-request: g-U8T0fwnc3A
>     kubernetes-cluster-id: d-TrVaOj1qNP
>     kubernetes-cluster-name: vdian_k8s_daily
>     afpacket-blocks-enabled: true
>     afpacket-blocks: 1024
> ```
> 
> @1473371932

不对，是通过 deepflow-ctl 改 agent-group-config 配置，具体参考下面两个链接，注意格式：
https://deepflow.io/docs/zh/best-practice/agent-advanced-config/
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml

**Comment by Tian90coder** [comment]
@1473371932  已修改 agent group config：
![image](https://github.com/deepflowio/deepflow/assets/56345542/03a54c56-2b4f-4d24-a6bd-fc340da9d77c)

**Comment by 1473371932** [comment]
> @1473371932 已修改 agent group config： ![image](https://private-user-images.githubusercontent.com/56345542/325051288-03a54c56-2b4f-4d24-a6bd-fc340da9d77c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzgwMzksIm5iZiI6MTcxMzkzNzczOSwicGF0aCI6Ii81NjM0NTU0Mi8zMjUwNTEyODgtMDNhNTRjNTYtMmI0Zi00ZDI0LWE2YmQtZmMzNDBkYTlkNzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA1NDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZTZkZjEzOGU2YmQ0ZTg3MjM5Y2JiNzUxNjQzZmIyOWRlYjU0NTc1YmY1YzM3YTg4YWM0YTJlZjE3MTk5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ci0Ay0uPgbvCu6xfYCpaG2b3alfF48embdDs-SiTqLk)

目前在看 alert Dashboard，看看还有没有丢包

**Comment by Tian90coder** [comment]
> > @1473371932 已修改 agent group config： ![image](https://private-user-images.githubusercontent.com/56345542/325051288-03a54c56-2b4f-4d24-a6bd-fc340da9d77c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzgwMzksIm5iZiI6MTcxMzkzNzczOSwicGF0aCI6Ii81NjM0NTU0Mi8zMjUwNTEyODgtMDNhNTRjNTYtMmI0Zi00ZDI0LWE2YmQtZmMzNDBkYTlkNzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA1NDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhZTZkZjEzOGU2YmQ0ZTg3MjM5Y2JiNzUxNjQzZmIyOWRlYjU0NTc1YmY1YzM3YTg4YWM0YTJlZjE3MTk5OWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ci0Ay0uPgbvCu6xfYCpaG2b3alfF48embdDs-SiTqLk)
> 
> 目前在看 alert Dashboard，看看还有没有丢包

在配置完成后 drop 降低了很多，还在持续观察，但是感觉应该和这个丢包没很大关系，以为只是偶尔某分钟有丢包。其他时间应该都是正常的。

![image](https://github.com/deepflowio/deepflow/assets/56345542/581829a2-3634-4f13-8184-ad364bfc12ba)

**Comment by Tian90coder** [comment]
能否通过某种方式 debug，能看到 agent 上报的 pod 数据么？

**Comment by Tian90coder** [comment]
我们业务应用 pod 用的 openkruise 框架提供的 statefulset 部署的，在 server 端，debug 日志中看到大量如下日志：
![image](https://github.com/deepflowio/deepflow/assets/56345542/5bc133c1-00dc-4150-a558-38ceea1f2a9b)

https://github.com/deepflowio/deepflow/blob/v6.5.4/server/controller/cloud/kubernetes_gather/pod_group.go#L107

感觉[这里](https://github.com/deepflowio/deepflow/blob/v6.5.4/server/controller/cloud/kubernetes_gather/pod_group.go#L95)的限制（InPlaceSet）不是太死了，我们业务应用 pod 的 kind 都是：`StatefulSet`
<img width="762" alt="截屏2024-04-24 16 49 53" src="https://github.com/deepflowio/deepflow/assets/56345542/b83bc4ca-7c3d-411d-99ac-d0327bf40ced">

并且 label 里没有：`virtual-kubelet.io/provider-cluster-type` 和 `virtual-kubelet.io/provider-resource-name` 
@1473371932

**Comment by 1473371932** [comment]
> 我们业务应用 pod 用的 openkruise 框架提供的 statefulset 部署的，在 server 端，debug 日志中看到大量如下日志： ![image](https://private-user-images.githubusercontent.com/56345542/325134807-5bc133c1-00dc-4150-a558-38ceea1f2a9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjI2MzQsIm5iZiI6MTcxMzk2MjMzNCwicGF0aCI6Ii81NjM0NTU0Mi8zMjUxMzQ4MDctNWJjMTMzYzEtMDBkYy00MTUwLWE1NTgtMzhjZWVhMWYyYTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEyMzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTU4OTNiMGM2ZThiY2Y4MjgyYWQ2Zjk4NGM2YTQzMmE0YmRjNTgwYTMxZTJhNGU0NTRmMjI4NmIyZGYzYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W1ABxSeGLW9kFduWWlnCuPYv49z-8A_mF9aQz26zSUM)
> 
> https://github.com/deepflowio/deepflow/blob/v6.5.4/server/controller/cloud/kubernetes_gather/pod_group.go#L107
> 
> 感觉[这里](https://github.com/deepflowio/deepflow/blob/v6.5.4/server/controller/cloud/kubernetes_gather/pod_group.go#L95)的限制（InPlaceSet）不是太死了，我们业务应用 pod 的 kind 都是：`StatefulSet` <img alt="截屏2024-04-24 16 49 53" width="762" src="https://private-user-images.githubusercontent.com/56345542/325150328-b83bc4ca-7c3d-411d-99ac-d0327bf40ced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjI2MzQsIm5iZiI6MTcxMzk2MjMzNCwicGF0aCI6Ii81NjM0NTU0Mi8zMjUxNTAzMjgtYjgzYmM0Y2EtN2MzZC00MTFkLTk5YWMtZDAzMjdiZjQwY2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEyMzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MmMxZDZjYjAyN2EyYTNlNjRiMzBjN2JlMDU0MTE1YWMxNDQ2ZmI2OWEzZTNmNmY2ZDg0MjFjMTg4MWEzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hey0WAQUiCDOYIYbzAoHt6xh7dmL4R-ulWNnGFcofiQ">
> 
> 并且 label 里没有：`virtual-kubelet.io/provider-cluster-type` 和 `virtual-kubelet.io/provider-resource-name` @1473371932

使用 openkruise 还需要在部署 agent 时候做一下其他配置：
https://deepflow.io/docs/zh/best-practice/special-environment-deployment/#openkruise
你们有没有做这一步呀？

**Comment by Tian90coder** [comment]
> > 我们业务应用 pod 用的 openkruise 框架提供的 statefulset 部署的，在 server 端，debug 日志中看到大量如下日志： ![image](https://private-user-images.githubusercontent.com/56345542/325134807-5bc133c1-00dc-4150-a558-38ceea1f2a9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjI2MzQsIm5iZiI6MTcxMzk2MjMzNCwicGF0aCI6Ii81NjM0NTU0Mi8zMjUxMzQ4MDctNWJjMTMzYzEtMDBkYy00MTUwLWE1NTgtMzhjZWVhMWYyYTliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEyMzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3OTU4OTNiMGM2ZThiY2Y4MjgyYWQ2Zjk4NGM2YTQzMmE0YmRjNTgwYTMxZTJhNGU0NTRmMjI4NmIyZGYzYjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W1ABxSeGLW9kFduWWlnCuPYv49z-8A_mF9aQz26zSUM)
> > https://github.com/deepflowio/deepflow/blob/v6.5.4/server/controller/cloud/kubernetes_gather/pod_group.go#L107
> > 感觉[这里](https://github.com/deepflowio/deepflow/blob/v6.5.4/server/controller/cloud/kubernetes_gather/pod_group.go#L95)的限制（InPlaceSet）不是太死了，我们业务应用 pod 的 kind 都是：`StatefulSet` <img alt="截屏2024-04-24 16 49 53" width="762" src="https://private-user-images.githubusercontent.com/56345542/325150328-b83bc4ca-7c3d-411d-99ac-d0327bf40ced.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NjI2MzQsIm5iZiI6MTcxMzk2MjMzNCwicGF0aCI6Ii81NjM0NTU0Mi8zMjUxNTAzMjgtYjgzYmM0Y2EtN2MzZC00MTFkLTk5YWMtZDAzMjdiZjQwY2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDEyMzg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MmMxZDZjYjAyN2EyYTNlNjRiMzBjN2JlMDU0MTE1YWMxNDQ2ZmI2OWEzZTNmNmY2ZDg0MjFjMTg4MWEzOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hey0WAQUiCDOYIYbzAoHt6xh7dmL4R-ulWNnGFcofiQ">
> > 并且 label 里没有：`virtual-kubelet.io/provider-cluster-type` 和 `virtual-kubelet.io/provider-resource-name` @1473371932
> 
> 使用 openkruise 还需要在部署 agent 时候做一下其他配置： https://deepflow.io/docs/zh/best-practice/special-environment-deployment/#openkruise 你们有没有做这一步呀？

按照这个配置后，pod成功上报了！多谢，我遗漏了这个配置。
