### ISSUE TITLE
trace 看板展示异常

### ISSUE THREAD

**Issue by Tian90coder** [deepflowio/deepflow#6233]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

看这是解析 json 失败
![截屏2024-04-25 11 28 58](https://github.com/deepflowio/deepflow/assets/56345542/7166cbb3-ae44-4f6c-add9-752893feebca)

![image](https://github.com/deepflowio/deepflow/assets/56345542/2450a301-55cd-4741-aa9d-92332db3f44b)

这个 app: xxx 是我们的 pod 标签，用来标记应用名，但是根据 trace detail 数据来看，label是个字符串：
![image](https://github.com/deepflowio/deepflow/assets/56345542/e33d59b1-6d25-4528-a6a0-87bf6d99e2c8)

难道是将 string 当成 json 解析导致的问题么？grafana 也没有异常日志。。暂时没有排查思路

### DeepFlow version

`v6.5.4`

### Kubernetes CNI

macvlan

### Operation-System/Kernel version

Operating System: Ubuntu 22.04.2 LTS
Kernel: Linux 5.15.0-60-generic

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by twou12031** [comment]
正在尝试复现, 并尽快修复此问题.
We're working to reproduce the bug and fix it as quickly as possible.

**Comment by xiaochaoren1** [comment]
This is a bug that has been fixed in version v6.5.5
