### ISSUE TITLE
On the issue of insufficient stack space

### ISSUE THREAD

**Issue by guolifu** [deepflowio/deepflow#6246]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我在函数get_trace_key中增加了bpf_debug打印，
```
static __inline struct trace_key_t get_trace_key(__u64 timeout, bool is_socket_io)
{
	__u64 pid_tgid = bpf_get_current_pid_tgid();
	__u64 goid = 0;

	if (timeout){
		goid = get_rw_goid(timeout * NS_PER_SEC, is_socket_io);
	}
    bpf_debug("111");
```
当我基于镜像进行重新编译时，在编译到kernel时，编译器报错
```
/usr/bin/clang -I. -Ivmlinux -Iinclude -D__BPF_TRACING__ -D GROUP_LEADER_OFFSET_OVERRIDE=0 -DSTART_BOOTTIME_OFFSET_OVERRIDE=0 -DSTART_BOOTTIME_VARNAME=real_start_time  -std=gnu99 -Wimplicit-function-declaration \
	-ffreestanding -fno-builtin -Wall \
	-Wno-deprecated-declarations \
	-Wno-gnu-variable-sized-type-not-at-end \
	-Wno-pragma-once-outside-header \
	-Wno-address-of-packed-member \
	-Wno-unknown-warning-option \
	-fno-color-diagnostics \
	-fno-unwind-tables \
	-fno-stack-protector \
	-fno-asynchronous-unwind-tables -g -O2 -emit-llvm -D__TARGET_ARCH_x86 -o socket_trace.ll -c socket_trace.c && /usr/bin/llc -march=bpf -filetype=obj -mcpu=v2 -o socket_trace.elf socket_trace.ll
error: ./uprobe_base_bpf.c:255:23: in function bpf_prog_tp__data_submit i32 (i8*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.


error: ./uprobe_base_bpf.c:268:22: in function bpf_prog_tp__data_submit i32 (i8*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.


error: ./uprobe_base_bpf.c:255:23: in function bpf_prog_kp__data_submit i32 (i8*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.


error: ./uprobe_base_bpf.c:268:22: in function bpf_prog_kp__data_submit i32 (i8*): Looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map.

make: *** [socket_trace.elf] Error 1
```
删除这段打印则恢复正常

### Use case

从现象上看，新增的打印貌似触发了bpf的栈空间限制，是否是我们栈设计上导致的这个问题？如何避免它，并且可以正常打印一些日志

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
@guolifu 感谢您的问题反馈，我看您的调试位置说明在data_submit这eBPF prog支线上栈空间快饱和了，在调试的情况下试试下面来解决一下：
- 调整一下bpf_debug（）位置：
```c
static __inline struct trace_key_t get_trace_key(__u64 timeout,
                                                 bool is_socket_io)
{
        __u64 pid_tgid = bpf_get_current_pid_tgid();
        __u64 goid = 0;

        if (timeout) {
                goid = get_rw_goid(timeout * NS_PER_SEC, is_socket_io);
        }

        struct trace_key_t key = {};

        key.tgid = (__u32) (pid_tgid >> 32);

        if (goid) {
                key.goid = goid;
        } else {
                key.pid = (__u32) pid_tgid;
        }

        bpf_debug("111");
        return key;
}
```
- 去掉一些`__data_submit（）`中一些用不到的栈的占用(例如：)：
```
        if ((extra->source == DATA_SOURCE_GO_TLS_UPROBE ||
             extra->source == DATA_SOURCE_OPENSSL_UPROBE) ||
            (conn_info->tuple.l4_protocol == IPPROTO_TCP)) {
                /*
                 * If the current state is TCPF_CLOSE_WAIT, the FIN frame already has been received.
                 * However, it cannot be confirmed that it has been processed by the syscall,
                 * so use the tcp_seq value that entering the syscalls.
                 *
                 * Why not use "v->tcp_seq = args->tcp_seq;" ?
                 * This is because kernel 4.14 verify reports errors("R0 invalid mem access 'inv'").
                 */
                v->tcp_seq = tcp_seq;
#if 0
                // 这一部分几乎不大碰到，测试的时候可以忽略掉
                if (tcp_seq == 0 && conn_info->fd > 0) {
                        if (conn_info->direction == T_INGRESS) {
                                tcp_seq =
                                    get_tcp_read_seq_from_fd(conn_info->fd);
                                /*
                                 * If the current state is TCPF_CLOSE_WAIT, the FIN
                                 * frame already has been received.
                                 * Since tcp_sock->copied_seq has done such an operation +1,
                                 * need to fix the value of tcp_seq.
                                 */
                                if ((1 << conn_info->skc_state) &
                                    TCPF_CLOSE_WAIT) {
                                        tcp_seq--;
                                }
                        } else {
                                tcp_seq =
                                    get_tcp_write_seq_from_fd(conn_info->fd);
                        }

                        v->tcp_seq = tcp_seq - syscall_len;
                }
#endif
        }
```
如果不做追踪调试也可以屏蔽掉`trace_process()`的调用。

**Comment by guolifu** [comment]
感谢您的回复！
我按照你的提供的经验调试一下👍🏻

> @guolifu 感谢您的问题反馈，我看您的调试位置说明在data_submit这eBPF prog支线上栈空间快饱和了，在调试的情况下试试下面来解决一下：
> 
> * 调整一下bpf_debug（）位置：
> 
> ```c
> static __inline struct trace_key_t get_trace_key(__u64 timeout,
>                                                  bool is_socket_io)
> {
>         __u64 pid_tgid = bpf_get_current_pid_tgid();
>         __u64 goid = 0;
> 
>         if (timeout) {
>                 goid = get_rw_goid(timeout * NS_PER_SEC, is_socket_io);
>         }
> 
>         struct trace_key_t key = {};
> 
>         key.tgid = (__u32) (pid_tgid >> 32);
> 
>         if (goid) {
>                 key.goid = goid;
>         } else {
>                 key.pid = (__u32) pid_tgid;
>         }
> 
>         bpf_debug("111");
>         return key;
> }
> ```
> 
> * 去掉一些`__data_submit（）`中一些用不到的栈的占用(例如：)：
> 
> ```
>         if ((extra->source == DATA_SOURCE_GO_TLS_UPROBE ||
>              extra->source == DATA_SOURCE_OPENSSL_UPROBE) ||
>             (conn_info->tuple.l4_protocol == IPPROTO_TCP)) {
>                 /*
>                  * If the current state is TCPF_CLOSE_WAIT, the FIN frame already has been received.
>                  * However, it cannot be confirmed that it has been processed by the syscall,
>                  * so use the tcp_seq value that entering the syscalls.
>                  *
>                  * Why not use "v->tcp_seq = args->tcp_seq;" ?
>                  * This is because kernel 4.14 verify reports errors("R0 invalid mem access 'inv'").
>                  */
>                 v->tcp_seq = tcp_seq;
> #if 0
>                 // 这一部分几乎不大碰到，测试的时候可以忽略掉
>                 if (tcp_seq == 0 && conn_info->fd > 0) {
>                         if (conn_info->direction == T_INGRESS) {
>                                 tcp_seq =
>                                     get_tcp_read_seq_from_fd(conn_info->fd);
>                                 /*
>                                  * If the current state is TCPF_CLOSE_WAIT, the FIN
>                                  * frame already has been received.
>                                  * Since tcp_sock->copied_seq has done such an operation +1,
>                                  * need to fix the value of tcp_seq.
>                                  */
>                                 if ((1 << conn_info->skc_state) &
>                                     TCPF_CLOSE_WAIT) {
>                                         tcp_seq--;
>                                 }
>                         } else {
>                                 tcp_seq =
>                                     get_tcp_write_seq_from_fd(conn_info->fd);
>                         }
> 
>                         v->tcp_seq = tcp_seq - syscall_len;
>                 }
> #endif
>         }
> ```
> 
> 如果不做追踪调试也可以屏蔽掉`trace_process()`的调用。
