### ISSUE TITLE
[BUG] v6.4 Trace Completion API 调用返回500 

### ISSUE THREAD

**Issue by YuanChuan11** [deepflowio/deepflow#6276]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

根据官网文档调用Trace Completion API（ https://deepflow.io/docs/zh/integration/output/query/trace-completion/）时报错 
调用接口：http://${deepflow_server_node_ip}:${port}/v1/stats/querier/tracing-completion-by-external-app-spans。
返回500错误码和如下报错信息。
{
    "OPT_STATUS": "INTERNAL_SERVER_ERROR",
    "DESCRIPTION": "'str' object has no attribute 'signal_source'"
}

deepflow-app打印的错误日志如下：
'str' object has no attribute 'signal_source'Traceback (most recent call last):  File "/root/app/common/utils.py", line 105, in wrapper    response = await function(*args, **kwargs)  File "/root/app/application/application.py", line 41, in l7_flow_app_tracing    status, response, failed_regions = await TracingCompletion(  File "/root/app/application/tracing_completion.py", line 38, in query    rst = await self.trace_l7_flow(time_filter=time_filter,  File "/root/app/application/tracing_completion.py", line 416, in trace_l7_flow    set_all_relate(dataframe_flowmetas, related_map, network_delay_us)  File "/root/app/application/l7_flow_tracing.py", line 631, in set_all_relate    if ti.signal_source != L7_FLOW_SIGNAL_SOURCE_OTEL:AttributeError: 'str' object has no attribute 'signal_source'

### DeepFlow version

deepflow-server v6.4 
deepflow-agent v6.4
deepflow-app v6.4

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by taloric** [comment]
@YuanChuan11 plz try the latest version

**Comment by lpq131004** [comment]
@YuanChuan11 请问通过调用trace completion api补充spans需要在服务请求header加上traceid或者requestid嘛
