### ISSUE TITLE
[FR] Agent对Traefik性能影响基准测试

### ISSUE THREAD

**Issue by chrisdamon** [deepflowio/deepflow#6277]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

deepflow-agent是否覆盖对traefik网关应用测试，若有，影响程度如何？
若无，是否可以交流下测试工具或测试方法？

deepflow-agent: v6.4
deepflow-server: v6.4
deepflow-app: v6.4

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by LYootsz** [comment]
目前还没有针对traefik网关的应用测试。
测试方法主要是通过wrk2或者我们自己写的打流工具，分别测试目标应用在有无agent情况下的rps极限以及指定rps下的应用资源占用等指标。
如果需要这方面的测试报告，后续我们会考虑进行针对traefik的测试。

**Comment by chrisdamon** [comment]
> 目前还没有针对traefik网关的应用测试。 测试方法主要是通过wrk2或者我们自己写的打流工具，分别测试目标应用在有无agent情况下的rps极限以及指定rps下的应用资源占用等指标。 如果需要这方面的测试报告，后续我们会考虑进行针对traefik的测试。

主要是想咨询下有无agent对traefik的测试工具和测试方法，看看对traefik服务本身的影响以及资源使用情况。
您提到打流工具指的是什么？有没有操作或者使用之类的文档？
后续如果有专门针对traefik的测试报告就更好了。

**Comment by sharang** [comment]
@chrisdamon 工具和方法可参考[这篇博客](https://deepflow.io/blog/030-deepflow-agent-ebpf-benchmark/#0x2-Agent-%E5%AF%B9%E4%B8%9A%E5%8A%A1%E7%9A%84%E5%BD%B1%E5%93%8D)，里面有对 nginx 的测试。

**Comment by chrisdamon** [comment]
> @chrisdamon 工具和方法可参考[这篇博客](https://deepflow.io/blog/030-deepflow-agent-ebpf-benchmark/#0x2-Agent-%E5%AF%B9%E4%B8%9A%E5%8A%A1%E7%9A%84%E5%BD%B1%E5%93%8D)，里面有对 nginx 的测试。

好的，我试试，非常感谢

**Comment by sharang** [comment]
@chrisdamon 如果你做了 traefik 的测试，非常欢迎能在社区中分享出来。除了 DeepFlow 社区以外，我们和 Traefik 社区也有一些联系，到时候可分享到两个社区中 :)
