### ISSUE TITLE
[BUG] MySQL注释添加全局id后grafana界面无trace id

### ISSUE THREAD

**Issue by syzhang42** [deepflowio/deepflow#6292]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

我使用hostNetwork进行k8s网络设置，通过设置agent group设置全局traceid。可以看到，我的http和grpc种均正常工作。
![image](https://github.com/deepflowio/deepflow/assets/155063522/30def2b9-ba55-4a9a-93b0-95953bf38efb)
![8cf505ccc5bf2bff1181e11ffdf6433](https://github.com/deepflowio/deepflow/assets/155063522/68aff170-50c1-41cf-bad2-a06442788ebb)
我也在mysql中添加了前缀注释：
![image](https://github.com/deepflowio/deepflow/assets/155063522/ed550141-2391-4b0b-a8b0-1b64dbe5987f)
但是我的mysql对应的traceid，为空。
我的agent和server版本均为6.5.2

### How to reproduce

应用使用hostNetwork，mysql使用service。

### DeepFlow version

![image](https://github.com/deepflowio/deepflow/assets/155063522/80baf9fe-7f61-45b3-a8d1-e7d6815fa74a)
![image](https://github.com/deepflowio/deepflow/assets/155063522/e4aa857b-307e-45b1-9fdb-2fcce9d43d11)

### DeepFlow agent list

![image](https://github.com/deepflowio/deepflow/assets/155063522/41514bd4-88ed-4935-a54b-dc3ac27d7320)

### Kubernetes CNI

Kube-DNS

### Operation-System/Kernel version

5.15.0-52-generic

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by taloric** [comment]
@syzhang42 plz try to upgrade deepflow-agent with this patch:
https://github.com/deepflowio/deepflow/pull/6399
