### ISSUE TITLE
[BUG] `inet.af/netaddr`无法下载导致server编译失败

### ISSUE THREAD

**Issue by asdfsx** [deepflowio/deepflow#6382]
### DeepFlow Component

Server

### What you expected to happen

编译server时，依赖`inet.af/netaddr`无法下载，报错内容为
```
github.com/deepflowio/deepflow/server/controller/election imports
        k8s.io/client-go/tools/leaderelection tested by
        k8s.io/client-go/tools/leaderelection.test imports
        k8s.io/client-go/tools/record imports
        github.com/golang/groupcache/lru: inet.af/netaddr@v0.0.0-20211027220019-c74959edd3b6: unrecognized import path "inet.af/netaddr": https fetch: Get "https://inet.af/netaddr?go-get=1": dial tcp: lookup inet.af on 8.8.8.8:53: no such host 
```

导致该问题的原因可以在 https://github.com/inetaf 看到

目前我的解决办法时在go.mod 上增加replace设置
```
replace inet.af/netaddr => github.com/inetaf/netaddr v0.0.0-20211027220019-c74959edd3b6
```

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by hugh2021** [comment]
> 可通过调整编译环境解决，PR 6385 中已经去掉了 go mod replace

您能详细点描述一下怎么调整的编译环境吗？我在其他项目遇到了同样的问题，多谢多谢！
