### ISSUE TITLE
[BUG] 构建时ip_info.py 中发生错误``UnicodeEncodeError: 'ascii' codec can't encode characters in position`

### ISSUE THREAD

**Issue by asdfsx** [deepflowio/deepflow#6384]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

我在centos7.9的容器中构建server端时ip_info.py报错
```
go generate ./...
Traceback (most recent call last):
  File "ip_info.py", line 101, in <module>
    gen_code(sys.argv[1])
  File "ip_info.py", line 85, in gen_code
    wf.write('var COUNTRY_NAMES = [...]string{%s}\n' % ', '.join(['"%s"' % name for name in country_encoder.items]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 33-34: ordinal not in range(128)
libs/geo/generator.go:19: running "python3": exit status 1
make: *** [libs/hmap/idmap/ubig_id_map.go] Error 1 
```
解决办法是在打开文件是指定字符集为`utf-8`

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
目前使用的是我们提供的build镜像，还是通过手动构做的呀？
