### ISSUE TITLE
[BUG] All-in-one部署出错

### ISSUE THREAD

**Issue by ZhangJiaQiao** [deepflowio/deepflow#6393]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

我根据文档https://deepflow.io/docs/zh/ce-install/all-in-one/快速部署，通过docker compose部署了deepflow server，状态如下：
```
$ sudo docker compose -f deepflow-docker-compose/docker-compose.yaml up -d
WARN[0000] /home/zhangjiaqiao/deepflow-docker-compose/docker-compose.yaml: `version` is obsolete 
[+] Running 9/9
 ✔ Network deepflow-docker-compose_deepflow        Created                                   0.2s 
 ✔ Container deepflow-grafana-init-worksdir        Started                                   1.2s 
 ✔ Container deepflow-app                          Started                                   1.4s 
 ✔ Container deepflow-mysql                        Started                                   1.5s 
 ✔ Container deepflow-grafana-init-custom-plugins  Started                                   2.3s 
 ✔ Container deepflow-grafana-init-grafana-ds-dh   Started                                   2.1s 
 ✔ Container deepflow-clickhouse                   Starte...                                 2.4s 
 ✔ Container deepflow-grafana                      Started                                   3.3s 
 ✔ Container deepflow-server                       Started                                   3.8s
```
并安装deepflow-ctl：
```
curl -o /usr/bin/deepflow-ctl https://deepflow-ce.oss-cn-beijing.aliyuncs.com/bin/ctl/stable/linux/$(arch | sed 's|x86_64|amd64|' | sed 's|aarch64|arm64|')/deepflow-ctl
chmod a+x /usr/bin/deepflow-ctl
```

然后根据文档https://deepflow.io/docs/zh/ce-install/legacy-host/ 准备监控传统服务器，在创建采集器组的时候出现如下错误：
```
$ deepflow-ctl agent-group create $AGENT_GROUP
curl (http://xxxxx:xxxx/v1/vtap-groups/) failed, ({"OPT_STATUS":"INVALID_POST_DATA","DESCRIPTION":"Key: 'VtapGroupCreate.TeamID' Error:Field validation for 'TeamID' failed on the 'required' tag","DATA":null})
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
这里看起来，是因为你没有给 $AGENT_GROUP 设置一个值呀，下面报错："INVALID_POST_DATA"，需要设置一个组名，或者：
`deepflow-ctl agent-group create k8s-prod`
类似于这样执行也可以

**Comment by ZhangJiaQiao** [comment]
> 这里看起来，是因为你没有给 $AGENT_GROUP 设置一个值呀，下面报错："INVALID_POST_DATA"，需要设置一个组名，或者： `deepflow-ctl agent-group create k8s-prod` 类似于这样执行也可以

应该设置了，根据教程上面设了$AGENT_GROUP环境变量，指定名字也不行，api版本是不是有变化呢
deepflow-ctl agent-group create k8s-prod
curl (http://xxx:xxx/v1/vtap-groups/) failed, ({"OPT_STATUS":"INVALID_POST_DATA","DESCRIPTION":"Key: 'VtapGroupCreate.TeamID' Error:Field validation for 'TeamID' failed on the 'required' tag","DATA":null})

**Comment by 1473371932** [comment]
[pr](https://github.com/deepflowio/deepflow/commit/8db576ec85562db90f2b1bfa778ac679f959db7e)
这个是 server 的问题，目前最新的 server 已经解决这个问题了才对，先更新 server 看下是否还会出现这个问题，如果还出现，麻烦进入server执行`deepflow-server -v`看一下详细版本
