### ISSUE TITLE
[BUG] grafana图形无法展示，数据库查询Resolve identifier 'tag.host' from parent scope only supported for constants and CTE

### ISSUE THREAD

**Issue by vslinux** [deepflowio/deepflow#6424]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

A
the expected status code returns 200, the actual return is 500, the parameter data is map[db:[deepflow_system] sql:[SELECT Avg(`metrics.cpu_percent`) AS `cpu-avg`, time(time, 10) AS `time_10`, `tag.host` FROM deepflow_server_monitor WHERE `tag.host` IN ('10.143.151.51') AND time>=1715651990 AND time<=1715652890 GROUP BY `time_10`, `tag.host` SLIMIT 20 LIMIT 1000]], and the data is
Status: 400
Object
OPT_STATUS:"FAIL"
DESCRIPTION:"code: 1, message: Resolve identifier 'tag.host' from parent scope only supported for constants and CTE. Actual tag_values[indexOf(tag_names, 'host')] AS `tag.host` node type FUNCTION. In scope (SELECT tag_values[indexOf(tag_names, 'host')] AS `tag.host` FROM deepflow_system.deepflow_system WHERE (virtual_table_name = 'deepflow_server_monitor') AND ((tag_values[indexOf(tag_names, 'host')]) IN ('10.143.151.51')) AND (time >= 1715651990) AND (time <= 1715652890) AND (tag.host != '') GROUP BY `tag.host` LIMIT 20)"
result:null
debug:null

### DeepFlow version

#kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
Name: deepflow-server community edition
Branch: v6.5.4
CommitID: 8b0dda74cba2509b0dcae74ae68000f9f374ce8e
RevCount: 10029
Compiler: go version go1.20.14 linux/amd64
CompileTime: 2024-04-11 01:14:41

#kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
10029-8b0dda74cba2509b0dcae74ae68000f9f374ce8e
Name: deepflow-agent community edition
Branch: v6.5.4
CommitId: 8b0dda74cba2509b0dcae74ae68000f9f374ce8e
RevCount: 10029
Compiler: rustc 1.77.1 (7cf61ebde 2024-03-27)
CompileTime: 2024-04-11 01:16:03

### Operation-System/Kernel version

centos 5.18.15-1.el7.elrepo.x86_64

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by vslinux** [comment]
数据库： 
2024-05-14T10:08:18+08:00,deepflow_server_querier_querier_count,1,['host'],['10.143.151.51'],"['api_count', 'api_time_avg', 'api_time_max', 'column_count', 'query_count', 'query_time_avg', 'query_time_max', 'response_size', 'row_count']","[0, 0, 0, 0, 3, 26209089, 36590951, 0, 0]"

**Comment by 1473371932** [comment]
能否截个图看一下？目前是所有 Dashboard 查询都有问题，还是只有某些表查询时有问题呢？
ck 和 mysql 用的 chart 包里的还是你们的呀？都是什么版本

**Comment by vslinux** [comment]
使用外部的，目前在测试环境部署，所以临时用docker启动了ClickHouse和mysql，版本如下：
ClickHouse local version 24.3.2.23
mysql: 8

所有的图形都出不来，但是数据库和ck表里能看到有生成数据，附件已上传截图
![Uploading 1715757204453.jpg…]()

**Comment by vslinux** [comment]
CK数据库里的表：

4bc3a78a96e8 :) use flow_metrics;

USE flow_metrics

Query id: 19a0d1ff-a43f-4be5-8ceb-b3c20d932488

Ok.

0 rows in set. Elapsed: 0.001 sec.

4bc3a78a96e8 :) show tables;

SHOW TABLES

Query id: 35714b54-b26f-4a21-87fe-a4c5e605d43f

    ┌─name─────────────────────┐
 1. │ application.1m           │
 2. │ application.1m_local     │
 3. │ application.1s           │
 4. │ application.1s_local     │
 5. │ application_map.1m       │
 6. │ application_map.1m_local │
 7. │ application_map.1s       │
 8. │ application_map.1s_local │
 9. │ network.1m               │
10. │ network.1m_local         │
11. │ network.1s               │
12. │ network.1s_local         │
13. │ network_map.1m           │
14. │ network_map.1m_local     │
15. │ network_map.1s           │
16. │ network_map.1s_local     │
17. │ traffic_policy.1m        │
18. │ traffic_policy.1m_local  │
    └──────────────────────────┘



grafana查询： 

SELECT PerSecond(Avg(`request`)) AS `PerSecond(Avg(Request))`, Max(`client_error_ratio`) AS `Max(Client Error %)`, Max(`server_error_ratio`) AS `Max(Server Error %)`, Sum(`timeout`) AS `Sum(Timeout)`, Percentile(`rrt_max`,0.9) AS `Percentile(Max Delay,0.9)`, Percentile(`rrt_max`,0.99) AS `Percentile(Max Delay,0.99)`, auto_service_1, Enum(l7_protocol), endpoint, auto_service_id_1, node_type(auto_service_1) AS `server_node_type`, icon_id(auto_service_1) AS `server_icon_id`, l7_protocol FROM application_map WHERE exist(`l7_protocol`) AND exist(auto_service_id_1) AND `endpoint` LIKE('*') AND `signal_source` IN ('3') AND time>=1715757069 AND time<=1715757969 GROUP BY auto_service_1, l7_protocol, endpoint, auto_service_id_1, `server_node_type` LIMIT 1000;

报错：

Status: 400
Object
OPT_STATUS:"FAIL"
DESCRIPTION:"code: 179, message: Multiple expressions if(auto_service_type_1 IN (0, 255), subnet_id_1, auto_service_id_1) AS auto_service_id_1 and if(auto_service_type_1 IN (0, 255), subnet_id_1, auto_service_id_1) AS au .................

**Comment by 1473371932** [comment]
你好，提交的这个图片链接地址是这个 ISSUE 的地址，点击后又回到这个 ISSUE 了，可能上传的方式有些问题，

`DeepFlow System`和`DeepFlow Templates`两个目录下的面板都没有数据么？
从你们 Clickhouse 版本来看，应该是太新导致的，我们预计 v6.6 版本后会支持 24 版本，目前使用的 ck 版本还是 23，建议你们使用的外部的 ck 和我们 chart 包里的版本同步一下
