### ISSUE TITLE
请问一下，资源变更事件是通过k8s的api获取的吗，agent相关的代码在哪里？

### ISSUE THREAD

**Issue by lobsterHe** [deepflowio/deepflow#6468]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
@lobsterHe 资源变更事件是通过 list&watch k8s apiserver 拿到的。我们采集了两种事件：
1. 通过 list&watch k8s pod 等资源，由 deepflow-server 构造 pod 的增删改重建等事件
2. 通过 list&watch k8s event，直接获取 k8s 的其他类型事件（这个还在开发中）

对于 1，请参考 agent/src/platform/kubernetes 代码
