### ISSUE TITLE
[FR] deepflow-agent set dynamic configurations

### ISSUE THREAD

**Issue by panda87** [deepflowio/deepflow#6477]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

The current configuration is located in `src/config/` as .rs files rather than in config files or env vars that can be populated during the agent setup dynamically.  

The feature is make the agent/server configuration dynamic as env vars with code defaults.to makes

### Use case

I'd like to enable only metrics by default (*l7_metrics_enabled*) and disable (*l4_performance_enabled*) in some cases to improve DB capacity management and align the needs with expectations.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
Hello, it appears you wish to alleviate storage pressure by reducing the amount of data in certain areas. You can refer to [this article](https://deepflow.io/docs/zh/best-practice/reduce-storage-overhead/) to address this issue by reducing unnecessary collection points. However, in most cases, users require data from all aspects, so we do not disable the collection of certain metrics by default. Users must decide for themselves which data they do not need. For information on how to change the configuration, you can refer to [this article](https://deepflow.io/docs/best-practice/agent-advanced-config/).

**Comment by panda87** [comment]
Thanks for the quick answer @1473371932 
I'll take a look at both links, it seems there is still a lot of info that hasn't been translated like [this](https://deepflow.io/docs/zh/best-practice/reduce-storage-overhead/) which includes networking info. 
Any plan to translate more pages to EN soon?

**Comment by sharang** [comment]
> Any plan to translate more pages to EN soon?

We will release version 6.5 soon (planned for mid-June). Before that, we will update all the documentation to English. @panda87

**Comment by sharang** [comment]
> Thanks for the quick answer @1473371932 I'll take a look at both links, it seems there is still a lot of info that hasn't been translated like [this](https://deepflow.io/docs/zh/best-practice/reduce-storage-overhead/) which includes networking info. Any plan to translate more pages to EN soon?

done

https://www.deepflow.io/docs/best-practice/reduce-storage-overhead/
