### ISSUE TITLE
请问deepflow agent 对于cbpf 的采集部分逻辑在代码里有体现吗？是基于bpf单独开发的吗

### ISSUE THREAD

**Issue by lichao5585** [deepflowio/deepflow#6479]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

请问deepflow agent 对于cbpf 的采集部分逻辑在代码里有体现吗？是基于bpf单独开发的吗

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lichao5585** [comment]
因为就我理解，cbpf只能实现过滤包的功能。

**Comment by sharang** [comment]
@lichao5585 是的，cBPF 用来过滤（以及截断）Packet，除此之外我们使用了 Linux Kernel 的 AF_PACKET 接口来拿到过滤后的 Packet。拿到用户态以后，我们会将 Packet 还原为 TCP/UDP Flow，并从中识别出来应用协议。具体代码可参考 agent/src/dispatcher 和 agent/src/flow_generator
