### ISSUE TITLE
[FR] DeepFlow 使用什么 eBPF 框架以及如何添加新的 eBPF 探测功能

### ISSUE THREAD

**Issue by ZhangJiaQiao** [deepflowio/deepflow#6502]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我们想利用deepflow做进程内核指标的探测，但是这些指标deepflow似乎没有支持。deepflow使用哪种ebpf框架进行开发？如果要自己增加探测代码，有相关模版参考吗？最后如何接入deepflow并进行展示？

### Use case

比如我想增加ebpf代码来探测mongodb的内核指标，如何开发并接入deepflow进行展示

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
@ZhangJiaQiao DeepFlow 内置的 eBPF 能力主要聚焦在 Tracing & Profiling 方面，如果想增加 eBPF 获取内核指标的能力，我们建议的方式是通过如下方式来实现：
1. 实现一个 ebpf prometheus exporter。或者增强一个已有的 ebpf exporter，例如：https://github.com/cloudflare/ebpf_exporter
2. 将 exporter 的指标暴露给 prometheus-server（可以使用 agent mode 即可，无需存储数据，推荐使用 grafana-agent）
3. grafana-agent 将数据 remote-write 给 deepflow，参考文档：https://deepflow.io/docs/zh/integration/input/metrics/prometheus/

也就是说，数据流是 `ebpf-exporter => grafana-agent => deepflow-agent => deepflow-server => clickhouse`。

未来，deepflow-agent 将会支持直接 pull prometheus exporter，届时上述数据流中的 grafana-agent 将可以被去除。
