### ISSUE TITLE
[FR] Data changes in Genesis have caused a large number of binlogs in database tables

### ISSUE THREAD

**Issue by zcl1115** [deepflowio/deepflow#6515]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://github.com/deepflowio/deepflow/blob/main/server/controller/genesis/datatypes.go#L243
想咨询一下genesis类型开头的数据库表中，存储的数据的作用是什么，这边看到是过期的数据会导致相关涉及的全部genesis表数据进行刷新，然后刷新的动作涉及到delete整个node_ip相关的数据，因为node_ip是deepflow-server节点所在的ip，这样就会一次性删除掉一大部分数据然后再插入回来，对于genesis_process这张表而言，可能中间操作的大部分数据都会是相同的，所以想问一下genesis此类数据的作用以及更新是怎么发生的？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SongZhen0704** [comment]
genesis此类数据变化主要会发现在下面两种情况：
- agent上报的相关数据有变化（通过version判断），但是由于我们没有对比具体的变化内容，所以会进行整体的删除和更新
- agent上报的server发生变化，原有server上的数据过期后会被清理

**Comment by chestack** [comment]
v7.1.0代码里还是有全量 delete 再 insert的逻辑，会打爆binlog

@zcl1115 请问这个问题有啥解决或者规避思路

@SongZhen0704 这里有修复优化计划吗
