### ISSUE TITLE
[BUG] Overflow of the vtap_id value range

### ISSUE THREAD

**Issue by rosenlo** [deepflowio/deepflow#6666]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

We found that many records lacked k8s labels from the flow log, and when we looked deeper, we found that the vtap_id (now called agent_id) value overflow prevented us from associating to k8s labels via pod_id and epc_id queries, because both IDs are 0.

We now have more than 100,000 vtap_id, so uint16 is not enough (uint16 up to 65536), according to the modification of the private code to uint32 after verification can fix the problem, but due to the large number of modified files, you guys need to be cautious review, refer to the [PR](https://github.com/deepflowio/deepflow/pull/6665).

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by SongZhen0704** [comment]
https://github.com/deepflowio/deepflow/pull/6735
