### ISSUE TITLE
How to solve the problem `A call to built-in function 'memset' is not supported` when using `__builtin_memset`

### ISSUE THREAD

**Issue by asdfsx** [deepflowio/deepflow#6707]
https://github.com/deepflowio/deepflow/blob/f4ed72b03885253686eb1ee8c592d3348c9f6212/agent/src/ebpf/kernel/socket_trace.bpf.c#L2049-L2051

I write a simple bpf demo like

```
KPROG(vfs_write) (struct pt_regs* ctx) {
       ....
	__u32 k0 = 0;
	struct __fs_event_buffer *v_buff = bpf_map_lookup_elem(&NAME(fs_event_buf), &k0);
	struct __fs_event *v = (struct __fs_event *)&v_buff->data[0];
	__builtin_memset(v, 0, offsetof(typeof(struct __fs_event), data));
        ....
}
```

but when I build the code, I got the error `in function kprobe__vfs_write i32 (%struct.pt_regs*): A call to built-in function 'memset' is not supported.`

But in your code I find there‘s a lot of `__builtin_memset`, I want to know how to solve the problem?

**Comment by yinjiping** [comment]
Try the following method to see if it can solve the issue:

Use Clang/LLVM 11.0.0 (If you are using our build image, you can ignore this).
Add a safety check similar to the one below to ensure that the remaining space in the buffer can accommodate the data you want to store.
```c
if ((void *)v + offsetof(typeof(struct __fs_event), data) <  (void *)v + sizeof(v_buff->data))
   __builtin_memset((void *)v, 0, offsetof(typeof(struct __fs_event), data));
```
