### ISSUE TITLE
acquire invoked method duration

### ISSUE THREAD

**Issue by catkkt** [deepflowio/deepflow#6799]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

Hi, all
I'm wondering  if DeepFlow could acquire the duration of Java application invoking method, such as Tomcat Servlet.service()?

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
Hello, the presentation of performance profiling results is a feature exclusive to DeepFlow Enterprise Edition. The open-source version does not include a dedicated page for displaying performance profiling; you will need to develop this page yourself. For information on how to use this feature, please refer to this document: https://deepflow.io/docs/features/continuous-profiling/auto-profiling/

**Comment by catkkt** [comment]
> Hello, the presentation of performance profiling results is a feature exclusive to DeepFlow Enterprise Edition. The open-source version does not include a dedicated page for displaying performance profiling; you will need to develop this page yourself. For information on how to use this feature, please refer to this document: https://deepflow.io/docs/features/continuous-profiling/auto-profiling/

Got it,thanks.
