### ISSUE TITLE
[FR] 在看处理cbpf抓取的网络数据时，找不到flow_map到L4FlowPerf.parse的路线，能帮忙解答一下吗？

### ISSUE THREAD

**Issue by lobsterHe** [deepflowio/deepflow#6935]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
Could you please provide a detailed description of the current situation, or perhaps some screenshots?

**Comment by 1473371932** [comment]
Hello, if you have any further questions, you can join the group chat on the project homepage or re-trigger this issue
