### ISSUE TITLE
[BUG] deepflow-agent log print: Address already in use 

### ISSUE THREAD

**Issue by zcl1115** [deepflowio/deepflow#7061]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

部署node机器，端口38086上已经存在服务监听，启动agent会打印错误日志，但实际上不影响采集的数据
[2024-06-21 12:09:03.256951 +08:00] WARN [src/integration_collector.rs:1149] the port=(38086) listen by the integration collector lost, restart the collector
[2024-06-21 12:09:05.999601 +08:00] ERROR [src/integration_collector.rs:1033] integration collector error: error creating server listener: Address already in use (os error 98) with addr=[::]:38086

### DeepFlow version

deepflow-agent v6.5.5 10116-c29adff9e4a375dbcda32fc8c08aeb4455cd7462

### DeepFlow agent list

ID     NAME                   TYPE       CTRL_IP           CTRL_MAC            STATE    GROUP                  EXCEPTIONS                 REVISION       UPGRADE_REVISION   
1051   169.136.153.209-V372   K8S_VM     169.136.153.209   9c:c2:c4:2d:ac:29   NORMAL   docker-cluster-sg-19   INTEGRATION_SOCKET_ERROR   v6.5.5 10116                      

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
This port number is only used for integrating Prometheus/OpenTelemetry/Vector data. If you do not need this feature, you can disable it. Of course, you can also change it to another port number.

https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L466
```yaml
## Data Integration Socket
## Default: 1. Options: 0 (disabled), 1 (enabled).
## Note: Whether to enable receiving external data sources such as Prometheus,
##   Telegraf, OpenTelemetry, and SkyWalking.
#external_agent_http_proxy_enabled: 1

## Listen Port of the Data Integration Socket
## Default: 38086. Options: [1, 65535]
#external_agent_http_proxy_port: 38086
```
