### ISSUE TITLE
deepflow  grafana Dashboards Deepflow-Template/Application-开箱即用，查询请求 No Data

### ISSUE THREAD

**Issue by LemonSqi** [deepflowio/deepflow#7091]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在使用deepflow grafana的Dashboards去测试Deepflow-Template/Application-开箱即用面板时遇到查询请求No Data的情况：
![43e5bd20071193ad7af5159d31d63e1](https://github.com/deepflowio/deepflow/assets/36250184/4d5c83a2-6416-4855-b413-8254f5b9bd66)
![5bfb6e76b6299959078bf1c1548c922](https://github.com/deepflowio/deepflow/assets/36250184/4c635a0b-2b13-4fd9-80ee-c39f6a4ead89)

观察到后台所有服务均处于Running状态：
![79b7f8a3ae0b079e23560732fd291b6](https://github.com/deepflowio/deepflow/assets/36250184/f51aa63a-a7c8-4d9c-9b8b-b37b70c3e28b)

查看deepflow-server的日志看到如下报错：
![691030663d495cab9ec6469955acbd7](https://github.com/deepflowio/deepflow/assets/36250184/6cc08e76-43c6-471d-83db-a7d5f3b9b1a8)

请问这个是什么原因引起的？？

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
Hello, may I ask which version of Deepflow you are using? Currently, is it only the 'Deepflow-Template/Application-Out-of-the-Box' dashboard that has no data, or do all the panels lack data?

**Comment by LemonSqi** [comment]
Deepflow 6.5.8  
all the panels lack data

**Comment by LemonSqi** [comment]
> Deepflow 6.5.8
> all the panels lack data



> Hello, may I ask which version of Deepflow you are using? Currently, is it only the 'Deepflow-Template/Application-Out-of-the-Box' dashboard that has no data, or do all the panels lack data?

Deepflow 6.5.8
all the panels lack data

**Comment by LemonSqi** [comment]
Today，another strange phenomenon occurred. The pods of the deepflow cluster deepflow-server began to be rebuilt, and many pods were in the Evicted state.
![3dfac01606897d1d14830462b5c7e49](https://github.com/deepflowio/deepflow/assets/36250184/cd8422bc-ffe1-4485-8aaa-032933e1f9eb)

**Comment by 1473371932** [comment]
Hello, when encountering an "Evicted" status in the pod, please investigate whether it is due to issues with the corresponding k8s node itself, such as disk insufficiency causing the node to become tainted.

Regarding the aforementioned data issue, could you first upgrade to our v6.5 LTS version? You can change the image tag of the deepflow-related components, such as server, agent, and app, from v6.5.8 to v6.5. After updating to the LTS version, check the Dashboard panel again to see if the data issue persists.

**Comment by LemonSqi** [comment]
> Hello, when encountering an "Evicted" status in the pod, please investigate whether it is due to issues with the corresponding k8s node itself, such as disk insufficiency causing the node to become tainted.
> 
> Regarding the aforementioned data issue, could you first upgrade to our v6.5 LTS version? You can change the image tag of the deepflow-related components, such as server, agent, and app, from v6.5.8 to v6.5. After updating to the LTS version, check the Dashboard panel again to see if the data issue persists.

Sorry, I installed it through the intranet. The directly downloaded deepflow-charts warehouse package was installed and started locally through helm. I checked again and the version of Chart.yaml was 6.5.009.
I noticed that the 6.5.9 version of the chart only has Source code and does not have a compiled tgz package. Can you provide a compiled package?

**Comment by LemonSqi** [comment]
I found the v6.5.9 tgz installation package on the chart's release tag page, but when I tried to install it through helm, I got an error: missing in charts/ directory: deepflow-agent, grafana. I tried to check the contents of this tgz and found that deepflow-agent and grafana were indeed not included, and complete dependencies were provided in previous versions of charts. What considerations did the 6.5.9 LTS version take to change the release structure of the package? We are expecting a reply!

**Comment by LemonSqi** [comment]
I tried to put the package deepflow-agent in deedflow/charts, and put grafana in the previous 6.5.009 package in the same location. All images used v6.5 of the latest tag. After starting, grafana Still getting error:

![04c1ed2d9e5b2e7232bf0a351482232](https://github.com/deepflowio/deepflow/assets/36250184/9de3f90f-d0b0-42b9-b558-e390ed352c95)

![8754bb1ae2a4037c3b82e1b77fff4ef](https://github.com/deepflowio/deepflow/assets/36250184/72ad004f-ff40-431e-b5aa-211e8e5df487)

Now an error is reported directly. XX does not exist in the database. Maybe it is because the version is incompatible? I don’t know where the problem lies. Can you provide a complete version of the deepflow v6.5 chart package that has been tested internally for stability (LTS includes all components). We have invested a lot of time in the installation and use of components. A stable version of the chart Bags are really important to us, thank you so much for supporting us! ! !

**Comment by 1473371932** [comment]
> I found the v6.5.9 tgz installation package on the chart's release tag page, but when I tried to install it through helm, I got an error: missing in charts/ directory: deepflow-agent, grafana. I tried to check the contents of this tgz and found that deepflow-agent and grafana were indeed not included, and complete dependencies were provided in previous versions of charts. What considerations did the 6.5.9 LTS version take to change the release structure of the package? We are expecting a reply!

Hello, have you tried using helm repo update to refresh the helm repository? I noticed you mentioned the downloaded tar package is named v6.5.9 tgz, while our latest chart version is already 6.5.010. Alternatively, you can update by simply replacing the image tag, as the format in the chart package has not changed; only the image tag has been updated from v6.5.9 to v6.5.

**Comment by LemonSqi** [comment]
> > I found the v6.5.9 tgz installation package on the chart's release tag page, but when I tried to install it through helm, I got an error: missing in charts/ directory: deepflow-agent, grafana. I tried to check the contents of this tgz and found that deepflow-agent and grafana were indeed not included, and complete dependencies were provided in previous versions of charts. What considerations did the 6.5.9 LTS version take to change the release structure of the package? We are expecting a reply!
> 
> Hello, have you tried using `helm repo update` to refresh the helm repository? I noticed you mentioned the downloaded tar package is named v6.5.9 tgz, while our latest chart version is already 6.5.010. Alternatively, you can update by simply replacing the image tag, as the format in the chart package has not changed; only the image tag has been updated from v6.5.9 to v6.5.
> 
> If you are using an internal network and cannot directly connect to GitHub to download or update the latest chart package, you can first download the chart package and the corresponding image through an external network, then upload them to your intranet host for updating. Based on the error message in your current screenshot, it appears that ClickHouse is missing some tables. However, I still recommend updating using the aforementioned method and then checking if there are any data issues.

I deployed in an offline environment, so I cannot update my chart package through the helm update command. I need to download the specified version of the chart package and image on a networked machine and import it into the offline environment. I have downloaded the 6.5.010 chart package and redeployed it as you said, but there is still a problem with the display of grafana, No data. This confuses us. Because it is a black box, we cannot determine the cause of the problem. We cannot directly complete the test of the open source deepflow component through containerized deployment. We look forward to your further reply.

**Comment by 1473371932** [comment]
> I tried to put the package deepflow-agent in deedflow/charts, and put grafana in the previous 6.5.009 package in the same location. All images used v6.5 of the latest tag. After starting, grafana Still getting error:
> 
> ![04c1ed2d9e5b2e7232bf0a351482232](https://private-user-images.githubusercontent.com/36250184/343660953-9de3f90f-d0b0-42b9-b558-e390ed352c95.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDMyNjYsIm5iZiI6MTcxOTgwMjk2NiwicGF0aCI6Ii8zNjI1MDE4NC8zNDM2NjA5NTMtOWRlM2Y5MGYtZDBiMC00MmI5LWI1NTgtZTM5MGVkMzUyYzk1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAzMDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDEyMjhmZjg0ODlmYjMzOGMzZDRkN2JiYjU4NjIzYzBiMjFkY2U2MmM4MTUzZmFhY2VjYTU0MDgwZTUxYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M5IFcP_tzn5ryoaler01dxlXBOfPlO2vWC9ObMHXvnY)
> 
> ![8754bb1ae2a4037c3b82e1b77fff4ef](https://private-user-images.githubusercontent.com/36250184/343662240-72ad004f-ff40-431e-b5aa-211e8e5df487.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDMyNjYsIm5iZiI6MTcxOTgwMjk2NiwicGF0aCI6Ii8zNjI1MDE4NC8zNDM2NjIyNDAtNzJhZDAwNGYtZmY0MC00MzFlLWI1YWEtMjExZThlNWRmNDg3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAzMDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NjQ2MTAwNGJiMTU1MjM2NzQyNzM3MjIxYWUwMzgxN2EwZGE5MTgwYjMyYmE5NTg0ZmFlMmJjZTZiZmFhZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pgum9TDQRPDoF3MWS0XcUEwihEoeU-_OgFbsQfp8Tjc)
> 
> Now an error is reported directly. XX does not exist in the database. Maybe it is because the version is incompatible? I don’t know where the problem lies. Can you provide a complete version of the deepflow v6.5 chart package that has been tested internally for stability (LTS includes all components). We have invested a lot of time in the installation and use of components. A stable version of the chart Bags are really important to us, thank you so much for supporting us! ! !

After the update, are there still any errors? Could you select "Data" at the screenshot's indicated position to check for any content, and also try querying the controller's status in MySQL with `SELECT state FROM deepflow.controller;` to rule out issues caused by the controller?

**Comment by LemonSqi** [comment]
> > I tried to put the package deepflow-agent in deedflow/charts, and put grafana in the previous 6.5.009 package in the same location. All images used v6.5 of the latest tag. After starting, grafana Still getting error:
> > ![04c1ed2d9e5b2e7232bf0a351482232](https://private-user-images.githubusercontent.com/36250184/343660953-9de3f90f-d0b0-42b9-b558-e390ed352c95.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDMyNjYsIm5iZiI6MTcxOTgwMjk2NiwicGF0aCI6Ii8zNjI1MDE4NC8zNDM2NjA5NTMtOWRlM2Y5MGYtZDBiMC00MmI5LWI1NTgtZTM5MGVkMzUyYzk1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAzMDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDEyMjhmZjg0ODlmYjMzOGMzZDRkN2JiYjU4NjIzYzBiMjFkY2U2MmM4MTUzZmFhY2VjYTU0MDgwZTUxYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M5IFcP_tzn5ryoaler01dxlXBOfPlO2vWC9ObMHXvnY)
> > ![8754bb1ae2a4037c3b82e1b77fff4ef](https://private-user-images.githubusercontent.com/36250184/343662240-72ad004f-ff40-431e-b5aa-211e8e5df487.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDMyNjYsIm5iZiI6MTcxOTgwMjk2NiwicGF0aCI6Ii8zNjI1MDE4NC8zNDM2NjIyNDAtNzJhZDAwNGYtZmY0MC00MzFlLWI1YWEtMjExZThlNWRmNDg3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAzMDI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NjQ2MTAwNGJiMTU1MjM2NzQyNzM3MjIxYWUwMzgxN2EwZGE5MTgwYjMyYmE5NTg0ZmFlMmJjZTZiZmFhZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pgum9TDQRPDoF3MWS0XcUEwihEoeU-_OgFbsQfp8Tjc)
> > Now an error is reported directly. XX does not exist in the database. Maybe it is because the version is incompatible? I don’t know where the problem lies. Can you provide a complete version of the deepflow v6.5 chart package that has been tested internally for stability (LTS includes all components). We have invested a lot of time in the installation and use of components. A stable version of the chart Bags are really important to us, thank you so much for supporting us! ! !
> 
> After the update, are there still any errors? Could you select "Data" at the screenshot's indicated position to check for any content, and also try querying the controller's status in MySQL with `SELECT state FROM deepflow.controller;` to rule out issues caused by the controller?

I don’t understand the test method you mentioned above. When it comes to mysql you mentioned above, does this instruction mean that I access it directly through the url api, or does it mean that I log in to the deepflow-mysql service and select it? The other screenshot is the log of deepflow-server. How to get the data in the log? Do not understand what you mean

**Comment by LemonSqi** [comment]
I try to understand your test method: I entered the pod of deepflow-mysql, and the result of the query through select state from deepflow.controller is 2.what does this status mean?

**Comment by LemonSqi** [comment]
通过进一步的跟踪定位，我们发现ck的日志里存在一些比较奇怪的报错：
![1aa91ad2a3768ec35ed2c63e16d4000](https://github.com/deepflowio/deepflow/assets/36250184/be3d7031-84ed-49b0-887b-e1b06ad46da8)
跟着这个报错，我们进入了pod内部，定位到该路径下确实没有证书：
![76dc12c44a8725cd1d1152e31e1712e](https://github.com/deepflowio/deepflow/assets/36250184/0e1cba3e-6d82-45b1-b97f-b81452e0fe23)
查看config.yaml, openSSL确实配置了证书路径：
![812adea915608f9c8dd19824b3551eb](https://github.com/deepflowio/deepflow/assets/36250184/c8afa51d-0cb5-41d5-bbbb-ec79796318ed)

请问，grafana查询不到数据是否和ck的这个异常有关，如果有关系，为什么成功启动的ck在该路径下没有生成可用的证书，期待你们的答复！！！

**Comment by liqian1834** [comment]
你好，对于 Grafana 中 No Data 的情况，整个 Issue 里面目前看到问题如下：
- `auto create domain failed：record not found，try again after 3s` 报错，这个是 6.5 版本新增多租户功能引入的一个 Bug，通过升级到 6.5 LTS 版本可解决
![img_v3_02cj_dd778b1b-05b3-4e35-970d-089c52089feg](https://github.com/deepflowio/deepflow/assets/19233457/1130aa22-8dd9-43e2-9959-5f68375d19a2)
- deepflow-server pod 的状态不对，这个状态是否已经正常？
![image](https://github.com/deepflowio/deepflow/assets/19233457/cabdc111-d6cf-4018-9982-c7fac8404ef4)
-  `cannot view these namespaces in grafana's explore panel` 这里应该是 K8s 对接存在问题，然后引入了后续的一系列问题
- `the result of the query through select state from deepflow.controller is 2` 这里看 deepflow-server 的 controller 有问题，也需要继续看下问题

上面的问题，持续在 Issue 跟进可能效率并不高，可以加我们微信，语音下快速解决
![image](https://github.com/deepflowio/deepflow/assets/19233457/e824a904-031e-4a31-af98-f2b83e6d1351)

**Comment by LemonSqi** [comment]
感谢支持~！！！问题已经及时被解决~！！
