### ISSUE TITLE
[FR] 请教下可以在 L7FlowLog 中注入容器ID信息吗

### ISSUE THREAD

**Issue by midorifizz** [deepflowio/deepflow#7137]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在 L7FlowLog 中可以看到能够注入 Pod 相关的信息（PodID0 和 PodID1 等），但是没有看到 ContainerID 的信息，想问一下是因为我 agent 相关配置没有开启还是说本身就不会注入容器ID。我理解通过 Process PID 查询 cgoup 文件就能获取到 ContainerID，我看 deepflow agent 的代码中也有相关实现（如下图所示），在 L7FlowLog 中也注入了 ProcessID0、ProcessID1 这样的进程 PID。感谢解答！
![image](https://github.com/deepflowio/deepflow/assets/20487362/2f8a3076-624f-4574-833c-7cb04b2cfe53)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
@midorifizz 能力上是可以支持注入 containerid 的，但这个 id 我们理解就是一段 hash 码，不可读。你们会怎么使用 container id ？

**Comment by midorifizz** [comment]
@sharang 你好  我们这边有一个资源发现的服务 通过容器ID可以查询到相关的K8S信息进行关联 所以这部分能力不打算依赖 deepflow-server 这个属于业务相关的改造了 目前我已经找到代码修改点 所以我打算关闭这个issue 感谢你的回复
