### ISSUE TITLE
[FR] FR-29: deepflow supports  users to extend 4/7 layers of custom fields.

### ISSUE THREAD

**Issue by wenhuwang** [deepflowio/deepflow#715]
### Feature request
we wonder if we can display http header or body data, so we need deepflow to provide a way for users to extend 4/7 layers of custom fileds.

**Comment by sharang** [comment]
You can check our `Wasm plugin` mechnisim.

Here is a blog post: https://deepflow.io/blog/035-deepflow-enabling-zero-code-observability-for-applications-by-webAssembly/
