### ISSUE TITLE
[FR] deepflow能否将链路信息对接到jaeger中

### ISSUE THREAD

**Issue by xiaoyuan2019** [deepflowio/deepflow#7154]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

deepflow支持对接指定的链路后端进行存储，如jaeger

### Use case

我们自己的环境上已经有jaeger了，但是由于微服务过多，jaeger接入缓慢且链路信息不深入不完善，导致jaeger无法正常使用，希望能在deepflow基础上，将其采集到的更深更细的链路信息对接到jaeger中存储，不知道deepflow是否支持自定义链路存储对接?

### Related issues

没找到

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
Hello, you can refer to [this article](https://www.deepflow.io/docs/zh/integration/output/export/opentelemetry-exporter/) to export data to Jaeger via Deepflow-server. The exported data can be configured to remain in Deepflow using [this parameter](https://github.com/deepflowio/deepflow/blob/main/server/server.yaml#L383).

**Comment by xiaoyuan2019** [comment]
@1473371932 hello，deepflow-server error log：**unknown service opentelemetry.proto.collector.trace.v1.TraceService**
server config：
![image](https://github.com/deepflowio/deepflow/assets/48978805/a46f90b5-9147-499d-b41b-cc167ba11344)
server pod network test：
![image](https://github.com/deepflowio/deepflow/assets/48978805/71f38631-4c02-4a3c-a49f-c284139fe1e5)

**Comment by lzf575** [comment]
@xiaoyuan2019  server的日志报错的详细信息，尽量都返回下。 接收方有异常日志信息么。

**Comment by 1473371932** [comment]
Hello, you may refer to the [Jeager official documentation](https://www.jaegertracing.io/docs/1.58/deployment/#collector). The 14250 port is used by the Jeager agent for reporting data. If you need to import data externally to Jeager, the 4317 port should be used.
