### ISSUE TITLE
[FR]  外部ck ttl 删除很慢

### ISSUE THREAD

**Issue by yhcloud123** [deepflowio/deepflow#7254]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

![f25a1f14beea096c3ef757a21ed4708](https://github.com/deepflowio/deepflow/assets/110751250/6ff21a2a-f6de-48ba-9c12-c5618e531bac)
![aa6c066f1e79fc21e0666383914ff04](https://github.com/deepflowio/deepflow/assets/110751250/23ab02aa-d707-4352-a5d5-96480bbe2ec8)
有遇到过外部ck，ttl 3d到期实际删除很慢吗，对比两套环境一样的配置，采集数据量小的会严格遵循ttl，数据量大一点的的ck ttl到期会删除一小部分数据（如删除近10天随机过期数据），比如最开始几天的部分一直没有删除

或者可以测试建表设置参数ttl_only_drop_parts 会不会好点
这块有什么建议吗

### Use case

1

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
This may be a bug inherent in ClickHouse, occasionally failing to clean up as expected. You might try restarting ClickHouse to potentially resolve this issue. 
Note: If you are using an external ClickHouse and data storage exceeds 80%, DeepFlow-Server will not trigger automatic cleanup

**Comment by lzf575** [comment]
@yhcloud123  v6.5 和 main版本 新建表会增加ttl_only_drop_parts  这个配置了。  你也可以 手动修改表，加上这个配置看看，是否有效果。例如 `alter table flow_log.l7_flow_log_local MODIFY SETTING ttl_only_drop_parts=1;`
