### ISSUE TITLE
[BUG] minikube namespace can not be collect

### ISSUE THREAD

**Issue by a775189488** [deepflowio/deepflow#7454]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

集群中创建了多个 ns 和 pod。
- 在 Mysql Table 的 Pod Group 表上看到的 pod 信息是齐全的
- 在 K8S pod 和 K8S pod map 上只能看到 deepflow 本身的 pod 信息，使用 ns 过滤也没有其他 ns 信息

### How to reproduce

--

### DeepFlow version

server
```
Name: deepflow-server community edition
Branch: v6.5
CommitID: 2790cf80b74774192d99ea8f50bf4bbc6aae7f8f
RevCount: 10744
Compiler: go version go1.21.12 linux/amd64
CompileTime: 2024-07-17 17:44:01
```
agent
```
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
10714-059e91fe2a948611a7cf751c99b980f0fa632851
Name: deepflow-agent community edition
Branch: v6.5
CommitId: 059e91fe2a948611a7cf751c99b980f0fa632851
RevCount: 10714
Compiler: rustc 1.77.1 (7cf61ebde 2024-03-27)
CompileTime: 2024-07-16 11:03:57
```

### DeepFlow agent list

```
ID   NAME          TYPE     CTRL_IP        CTRL_MAC            STATE    GROUP     EXCEPTIONS   REVISION     UPGRADE_REVISION
1    minikube-V1   K8S_VM   192.168.49.2   02:42:c0:a8:31:02   NORMAL   default                v6.5 10714
```

### Kubernetes CNI

bridge

### Operation-System/Kernel version

```
centos7
3.10.0-1160.99.1.el7.x86_64
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yujianweilai** [comment]
请问这个问题，后来怎么解决的？我部署了v6.4 然后发现业务容器的信息能上送到deepflow，k8s的ns信息，pod信息，在grafana上看不到，如下图：
![image](https://github.com/user-attachments/assets/1b6820c6-fbd1-4624-baee-b88bde70116f)
