### ISSUE TITLE
deepflow-server API  should  add authentication[FR] 

### ISSUE THREAD

**Issue by wyf0520** [deepflowio/deepflow#7571]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

deepflow-server API  should  add authentication
eg:
http://${deepflow_server_node_ip}:${port}/v1/query/

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
The Community Edition does not have plans to support authentication. However, you can add a wrapper service layer to provide an authentication mechanism.
