### ISSUE TITLE
[FR] 腾讯云容器集群部署时候异常，无法用deepflow-ctl无法获取到信息

### ISSUE THREAD

**Issue by lynyuxuan** [deepflowio/deepflow#7615]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

腾讯云eks上面的容器服务集群。k8s是托管在腾讯的。环境涉及1.16,1.20,1.22,1.28版本

### Use case

参考部署文档里面的操作
https://www.deepflow.io/docs/zh/ce-install/managed-k8s/
执行命令deepflow-ctl 会报错
![image](https://github.com/user-attachments/assets/ddbd213b-0ee6-4873-9f23-167426ef11f5)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by lynyuxuan** [comment]
我通过server的服务里面去获取也拿不到对应信息
![image](https://github.com/user-attachments/assets/b6847dee-f983-41da-b52b-98adb20cf267)

**Comment by 1473371932** [comment]
你好，腾讯云 EKS 是 Serverless 类型的，需要用[这种方式](https://www.deepflow.io/docs/zh/ce-install/serverless-pod/)部署

**Comment by lynyuxuan** [comment]
> 你好，腾讯云 EKS 是 Serverless 类型的，需要用[这种方式](https://www.deepflow.io/docs/zh/ce-install/serverless-pod/)部署

是的目前我是用的这个类型的，已经部署上去了但是agent采集不到数据。是对cni的网络有要求吗。

我在容器内获取clustername:
![image](https://github.com/user-attachments/assets/9e40e690-4064-45bf-b9ff-7493ae23a99b)
helm upgrade 的配置
![image](https://github.com/user-attachments/assets/976f844f-602e-46be-8641-03b476b9a13f)
server日志，
![image](https://github.com/user-attachments/assets/505db332-8acb-4a66-a131-98a0ba5df208)
agent日志：
![image](https://github.com/user-attachments/assets/454f064d-5476-4a6e-bb32-b7f0f9bcd652)

**Comment by lynyuxuan** [comment]
![image](https://github.com/user-attachments/assets/92f30acd-aed7-4d09-a75a-4e7b0e684923)
查到到这2个表里面数据是空的

**Comment by 1473371932** [comment]
![Snipaste_2024-08-02_17-18-08](https://github.com/user-attachments/assets/01377748-fab6-4f4c-a302-d411170d8311)

你好，能否通过社区助手加一下社区群呢？直接在群里沟通会更方便，解决起来也会更快一些

**Comment by 1473371932** [comment]
总结：

1. deepflow-server 需要部署在可以获取 node 信息的集群中，当是部署在 serverless 中，获取不到主机信息，导致识别有问题
2. 按照 [Serverless](https://www.deepflow.io/docs/zh/ce-install/serverless-pod/) 流程部署，已无问题
