### ISSUE TITLE
[BUG] otel trace数据无法导入到deepflow

### ISSUE THREAD

**Issue by yujianweilai** [deepflowio/deepflow#7783]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

我的k8s系统里部署了otel-agent，然后参考https://www.deepflow.io/docs/zh/integration/input/tracing/opentelemetry/ 试图将otel采集到的trace数据传递给deepflow做汇总与展示。部署方式也是采用文档中推荐的“使用 agent 模式的 otel-collector 向 deepflow-agent 发送 trace 数据”。但是配置完成后，发现deepflow上，无法展示从otel-agent汇聚上来的业务trace信息，如下图：
![image](https://github.com/user-attachments/assets/8be66217-1d33-4026-b2f9-1f976261a708)

我通过https://www.deepflow.io/docs/zh/diagnose/FAQ/ 对部署进行了排查，发现下图高亮内容，我不满足
![image](https://github.com/user-attachments/assets/106dd93a-668c-443e-8065-6e04f72dc9ca)
我在deepflow-agent 这个pod所在宿主机上，执行netstat命令，确实没有38086端口的监听，但是每个节点的deepflow-agent pod也是启动正常的，没有报错。
![image](https://github.com/user-attachments/assets/8eb04558-9561-462e-8fb5-084e6af221fa)

[root@staging-cetccx-m3 ~]# deepflow-ctl agent-group-config list g-f0226f2a54 -o yaml
vtap_group_id: g-f0226f2a54
external_agent_http_proxy_enabled: 1
external_agent_http_proxy_port: 38086

otel-agent的日志，我总是看到“Preparing to make HTTP request”，然后后面就没有关于业务trace的输出信息了，如下图：
![image](https://github.com/user-attachments/assets/db6255f0-1f69-45df-b25a-68bd8418db97)

我也是第一次部署otel 和 deepflow，不知是配置的不对，还是程序有bug，还请专家们给指点一下，感谢。

以下是otel-collector的配置信息（因为我的k8s是1.19版本，所以我用的otel 版本是0.85.0）：
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: opentelemetry-operator-system
spec:
  mode: daemonset
  hostNetwork: true
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.85.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s
      # for deepflow
      k8sattributes:
        #auth_type: 'serviceAccount'
        #extract:
        #  metadata:
        #    - k8s.namespace.name
        #    - k8s.deployment.name
        #    - k8s.statefulset.name
        #    - k8s.daemonset.name
        #    - k8s.cronjob.name
        #    - k8s.job.name
        #    - k8s.node.name
        #    - k8s.pod.name
        #    - k8s.pod.uid
        #    - k8s.pod.start_time
        #filter:
        #  node_from_env_var: K8S_NODE_NAME
        #passthrough: false
        #pod_association:
        #  - sources:
        #      - from: resource_attribute
        #        name: k8s.pod.ip
        #  - sources:
        #      - from: resource_attribute
        #        name: k8s.pod.uid
        #  - sources:
        #      - from: connection
      resource:
        attributes:
          - key: app.host.ip
            from_attribute: k8s.pod.ip
            action: insert
      # end
    extensions:
      health_check:
    exporters:
      # 注意：在v0.86.0之前，请使用`logging`而不是`debug`。
      logging:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200
      # Data sources: traces
      #otlp:
      #  endpoint: "jaeger.default:4317"
      #  tls:
      #    insecure: true
      otlphttp:
        traces_endpoint: 'http://deepflow-agent.deepflow/api/v1/otel/trace'
        #endpoint: 'http://deepflow-agent.deepflow'
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
      #prometheusremotewrite:
      #  endpoint: http://prometheus-kube-prometheus-prometheus.monitoring:9090/api/v1/write
      #  tls:
      #    insecure: true
      #prometheus:
      # 暴露的prometheus export的url, 为自定义端口 
      #  endpoint: "http://10.100.220.62:9090/metrics"
      #  namespace: "default" # 要监控的命名空间
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [k8sattributes, resource, memory_limiter, batch]
          exporters: [otlphttp]
        #metrics:
        #  receivers: [otlp]
        #  processors: []
        #  exporters: [logging]
        logs:
          receivers: [otlp]
          processors: []
          exporters: [logging]
      telemetry:
        logs:
          level: "DEBUG"
          development: true
          encoding: "json"

### DeepFlow version

[root@staging-cetccx-master1 ~]# kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
Name: deepflow-server community edition
Branch: v6.5
CommitID: 9bb16a8ff644a9279300aa7220edcc2f21321d80
RevCount: 10821
Compiler: go version go1.21.13 linux/amd64
CompileTime: 2024-08-12 06:11:31
[root@staging-cetccx-master1 ~]# kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
10805-c6a440e933afb1de0242f55c7aecaa6e6086e69a
Name: deepflow-agent community edition
Branch: v6.5
CommitId: c6a440e933afb1de0242f55c7aecaa6e6086e69a
RevCount: 10805
Compiler: rustc 1.77.1 (7cf61ebde 2024-03-27)
CompileTime: 2024-08-07 05:01:34
[root@staging-cetccx-master1 ~]# 

### DeepFlow agent list

[root@staging-cetccx-master1 ~]# deepflow-ctl agent list
ID   NAME                        TYPE     CTRL_IP         CTRL_MAC            STATE    GROUP     EXCEPTIONS                    REVISION     UPGRADE_REVISION   
1    staging-cetccx-m3-V2        K8S_VM   10.100.220.54   00:50:56:81:02:d4   NORMAL   default                                 v6.5 10805                      
2    staging-cetccx-master1-V4   K8S_VM   10.100.220.63   00:50:56:81:1b:7a   NORMAL   default                                 v6.5 10812                      
12   staging-cetccx-nginx2-V3    K8S_VM   10.100.220.59   00:50:56:81:e5:01   NORMAL   default                                 v6.5 10805                      
13   staging-cetccx-nginx1-V1    K8S_VM   10.100.220.58   00:50:56:81:0a:0d   NORMAL   default                                 v6.5 10805                      
14   staging-cetccx-master2-V7   K8S_VM   10.100.220.64   00:50:56:81:29:89   NORMAL   default                                 v6.5 10812                      
15   staging-cetccx-master3-V8   K8S_VM   10.100.220.65   00:50:56:81:8b:bf   NORMAL   default                                 v6.5 10812                      
16   staging-cetccx-m1-V6        K8S_VM   10.100.220.53   00:50:56:81:94:8f   NORMAL   default                                 v6.5 10822                      
17   staging-cetccx-m2-V5        K8S_VM   10.100.220.62   00:50:56:81:ad:1a   NORMAL   default   SYSTEM_LOAD_CIRCUIT_BREAKER   v6.5 10812                      
[root@staging-cetccx-master1 ~]# 

### Operation-System/Kernel version

[root@staging-cetccx-master1 ~]# awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"CentOS Linux 7 (Core)"
[root@staging-cetccx-master1 ~]# uname -r
5.16.13-1.el7.elrepo.x86_64
[root@staging-cetccx-master1 ~]# 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Fancyki1** [comment]
编辑一下信号源？查一下试试
![70c33659-3f1e-4f72-b920-b59ff4b31355](https://github.com/user-attachments/assets/248a6eb3-766a-449e-9a55-9f9346c89f47)

**Comment by yujianweilai** [comment]
> 编辑一下信号源？查一下试试 ![70c33659-3f1e-4f72-b920-b59ff4b31355](https://private-user-images.githubusercontent.com/22786883/357081511-248a6eb3-766a-449e-9a55-9f9346c89f47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MTI5NjgsIm5iZiI6MTcyMzUxMjY2OCwicGF0aCI6Ii8yMjc4Njg4My8zNTcwODE1MTEtMjQ4YTZlYjMtNzY2YS00NDllLTlhNTUtOWY5MzQ2Yzg5ZjQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDAxMzEwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YTYzMWUwOTQzMmFiZTQ4NmNjZWEwMGRjYmRlYzNhOWQ0ZjI3NjQ2MGNmNGZjYzE5NjZmYzliM2MyMDlmY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RPVQ1vKWJXYUQc6EoL1_JxoxOjItnvG8L0VBGhFj0hI)

非常感谢您的关注与回复。
我尝试在数据源里增加了您截图里的otel条件，确实可以查出数据来，如下：
![image](https://github.com/user-attachments/assets/29f4f10c-2484-426e-ae07-682063c03117)
所以，我理解otel的遥测数据，确实已经传到了deepflow了，连通性上是没有问题的，对吗？
但是，虽然有otel数据传上来，但似乎数据不全。上图的cx-oss和cx-job 这些确实是我的应用程序，但是我试着操作了几个其他微服务的业务动作，却查询不到相关微服务的otel数据，我所有的微服务编排文件，都统一加了annotations ，如下图，
![image](https://github.com/user-attachments/assets/d43ecd25-0652-4748-ac7d-9d0b86b176ec)

为何有的微服务trace数据传不上来呢 ？用otel-agent还需要改业务代码吗？

**Comment by yujianweilai** [comment]
> @yujianweilai 不需要改业务代码，你的数据量（速率）有多大？是不是 otel-agent 丢数据了，另外也可看看 deepflow 侧是否有 alert：
> 
> https://ce-demo.deepflow.yunshan.net/d/DeepFlow_Alert_Analysis/deepflow-alert-analysis?orgId=1

感谢向阳大佬的回复。
我是在公司一套全新的测试环境里，部署的deepflow，这套环境还没有业务接入。20+个业务容器，目前出于空转的状态。
我参考：https://www.deepflow.io/docs/zh/diagnose/how-to-profile-deepflow-server-ingester/ 查了一下，结果如下
-- 单个 clickhouse 的接收性能：
<img width="598" alt="image" src="https://github.com/user-attachments/assets/d3480fde-ecb9-4e93-bdc7-0bd4f471f61a">

-- server 每秒平均写入 clickhouse 数据（官方文档中的sql ，数据库不存在）
![image](https://github.com/user-attachments/assets/fe65fc93-88fd-46f4-8215-f83aa3da0fe7)

-- server 丢包队列查看方式（官方文档中的sql ，数据库不存在）
![image](https://github.com/user-attachments/assets/68460007-6c0c-4e17-a401-022c80bca555)
![image](https://github.com/user-attachments/assets/15f385be-2e14-4a5e-8a25-12bca16b8dab)

grafana 上alert有数据的，我都截图了，如下： 
![image](https://github.com/user-attachments/assets/6c80934d-5a58-4caa-917c-cf96a932d53f)
![image](https://github.com/user-attachments/assets/9ee53a11-066e-4601-a800-a9bf85b956c1)
![image](https://github.com/user-attachments/assets/65e4ef7b-a77a-48c8-ac93-3f46090edbce)
![image](https://github.com/user-attachments/assets/561ceebd-b4c5-434a-bce4-06c8655e5179)
![image](https://github.com/user-attachments/assets/ff082b48-7c64-47e9-bba4-1415671de57e)
![image](https://github.com/user-attachments/assets/962c4e63-b2d2-4d3e-8a1d-d79de3ee1f81)
![image](https://github.com/user-attachments/assets/9ab33a19-648c-445b-a33b-6c8f49b587f1)

我现在的情况就是20几个业务容器的otel数据，有三四个微服务的otel数据，能在grafana上显示出来（通过增加筛选条otel信号源的过滤），然后我把业务容器重启后，之前的三四个微服务otel数据，又换成其他微服务了，把我整不会了。。。 请研发老师们给分析分析，感谢。
![image](https://github.com/user-attachments/assets/3faef4cd-9784-4b93-be38-886af6c9b4d2)

**Comment by yujianweilai** [comment]
我今天用 v6.4.013版本试了一下，同样存在部分业务容器otel采集数据，在grafana上查询不到的情况：
<img width="803" alt="image" src="https://github.com/user-attachments/assets/5aae80f3-92ea-4de6-9723-1d670d12779d">

**Comment by 1473371932** [comment]
你好，从 otel 日志来看，并没有看出什么具体报错，可以按照下图查询一下是否有非 Success 的状态
![Snipaste_2024-08-17_20-43-45](https://github.com/user-attachments/assets/c69cf77a-ea7d-4aed-98f7-0c89dfd1cf8b)

以及，目前已经发送到 deepflow 中的这部分 otel 数据，你点击具体的 span 后绘制出来的火焰图是否能与 deepflow 的数据相结合？

**Comment by yujianweilai** [comment]
> 你好，从 otel 日志来看，并没有看出什么具体报错，可以按照下图查询一下是否有非 Success 的状态 ![Snipaste_2024-08-17_20-43-45](https://private-user-images.githubusercontent.com/84362246/358845907-c69cf77a-ea7d-4aed-98f7-0c89dfd1cf8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzI1MzIsIm5iZiI6MTcyNDAzMjIzMiwicGF0aCI6Ii84NDM2MjI0Ni8zNTg4NDU5MDctYzY5Y2Y3N2EtZWE3ZC00YWVkLTk4ZjctMGM4OWRmZDFjZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAxNTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MzE5MWY2YTI1OGUwYjg2MjhkOGQzYmU5MDY4Zjk4MGJmYzg0OWNhZDdhM2RkYjM1YjRmY2RmM2ZmNDM2YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1x7MnsDdgU4VVNGLnhPSRK3X07PbBnHfrgzAMPVO5eA)
> 
> 以及，目前已经发送到 deepflow 中的这部分 otel 数据，你点击具体的 span 后绘制出来的火焰图是否能与 deepflow 的数据相结合？

您的截图，我无法点击打开看大图，所以看不清里面的内容，能否重发一下截图，谢谢了

**Comment by yujianweilai** [comment]
> 你好，从 otel 日志来看，并没有看出什么具体报错，可以按照下图查询一下是否有非 Success 的状态 ![Snipaste_2024-08-17_20-43-45](https://private-user-images.githubusercontent.com/84362246/358845907-c69cf77a-ea7d-4aed-98f7-0c89dfd1cf8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzI1MzIsIm5iZiI6MTcyNDAzMjIzMiwicGF0aCI6Ii84NDM2MjI0Ni8zNTg4NDU5MDctYzY5Y2Y3N2EtZWE3ZC00YWVkLTk4ZjctMGM4OWRmZDFjZjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAxNTAzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MzE5MWY2YTI1OGUwYjg2MjhkOGQzYmU5MDY4Zjk4MGJmYzg0OWNhZDdhM2RkYjM1YjRmY2RmM2ZmNDM2YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1x7MnsDdgU4VVNGLnhPSRK3X07PbBnHfrgzAMPVO5eA)
> 
> 以及，目前已经发送到 deepflow 中的这部分 otel 数据，你点击具体的 span 后绘制出来的火焰图是否能与 deepflow 的数据相结合？

按您提供的截图，我查了，没有任何日志：
![image](https://github.com/user-attachments/assets/f1b5c95f-f3fd-403c-b174-5e09fc251ce6)

下面两张截图是我随机点了两个traceid，展示的火焰图：
![image](https://github.com/user-attachments/assets/41406b48-e62e-49dc-a5b8-06df26634607)
![image](https://github.com/user-attachments/assets/307e6fa3-0e64-4fd8-b2d0-bafcd1fe5154)

**Comment by yujianweilai** [comment]
@1473371932  请问我们deepflow对于otel-agent的版本有要求吗？ 因为我的k8s集群是1.19版本，所以能用的otel-agent最高版本是0.85.0

**Comment by yujianweilai** [comment]
我打开了otel-agent debug，从日志中找到一个deepflow中查不到otel trace的服务日志，见附件：
[cx-auth服务的trace信息.txt](https://github.com/user-attachments/files/16668614/cx-auth.trace.txt)
从中选取了一个traceid d697ed17f1772d0b09afbeccd983731c ，然后又找了一条可以在deepflow中查到otel trace信息的另外一个服务的traceid 3806b39dd413d424ba587a11e6512bff
将这两个id去clickhouse中查询，并将结果导出html，如下：
[20240820-114502.zip](https://github.com/user-attachments/files/16668775/20240820-114502.zip)
比较两条信息的查询结果看，grafana上查不到otel-trace的那条信息，其实已经入库到clickhouse了，但是这条记录中，我标出的字段，没有关联到必要得信息，所以展示不出来，如下图：
![image](https://github.com/user-attachments/assets/5c28e0bd-8f9e-4177-a95c-07484e72f353)

这个问题，我已经能查到这里了，具体为何otel上来的信息，deepflow没有关联到必要的信息，还请deepflow研发老师给分析一下，谢谢。
@1473371932

**Comment by yujianweilai** [comment]
原因已找到，是因为app 通过otel-svc 发送数据给 otel，由于svc负载均衡模式，导致当前节点 app 发送的数据，可能被负载均衡到其他 node 上的 otel-agent，中间经过一层转换，传到 otel 的数据就从 pod ip 变成 node ip 了，deepflow 就没法在 pod 字段关联这些信息。
解决办法：
一是，k8s v1.26版本支持为服务设置internalTrafficPolicy=Local参数，实现服务的内部流量，优先在当前地节点内部进行流转。 参考：https://kubernetes.io/zh-cn/blog/2022/12/30/advancements-in-kubernetes-traffic-engineering/
二是，在业务容器中，注入所在节点的NODE_IP，然后将my-instument中，endpoint改为http://$(my_node_ip):4317 ，这样，每个容器启动时，会将自己当前所在节点IP，注入给OTEL_EXPORTER_OTLP_ENDPOINT环境变量，实现链路调用数据，只发给本节点的otel-collector。
![image](https://github.com/user-attachments/assets/93a39137-cf3e-484e-b8da-f28b2e54f8f1)

感谢deepflow的研发 @1473371932
