### ISSUE TITLE
[FR] 关于controller表跟analyzer表中的vtap_max字段的疑问

### ISSUE THREAD

**Issue by zcl1115** [deepflowio/deepflow#7796]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我发现controller表中vtap_max字段是2000，然后analyzer表中是200，我们目前灰度的机器已经达到1100+，但是我们发现一些机器，在一开始安装的时候，我们通过deepflow-ctl agent list能够获取到，然后过了一段时间后我们再通过deepflow-ctl agent list就无法获取到了，deepflow-ctl 获取的agent数量大概常驻在700+，我们的server是三个节点，是不是存在数目上的影响

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
问题总结：
目前 3 server 配置为 8c 25g，通过 deepflow server 面板看出资源使用已到瓶颈，3 server 对应 1100+ agent 比例过大，并且 server 资源也不够，导致丢失了很多 agent，我们更建议 1 server 对应 200 内的 agent，并且需要根据 server 资源使用情况调整他的资源上限
