### ISSUE TITLE
[FR] CK 查询接口速度优化

### ISSUE THREAD

**Issue by WongLoKat** [deepflowio/deepflow#7816]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

针对简单的 SQL 语句查询，希望直接提供一个 simple_query 接口，不再针对简单 sql 执行完整的 sql 解析流程

### Use case

CK 查询时，针对 select 所需要查询的字段，会遍历所有字段都执行 GetTagDescriptions() 方法，而 GetTagDescriptions() 方法本身又会进行多次 CK 查询，导致速度很慢
![1](https://github.com/user-attachments/assets/73b3818f-1e06-4caf-9270-d9f5509a4a83)

尤其在火焰图场景下，因为火焰图查询所有相关联的 l7_flow_log 时允许循环 30 次，导致进行大量 CK 查询

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yujianweilai** [comment]
我这边遇到的现象是：点击一个traceid，展示火焰图时，要等待一段时间，才能出图。是你说的这个原因吗

**Comment by WongLoKat** [comment]
> 我这边遇到的现象是：点击一个traceid，展示火焰图时，要等待一段时间，才能出图。是你说的这个原因吗

是的，除了这个，还有 deepflow-app 查询也不是很快的原因，这 2 个 issue 他们都已经在处理了

**Comment by yujianweilai** [comment]
> > 我这边遇到的现象是：点击一个traceid，展示火焰图时，要等待一段时间，才能出图。是你说的这个原因吗
> 
> 是的，除了这个，还有 deepflow-app 查询也不是很快的原因，这 2 个 issue 他们都已经在处理了

收到。多谢。

**Comment by yujianweilai** [comment]
另外，请问一下，火焰图中，有空行，类似下图这样，你那边有吗？ 这是什么原因了解吗
![image](https://github.com/user-attachments/assets/f6255938-2505-4df7-97ec-7009d92fcc5f)

**Comment by WongLoKat** [comment]
> 另外，请问一下，火焰图中，有空行，类似下图这样，你那边有吗？ 这是什么原因了解吗 ![image](https://private-user-images.githubusercontent.com/38240590/366364597-f6255938-2505-4df7-97ec-7009d92fcc5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNDYxODAsIm5iZiI6MTcyNjA0NTg4MCwicGF0aCI6Ii8zODI0MDU5MC8zNjYzNjQ1OTctZjYyNTU5MzgtMjUwNS00ZGY3LTk3ZWMtNzAwOWQ5MmZjYzVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTExVDA5MTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMWMxYzVmZWNiYjZlMzk0NzRhMTM0OTg4NWNiZDE1MzNhYzljZTU4ZDI4ZGJmZTVmZWI1YjNiOGNmMDdkZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XGEDnUqKTqtSqHtVmkH6sbt1q3PJ9aRuWnsH6Ulok4U)

也有，可能是没采集到，或者采集到但传输到 server 端数据丢了

**Comment by 1473371932** [comment]
在 v6.5 版本时，我们做了两个查询优化，不过上周我们已经发布了 v6.6 LTS 版本，我建议可以先升级到 v6.6 版本后再测试一下新版本的查询速度是否符合预期：

https://github.com/deepflowio/deepflow-app/issues/287
