### ISSUE TITLE
[QA] 如何评估deepflow的资源占用情况

### ISSUE THREAD

**Issue by yujianweilai** [deepflowio/deepflow#7846]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

产线上一个新组件前，通常需要评估一下该组件的资源占用情况，比如：内存、CPU、磁盘等。
# 1 关于内存cpu资源占用
我在https://github.com/deepflowio/deepflow/issues/7279里看到研发给的配置建议，如下图：
![image](https://github.com/user-attachments/assets/5b26b2ab-bfdb-42f2-b220-369cc7072341)
我的问题
1. 这个“50-100个业务节点，需要1台server跑deepflow”结论，是基于这些业务节点上运行多少个业务容器副本，所进行的推算呢？
2. “50-100个业务节点，需要1台server跑deepflow”，这台server上可以跑deepflow的所有组件吗，比如：同时运行deepflow-server和clickhouse
3. 50个业务节点以下的场景，运行deepflow的主机，有配置建议吗？比如：20个节点，deepflow主机8c32G可以吗？

# 2 关于磁盘资源占用
我在https://www.deepflow.io/docs/zh/best-practice/reduce-storage-overhead/ 看到有关如何降低存储使用的说明，我的问题是：
我们如何在上生产之前，预估一下大致的存储占用，以便在给deepflow创建云主机时，分配相应空间的存储资源。
我能想到的是，上生产前先在测试环境（业务容器空转运行），部署一套deepflow，然后基于产线一天的数据量，进行一次压测，然后再看磁盘占用？不知道我的办法是否科学可行？ 或者deepflow有更合理的评估方案？

# 3 关于带宽消耗
 有关带宽消耗，我们该如何评估。

谢谢。

### Use case

希望技术老师们，基于Description描述的内容，给出解答，谢谢。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
你好，一般来说评估存储量我们建议先在环境中部署一天 deepflow 后，根据[此文章](https://www.deepflow.io/docs/zh/best-practice/reduce-storage-overhead/)中提供的 SQL 语句来查看一天内存了多少数据，例如数据总量、单独某个协议存了多少行等等...我们没有办法在不知道你们数据量的情况下推断应该预留多少存储空间
对于 agent、server 使用的资源来说也是这样，在部署后，有专门的 server、agent 面板来查看当前的资源消耗，根据当前的使用情况来调整分配的资源

**Comment by yujianweilai** [comment]
> 你好，一般来说评估存储量我们建议先在环境中部署一天 deepflow 后，根据[此文章](https://www.deepflow.io/docs/zh/best-practice/reduce-storage-overhead/)中提供的 SQL 语句来查看一天内存了多少数据，例如数据总量、单独某个协议存了多少行等等...我们没有办法在不知道你们数据量的情况下推断应该预留多少存储空间 对于 agent、server 使用的资源来说也是这样，在部署后，有专门的 server、agent 面板来查看当前的资源消耗，根据当前的使用情况来调整分配的资源，其实图中提到的也只是一个建议，具体还是要根据真实的情况来。 8c32g 对应 20 个 agent 一般来说是没问题的，另一方面可以加一下我们开源社群，这个问题也能更方便的交流 ![image](https://private-user-images.githubusercontent.com/84362246/358845485-ea695f2c-3d9f-42c2-bf8f-0ce9a4d72ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyOTA2ODcsIm5iZiI6MTcyNDI5MDM4NywicGF0aCI6Ii84NDM2MjI0Ni8zNTg4NDU0ODUtZWE2OTVmMmMtM2Q5Zi00MmMyLWJmOGYtMGNlOWE0ZDcyZWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDAxMzMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMzcyMmE0MmJkZjI4YWIzNzFmYmJlOGY4Njg0YTRjM2EzOGVhNTMzM2VkMzM3Y2VkZTljN2VmMTQyMjdlYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WcA3MkeFuXBe7hf7CgVX4-NqtnC76LiZwfIkiRDurbU)

我加了，请通过一下，谢谢。

**Comment by yujianweilai** [comment]
我参考https://www.deepflow.io/docs/zh/best-practice/reduce-storage-overhead/ 进行数据存储的评估。
请问，查询后得到的“压缩后总大小”和我clickhouse所占用宿主机磁盘大小是差不多的，那这个sql查询结果中，“压缩前总大小”又表示什么意思呢？
<img width="772" alt="image" src="https://github.com/user-attachments/assets/89420293-c0e4-4aa7-bd9a-eeedc539e582">
![image](https://github.com/user-attachments/assets/fc5b8536-825b-4b92-bcc4-4efc1f45dd72)
