### ISSUE TITLE
[QA] 6.5.4 版本 agent 没有上报 pod 中第二张网卡的流量，deepflow-agent 在采集完 网卡数据后，会过滤掉第二张网卡的流量？过滤逻辑是什么，对应agent代码大概是哪部分？

### ISSUE THREAD

**Issue by wlooppy** [deepflowio/deepflow#7881]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by sharang** [comment]
@wlooppy 你使用的是什么 cni？贴一下 k8s node 上的 ip addr 输出、pod 内部的 ip addr 输出 看看。

**Comment by wlooppy** [comment]
感谢回复，用的是 kube-ovn
pod1 ：
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
10817: eth0@if10818: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 00:00:00:34:0c:9a brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.10.202.136/16 brd 172.10.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd00:10:16::2e/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe34:c9a/64 scope link
       valid_lft forever preferred_lft forever
10819: net1@if10820: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 00:00:00:86:8d:ea brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.199.22/24 brd 172.18.199.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe86:8dea/64 scope link
   
   第二张网卡 对应 node 网卡（veth）
# ip a s c670274e_net1_h
10820: c670274e_net1_h@if10819: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master ovs-system state UP group default qlen 1000
    link/ether 42:e0:f8:4a:4d:8b brd ff:ff:ff:ff:ff:ff link-netns cni-edfe21aa-24fb-816b-506c-8c5521d8f2fa
    inet6 fe80::40e0:f8ff:fe4a:4d8b/64 scope link
       valid_lft forever preferred_lft forever
  =================
  pod2:
  1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
10775: eth0@if10776: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 00:00:00:bc:38:52 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.10.198.16/16 brd 172.10.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd00:10:16::175a/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:febc:3852/64 scope link
       valid_lft forever preferred_lft forever
10777: net1@if10778: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 00:00:00:26:97:67 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.18.199.20/24 brd 172.18.199.255 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe26:9767/64 scope link
       valid_lft forever preferred_lft forever
       
第二张网卡对应 node 网卡（veth）
# ip a s f31c2ab6_net1_h
10778: f31c2ab6_net1_h@if10777: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master ovs-system state UP group default qlen 1000
    link/ether 22:57:56:e7:46:10 brd ff:ff:ff:ff:ff:ff link-netns cni-23e239e6-97e8-fa69-e709-2df74bbd8d95
    inet6 fe80::2057:56ff:fee7:4610/64 scope link
       valid_lft forever preferred_lft forever
================
pod1 和 pod2 在同一节点； 使用 172.18.199.20（pod2 第二张网卡） ping  172.18.199.22 （pod1 第二张网卡），agent 没有上报对应流量

**Comment by sharang** [comment]
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L114

```yaml
# Regular Expression for TAP (Traffic Access Point)
# Length: [0, 65535]
# Default:
#   Localhost:   lo
#   Common NIC:  eth.*|en[osipx].*
#   QEMU VM NIC: tap.*
#   Flannel:     veth.*
#   Calico:      cali.*
#   Cilium:      lxc.*
#   Kube-OVN:    [0-9a-f]+_h$
# Note: Regular expression of NIC name for collecting traffic
#   When the `tap_interface_regex` is not configured, it indicates
#   that network card traffic is not being collected.
tap_interface_regex: ^(tap.*|cali.*|veth.*|eth.*|en[osipx].*|lxc.*|lo|[0-9a-f]+_h)$
```

在 agent-grouop-config 中对 tap_interface_regex 增加一下 `f31c2ab6_net1_h` 对应的正则 `[0-9a-f]+_net1_h`。

默认配置中有 `[0-9a-f]+_h`，但缺少了 Pod 第二块网卡对应的 `[0-9a-f]+_net1_h`
