### ISSUE TITLE
[FR] 如何使用trace id，串联整个链路数据

### ISSUE THREAD

**Issue by qiaozeguang** [deepflowio/deepflow#7887]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

在Deepflow使用的过程中，我们发现，有时候Deepflow火焰图，与skywalking的span无法完美匹配，如下是个示例:

skywalking采集的span如下：
<img width="713" alt="image" src="https://github.com/user-attachments/assets/6807666a-413a-4d2c-ab75-d857ca3d3a13">

Deepflow的火焰图如下：
![image](https://github.com/user-attachments/assets/1e943ede-3d3e-495a-8981-d0f2454bb246)

在上面的示例中，很明显Deepflow缺少MySQL相关的span。
因此，我们想抛开火焰图，直接从clickhouse数据库中，查询数据，以确认是数据问题，还是前端问题。

<img width="253" alt="image" src="https://github.com/user-attachments/assets/17a1e125-3dcf-4902-915b-3279f131e01f">

我们参考如上视频，发现会查到不相关的trace id数据

<img width="1184" alt="image" src="https://github.com/user-attachments/assets/831fda2c-a03b-4f9a-baf5-934470b8589f">

https://github.com/deepflowio/deepflow-app/blob/main/app/app/application/l7_flow_tracing.py
上面这个文件，有查询数据的逻辑
但是代码太多了，也不是很懂Python，从代码梳理数据查询逻辑，成本比较高

能否将上面的代码逻辑，整理成文档，然后我们参考文档，查询数据，最终达到辅助定位问题的目的

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by taloric** [comment]
> ### Search before asking
> * [x]  I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.
> 
> ### Description
> 在Deepflow使用的过程中，我们发现，有时候Deepflow火焰图，与skywalking的span无法完美匹配，如下是个示例:
> 
> skywalking采集的span如下： <img alt="image" width="713" src="https://private-user-images.githubusercontent.com/26568487/359384598-6807666a-413a-4d2c-ab75-d857ca3d3a13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDE4MzcsIm5iZiI6MTcyNDE0MTUzNywicGF0aCI6Ii8yNjU2ODQ4Ny8zNTkzODQ1OTgtNjgwNzY2NmEtNDEzYS00ZDJjLWFiNzUtZDg1N2NhM2QzYTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA4MTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2YmU3Y2NkMzdkMzcwNDUzZWE5NjgyY2E4YjYwMjE4NWYxYmM0M2U0ZmE0NWEwNjI3OGMzYTYxZWM0YzU5Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aeI9HM-ybae_ilL4EIudxpQ-Tq-CBkFDcc53fuQy2AQ">
> 
> Deepflow的火焰图如下： ![image](https://private-user-images.githubusercontent.com/26568487/359384816-1e943ede-3d3e-495a-8981-d0f2454bb246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDE4MzcsIm5iZiI6MTcyNDE0MTUzNywicGF0aCI6Ii8yNjU2ODQ4Ny8zNTkzODQ4MTYtMWU5NDNlZGUtM2QzZS00OTVhLTg5ODEtZDBmMjQ1NGJiMjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA4MTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOWZjOGRlNDA1MmZiZTg1MDk1M2RiY2FhMWNlMjZiOWRjOTJlOWY5N2ZmMzk2MThkZTYyOGVjYTliYTAzNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rSQDynRH-nKakY7Cz2th5opZAPH-5GBrxaJ0zKRxV_E)
> 
> 在上面的示例中，很明显Deepflow缺少MySQL相关的span。 因此，我们想抛开火焰图，直接从clickhouse数据库中，查询数据，以确认是数据问题，还是前端问题。
> 
> <img alt="image" width="253" src="https://private-user-images.githubusercontent.com/26568487/359385845-17a1e125-3dcf-4902-915b-3279f131e01f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDE4MzcsIm5iZiI6MTcyNDE0MTUzNywicGF0aCI6Ii8yNjU2ODQ4Ny8zNTkzODU4NDUtMTdhMWUxMjUtM2RjZi00OTAyLTkxNWItMzI3OWYxMzFlMDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA4MTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NGU5NzNhM2ZlM2E0YTdhZDQ1NzYzMDQ5OGE0YzU5NWIzNzFlODI3MzAyNmMxODY5MjEwNTc1NzdmNjlhOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TI2IGwL8OAUP1RE7eyvYRIc1rKaEsN_nOHzGvGPtDXI">
> 我们参考如上视频，发现会查到不相关的trace id数据
> 
> <img alt="image" width="1184" src="https://private-user-images.githubusercontent.com/26568487/359386491-831fda2c-a03b-4f9a-baf5-934470b8589f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQxNDE4MzcsIm5iZiI6MTcyNDE0MTUzNywicGF0aCI6Ii8yNjU2ODQ4Ny8zNTkzODY0OTEtODMxZmRhMmMtYTAzYi00ZjlhLWJhZjUtOTM0NDcwYjg1ODlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIwVDA4MTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2ZThlYzJiZDg5ZDFhMTQyNDQyNGMyMTljNDU3YjlmNDBmY2ZmYmU4NDBjMmQ1M2Q0Y2Y2YmE3ZjY4MDYyNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vOdpnKoJzjpIsiBPwVYPxvPKOakY9hdvllg1LP10-2s">
> https://github.com/deepflowio/deepflow-app/blob/main/app/app/application/l7_flow_tracing.py 上面这个文件，有查询数据的逻辑 但是代码太多了，也不是很懂Python，从代码梳理数据查询逻辑，成本比较高
> 
> 能否将上面的代码逻辑，整理成文档，然后我们参考文档，查询数据，最终达到辅助定位问题的目的
> 
> ### Use case
> _No response_
> 
> ### Related issues
> _No response_
> 
> ### Are you willing to submit a PR?
> * [x]  Yes I am willing to submit a PR!
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

@qiaozeguang 中间这里的完整查询语句，先直接用 trace_id = xxx 来查询；另外即使通过其他关联条件查到了不相关的 trace_id，也会在 [这个位置](https://github.com/deepflowio/deepflow-app/blob/main/app/app/application/l7_flow_tracing.py#L406-L420) 清理掉不相关的数据，不会影响结果

文档的问题，可以先参考如下文档(细节可能有些过时，但大致逻辑不变)：[HOW-TO-GET-SPAN-LIKE-DATA](https://github.com/deepflowio/deepflow-app/blob/main/HOW-TO-GET-SPAN-LIKE-DATA.md)

关联关系是层层递进的：
1. 先搜索出同一个 trace_id 的数据；(trace_id = xx)
2. 基于搜索出的 trace_id，搜索出 syscall_trace_id / tcp_seq / x_request_id 关联的数据 (syscall=xx or tcp_seq=xx or x_request_id=xx)
3. 基于 2 ，继续迭代，直至全部关联数据被查出

对于 issue 提到的 mysql 场景，如果导入了 App Span，直接用 trace_id 查询即可；
如果没有导入 App Span，可以找到发起请求 网络 span 的 tcp_seq，从图上看应该是 getLastLog(?)，使用它的 tcp_seq 来尝试查询看能否找到 mysql 的 net span 与 sys span
