### ISSUE TITLE
[QA] 为什么 Ingress 观测必须是 hostNetwork=true ？ 

### ISSUE THREAD

**Issue by ZhuoZhuoCrayon** [deepflowio/deepflow#7923]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

如题

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
此处理解有些歧义，正确的是：
如果 ingress pod 使用 hostnetwork=true，我们就不能看到他的数据，因为如果 pod 使用宿主机网络，我们看到的是宿主机信息，无法获取 pod 信息
