### ISSUE TITLE
[FR] 优化agent ebpf map内存占用

### ISSUE THREAD

**Issue by qyzhaoxun** [deepflowio/deepflow#8028]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

deepflow-agent ebpf collect启动后会初始化大量ebpf map，在不同配置下有些map可能并不会使用到，另外有些map初始化的size较大，在使用sidecar模式下会占用大量内存。这里基于6.6.4实际测试了没有部署和实际部署前后的内存占用区别，内存相差135M，其中agent内存占用大概60M，ebpf map初始化占用70-80M
<img width="369" alt="企业微信截图_d732099e-ec13-4350-b1af-dcd398dce4f5" src="https://github.com/user-attachments/assets/72874830-ab79-4bfb-b547-71308eb22f7c">
<img width="396" alt="企业微信截图_2e11115c-cd39-46ff-9692-3b8f70f121dd" src="https://github.com/user-attachments/assets/6c7e4c74-8507-462e-9af0-36ba2c915357">

### Use case

看到deepflow中大量采用了array和hash map，希望能针对sidecar模式降低array size，并且针对hash map支持非预占用模式，希望内存占用初始值可以在20M以内

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by qyzhaoxun** [comment]
https://github.com/qyzhaoxun/deepflow/commit/47d08d0fd9054598cbfad87a9648a7826a42eb72

**Comment by yinjiping** [comment]
@qyzhaoxun 
max-socket-entries,socket-map-max-reclaim,max-trace-entries，这些设置是支持的最大链接（socket）数量，ebpf map size缩小，而当前节点的实际业务流量（链接数）大于ebpf map size的大小，这时候ebpf map 时间比较老的链接（socket）就会被刷掉，这样以来本来同一条数据流的数据，就会分成两个或多个不同的数据流的数据，极端情况下可能请求响应无法聚合。

我们希望尽量避免上面情况发生，所以把范围设置大了一些，但是确实没有考虑到kernel的内存占用过多的情况，这个我们会调进行下调放宽这个范围。

感谢您提的这个问题，我们会做个整体优化在map方面。

**Comment by qyzhaoxun** [comment]
这里hash_map如果换成lru_hash_map会不会更好些？另外size缩小后会有什么风险吗？

**Comment by yinjiping** [comment]
> 这里hash_map如果换成lru_hash_map会不会更好些？另外size缩小后会有什么风险吗？

lru_hash_map 在hash map中性能比较差，我们没有选用。目前的socket 和 trace hash map有回收机制
https://github.com/deepflowio/deepflow/blob/main/agent/src/ebpf/user/socket.c#L1193

size缩小后，如果你的环境流量很大， 可能会频繁触发回收机制，挤出比较老的socket记录，严重可能会使得新链接无法加入到socket hash中，还是需要根据实际环境的流量酌情设置这个值。

**Comment by qyzhaoxun** [comment]
这块咱们有计划优化下 ebpf map 的内存占用吗？

**Comment by yinjiping** [comment]
@qyzhaoxun 已在TODO里面，预计在月底（9月份）提交优化。

**Comment by qyzhaoxun** [comment]
这块优化的方案是咋样的，可以大致分享下吗？

**Comment by yinjiping** [comment]
可能会在下面几点进行优化：
- 增加map大小配置选项
- 如果一些功能不启用，比如UPROBE/on-cpu Profile/off-cpu profile/memory profile等，就不创建相关联的map，避免内存占用。
- 对于hash类型的map，添加配置项用于选择预先分配内存还是用时现申请。

上面是大致思路

**Comment by yinjiping** [comment]
**目前做了下面的优化：**
- 禁用预分配内存
  - PR：https://github.com/deepflowio/deepflow/pull/8236
  - 当完整的map预分配过于昂贵时，将 `map_prealloc_disabled` 设置为 true 可以防止在定义map时进行内存预分配，但这可能会导致一些性能下降。此配置仅适用于 `BPF_MAP_TYPE_HASH` 类型的 map。目前适用于 socket trace 和 uprobe Golang/OpenSSL trace 功能。禁用内存预分配大约会减少45M的内存占用。
  - 配置选项：static_config.ebpf.map-prealloc-disabled （默认为false）
- 调整了消耗内存比较多的配置项的取值范围
  - PR https://github.com/deepflowio/deepflow/pull/8239
  - static_config.ebpf.max-socket-entries
    - 取值范围： [10000, 2000000]
  - static_config.ebpf.socket-map-max-reclaim
    - 取值范围： [8000, 2000000]
  - static_config.ebpf.max-trace-entries
    - 取值范围： [10000, 2000000]
- eBPF Maps和功能模块关联，实现当某个功能模块禁用时Maps占用的内存以最少量占用。
  - PR https://github.com/deepflowio/deepflow/pull/8243
  
**测试情况：**
Memory usage of maps corresponding to eBPF capabilities in DeepFlow:

| Uprobe Trace [1]  | Continuous Profile | Pre-allocating Memory| Dwarf Unwinding [1] |Memory used (Bytes)|
 | ----------------------- | --------------------------| ----------------------|---|---|
 |  Disable |  Disable |Disable |Disable | 13,674,008|
| **Enable** | Disable  | Disable |Disable | 30,909,632|
 |  Disable  | **Enable**  | Disable |Disable | 31,731,736|
| Disable  | Disable  | **Enable** |Disable|59,557,832|
| Disable  | **Enable**|Disable  |**Enable [2]**|182,281,992|
| Disable  | **Enable**|**Enable**  |**Enable [2]**|228,165,816|
| **Enable**  | **Enable**|**Enable**  |**Enable [2]**|263,095,728|
 |  Disable  | **Enable**  | **Enable** |Disable |77,615,560 [3]|

Additional note: 
 - [1]:  Disabled by default.
 - [2]:  DWARF unwinding relies on Continuous Profile.
 - [3]:  Memory usage in the default configuration.
 
**Optimization Results**:
- When Uprobe Trace and DWARF Unwinding are disabled, this optimization reduces memory usage by 17,235,624MB compared to the previous version.
- If `Disable Pre-allocating Memory` is set, this optimization reduces memory usage by 45,883,824MB compared to the previous version.

In total, this optimization reduces memory usage by 63,119,448MB compared to the previous version.

**Comment by qyzhaoxun** [comment]
[deepflow-mem-status.log](https://github.com/user-attachments/files/17302667/deepflow-mem-status.log)

这里另外发现了两个问题，麻烦确认下
