### ISSUE TITLE
[BUG] 【Deepflow v6.5.9 Server模块源码编译】深层次依赖旧版包导致编译失败的问题

### ISSUE THREAD

**Issue by LemonSqi** [deepflowio/deepflow#8034]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

![7a362b760fd8bbce0350988b96a38ee](https://github.com/user-attachments/assets/b4f9b3fe-6353-4cce-873c-d583c468f8f5)
目前编译的时候卡在这里，编译时，go编译器自动查找到的最新的otlp版本是v0.20.1版本，而编译出错的提示是说这个版本缺少internal和envconfig，我们内部怀疑你们项目组使用的go proxy库源比较旧，里面的包不是最新的，导致项目使用了较旧的版本依赖，从而引入编译失败的问题，目前希望内部提供一个可编译通过的go.mod，我们直接基于该go.mod下载对应版本的依赖构建，谢谢支持~！

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by taloric** [comment]
@LemonSqi 
是改过引用 go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin 的版本么？这里我们用 0.49.0，但看图 found 的是 0.54.0（见下）
直接用以下这个  go mod 亦可
https://github.com/deepflowio/deepflow/blob/v6.5.9/server/go.mod#L76

**Comment by LemonSqi** [comment]
编译继续出现了protoc-gen-gofast的问题：
![4f48d37c749de108a3114ce09ec1e99](https://github.com/user-attachments/assets/bf7c045a-7c4d-42f2-bf6f-b7742b2d1280)

**Comment by LemonSqi** [comment]
![86446d88449105297c9460ba5daa5b7](https://github.com/user-attachments/assets/1e888476-20c1-4389-9d77-7398aeb20d37)
进一步的查看问题

**Comment by LemonSqi** [comment]
现在的问题：
![86446d88449105297c9460ba5daa5b7](https://github.com/user-attachments/assets/bf5d1293-dbbf-43f7-908a-7ac8847149c6)

**Comment by taloric** [comment]
@LemonSqi 
确认下 $PATH 里没有 /../project/... 这个路径，$PATH 里是 /../protobuf/bin/ 路径
另外既然 go 及相关工具链都在 sqwang 这个用户下，登录此用户来执行编译即可，使 gopath 相关可以找到正确的路径

**Comment by LemonSqi** [comment]
![b9efa956eb7e6671f5ceb85ba48ae9d](https://github.com/user-attachments/assets/5447d32c-b7c4-4f23-9adc-219becee9436)
配置了PATH以后编译继续进行，但报错提示缺少tmpl工具，询问了下gpt，提示说安装go install github.com/benbjohnson/tmpl@latest
继续报错如上所示，  这一步在编译手册里并没有体现，请问，内部tmpl使用的包是哪个，以及上述编译问题应该怎么处理与解决，谢谢~！

**Comment by taloric** [comment]
@LemonSqi 
tmpl 引用的包可见：
https://github.com/deepflowio/deepflow/blob/main/.github/workflows/server-build.yml#L50

以及里面有完整的构建编译环境所需的依赖工具包的流程；

另外最后一幅图的报错，确认下是否对 /server 目录下的内容修改或删除过文件，需要确认 `xxxx/server/patch`  此文件夹下的内容是否完整。

如果确认完整，可以先清理掉之前的编译产物，重新编译，另外注意下其他文件不需要改动，不需要在 server 目录下手动更新依赖，使用 makefile 定义的命令更新即可
清理：
```bash
make clean
```

重新编译：
```bash
CGO_ENABLED=0 make all
```

**Comment by LemonSqi** [comment]
6.5.9完整的，没有动过，确认了
tmpl这个包我看server-build.yaml没有引用啊，是个#注释掉的apt包，yum源里也没发现这个包，并不是直接引用的，按照你的说法，执行make clean然后重新编译跟之前报错一样
