### ISSUE TITLE
如何监控托管k8s集群

### ISSUE THREAD

**Issue by tripitakav** [deepflowio/deepflow#8051]
![image](https://github.com/user-attachments/assets/89180229-a003-49b3-b98f-2ec59da938c0)
按照官方文档教程这里vpc uuid该怎么获得

![image](https://github.com/user-attachments/assets/edefc204-6015-49fe-9485-e248d807fff2)

**Comment by 1473371932** [comment]
你好，你们用的什么云呀，部署方式还是要按照[监控单个 K8s 集群](https://www.deepflow.io/docs/zh/ce-install/single-k8s/)来，你截图的这种方式，是基于完成 "监控单个 K8s 集群" 操作后做的，可以通过云厂商提供的 API，自动注入云资源的标签。

**Comment by tripitakav** [comment]
> 你好，你们用的什么云呀，部署方式还是要按照[监控单个 K8s 集群](https://www.deepflow.io/docs/zh/ce-install/single-k8s/)来，你截图的这种方式，是基于完成 "监控单个 K8s 集群" 操作后做的，可以通过云厂商提供的 API，自动注入云资源的标签。

AWS和阿里云。如果我在中心云部一套server集群，每个单独的集群使用agent-group下发agent 配置，这样的架构也可以通过云厂商API自动注入云资源标签吗？

**Comment by 1473371932** [comment]
> > 你好，你们用的什么云呀，部署方式还是要按照[监控单个 K8s 集群](https://www.deepflow.io/docs/zh/ce-install/single-k8s/)来，你截图的这种方式，是基于完成 "监控单个 K8s 集群" 操作后做的，可以通过云厂商提供的 API，自动注入云资源的标签。
> 
> AWS和阿里云。如果我在中心云部一套server集群，每个单独的集群使用agent-group下发agent 配置，这样的架构也可以通过云厂商API自动注入云资源标签吗？

不可以，目前想获取云厂商资源标签，只能通过 ak/sk 形式，让 deepflow 有权限获取才可以

**Comment by tripitakav** [comment]
> > > 你好，你们用的什么云呀，部署方式还是要按照[监控单个 K8s 集群](https://www.deepflow.io/docs/zh/ce-install/single-k8s/)来，你截图的这种方式，是基于完成 "监控单个 K8s 集群" 操作后做的，可以通过云厂商提供的 API，自动注入云资源的标签。
> > 
> > 
> > AWS和阿里云。如果我在中心云部一套server集群，每个单独的集群使用agent-group下发agent 配置，这样的架构也可以通过云厂商API自动注入云资源标签吗？
> 
> 不可以，目前想获取云厂商资源标签，只能通过 ak/sk 形式，让 deepflow 有权限获取才可以

好的，所以只能每个集群每个region单独部署一套是吧

**Comment by 1473371932** [comment]
> > > > 你好，你们用的什么云呀，部署方式还是要按照[监控单个 K8s 集群](https://www.deepflow.io/docs/zh/ce-install/single-k8s/)来，你截图的这种方式，是基于完成 "监控单个 K8s 集群" 操作后做的，可以通过云厂商提供的 API，自动注入云资源的标签。
> > > 
> > > 
> > > AWS和阿里云。如果我在中心云部一套server集群，每个单独的集群使用agent-group下发agent 配置，这样的架构也可以通过云厂商API自动注入云资源标签吗？
> > 
> > 
> > 不可以，目前想获取云厂商资源标签，只能通过 ak/sk 形式，让 deepflow 有权限获取才可以
> 
> 好的，所以只能每个集群每个region单独部署一套是吧

需要看你们怎么规划，一个 region 可以部署多套 deepflow，比如说一个 region 中你们分为了生产、测试两个环境，你可以在 生产环境部署一套 deepflow，测试环境只需要部署 deepflow-agent 注册到生产的 server 上即可，也可以两套环境部署两套 deepflow，具体还是要看你们怎么规划

**Comment by tripitakav** [comment]
已有同事微信沟通你们，先关闭该issue
