### ISSUE TITLE
[BUG] deepflow-ctl 上传wasm插件报错

### ISSUE THREAD

**Issue by chluknight** [deepflowio/deepflow#8138]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

deepflow-ctl 执行deepflow-ctl create plugin命令报错invaid byte sequence for encoding UTF8: 0x9c (SQLSTATE 22021)
<img width="727" alt="1c59de39edfdb26001cd1f54884a17d" src="https://github.com/user-attachments/assets/8d03dd88-8e5b-455d-86fb-09bef6ba0fc3">

### How to reproduce

我把deepflow-server使用的MySQL数据库改造成了PostgreSQL
在使用PostgreSQL作为元数据引擎的环境上执行deepflow-ctl create pluing报错
<img width="727" alt="1c59de39edfdb26001cd1f54884a17d" src="https://github.com/user-attachments/assets/f11a802b-28dc-4331-b885-3a031ff76804">

但是在本地使用原生MySQL数据库的环境中上传wasm插件是正常的
<img width="572" alt="20b7139a797f2020ab2a66f41c57f3e" src="https://github.com/user-attachments/assets/9db1e10d-6eb2-4857-a21e-cf9a62458e21">

请问deepflow-ctl在执行deepflow-ctl create pluign命令时是会转成MySQL格式的SQL语句吗？调用的是deepflow-server的哪个接口？

这个问题可以麻烦给个解决思路吗？谢谢！

### DeepFlow version

v6.4.9

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by roryye** [comment]
deepflow-server 目前是没支持 PostgreSQL 的，适当改造即可，下面是一些资料：
- 请求的 server 接口：https://github.com/deepflowio/deepflow/blob/main/server/controller/http/router/plugin.go#L43
- gorm PostgreSQL 文档：https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL
- gorm PostgreSQL UTF8 issue：https://github.com/go-gorm/gorm/issues/5418
- deepflow-server 数据库初始化https://github.com/deepflowio/deepflow/blob/main/server/controller/db/mysql/common/gorm.go#L77
