### ISSUE TITLE
[BUG] deepflow-agent v6.6.4 EbpfRunningError

### ISSUE THREAD

**Issue by qyzhaoxun** [deepflowio/deepflow#8180]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

tkeserverless可以正常运行deepflow

### How to reproduce

在tkeserverless上以sidecar模式部署deepflow，EbpfRunningError报错

[2024-09-20 21:02:55.187512 +08:001 INFO [src/ebpf/mod.rs:721] [eBPF] WARN func load_obj_progs() luser/load.c:5871 bcc_prog_load() failed. name: kfunc__ksys_write, Permission denied errno: 13
［2024-09-28 21:02:55.187576 +08:00］INFO [src/ebpf/mod.rs:721] [eBPF] WARN func ebpf_obj_load() luser/load.c:941] eBPF load programs failed.(errno13)

### DeepFlow version

v6.6.4

### DeepFlow agent list

K8S_SIDECAR

### Kubernetes CNI

ipvlan

### Operation-System/Kernel version

5.4.241-1-tlinux4-0017.10.eks.4

### Anything else

5.4.119-1-tlinux4-0009-public-eks ebpf collect可以正常运行

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
你好，能否在 agent log 中`grep -i ebpf`过滤一下更详细的 ebpf 日志

**Comment by qyzhaoxun** [comment]
<img width="1026" alt="image" src="https://github.com/user-attachments/assets/afa56483-b56c-4fc9-a1f2-be6802adbc55">

**Comment by yinjiping** [comment]
5.4.241-1-tlinux4-0017.10.eks.4, 这个内核的在加载fentry/fexit 类型的eBPF字节码时，Verify似乎存在问题，测试其他内核版本没发现这种情况，我做了下修复，如果加载失败将会尝试加载其他类型的eBPF字节码来避免加载失败的问题。
