### ISSUE TITLE
[BUG] 使用deepflow监控传统服务器时遇到了问题，agent无法注册

### ISSUE THREAD

**Issue by fujianli1995** [deepflowio/deepflow#8254]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

我尝试按照社区版文档安装agent监控传统服务器，agent安装后使用deepflow-ctl 查询agent列表中没有

### DeepFlow version

v6.6.5

### Operation-System/Kernel version

3.10.0-957.21.3

### Anything else

![Snipaste_2024-10-09_09-03-16](https://github.com/user-attachments/assets/82378184-ca88-414c-8689-98bb01d42eb1)
deepflow server中的相关报错。但是agent无报错。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by fujianli1995** [comment]
![Snipaste_2024-10-09_09-03-16](https://github.com/user-attachments/assets/216a8b5b-89a1-4dc0-9786-83a80c63ce50)

**Comment by 1473371932** [comment]
1. 目前传统服务器所在的网段是什么，确认下是否包含在 deepflow configmap 配置中
2. `deepflow-ctl domain list`查看创建好的用于同步传统服务器的 domain 信息
3. `deepflow-ctl agent-group-config list -o yaml` 看一下目前的组配置

以上都正常的话，先尝试卸载 deepflow 后删除 /opt/deepflow-* 数据后，使用 v6.5 LTS 版本（镜像 tag 从 v6.6.5 换成 v6.5 即可）再试一下

**Comment by fujianli1995** [comment]
网段是包含在configmap配置中的，目前已经替换为v6.5版本，agent注册成功。
