### ISSUE TITLE
[BUG] 监控传统服务器，可以采集到trace数据，但是agent日志中有报错信息

### ISSUE THREAD

**Issue by Alfred088** [deepflowio/deepflow#8262]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

[t.txt](https://github.com/user-attachments/files/17323936/t.txt)

### DeepFlow version

传统服务器

### Operation-System/Kernel version

Linux 5.14.21-150400.24.100-default #1 SMP PREEMPT_DYNAMIC Mon Dec 4 19:12:13 UTC 2023 (3f5cd84) x86_64 x86_64 x86_64 GNU/Linux

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
epoll_wait() 返回 Interrupted system call (errno 4) 的原因通常是系统调用被信号中断了。

可以把on-cpu-profile关闭，看看是否和Profile有关。

```
static_config:
  ebpf:
    on-cpu-profile:
      disabled: true
```

**Comment by 1473371932** [comment]
你好，更新 [agent-group-config](https://www.deepflow.io/docs/zh/best-practice/agent-advanced-config/) 后，如果还有问题，可以添加项目主页企业微信，在社区交流群中沟通会更方便一些
