### ISSUE TITLE
[BUG] 持续性能剖析火焰图展示问题

### ISSUE THREAD

**Issue by ZSJGG** [deepflowio/deepflow#8285]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

server版本6.6在6.5的基础上对profile的api查询返回数据的结构做出了调整：
在6.5中的结构如下图(官方文档)：
![image](https://github.com/user-attachments/assets/c11cb405-e14f-45fd-956e-d98ef26ba5ce)
在6.6中的结构如下图(官方文档):
![image](https://github.com/user-attachments/assets/0b11c929-effb-4ade-a28e-e09c36327594)
在6.5中返回了parent_node_id和node_id用于确定节点间的父子关系，但是更新到6.6后 只返回了parent_node_id, 猜测function_id也只是用于确认函数名称，那么根据现有的数据还可以确定节点间的父子关系吗？希望官方能答复一下，谢谢。

### How to reproduce

update 6.5 to 6.6 release

### DeepFlow version

6.6 release

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by xiaochaoren1** [comment]
6.6 版本中，数组下标即为 node_id

**Comment by ZSJGG** [comment]
感谢答复 现在我使用数组下标作为node_id时，在一次查询发现返回的values的长度是1705，但是也同时存在parent_node_id为1705 这是合理的现象吗
