### ISSUE TITLE
[BUG] epbf 采集数据报错

### ISSUE THREAD

**Issue by tjlqq** [deepflowio/deepflow#8302]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

agent采集ebpf数据报错
![1728974464619](https://github.com/user-attachments/assets/41c5f61e-354e-494b-a872-107bc933bf69)
客服那里有日志记录

### DeepFlow version

[root@ ~]# kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
4483-9cfb24c9c7add03fa9805886c5bfbcb848510072
Name: deepflow-agent enterprise edition
Branch: B_LC_RELEASE_v6_4
CommitId: 9cfb24c9c7add03fa9805886c5bfbcb848510072
RevCount: 4483
Compiler: rustc 1.75.0 (82e1608df 2023-12-21)
CompileTime: 2024-01-18 10:52:39
kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
Name: deepflow-server community edition
Branch: v6.6.1
CommitID: 6eb9865fee448337a54b71e8e260318005c1669f
RevCount: 10797
Compiler: go version go1.21.12 linux/amd64
CompileTime: 2024-07-19 02:07:39

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
[root@ ~]# kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
4483-9cfb24c9c7add03fa9805886c5bfbcb848510072
Name: deepflow-agent enterprise edition
Branch: B_LC_RELEASE_v6_4
CommitId: 9cfb24c9c7add03fa9805886c5bfbcb848510072
RevCount: 4483

B_LC_RELEASE_v6_4   4483这个版本不支持3.10内核
请升级版本 6.4.9 最新版本（比如 v6.4.4713）

@tjlqq
