### ISSUE TITLE
[FR] 请问如何在 agent 中新增 uprobe 探针

### ISSUE THREAD

**Issue by midorifizz** [deepflowio/deepflow#8313]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

想在 deepflow agent 中开发 uprobe 探针做功能扩展。比如针对某个应用程序或数据库的函数进行插桩，然后将采集的数据通过 agent 暴露出来。请问有具体的开发流程文档可以参考吗？非常感谢！

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Fancyki1** [comment]
uprobe插桩其实并不容易，建议你改服务的代码比搞这个uprobe来的快，而且官方搞了那么久，也没说很多语言适配，不同的版本等等，是基于kprobe做的协议采集，是存在很多落地难度的，如果你想搞可以自己写个ebpf程序跑一下。

**Comment by rvql** [comment]
采集器目前无法扩展 uprobe 进行应用程序或数据库的插桩采集；可以考虑能否通过流量数据解析来实现所需功能
