### ISSUE TITLE
AutoProfiling 监控指定进程无数据，也无法搜索到

### ISSUE THREAD

**Issue by 619733575** [deepflowio/deepflow#8314]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

deepflow 启用AutoProfiling 无数据   [
![微信图片_20241016182858](https://github.com/user-attachments/assets/b4fd7252-31a5-4fd0-9708-d7227e097467)
![微信图片_20241016182847](https://github.com/user-attachments/assets/3b3fa284-c2cb-466c-b6b5-bc8ed0069b95)
![微信图片_20241016182837](https://github.com/user-attachments/assets/b6f09b3c-92d5-4b43-a456-2e8c8a0a1d35)
![微信图片_20241016182831](https://github.com/user-attachments/assets/2063bbf4-4028-4e9f-ba1b-e1ae77bb7a6f)
](url)

### DeepFlow version

kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v ：

Name: deepflow-server community edition
Branch: v6.6.6
CommitID: d5e26dd2618cf3dbac2c10594d06d75aab3a38e1
RevCount: 11227
Compiler: go version go1.21.13 linux/amd64
CompileTime: 2024-10-11 05:20:20

kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v：

Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
11227-d5e26dd2618cf3dbac2c10594d06d75aab3a38e1
Name: deepflow-agent community edition
Branch: v6.6.6
CommitId: d5e26dd2618cf3dbac2c10594d06d75aab3a38e1
RevCount: 11227
Compiler: rustc 1.77.1 (7cf61ebde 2024-03-27)
CompileTime: 2024-10-11 07:20:14

### DeepFlow agent list

![image](https://github.com/user-attachments/assets/dcec1ef8-7d22-4217-9c07-30bb87ff7ee0)

### Kubernetes CNI

v1.28.2

### Anything else

无

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 619733575** [comment]
配置：
![image](https://github.com/user-attachments/assets/c478bf05-7422-4d9c-b0e4-f1b06288de1d)

进程：
![image](https://github.com/user-attachments/assets/ee6f234e-8aae-42ae-8967-9fba7bb36ea1)

**Comment by yinjiping** [comment]
@yuanchaoa 下面三种方式

- cmdline 是 /proc/$pid/exe 对应的软连接对应的文件名
- cmdline_with_args 是 /proc/$pid/cmdline
- ProcessName是/proc/PID/status 中的Name

看看是否正则匹配有问题？

**Comment by 619733575** [comment]
> @yuanchaoa 下面三种方式
> 
> * cmdline 是 /proc/$pid/exe 对应的软连接对应的文件名
> * cmdline_with_args 是 /proc/$pid/cmdline
> * ProcessName是/proc/PID/status 中的Name
> 
> 默认是哪一种？看看是个ISSUE是否有正则匹配问题？

![image](https://github.com/user-attachments/assets/b45a3f85-090c-46ee-a56d-318ad8a55d2c)
![image](https://github.com/user-attachments/assets/6947b054-4b0c-4144-b391-64057e194eed)
![image](https://github.com/user-attachments/assets/242b14cd-7f0f-4954-8294-ea48592c566a)

**Comment by 1473371932** [comment]
<img width="392" alt="Snipaste_2024-11-11_14-27-33" src="https://github.com/user-attachments/assets/071a63fe-c342-4e9c-8f79-990bb56be8be">

<img width="1914" alt="Snipaste_2024-11-11_14-26-31" src="https://github.com/user-attachments/assets/1633c676-30d0-4424-aff5-cde971e8a4e7">

是的，按照正则匹配后无问题
