### ISSUE TITLE
[FR] Support for one custom workload

### ISSUE THREAD

**Issue by Hyzhou** [deepflowio/deepflow#8322]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

We have a special workload. named StatefulSetPlus. deepflow agent do not watch the resource cause pod under the StatefulSetPlus, can not be registered.

```
group = "platform.stke",
version = "apiextensions.k8s.io/v1",
kind = "StatefulSetPlus",
```

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rvql** [comment]
Will need a few lines of code for new CRDs.

An example: https://github.com/deepflowio/deepflow/commit/241448a7177208c8fc12d9ac0312dc670f364680
