### ISSUE TITLE
[FR] AutoTracing systrace_id具体是如何计算

### ISSUE THREAD

**Issue by ShawnJop** [deepflowio/deepflow#8330]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

 AutoTracing 一个进程收到的请求和转发请求，systrace_id具体是如何计算使得两个span的systrace_id一致
![微信图片_20241017180418](https://github.com/user-attachments/assets/d7157389-9f28-4efa-83e9-4b04248c2baa)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by yinjiping** [comment]
可以看看这部分的代码注释示意图：
https://github.com/deepflowio/deepflow/blob/main/agent/src/ebpf/kernel/socket_trace.bpf.c#L1126

结合下面这张图理解一下：
![img_v2_f825f658-c8d7-4424-8d57-2b0b6a63b09g](https://github.com/user-attachments/assets/a94d9470-15be-4f1e-836a-da85a9ffb2fd)
