### ISSUE TITLE
[FR] 关于rabbitmq的correlationId关联traceID的问题

### ISSUE THREAD

**Issue by qingwadefox** [deepflowio/deepflow#8351]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我们目前在研究mq的调用链想请教几个问题
1.是否一定需要在代码中设置correlationId才能traceid
2.因为很多是遗留代码并不会为追踪连做改造，能否通过不修改代码的方法实现mq的traceid
3.我设置了correlationId但是在查询界面上上没有显示traceId这个是什么原因
![image](https://github.com/user-attachments/assets/c39e456f-c9db-4bb4-b0ec-2f6ddd4d69f9)
![image](https://github.com/user-attachments/assets/f3436df9-c05f-4c34-9937-1f7bb852c65c)
![image](https://github.com/user-attachments/assets/d4c0b86b-25cd-4a8e-bd5a-99216df05415)
请问下这个是否有具体的使用限制或者使用方法吗？

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Fancyki1** [comment]
@qingwadefox 我最近也在看这部分，但是还没来得及验证，请确认一下已下内容
1.看官方是v6.5,v6.6才支持的功能，确认一下你用的什么版本
2.amqp的correlationId在官方文档上链路追踪的用法是否用对
![7295947679446](https://github.com/user-attachments/assets/4e601715-c6c7-44d1-bfba-54bf9e700163)
3.kafka对应的字段是correlationId，https://www.deepflow.io/docs/zh/features/l7-protocols/mq/
确认完后可以同步一下结果哈

**Comment by qingwadefox** [comment]
> @qingwadefox 我最近也在看这部分，但是还没来得及验证，请确认一下已下内容 1.看官方是v6.5,v6.6才支持的功能，确认一下你用的什么版本 2.amqp的correlationId在官方文档上链路追踪的用法是否用对 ![7295947679446](https://private-user-images.githubusercontent.com/22786883/378809247-4e601715-c6c7-44d1-bfba-54bf9e700163.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NTE4NTMsIm5iZiI6MTcyOTY1MTU1MywicGF0aCI6Ii8yMjc4Njg4My8zNzg4MDkyNDctNGU2MDE3MTUtYzZjNy00NGQxLWJmYmEtNTRiZjllNzAwMTYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAyNDU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3ZTQyY2M0N2I5YjFhMDA3MTNhNTE0ZDUxZTBmY2Q4MTZlNjcwYWVmOWYzMDllNzRlNWQ2NTg1M2VjOTIwMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mT6rT1OXGle-JUvyH3ja4PR23fHRcxeTcRpS9ZTKMdQ) 3.kafka对应的字段是correlationId，https://www.deepflow.io/docs/zh/features/l7-protocols/mq/ 确认完后可以同步一下结果哈

版本用的是6.5的 correlationId 我用的是java编程
![image](https://github.com/user-attachments/assets/ee3af395-3ca1-4a8e-b4b2-5e94681da41f)
rabbitmq官方的api
在测试过程中我生产者放入的 correlationId  在消费者消费队列的时候同样的已经获取到 correlationId  我认为 correlationId 的使用应该没问题 就是不知道deepflow什么机制能过够获取到correlationId   这个对于整体业务链的追踪调用感觉还是蛮重要的

**Comment by Fancyki1** [comment]
@qingwadefox 你不能自己认为amqp支持correlationId就用这个，要看deepflow是否支持和amqp协议解析使用了correlationId做关联，我看文档目前只有kafka是用correlationId这个字段实现svc<->mq的关联，deepflow文档中amqp是在content header中用trace关联

**Comment by PengBin9** [comment]
1. 目前 correlationId 在 deepflow-agent 中没有解析，和 trace id 也没有关联；
2. 目前 v6.5 版本已经支持解析 trace id，具体格式包含 traceparent、sw8、sw6 和 sw3;；
3. deepflow-agent 中没有解析 correlationId，可以通过[此处配置](https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L294)更新 agent-group-config 解析对应的全局id；
