### ISSUE TITLE
[QA] "Distributed Tracing"中service list的duration时间，与火焰图中链路的消耗时间不一致

### ISSUE THREAD

**Issue by yujianweilai** [deepflowio/deepflow#8354]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

在通过traceid进行链路查询的时候，发现service list中某一类服务的duration时间，与火焰图中该类服务所有涉及的链路信息的消耗时间之和，是对不上的。举例，如下图，这次链路调用 涉及ingress-nginx的地方有两处，两处的时间加在一起，和duration 对不上
![image](https://github.com/user-attachments/assets/10e4c42e-5019-40ca-a2ff-db1c61cd437e)

请老师给分析一下原因，感谢

### DeepFlow version

[root@pretycx-master1 ~]# kubectl exec -it -n deepflow deploy/deepflow-server -- deepflow-server -v
Name: deepflow-server community edition
Branch: v6.6.4
CommitID: https://github.com/deepflowio/deepflow/commit/6d70ea94436eb89fb3f0f1d3b45fbca15375f45c
RevCount: 11095
Compiler: go version go1.21.13 linux/amd64
CompileTime: 2024-09-12 06:53:08
[root@pretycx-master1 ~]#
[root@pretycx-master1 ~]# kubectl exec -it -n deepflow ds/deepflow-agent -- deepflow-agent -v
10898-a36223853576de2db72af854b3d7dc2afab9eea0
Name: deepflow-agent community edition
Branch: v6.5
CommitId: https://github.com/deepflowio/deepflow/commit/a36223853576de2db72af854b3d7dc2afab9eea0
RevCount: 10898
Compiler: rustc 1.77.1 (7cf61ebde 2024-03-27)
CompileTime: 2024-09-26 03:04:57
[root@pretycx-master1 ~]#

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by PengBin9** [comment]
<img width="1478" alt="4af081bba03677d8afc77b99a5e6a68" src="https://github.com/user-attachments/assets/40119a0a-9942-4c8d-8097-d360e5966eab">

图一红色标记中的 19.63 是经过计算，得出的这个 span 本身的相应时延，包含了下面的 子span，比如说 00:00 发起一个请求 A，它里面请求了 N 个服务，这 N 个服务总共运行了 8 秒，最后在 00:10 结束，那属于这个请求 A 本身的时延其实只有 2 秒，但是要包含这 8 秒，所以是 10 秒。

而图一黄色标记的 5409微妙，就是这个 span 本身的时间（上面举例说的那 2 秒），代码计算上只排除了第一级子节点。否则会重复排除，导致变负数。

<img width="1160" alt="895042a065a8189d5494481701b7fcb" src="https://github.com/user-attachments/assets/4d5d9ef9-67e8-4a56-9605-b409a97890b5">

至于图中为什么会出现图二中 子span > 父span 时间，也不是因为误差。本质上是统计逻辑的差异。 ebpf（上面的 S span）的计算是以 '内核接到网络请求、内核发出网络响应' 作为计算节点来计算时延的。但下面的 A span 则是 sdk 手动计算时延，且跟一个接口的请求响应无关，比如接口上请求结束了，但是还有些后续步骤（例如异步执行一些代码，释放一些内存对象，发生一些回调等），这些步骤完成了，这个 A span 才算结束，才记录结束时间 这两个计算逻辑的差异，才会产生这种 A 时间大于 S 时间的情况，时延是对的，只是在计算时会认为 A span 已包含 S span 时间，会排除统计

**Comment by yujianweilai** [comment]
感谢解答。
service list会列出本次链路调用，涉及到的所有k8s服务。同时记录每个服务实际的时间消耗情况（排除了等待其他子span执行的时间）。因此，我们在跟踪链路调用的时候，可以通过service list，直观的看出来在这次链路调用中，哪个环节（哪个服务）实际用时最多，然后聚焦问题服务，做进一步排查。
