### ISSUE TITLE
一石数字黑我10000垫付报销之我让他们背负“刑事责任”！！

### ISSUE THREAD

**Issue by nightzjp** [deepflowio/deepflow#8402]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

https://zhuanlan.zhihu.com/p/655630518
抖音已经发了实名帖子，且有官方红头文件-搜索“一石数字”。第一个就是我。

下一次他们会被我送进去！！

### Use case

https://zhuanlan.zhihu.com/p/655630518
抖音已经发了实名帖子，且有官方红头文件-搜索“一石数字”。第一个就是我。

下一次他们会被我送进去！！

### Related issues

https://zhuanlan.zhihu.com/p/655630518
抖音已经发了实名帖子，且有官方红头文件-搜索“一石数字”。第一个就是我。

下一次他们会被我送进去！！

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by nightzjp** [comment]
蹭个流量。抱歉！

**Comment by silly-episode** [comment]
哥们这么惨 嗐

**Comment by nightzjp** [comment]
> 哥们这么惨 嗐

虽然我有点xx。但是看着他们被罚款百万。背负刑事责任我还是很开心的。毕竟都是我做的(#^.^#)

**Comment by nightzjp** [comment]
实在不好意思。拿到的赔偿全部支持开源！

**Comment by LYootsz** [comment]
无关信息不支持讨论

**Comment by nightzjp** [comment]
不好意思。蹭了个流量。

| |
seven_nighter
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | LU ***@***.***> |
| 发送日期 | 2024年10月29日 14:47 |
| 收件人 | deepflowio/deepflow ***@***.***> |
| 抄送人 | ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [deepflowio/deepflow] 一石数字黑我10000垫付报销之我让他们背负“刑事责任”！！ (Issue #8402) |

无关信息不支持讨论
