### ISSUE TITLE
[QA] 如何提取响应 body 里的 status 字段判断响应是否错误，并聚合成指标

### ISSUE THREAD

**Issue by airclear** [deepflowio/deepflow#8448]
我们的业务接口，根据响应 body 里的 status 字段来区分响应是否错误：
```
{"seqNum":"2624110500000002","data": {},"status":0}
{"seqNum":"2624110500000003","message":"系统错误","status":1}
```

请问，
- 如果将 status 放到 header 里，是否就直接可以采集这个字段，不需要自己写 wasm 的开发吗
- 采集了这个字段，会存在哪个表里？
- 这个字段会自动聚合成 1s 或 1m 的指标吗？我们希望在拓扑图上展示这个指标，观察是否有错误产生
- 另外，请问通过 wasm 改写了 响应码 ，是会直接把返回给用户的响应码改掉吗？

**Comment by 1473371932** [comment]
- 是的，例如如果是http响应的在200 404的位置 替换一下
- flow_log.l7_flow_log
- 应用协议解析会根据响应码 统计服务端错误、客户端错误等异常指标 存入1s 1m的指标数据库里
- wasm改写的响应码 不会返回给用户，agent使用旁路检测的技术 不影响原网络的通信，另外wasm改写响应码agent不会再次解析

根据你的提问，如果是基于http协议的应用，最好的方案还是写wasm，大致是：
- wasm钩子放在HOOK_POINT_HTTP_RESP， 这样http解析后会调用wasm插件继续解析
- wasm插件的OnHttpResp函数 实现你这里自定义的对status的解析 ，并返回错误码；错误码这里需要转为http识别的，例如自定义的0  转http 200 ,  自定义的1 转为http 404 等
