### ISSUE TITLE
[BUG] MySQL协议Span ID解析失败

### ISSUE THREAD

**Issue by qiaozeguang** [deepflowio/deepflow#8457]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

执行SQL时，在SQL前添加注释，内部是sw8的值，期望可以正确解析traceid和spanid
实际上只能解析到traceid，解析不到spanid

通过查看代码，发现bug代码如下
![image](https://github.com/user-attachments/assets/2246bccc-2a3f-426a-9b11-1ad1b4d863c5)
sw8的值里面，是可能存在 = 的，这里在切割sw8值的时候，就出问题了。

### DeepFlow version

v6.5

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by rvql** [comment]
是一个问题，不过由于需要同时支持 `:` 和 `=` 作为 key/value 的分隔符，目前并没有什么好的办法解决

**Comment by 1473371932** [comment]
这里影响到不大，火焰图中可能会有空行;

有个简单的解决方案，就是不要传 base64 encode 过的值
