### ISSUE TITLE
[BUG] deepflow 查询同一个URL在不同观察点看到的请求数量数量不一致

### ISSUE THREAD

**Issue by xiaoqiangOB** [deepflowio/deepflow#8483]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

正常来说 访问svc-orde的请求在每个观察点看到的行为应该是一致的，不会说我在客户端这里看到的是5个请求，到了服务端这里就变成了6个请求，现在的情况是我在每个观测点看到的请求数都不太一致。
![svc_query](https://github.com/user-attachments/assets/35522a67-a958-4454-831a-5cd1f7bfc110)

### How to reproduce

目前看起来我的环境这个问题一直存在，需要我补充什么日志数据吗。

### DeepFlow version

Name: deepflow-server community edition
Branch: v6.6.5
CommitID: eb43fab700b5fa0a03764f0146f4c8ef4724cd1f
RevCount: 11188
Compiler: go version go1.21.13 linux/amd64
CompileTime: 2024-09-25 06:14:29

Defaulted container "deepflow-agent" out of: deepflow-agent, configure-sysctl (init)
11188-eb43fab700b5fa0a03764f0146f4c8ef4724cd1f
Name: deepflow-agent community edition
Branch: v6.6.5
CommitId: eb43fab700b5fa0a03764f0146f4c8ef4724cd1f
RevCount: 11188
Compiler: rustc 1.77.1 (7cf61ebde 2024-03-27)
CompileTime: 2024-09-25 06:15:33

### DeepFlow agent list

ID   NAME        TYPE     CTRL_IP        CTRL_MAC            STATE    GROUP     EXCEPTIONS   REVISION       UPGRADE_REVISION   
2    node01-V3   K8S_VM   10.5.104.182   00:50:56:8c:e8:7e   NORMAL   default                v6.6.5 11188                      
3    node02-V1   K8S_VM   10.5.104.183   00:50:56:8c:ed:e5   NORMAL   default                v6.6.5 11188     

### Kubernetes CNI

Client Version:    v3.24.5
Git commit:        f1a1611ac
Cluster Version:   v3.24.5
Cluster Type:      typha,kdd,k8s,operator,bgp,kubeadm

### Operation-System/Kernel version

"Ubuntu 22.04.2 LTS"

### Anything else

环境描述：
按照官方文档部署了一组skywalking demo,之后安装文档所说使用命令helm install deepflow -n deepflow deepflow/deepflow --version 6.5.012 --create-namespace -f values-custom.yaml 部署deepflow环境，截图如下。
![skywalkingdemo](https://github.com/user-attachments/assets/16c5777c-af3d-4d7b-941b-1b7afa8d793c)

之后查看grafana的时候发现访问svc-order的/createOrderurl 在不同观测点观测到的请求速率不一致。正常情况下，无论在客户端还是服务端观察到的请求数应该是一样的才对,下面是查询截图。
![svc_query](https://github.com/user-attachments/assets/11b50b49-b05e-41af-89e4-a7ebc2774037)

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
<img width="426" alt="Snipaste_2024-11-11_11-28-12" src="https://github.com/user-attachments/assets/dcddc45e-1b26-4b89-81ad-9330bae24a65">

是的，请求速率肯定是一致的，如图所示，请求速率使用的是 request 参数，目前情况看起来像是各个采集点采集到的请求量不一致，需要检查下：

1. 查看时是否为刚部署不久，建议在部署 5-10 分钟后查看，刚部署时会有丢包的情况
2. 如果部署一段时间后数据依然如此，查看 DeepFlow System - DeepFlow Alert Analysis 面板是否有数据，此面板可查看丢包监控，如果有数据，则说明有丢数据，对应面板注释中有丢包原因与解决方式，可以先参考解决一下

**Comment by 1473371932** [comment]
你好，如果后续还有问题，可以添加项目主页的企业微信，在社区群中沟通更方便一些
