### ISSUE TITLE
[BUG] promtheus上查询不出接口延时的数据

### ISSUE THREAD

**Issue by lynyuxuan** [deepflowio/deepflow#8490]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

![9784e9516c3335b3506930e669c3080](https://github.com/user-attachments/assets/a24409c5-c3f4-41e0-bad2-767de2da9ba3)
根据文档查询promtheus指标。没有查出数据，但是在grafana上是能查到数据的。

### How to reproduce

1.参考官方文字执行promsql语句：https://www.deepflow.io/docs/zh/integration/output/query/promql/#%E5%9F%BA%E4%BA%8E-promql-%E6%9F%A5%E8%AF%A2-deepflow-%E6%8C%87%E6%A0%87
2.查看监控面板，查看是延时的信息。

### DeepFlow version

 deepflow-server -v
Name: deepflow-server community edition
Branch: v6.6.6
CommitID: 36ec980d0212c86f2dedbfba3f067d834b9a2fb1
RevCount: 11234
Compiler: go version go1.21.13 linux/amd64
CompileTime: 2024-10-25 09:20:12

### DeepFlow agent list

 deepflow-ctl agent list
ID   NAME               TYPE     CTRL_IP        CTRL_MAC            STATE    GROUP     EXCEPTIONS                    REVISION       UPGRADE_REVISION   
4    10.10.96.16-V4     K8S_VM   10.10.96.16    52:54:00:bc:2e:76   NORMAL   default                                 v6.6.6 11234                      
6    10.10.97.244-V9    K8S_VM   10.10.97.244   52:54:00:0c:77:51   NORMAL   default   SYSTEM_LOAD_CIRCUIT_BREAKER   v6.6.6 11234                      
7    10.10.96.192-V5    K8S_VM   10.10.96.192   52:54:00:1e:e0:a1   NORMAL   default                                 v6.6.6 11234                      
10   10.10.98.168-V7    K8S_VM   10.10.98.168   52:54:00:4c:e6:d8   NORMAL   default                                 v6.6.6 11234                      
11   10.10.72.17-V11    K8S_VM   10.10.72.17    52:54:00:49:f4:34   NORMAL   default                                 v6.6.3 11010                      
12   10.10.72.12-V12    K8S_VM   10.10.72.12    52:54:00:9c:4b:37   NORMAL   default                                 v6.6.3 11010                      
13   10.10.72.13-V14    K8S_VM   10.10.72.13    52:54:00:0c:54:4d   NORMAL   default                                 v6.6.3 11010                      
14   10.10.72.15-V15    K8S_VM   10.10.72.15    52:54:00:8e:32:fd   NORMAL   default                                 v6.6.3 11010                      
15   10.10.98.111-V17   K8S_VM   10.10.98.111   52:54:00:dd:ed:c9   NORMAL   default   SYSTEM_LOAD_CIRCUIT_BREAKER   v6.6.6 11234                      
16   10.10.41.133-V20   K8S_VM   10.10.41.133   52:54:00:f7:aa:94   NORMAL   default                                 v6.6.3 11010                      
17   10.10.33.190-V21   K8S_VM   10.10.33.190   52:54:00:b3:cb:a7   NORMAL   default                                 v6.6.3 11010                      
18   10.10.32.95-V18    K8S_VM   10.10.32.95    52:54:00:67:9a:0c   NORMAL   default                                 v6.6.3 11010                      
19   10.10.35.163-V22   K8S_VM   10.10.35.163   52:54:00:78:70:8b   NORMAL   default                                 v6.6.3 11010                      
20   10.10.97.116-V23   K8S_VM   10.10.97.116   52:54:00:95:63:bc   NORMAL   default   SYSTEM_LOAD_CIRCUIT_BREAKER   v6.6.6 11234                      
22   10.10.97.28-V25    K8S_VM   10.10.97.28    52:54:00:ba:5c:3b   NORMAL   default   SYSTEM_LOAD_CIRCUIT_BREAKER   v6.6.6 11234                      
23   10.10.96.12-V2     K8S_VM   10.10.96.12    52:54:00:16:ca:64   NORMAL   default                                 v6.6.6 11234                      
24   10.10.104.2-V26    K8S_VM   10.10.104.2    52:54:00:83:02:9a   NORMAL   default   SYSTEM_LOAD_CIRCUIT_BREAKER   v6.6.6 11234                      
25   10.10.96.9-V6      K8S_VM   10.10.96.9     52:54:00:3e:52:a1   NORMAL   default                                 v6.6.6 11234                      
26   10.10.43.157-V27   K8S_VM   10.10.43.157   52:54:00:a8:79:9b   NORMAL   default                                 v6.6.3 11010                      
27   10.10.96.10-V8     K8S_VM   10.10.96.10    52:54:00:4e:ca:85   NORMAL   default                                 v6.6.6 11234                      
28   10.10.96.11-V10    K8S_VM   10.10.96.11    52:54:00:d8:3d:aa   NORMAL   default                                 v6.6.6 11234                      
29   10.10.97.149-V24   K8S_VM   10.10.97.149   52:54:00:e7:74:1c   NORMAL   default   SYSTEM_LOAD_CIRCUIT_BREAKER   v6.6.6 11234                      
30   10.10.96.120-V3    K8S_VM   10.10.96.120   52:54:00:3f:ad:9b   NORMAL   default   SYSTEM_LOAD_CIRCUIT_BREAKER   v6.6.6 11234                      
31   10.10.98.59-V1     K8S_VM   10.10.98.59    52:54:00:0f:73:c8   NORMAL   default   SYSTEM_LOAD_CIRCUIT_BREAKER   v6.6.6 11234  

### Kubernetes CNI

腾讯云vpc-cni插件

### Operation-System/Kernel version

"TencentOS Server 3.1 (Final)"
5.4.119-19.0009.44

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by taloric** [comment]
@lynyuxuan  plz try after v6.6.8 released

**Comment by taloric** [comment]
@lynyuxuan It seems miss one commit, maybe due to the workflow pipeline did not update after v6.6.8 has been released, what we expected is you should get commit id after 'ad91f9b9b3136344121812664fcd211e1dfd5ec3'.
btw I re-run v6.6.8 workflow , plz wait for a while after https://github.com/deepflowio/deepflow/actions/runs/12134632449/job/33832187337 was complete so that you can get the latest v6.6.8
