### ISSUE TITLE
[FR] 架构上存在丢弃数据的行为，是否可以增加中间件，或者直接数据落盘。保证原始数据的准确性

### ISSUE THREAD

**Issue by luolidong** [deepflowio/deepflow#8491]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

目前，我们的需求是需要精确统计到请求，去计算费用。
对于数据质量要求比较高，原有设计会在负载高情况下抛弃数据，保证实时性。
是否可以再agent上增加直接落地本地日志文件，为离线计算提供数据。

### Use case

![1](https://github.com/user-attachments/assets/cc293b46-7368-45e1-afae-25a7b0fe6844)
我们经过优化，确实可以再一定程度上不丢失。
但是因为在流量波动，或者增加采集协议的情况下，这个丢失的行为不可控，导致数据质量不可控。
不满足计费和精确计量的统计场景。

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by Fancyki1** [comment]
个人理解，原始数据完全不丢失并不是观测领域所追求的，otel的方案也有采样率的配置，如果你希望完全不丢，最好的方案是deepflow export 到 kafka这种的，然后kafka至于数据积压什么的，再慢慢消费，就是随便玩了，标准很难做到不丢数据。

**Comment by lzf575** [comment]
**deepflow-server 会接收大量agent的数据，如果处理不过来必然会丢包。** 
   - 若不丢包，就只能缓存下来，缓存到一定程度，内存不足，程序就oom。
   - 或者阻塞 agent 发送， agent 缓存队列满，也会丢包， 不丢包也一样的oom。

**解决丢包，只能增大处理能力。**
 目前deepflow-server 可以配置各种数据的 处理队列的个数(并行处理数) 和 队列长度 (缓存数据)
 - 如果是持续丢包，需要增加处理队列的个数。
 - 如果是偶尔丢包，可以增加队列长度.
 - 若还丢包，只能继续扩容。

**agent目前支持l4_flow_log和l7_flow_log 写本地(若写本地，就不发送给server了)， 本地写入只是纯文本写入，不压缩，会占用大量空间，也不利于分析。**

**Comment by lzf575** [comment]
建议把 throttle 设置为0，不限流。 后续观察，是否有存在其他处理队列丢包，增加相应的处理队列数或长度即可。
一般16c，64G，至少能处理 100K条/s  的数据。
https://github.com/deepflowio/deepflow/blob/main/server/server.yaml#L695
![image](https://github.com/user-attachments/assets/375ab817-6e38-4679-a121-72ce220fb418)
![image](https://github.com/user-attachments/assets/89f1e2b3-7813-4aa3-822d-40fce1775e5c)
![image](https://github.com/user-attachments/assets/5e5e9351-4e4a-4719-88c5-8430cb08fc5e)

**Comment by luolidong** [comment]
确实，做了优化之后，已经不丢包了。
但是不是基于设计上考虑不丢失的方案，只是优化消息处理，是无法对数据准确性做保证, 这毕竟是不可控。
对于全链路观测的场景，确实丢了就丢了，问题不大。
但是如果对于数据可靠性要求较高的场景，不可控的话，这个问题是致命性的。

如果增加了消息可靠性，确实会导致系统的复杂度的上升，以及消息延迟消费问题，这个是可以理解的。
所以先探讨下方案，是否可以考虑增加中间件，或者写入本地。
写入本地：
1 如果是写入本地的话，按小时或者大小滚动写入，再增加配置滚动删除或者占用空间问题由用户自己解决。
2 读取本地文件往server发数据，记录发送的offset。（类似flume）
3 压缩已经发送完消息的文件。

写入Kafka
1 这个就直接agent写入，server消费，比较简单。

至于延迟消费问题，由用户自己决定是否要使用这2种方式。

**Comment by lzf575** [comment]
**采集量流量大时，哪个环节都可能丢包**， 
  - 从agent采集源头开始 -->queue1->queue2->queueN   
  - 发送到  server-->queue1->queue2.... 
  - 每个环节都可能丢包，不仅仅是最后保存发送数据环节等，目前对每个队列的丢包都有监控。

**目前支持数据导出到kafka，即使这样，只要数据量过大，导出时也还可能丢包，其他环节一样也可能丢包**
  - http://apidocs.yunshan.net/deepflow-help/master/zh/integration/output/export/kafka-exporter/

**任何系统都不可能在资源不足时做到不丢包。如果存在也只是阻塞处理把问题丢给上级系统，最终是数据产生源处丢包。**
  - 只能根据采集量 和 系统资源 来做个最佳实践
  - 例如 流量 10Gbps时，都不丢包，那么当流量突变为20Gbps, 是否也不丢包，如果丢包，看是哪个环节丢包，可以修改队列配置或扩容来解决。只能通过运营经验，不断调整配置，使得在多数场景下都不丢包。
