### ISSUE TITLE
deepflow-ctl agent-group list -> body failed, (invalid character '<' looking for beginning of value)

### ISSUE THREAD

**Issue by StalkerOne** [deepflowio/deepflow#850]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

when i run:  deepflow-ctl agent-group list       it's output: 
      parse (http://xxx.xxx.xxx.xxx:30417/v1/vtap-groups/) body failed, (invalid character '<' looking for beginning of value)

**Comment by SongZhen0704** [comment]
@StalkerOne

**Comment by StalkerOne** [comment]
> @StalkerOne Hello, In #873, I print the complete response in output console. So can you use the latest deepflow-ctl, and tell me the new output? thank you

deepflow-ctl --version:

6496 f1c793ab0a47f3ca0d26360ce9da563273a10e00 2022-09-16
deepflow-ctl community edition
go version go1.18.5 linux/amd64

**Comment by SongZhen0704** [comment]
@StalkerOne 
I want the new output when you exec `deepflow-ctl agent-group list`

**Comment by SongZhen0704** [comment]
The issue cannot be reproduced at the moment
