### ISSUE TITLE
[FR] 我们发现在某些机器上的agent，cgroup会失效导致cpu跟内存占用不可控

### ISSUE THREAD

**Issue by zcl1115** [deepflowio/deepflow#8528]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### Description

我们观测到部分agent上报的cpu跟内存占用超过了配置限定的值，然后发现cgroup的配置信息有问题，想问下之前有没有遇到这种情况，内核版本是Linux 4.9.70-040970-generic x86_64
<img width="792" alt="企业微信截图_79e29086-0a37-4040-abc7-63c329050295" src="https://github.com/user-attachments/assets/ca19fd2e-7a93-4d70-ba83-97bf069a7219">

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by zcl1115** [comment]
我这边检查了下对应的cgroup限制信息，发现cgroup真正有效的信息是在deepflow-agent下面而非/system.slice/deepflow-agent.service下面
root@bigo:/sys/fs/cgroup# 
root@bigo:/sys/fs/cgroup# cat cpu,cpuacct/deepflow-agent/cpu.cfs_quota_us 
100000
root@bigo:/sys/fs/cgroup# cat cpu,cpuacct/system.slice/deepflow-agent.service/cpu.cfs_quota_us 
-1
root@bigo:/sys/fs/cgroup# cat memory/deepflow-agent/memory.limit_in_bytes 
1073741824
root@bigo:/sys/fs/cgroup# cat memory/system.slice/deepflow-agent.service/memory.limit_in_bytes 
9223372036854771712

**Comment by 1473371932** [comment]
agent 版本

```
Name: deepflow-agent community edition
Branch: v6.5.5
CommitId: c29adff9e4a375dbcda32fc8c08aeb4455cd7462
RevCount: 10116
Compiler: rustc 1.77.1 (7cf61ebde 2024-03-27)
CompileTime: 2024-04-25 02:30:48
```

**Comment by zcl1115** [comment]
deepflow_agent_monitor{host=~"$agent", type="cpu_percent"}
deepflow_agent_monitor{host=~"$agent", type="memory"}
![image](https://github.com/user-attachments/assets/4727e748-54d8-4f3b-b7e5-a181703e2260)

**Comment by rvql** [comment]
@zcl1115 没有遇到过这个现象，方便提供一下采集器日志吗？

**Comment by zcl1115** [comment]
@rvql agent的日志没有看到异常的情况，就类似正常打印
[2024-11-25 08:29:00.423695 +08:00] INFO [src/config/handler.rs:2185] memory limit set to 1.0 GiB
[2024-11-25 08:29:00.423700 +08:00] INFO [src/config/handler.rs:2246] log_file_size set to 100
这些信息，我们是将agent托管在我们内部的cicd平台，通过shell脚本执行拉起动作，然后每分钟定时检测进程是否存在，如果不存活会自动再执行shell脚本拉起，然后agent的启动配置里面是跟着官方的配置，配置了systemctl的restart=always，不知道是不是两个冲突的原因？shell脚本关于启动的逻辑如下：
cat << EOF > /etc/systemd/system/deepflow-agent.service
[Unit]
Description=deepflow-agent.service
After=syslog.target network-online.target

[Service]
Environment=GOTRACEBACK=single
LimitCORE=1G
ExecStart=/usr/sbin/deepflow-agent
Restart=always
RestartSec=10
LimitNOFILE=1024:4096

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable $APP_NAME
systemctl start $APP_NAME
