### ISSUE TITLE
[QA]deepflow-agent在k8s环境中，是否支持namespace级别过滤，实现仅收集指定业务namespace观测性数据？

### ISSUE THREAD

**Issue by wujy189** [deepflowio/deepflow#8529]

**Comment by 1473371932** [comment]
做不到，但可以控制其他数据采集位置：

拉黑某个端口，不要对应端口的 eBPF 数据：
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L1307

拉黑调用日志 uri，可以忽略一些健康检测的探测：
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L1073

忽略部分协议采集
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L1020

关掉 l4 的部分采集点：
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L423

关掉 l7 的部分采集点：
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L453

或者可以单方面全部关掉 l4/7 的采集点：
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L416
https://github.com/deepflowio/deepflow/blob/main/server/agent_config/example.yaml#L423
