### ISSUE TITLE
[BUG] k8s 1.30.4+cilium 1.16.1环境安装Deepflow chart 6.6.014，namespace变量无法展示

### ISSUE THREAD

**Issue by svensxl** [deepflowio/deepflow#8539]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Grafana Dashbaord

### What you expected to happen

![expected_namepsace](https://github.com/user-attachments/assets/355b576b-816f-438a-923e-90db302321bf)

上面是在k8s1.20.3+flannel测试正常截图，但k8s 1.30.4+cilium环境下没有数据, 如下图所示

![unexpected_namespace](https://github.com/user-attachments/assets/395f09ff-39cc-4ecd-ae0e-cd8a7a29b6a8)

### How to reproduce

1.部署完成后，打开pod map查看namespace变量，没有数据

2.执行以下SQL查询不到数据
SELECT
    dictGet(flow_tag.pod_ns_map, 'name', toUInt64(pod_ns_id)) AS value,
    dictGet(flow_tag.pod_ns_map, 'name', toUInt64(pod_ns_id)) AS display_name
FROM flow_metrics.`network.1m`
PREWHERE (('__any' IN ('__disabled')) OR ('__any' IN ('__any')) OR (toUInt64(pod_cluster_id) IN (
    SELECT id
    FROM flow_tag.pod_cluster_map
    WHERE name IN ('__any')
))) AND (time >= 1731398650) AND (time <= 1731399550) AND (pod_ns_id != 0)
GROUP BY value
LIMIT 99

3.flow_tag.pd_ns_map表可以查询到数据
![ck](https://github.com/user-attachments/assets/6c475397-47d1-4cc3-8f4d-7787f3e82ce3)

### DeepFlow version

Name: deepflow-server community edition
Branch: v6.6.6
CommitID: d5e26dd2618cf3dbac2c10594d06d75aab3a38e1
RevCount: 11227
Compiler: go version go1.21.13 linux/amd64
CompileTime: 2024-10-11 05:20:20

11234-36ec980d0212c86f2dedbfba3f067d834b9a2fb1
Name: deepflow-agent community edition
Branch: v6.6.6
CommitId: 36ec980d0212c86f2dedbfba3f067d834b9a2fb1
RevCount: 11234
Compiler: rustc 1.77.1 (7cf61ebde 2024-03-27)
CompileTime: 2024-10-25 09:22:09

### DeepFlow agent list

![agent_list](https://github.com/user-attachments/assets/db8ce7de-a9d0-4c2a-b93d-9c81b4818bde)

### Kubernetes CNI

cilium 1.16.1

### Operation-System/Kernel version

"Anolis OS 8.8" 
5.10.134-16.1.3.vip.an8.x86_64

### Anything else

pod map，network map能够正常显示拓扑图，pod_namespace表也有数据，直接原因是flow_metrics.`network.1m`表没有相关数据导致，不知道什么原因

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
network 表需要`客户端``服务端`位置的流量才会存数据，需要检查：

- 采集网口是否正确
- 学习的 MAC IP 地址是否和流量一致

**示例：**
<img width="646" alt="Snipaste_2024-11-28_11-36-04" src="https://github.com/user-attachments/assets/5f1f4c60-bac7-4b9a-8f30-89ee75e6382a">

- 通过`deepflow-ctl agent list`获取对应节点上 agent id
- `deepflow-ctl genesis agent $AGENT_ID`查看此 agent 上报的数据，查看服务 A、B 的 ip、mac 地址是否可以对应上

**Comment by svensxl** [comment]
> network 表需要`` 客户端``服务端 ``位置的流量才会存数据，需要检查：
> 
> * 采集网口是否正确
> * 学习的 MAC IP 地址是否和流量一致
> 
> **示例：** <img alt="Snipaste_2024-11-28_11-36-04" width="646" src="https://private-user-images.githubusercontent.com/84362246/390630918-5f1f4c60-bac7-4b9a-8f30-89ee75e6382a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDgzNTIsIm5iZiI6MTczMzMwODA1MiwicGF0aCI6Ii84NDM2MjI0Ni8zOTA2MzA5MTgtNWYxZjRjNjAtYmFjNy00YjlhLThmMzAtODllZTc1ZTYzODJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDEwMjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMjI5NjUwZjc0N2QxYjU4YjBjMTFkMGQxOTU3Njg4YzkxYjQ0Y2NjZDc5Yzc5NDIyMTVhMmFmOGFiZWZjOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9y1Yu_PsJ4ZkFNO-2YI8xI8UTFhh6ide-LigccZlMKc">
> 
> * 通过`deepflow-ctl agent list`获取对应节点上 agent id
> * `deepflow-ctl genesis agent $AGENT_ID`查看此 agent 上报的数据，查看服务 A、B 的 ip、mac 地址是否可以对应上

太棒了，我按照你的步骤，对tap_interface_regex配置项增加了vvport的正则匹配，目前可以采集到了一部分namespace。  
但仍然有一部分采集不到，我又按照第二步操作，检查了采集失败的namespace容器，agent上报的ip mac和容器的ip mac地址是一样的，仍无法上报的容器和上报成功容器的网络配置组件都是一样，并没有特别之处，请问还有什么线索可以排查呢？

**Comment by svensxl** [comment]
> > network 表需要` 客户端`服务端 ``位置的流量才会存数据，需要检查：
> > 
> > * 采集网口是否正确
> > * 学习的 MAC IP 地址是否和流量一致
> > 
> > **示例：** <img alt="Snipaste_2024-11-28_11-36-04" width="646" src="https://private-user-images.githubusercontent.com/84362246/390630918-5f1f4c60-bac7-4b9a-8f30-89ee75e6382a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDgzNTIsIm5iZiI6MTczMzMwODA1MiwicGF0aCI6Ii84NDM2MjI0Ni8zOTA2MzA5MTgtNWYxZjRjNjAtYmFjNy00YjlhLThmMzAtODllZTc1ZTYzODJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDEwMjczMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMjI5NjUwZjc0N2QxYjU4YjBjMTFkMGQxOTU3Njg4YzkxYjQ0Y2NjZDc5Yzc5NDIyMTVhMmFmOGFiZWZjOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9y1Yu_PsJ4ZkFNO-2YI8xI8UTFhh6ide-LigccZlMKc">
> > 
> > * 通过`deepflow-ctl agent list`获取对应节点上 agent id
> > * `deepflow-ctl genesis agent $AGENT_ID`查看此 agent 上报的数据，查看服务 A、B 的 ip、mac 地址是否可以对应上
> 
> 非常感谢，我按照你的步骤，对tap_interface_regex配置项增加了vvport的正则匹配，目前可以采集到了一部分namespace。 但仍然有一部分采集不到，我按照第二步操作，检查了采集失败的namespace容器，agent上报的ip mac和容器的ip mac地址是一样的，仍无法上报的容器和上报成功容器的网络配置组件都是一样，并没有特别之处，请问还有什么线索可以排查呢？

部分无法上报的namespace原因是，由kubeblocks创建的自定义资源，无法被deepflow采集上报，需要修改源码，增加自定义资源定义：
https://github.com/deepflowio/deepflow/issues/8322  
或参考：https://www.cnblogs.com/pengbin123/p/18618094
