### ISSUE TITLE
[BUG] Mysql协议 l7 flow log识别失败

### ISSUE THREAD

**Issue by jordgedu** [deepflowio/deepflow#8547]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Server

### What you expected to happen

mysql协议识别有问题，l4flow中能看到mysql得链接，但是在l7中却找不到
![Clipboard_Screenshot_1732521199](https://github.com/user-attachments/assets/de8e0819-17e8-44a8-bac5-9443b410d704)
![Clipboard_Screenshot_1732521204](https://github.com/user-attachments/assets/f35b8edb-a669-445b-8ed2-834e537b1747)
在抓包中是可以找到的
![Clipboard_Screenshot_1732521212](https://github.com/user-attachments/assets/89968ab7-0758-48bb-8a9c-db1b88b88667)

### How to reproduce

在docker容器中用java去请求mysql即可

### DeepFlow version

deepflow server vsersion: v6.6.7

### DeepFlow agent list

deepflow agent vsersion: v6.6.7

### Operation-System/Kernel version

uname -r: 5.4.241-1-tlinux4-0017.10

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
你好，抓包中能否找到其他 mysql 的信息，wireshark 中看起来只有 mysql greeting 的数据，流量是tls加密的mysql，网卡的流量解析不了mysql，仅能解析出 tls
