### ISSUE TITLE
[BUG] agent无法注册成功

### ISSUE THREAD

**Issue by jordgedu** [deepflowio/deepflow#8548]
### Search before asking

- [X] I had searched in the [issues](https://github.com/deepflowio/deepflow/issues?q=is%3Aissue) and found no similar feature requirement.

### DeepFlow Component

Agent

### What you expected to happen

基于https://deepflow.io/docs/ce-install/all-in-one/搭建deepflow环境
server端版本： v6.6.7
server端日志
<img width="2250" alt="Clipboard_Screenshot_1732523548" src="https://github.com/user-attachments/assets/ebf44f9e-ac28-44e0-a28f-aad508af635a">
agent版本： v6.6.7
agent端日志
<img width="2005" alt="Clipboard_Screenshot_1732523564" src="https://github.com/user-attachments/assets/ab22c7eb-6fe3-4c63-96ab-c2065aa804bc">
在多台机器上启动agent均无法连接到server
vinterface表没有任何数据
<img width="684" alt="Clipboard_Screenshot_1732523777" src="https://github.com/user-attachments/assets/f5e5b89e-ec95-4ffa-990d-df2ba97aab29">

### How to reproduce

基于https://deepflow.io/docs/ce-install/all-in-one/搭建deepflow v6.6.7环境监控传统云服务器，且都用docker compose安装就会复现

### Operation-System/Kernel version

uname -r: 5.4.241-1-tlinux4-0017.10

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/deepflowio/deepflow/blob/main/CODE_OF_CONDUCT.md)

**Comment by 1473371932** [comment]
尝试使用 v6.6.7 版本通过[此链接](https://www.deepflow.io/docs/zh/ce-install/legacy-host/)方式注册无问题：

<img width="1632" alt="Snipaste_2024-11-26_17-32-35" src="https://github.com/user-attachments/assets/8d16a3cf-011b-4980-8ffc-c5d95cc91102">

- deepflow-server 端通过 docker 方式部署，`.env` 文件中版本变量填写 v6.6.7，ip 变量填写 docker 主机 ip
- 通过`deepflow-ctl domain create`创建 domain
- 创建 agent-group-config 更新配置
- `/etc/deepflow-agent.yaml`引用对应组配置

**Comment by xiaoyuan2019** [comment]
@1473371932 @jordgedu 我使用v6.6.7为什么没有解决这个问题？你们这边解决了吗？我这边是纯docker模式，server/agent都是docker-compose启动的，现在server和agent也是报无法注册成功，请问如何处理？
